'use server';
import {revalidatePath} from 'next/cache';
import {createClient} from '@/lib/supabase/server';

const num=(v:FormDataEntryValue|null)=>{const n=Number(v??0);return Number.isFinite(n)?n:0};
const round=(v:number)=>Math.round((v+Number.EPSILON)*100)/100;
async function ctx(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Not signed in');const {data:profile}=await supabase.from('profiles').select('company_id,role').eq('id',user.id).single();if(!profile?.company_id||profile.role==='employee')throw new Error('Owner access required');return{supabase,user,companyId:profile.company_id};}

export async function approveEmployeeShift(formData:FormData){
 const shiftId=String(formData.get('shift_id')||'');const regularHours=num(formData.get('regular_hours'));const overtimeHours=num(formData.get('overtime_hours'));const totalHours=round(regularHours+overtimeHours);if(!shiftId||totalHours<=0)throw new Error('Enter approved hours.');
 const {supabase,user,companyId}=await ctx();
 const {data:shift}=await supabase.from('employee_shift_sessions').select('*,crew_members(id,name,hourly_rate,internal_field_rate,is_owner,default_risk_class_code)').eq('id',shiftId).eq('company_id',companyId).eq('status','submitted').single();if(!shift)throw new Error('Shift is no longer waiting for approval.');
 const crew:any=shift.crew_members;const workDate=String(shift.work_date);const year=Number(workDate.slice(0,4));const riskClass=String(formData.get('risk_class_code')||crew.default_risk_class_code||'');
 const [{data:tax},{data:taxStatus},{data:risk},{data:overheadSnapshot,error:ohError},{data:segments}]=await Promise.all([
  supabase.from('labor_tax_settings').select('*').eq('company_id',companyId).eq('tax_year',year).maybeSingle(),
  supabase.from('employee_tax_status').select('*').eq('company_id',companyId).eq('crew_member_id',crew.id).eq('tax_year',year).maybeSingle(),
  riskClass?supabase.from('li_risk_classes').select('*').eq('company_id',companyId).eq('tax_year',year).eq('code',riskClass).maybeSingle():Promise.resolve({data:null}),
  supabase.rpc('capture_overhead_rate_snapshot',{p_effective_date:workDate}),
  supabase.from('employee_task_segments').select('production_tasks(name)').eq('shift_id',shiftId).order('started_at')
 ]);
 if(ohError)throw new Error(ohError.message);const isOwner=Boolean(crew.is_owner);const baseRate=Number(isOwner?(crew.internal_field_rate??crew.hourly_rate??0):(crew.hourly_rate??0));const gross=round(regularHours*baseRate+overtimeHours*baseRate*1.5);
 let ssRate=0,medicareRate=0,futaRate=0,suiRate=0,liRate=0,sickRate=0;if(!isOwner){if(!tax)throw new Error(`Labor tax settings are missing for ${year}.`);if(!risk)throw new Error('Choose the correct L&I class before approving.');ssRate=taxStatus?.social_security_cap_reached?0:Number(tax.social_security_rate||0);medicareRate=Number(tax.medicare_rate||0);futaRate=taxStatus?.futa_cap_reached?0:Number(tax.futa_rate||0);suiRate=taxStatus?.wa_sui_cap_reached?0:Number(tax.wa_sui_rate||0);liRate=Number(risk.employer_rate_per_hour||0);sickRate=Number(tax.sick_leave_accrual_rate||0);}
 const ss=round(gross*ssRate),med=round(gross*medicareRate),futa=round(gross*futaRate),sui=round(gross*suiRate),li=round(totalHours*liRate),sick=round(totalHours*baseRate*sickRate),direct=round(gross+ss+med+futa+sui+li+sick),ohRate=Number(overheadSnapshot?.overhead_rate_per_productive_hour||0),oh=round(totalHours*ohRate);
 const taskNames=[...new Set((segments||[]).map((s:any)=>s.production_tasks?.name).filter(Boolean))].join(', ');
 const {data:timecard,error}=await supabase.from('timecards').insert({company_id:companyId,project_id:shift.project_id,crew_member_id:crew.id,worker_name:crew.name,work_date:workDate,task:taskNames||'General',hours:totalHours,regular_hours:regularHours,overtime_hours:overtimeHours,hourly_rate:baseRate,base_hourly_rate:baseRate,risk_class_code:isOwner?null:riskClass,social_security_rate_snapshot:ssRate,medicare_rate_snapshot:medicareRate,futa_rate_snapshot:futaRate,wa_sui_rate_snapshot:suiRate,li_employer_rate_snapshot:liRate,sick_leave_accrual_rate_snapshot:sickRate,gross_wage_cost:gross,employer_social_security_cost:ss,employer_medicare_cost:med,employer_futa_cost:futa,employer_wa_sui_cost:sui,employer_li_cost:li,sick_leave_reserve_cost:sick,direct_labor_cost:direct,overhead_snapshot_id:overheadSnapshot?.id||null,overhead_rate_snapshot:ohRate,overhead_recovery_cost:oh,overhead_cost_method:'productive_hour_v1',labor_cost_method:isOwner?'owner_internal_v1':'statutory_v1',notes:String(formData.get('owner_note')||'').trim()||shift.employee_note||null,source_shift_id:shiftId}).select('id').single();
 if(error)throw new Error(error.message);await supabase.from('employee_shift_sessions').update({status:'approved',approved_by:user.id,approved_at:new Date().toISOString(),approved_timecard_id:timecard.id,owner_note:String(formData.get('owner_note')||'').trim()||null,updated_at:new Date().toISOString()}).eq('id',shiftId).eq('company_id',companyId);
 for(const p of ['/field','/field/review','/projects','/forecast','/payroll','/cashflow','/'])revalidatePath(p);
}

export async function rejectEmployeeShift(formData:FormData){const id=String(formData.get('shift_id')||'');if(!id)return;const {supabase,user,companyId}=await ctx();await supabase.from('employee_shift_sessions').update({status:'rejected',approved_by:user.id,approved_at:new Date().toISOString(),owner_note:String(formData.get('owner_note')||'').trim()||'Rejected for correction'}).eq('id',id).eq('company_id',companyId).eq('status','submitted');revalidatePath('/field/review');}

export async function saveDailyProduction(formData:FormData){const project_id=String(formData.get('project_id')||''),work_date=String(formData.get('work_date')||''),production_task_id=String(formData.get('production_task_id')||''),quantity=num(formData.get('quantity_completed')),unit=String(formData.get('unit')||'').trim();if(!project_id||!work_date||!production_task_id||quantity<0||!unit)throw new Error('Production record is incomplete.');const {supabase,user,companyId}=await ctx();const {error}=await supabase.from('daily_production_records').upsert({company_id:companyId,project_id,work_date,production_task_id,quantity_completed:quantity,unit,notes:String(formData.get('notes')||'').trim()||null,verified_by:user.id,updated_at:new Date().toISOString()},{onConflict:'project_id,work_date,production_task_id'});if(error)throw new Error(error.message);revalidatePath('/field/review');}

export async function setProjectJobsite(formData:FormData){const projectId=String(formData.get('project_id')||'');const lat=Number(formData.get('latitude')),lng=Number(formData.get('longitude')),radius=Math.max(50,Number(formData.get('radius_ft')||500));if(!projectId||!Number.isFinite(lat)||!Number.isFinite(lng))throw new Error('GPS location missing.');const {supabase,companyId}=await ctx();const {error}=await supabase.from('projects').update({site_latitude:lat,site_longitude:lng,geofence_radius_ft:radius}).eq('id',projectId).eq('company_id',companyId);if(error)throw new Error(error.message);revalidatePath('/field');revalidatePath('/field/review');}
