import {redirect} from 'next/navigation';
import Link from 'next/link';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';
import {createDailyLog,createTimecard} from './actions';
import {JobsiteLocationSetter} from '@/components/field/JobsiteLocationSetter';

const today=()=>new Date().toISOString().slice(0,10);

export default async function FieldPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(profile?.role==='employee')redirect('/employee');if(!profile?.company_id)redirect('/login');
 const [{data:projects},{data:crew},{data:riskClasses},{data:waiting},{data:logs},{data:recentApproved}]=await Promise.all([
  supabase.from('projects').select('id,job_number,name,site_latitude,site_longitude,geofence_radius_ft').eq('status','active').order('job_number'),
  supabase.from('crew_members').select('id,name,hourly_rate,is_owner,default_risk_class_code').eq('active',true).order('name'),
  supabase.from('li_risk_classes').select('code,name').eq('company_id',profile.company_id).eq('tax_year',2026).eq('active',true).order('code'),
  supabase.from('employee_shift_sessions').select('id').eq('status','submitted'),
  supabase.from('daily_logs').select('*,projects(job_number,name)').order('log_date',{ascending:false}).limit(8),
  supabase.from('employee_shift_sessions').select('id,work_date,clock_in_at,clock_out_at,crew_members(name),projects(job_number,name)').eq('status','approved').order('work_date',{ascending:false}).limit(8)
 ]);
 return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page">
  <div className="command-hero"><div><h1>Field</h1><p>Employee time, GPS verification, daily logs and real production tracking.</p></div><div className="command-actions"><Link className="button" href="/field/review">Review Employee Time {(waiting||[]).length>0?`(${(waiting||[]).length})`:''}</Link><Link className="button secondary" href="/crew/access">Employee Access</Link></div></div>
  <div className="command-grid"><div className={`command-card ${(waiting||[]).length?'watch':'good'}`}><div className="command-label">Time Waiting for Approval</div><div className="command-value">{(waiting||[]).length}</div><div className="command-help">Clocked-out employee shifts that still need your approval.</div></div><div className="command-card"><div className="command-label">Active Jobs</div><div className="command-value">{(projects||[]).length}</div><div className="command-help">Jobs employees can choose when they clock in.</div></div><div className="command-card"><div className="command-label">Employees</div><div className="command-value">{(crew||[]).filter((c:any)=>!c.is_owner).length}</div><div className="command-help">Active crew records available for timekeeping.</div></div></div>

  <section className="section"><div className="section-heading"><div><div className="section-kicker">GPS</div><div className="section-title">Jobsite Locations</div><div className="section-heading-meta">Set the pin once from the jobsite. Carez then shows how far each employee was from that pin at clock in/out.</div></div></div><JobsiteLocationSetter projects={(projects||[]) as any}/></section>

  <section className="section"><div className="section-heading"><div><div className="section-kicker">Daily Record</div><div className="section-title">Daily Log</div><div className="section-heading-meta">Keep the field record simple: what happened, how much concrete, and anything that affected production.</div></div></div><div className="surface"><div className="surface-body"><form action={createDailyLog} className="form"><label className="field"><span>Job</span><select name="project_id" required defaultValue=""><option value="" disabled>Choose job</option>{(projects||[]).map((p:any)=><option key={p.id} value={p.id}>{p.job_number} — {p.name}</option>)}</select></label><div className="grid grid2"><label className="field"><span>Date</span><input type="date" name="log_date" defaultValue={today()} required/></label><label className="field"><span>Crew Count</span><input type="number" min="0" name="crew_count" defaultValue="0"/></label></div><div className="grid grid2"><label className="field"><span>Concrete Placed (CY)</span><input type="number" step="0.1" min="0" name="concrete_yards" defaultValue="0"/></label><label className="field"><span>Weather</span><input name="weather" placeholder="Dry, 68°F"/></label></div><label className="field"><span>What We Got Done</span><textarea name="work_completed" rows={3} required/></label><label className="field"><span>Problems / Delays</span><textarea name="delays_issues" rows={2}/></label><label className="field"><span>Notes</span><input name="notes"/></label><button className="button">Save Daily Log</button></form></div></div></section>

  <section className="section"><details className="controls-disclosure create-disclosure"><summary>Manual Timecard / Correction</summary><div className="controls-body"><div className="alert info">Use this only when an employee could not use the clock or you are entering owner/manual time. Normal employee time should come through the GPS clock and daily approval.</div><form action={createTimecard} className="form"><label className="field"><span>Job</span><select name="project_id" required defaultValue=""><option value="" disabled>Choose job</option>{(projects||[]).map((p:any)=><option key={p.id} value={p.id}>{p.job_number} — {p.name}</option>)}</select></label><label className="field"><span>Worker</span><select name="crew_member_id" required defaultValue=""><option value="" disabled>Choose worker</option>{(crew||[]).map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="grid grid2"><label className="field"><span>Date</span><input type="date" name="work_date" defaultValue={today()} required/></label><label className="field"><span>Work Type</span><input name="task" defaultValue="General"/></label></div><label className="field"><span>L&I Class</span><select name="risk_class_code" defaultValue=""><option value="">Choose class</option>{(riskClasses||[]).map((r:any)=><option key={r.code} value={r.code}>{r.code} — {r.name}</option>)}</select></label><div className="grid grid2"><label className="field"><span>Regular Hours</span><input type="number" step="0.25" min="0" name="regular_hours" defaultValue="8"/></label><label className="field"><span>Overtime Hours</span><input type="number" step="0.25" min="0" name="overtime_hours" defaultValue="0"/></label></div><label className="field"><span>Reason / Notes</span><input name="notes" placeholder="Phone died, owner time, correction..."/></label><button className="button">Save Manual Time</button></form></div></details></section>

  <section className="section"><div className="section-heading"><div><div className="section-kicker">Recent</div><div className="section-title">Approved Employee Time</div></div></div><div className="surface"><div className="surface-body"><div className="list">{(recentApproved||[]).length===0?<div className="meta">No approved employee time yet.</div>:(recentApproved||[]).map((s:any)=><div className="row" key={s.id}><div><div className="title">{s.crew_members?.name} · {s.projects?.job_number} — {s.projects?.name}</div><div className="meta">{s.work_date}</div></div><span className="status active">Approved</span></div>)}</div></div></div></section>

  <section className="section"><div className="section-heading"><div><div className="section-kicker">Recent</div><div className="section-title">Daily Logs</div></div></div><div className="surface"><div className="surface-body"><div className="list">{(logs||[]).length===0?<div className="meta">No daily logs yet.</div>:(logs||[]).map((l:any)=><div className="row" key={l.id}><div><div className="title">{l.log_date} · {l.projects?.job_number||'Job'}</div><div className="meta">{l.work_completed}</div></div><span className="status">{Number(l.concrete_yards||0).toFixed(1)} CY</span></div>)}</div></div></div></section>
 </div></AppShell>;
}
