'use client';
import {useMemo,useState} from 'react';
import {Accordion,AccordionHeader,AccordionItem,AccordionPanel,Badge,Button,Card,CardHeader,Select,Textarea} from '@fluentui/react-components';
import {createClient} from '@/lib/supabase/client';

type PortalState={
 employee:{id:string;name:string;role:string;can_report_production?:boolean};projects:any[];tasks:any[];assigned_schedule:any[];suggested_tasks?:any[];
 active_shift:any|null;active_task:any|null;active_break:any|null;work_tracking?:any;today_reports?:any[];recent:any[]
};
function position(){return new Promise<GeolocationPosition>((resolve,reject)=>{if(!navigator.geolocation){reject(new Error('This phone does not support GPS.'));return;}navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0});});}
function fmtTime(v?:string|null){if(!v)return '—';if(/^\d{2}:\d{2}/.test(v)){const [h,m]=v.split(':').map(Number);const d=new Date();d.setHours(h,m||0,0,0);return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(d);}return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(v));}
function fmtDay(v:string){return new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric'}).format(new Date(`${v}T12:00:00`));}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function q(v:any,u?:string){return v==null?'':`${Number(v).toLocaleString(undefined,{maximumFractionDigits:2})}${u?` ${u}`:''}`;}
function blockedWork(v:any){return Boolean(v?.work_package_operation_id&&v?.ready_to_start===false);}
const selectClass='h-10 w-full rounded-lg border border-input bg-background px-3 text-sm text-foreground outline-none transition-shadow focus:border-ring focus:ring-3 focus:ring-ring/20';

export function EmployeeClockClient({initial}:{initial:PortalState}){
 const [state,setState]=useState(initial);const [projectId,setProjectId]=useState(initial.active_shift?.project_id||'');const [taskId,setTaskId]=useState(initial.active_task?.production_task_id||'');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const supabase=useMemo(()=>createClient(),[]);
 const project=state.projects.find((p:any)=>p.id===state.active_shift?.project_id);const schedule=state.assigned_schedule||[];const todayRows=schedule.filter((s:any)=>s.schedule_date===today());const suggested=state.suggested_tasks||[];const tracking=state.work_tracking||{};
 async function refresh(){const {data,error}=await supabase.rpc('employee_portal_state');if(error)throw error;const next=data as PortalState;setState(next);if(next.active_task?.production_task_id)setTaskId(next.active_task.production_task_id);}
 async function withGps(fn:(lat:number,lng:number,acc:number)=>Promise<void>){setBusy(true);setMessage('Getting GPS location...');try{const p=await position();await fn(p.coords.latitude,p.coords.longitude,p.coords.accuracy);await refresh();setMessage('');}catch(e:any){setMessage(e?.message||'Could not get your location. Turn on location access and try again.');}finally{setBusy(false);}}
 async function clockIn(id=projectId){if(!id){setMessage('Choose today’s job first.');return;}setProjectId(id);await withGps(async(lat,lng,acc)=>{const {error}=await supabase.rpc('employee_clock_in',{p_project_id:id,p_lat:lat,p_lng:lng,p_accuracy_m:acc,p_device_label:navigator.userAgent.slice(0,180)});if(error)throw error;});}
 async function clockOut(){await withGps(async(lat,lng,acc)=>{const {error}=await supabase.rpc('employee_clock_out',{p_lat:lat,p_lng:lng,p_accuracy_m:acc,p_note:note||null});if(error)throw error;setNote('');});}
 async function startTask(id=taskId){if(!id){setMessage('Choose what you are working on.');return;}setTaskId(id);await withGps(async(lat,lng,acc)=>{const {error}=await supabase.rpc('employee_start_task',{p_task_id:id,p_lat:lat,p_lng:lng,p_accuracy_m:acc});if(error)throw error;});}
 async function startAssignedWork(work:any){if(blockedWork(work)){setMessage(`DO NOT START: ${work.readiness_action||'Office must clear this work first.'}`);return;}if(work.work_package_operation_id){await withGps(async(lat,lng,acc)=>{const {error}=await supabase.rpc('employee_start_work',{p_work_package_operation_id:work.work_package_operation_id,p_lat:lat,p_lng:lng,p_accuracy_m:acc});if(error)throw error;});return;}await startTask(work.id);}
 async function completeAssignedWork(){const id=state.active_task?.work_package_operation_id;if(!id)return;const label=state.active_task?.work_package_name||state.active_task?.task_name||'this work';if(!window.confirm(`Mark ${label} finished? The quantity defined by the office will be credited.`))return;setBusy(true);setMessage('');try{const {error}=await supabase.rpc('employee_complete_work_package_operation',{p_work_package_operation_id:id});if(error)throw error;await refresh();setMessage('Work package finished. Quantity was recorded automatically.');}catch(e:any){setMessage(e?.message||'Could not finish this work package.');}finally{setBusy(false);}}
 async function simpleRpc(name:string,errorText:string){setBusy(true);setMessage('');try{const {error}=await supabase.rpc(name);if(error)throw error;await refresh();}catch(e:any){setMessage(e?.message||errorText);}finally{setBusy(false);}}
 const geoText=state.active_shift?.clock_in_inside_geofence===true?`On jobsite · ${Math.round(Number(state.active_shift.clock_in_distance_ft||0))} ft from pin`:state.active_shift?.clock_in_inside_geofence===false?`Outside jobsite · ${Math.round(Number(state.active_shift.clock_in_distance_ft||0))} ft from pin`:'GPS captured · jobsite pin not set';
 const ticketWork=state.active_task?.work_package_operation_id&&state.active_task?.measurement_method==='ticket';

 return <div className="mx-auto flex min-h-dvh w-full max-w-2xl flex-col gap-4 px-3 py-4 sm:px-4 sm:py-6">
  <header><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">PourTrace</div><h1 className="mt-1 text-2xl font-semibold tracking-tight">{state.employee.name}</h1><p className="mt-1 text-sm text-muted-foreground">Your job and work are already set up. If an inspection or prerequisite is not clear, the work is placed on HOLD before you start it.</p></header>
  {message&&<div className="rounded-lg border border-warning/30 bg-warning/10 px-3 py-3 text-sm text-warning">{message}</div>}

  {!state.active_shift&&todayRows.length>0&&<Card className="border-primary/20"><CardHeader><Badge appearance="outline" className="w-fit">TODAY</Badge></CardHeader><div className="p-4 space-y-4">{todayRows.map((s:any)=>{const blocked=blockedWork(s);return <div className="space-y-3 rounded-lg border border-border p-3" key={s.id}><div><div className="font-semibold">{s.job_number} — {s.project_name}</div><div className="mt-1 text-lg font-medium">{s.work_package_name?s.work_package_name:(s.task_name||s.title)}</div>{s.work_package_name&&<div className="mt-1 text-sm text-muted-foreground">{s.task_name}{s.work_package_location?` · ${s.work_package_location}`:''}{s.measurement_method==='ticket'?' · Concrete tickets track the quantity':''}</div>}<div className="mt-2 text-sm text-muted-foreground">{fmtTime(s.start_time)}{s.address?` · ${s.address}`:''}</div></div>{blocked&&<div className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm"><strong className="text-destructive">DO NOT START — WORK ON HOLD</strong><div className="mt-1 text-muted-foreground">{s.readiness_action||'Office must clear this work first.'}</div></div>}<Button className="h-12 w-full text-sm font-semibold" appearance={blocked?'outline':'primary'} disabled={busy||blocked} onClick={()=>clockIn(s.project_id)}>{blocked?'ON HOLD — CONTACT OFFICE':busy?'CHECKING GPS...':`START MY DAY${s.task_name?` — ${s.task_name.toUpperCase()}`:''}`}</Button>{!blocked&&s.task_name&&<div className="text-xs text-muted-foreground">If this is your only ready assignment, it starts automatically when you clock in.</div>}</div>;})}</div></Card>}

  {!state.active_shift&&<Card><CardHeader><Badge appearance="outline" className="w-fit">OFF THE CLOCK</Badge></CardHeader><div className="p-4 space-y-4">{todayRows.length===0&&<div className="text-sm font-medium text-muted-foreground">Nothing is assigned to you today. Choose the job only if you were told to work there.</div>}<Accordion collapsible className="rounded-lg border border-border"><AccordionItem value="other-job"><AccordionHeader size="small">Choose a different job</AccordionHeader><AccordionPanel className="space-y-3 border-t border-border p-3"><Select appearance="outline" className={selectClass} value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Choose job</option>{state.projects.map((p:any)=><option value={p.id} key={p.id}>{p.job_number} — {p.name}</option>)}</Select><Button className="w-full" appearance="outline" disabled={busy||!projectId} onClick={()=>clockIn()}>{busy?'Checking GPS...':'CLOCK IN TO THIS JOB'}</Button></AccordionPanel></AccordionItem></Accordion><div className="text-xs text-muted-foreground">Location is captured at clock-in and clock-out. Assigned work readiness is checked on the server.</div></div></Card>}

  {state.active_shift&&<><Card className="border-success/30"><CardHeader><Badge appearance="outline" className="w-fit border-success/30 bg-success/10 text-success">CLOCKED IN</Badge><h3>{project?.job_number} — {project?.name}</h3><p>Since {fmtTime(state.active_shift.clock_in_at)}</p></CardHeader><div className="p-4 space-y-3"><div className={`rounded-lg border px-3 py-2 text-sm ${state.active_shift.clock_in_inside_geofence===false?'border-destructive/30 bg-destructive/10 text-destructive':'border-success/30 bg-success/10 text-success'}`}>{geoText}</div>{Number(tracking.paid_work_minutes||0)>=30&&<div className={`rounded-lg border px-3 py-3 ${tracking.needs_attention?'border-warning/30 bg-warning/10':'border-success/30 bg-success/10'}`}><div className="font-semibold">{Math.round(Number(tracking.coverage_percent||0))}% work identified</div><div className="mt-1 text-xs text-muted-foreground">{tracking.needs_attention?'Choose your work below so your time is accurate.':'Your time is being tracked correctly.'}</div></div>}</div></Card>

   {state.active_break?<Card className="border-warning/30"><CardHeader><Badge appearance="outline" className="w-fit border-warning/30 bg-warning/10 text-warning">ON BREAK</Badge><p>Started {fmtTime(state.active_break.started_at)}</p></CardHeader><div className="p-4 space-y-3"><Button className="h-12 w-full" disabled={busy} onClick={()=>simpleRpc('employee_end_break','Could not end break.')}>END BREAK</Button><div className="text-xs text-muted-foreground">Your previous work starts again automatically when the break ends.</div></div></Card>:
   <Card><CardHeader><h3>What are you working on right now?</h3></CardHeader><div className="p-4 space-y-4">{state.active_task?<div className="rounded-lg border border-primary/20 bg-primary/5 p-3"><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">You are on</div><div className="mt-1 font-semibold">{state.active_task.work_package_name||state.active_task.task_name}</div>{state.active_task.work_package_name&&<div className="mt-1 text-sm text-muted-foreground">{state.active_task.task_name}{state.active_task.work_package_location?` · ${state.active_task.work_package_location}`:''}</div>}<div className="mt-1 text-xs text-muted-foreground">Since {fmtTime(state.active_task.started_at)}</div>{state.active_task.work_package_operation_id&&!ticketWork&&<div className="mt-1 text-xs text-muted-foreground">Known scope: {q(state.active_task.planned_quantity,state.active_task.operation_unit)}. You do not need to measure it again.</div>}{ticketWork&&<div className="mt-1 text-xs text-muted-foreground">Concrete delivery tickets track this quantity automatically.</div>}</div>:<div className="rounded-lg border border-warning/30 bg-warning/10 p-3 text-sm text-warning">No work selected. Tap what you are doing now.</div>}
    {ticketWork&&<div className="rounded-lg border border-primary/20 bg-primary/5 p-3 text-sm"><strong>CONCRETE TICKETS TRACK THIS QUANTITY</strong><div className="mt-1 text-muted-foreground">No CY entry and no finish button are needed. When placement is over, switch to the next work or clock out. Production closes from the pour and matched ticket evidence.</div></div>}
    {state.active_task?.work_package_operation_id&&!ticketWork&&<div className="space-y-2"><Button className="h-11 w-full" disabled={busy} onClick={completeAssignedWork}>FINISH THIS WORK</Button><div className="text-xs font-medium text-muted-foreground">Only tap this when the physical package is actually complete. The known quantity is recorded automatically.</div></div>}
    {suggested.length>0&&<div className="space-y-2"><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Today's Work</div>{suggested.map((t:any)=>{const selected=t.work_package_operation_id?state.active_task?.work_package_operation_id===t.work_package_operation_id:(!state.active_task?.work_package_operation_id&&state.active_task?.production_task_id===t.id);const blocked=blockedWork(t);return <Button type="button" appearance={selected?'subtle':'outline'} className="h-auto w-full justify-start whitespace-normal px-3 py-3 text-left" key={t.work_package_operation_id||t.id} disabled={busy||selected||blocked} onClick={()=>startAssignedWork(t)}><span className="flex w-full flex-col items-start gap-1"><strong>{t.work_package_name||t.name}</strong><span className="text-xs font-normal text-muted-foreground">{blocked?`HOLD — ${t.readiness_action||'contact office'}`:t.work_package_name?`${t.name}${t.work_package_location?` · ${t.work_package_location}`:''}`:(selected?'Working on this now':state.active_task?'Switch to this':'Start this work')}</span>{t.work_package_operation_id&&!blocked&&<span className="text-xs font-normal text-muted-foreground">{t.measurement_method==='ticket'?'Quantity from concrete tickets':`${q(t.planned_quantity,t.operation_unit)} already defined`} · {selected?'Working on this now':state.active_task?'Switch to this':'Start this work'}</span>}</span></Button>})}</div>}
    <Accordion collapsible className="rounded-lg border border-border"><AccordionItem value="different-work"><AccordionHeader size="small">Doing unplanned / different work?</AccordionHeader><AccordionPanel className="space-y-3 border-t border-border p-3"><Select appearance="outline" className={selectClass} value={taskId} onChange={e=>setTaskId(e.target.value)}><option value="">Choose work</option>{state.tasks.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</Select><Button className="w-full" appearance="outline" disabled={busy||!taskId} onClick={()=>startTask()}>{state.active_task?'SWITCH TO THIS WORK':'START THIS WORK'}</Button><div className="text-xs text-muted-foreground">Use this only when the planned work package is wrong or the crew was moved to work the office did not schedule.</div></AccordionPanel></AccordionItem></Accordion>
    <Button className="w-full" appearance="outline" disabled={busy} onClick={()=>simpleRpc('employee_start_break','Could not start break.')}>START BREAK</Button>
   </div></Card>}

   <Card><CardHeader><h3>End of day</h3></CardHeader><div className="p-4 space-y-4"><Textarea appearance="outline" rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="Anything the office should know?"/>{tracking.needs_attention&&<div className="rounded-lg border border-warning/30 bg-warning/10 p-3 text-sm text-warning">Some of your day is not assigned to work. You can still clock out, but the office will be asked to review it.</div>}<Button className="h-12 w-full" appearance="primary" disabled={busy} onClick={clockOut}>{busy?'CHECKING GPS...':'CLOCK OUT'}</Button></div></Card>
  </>}

  {schedule.length>0&&<Card><CardHeader><h3>My Schedule</h3></CardHeader><div className="p-4"><div className="divide-y rounded-lg border border-border">{schedule.map((s:any)=>{const blocked=blockedWork(s);return <div className="flex flex-col gap-2 px-3 py-3 sm:flex-row sm:items-center sm:justify-between" key={s.id}><div><div className="font-medium">{fmtDay(s.schedule_date)} · {fmtTime(s.start_time)} · {s.job_number||'Job'}</div><div className="mt-1 text-xs text-muted-foreground">{s.work_package_name?`${s.work_package_name} · ${s.task_name}${s.measurement_method==='ticket'?' · tickets track quantity':''}`:(s.task_name||s.title)}{blocked?` · HOLD: ${s.readiness_action||'contact office'}`:''}</div></div><Badge appearance="outline" className={blocked?'border-destructive/30 bg-destructive/10 text-destructive':s.operation_status==='completed'?'border-success/30 bg-success/10 text-success':s.status==='confirmed'?'border-primary/30 bg-primary/10 text-primary':'text-muted-foreground'}>{blocked?'HOLD':s.operation_status==='completed'?'finished':s.status}</Badge></div>;})}</div></div></Card>}
  <Card><CardHeader><h3>My Recent Time</h3></CardHeader><div className="p-4">{state.recent.length===0?<div className="text-sm text-muted-foreground">No time submitted yet.</div>:<div className="divide-y rounded-lg border border-border">{state.recent.map((r:any)=><div className="flex flex-col gap-2 px-3 py-3 sm:flex-row sm:items-center sm:justify-between" key={r.id}><div><div className="font-medium">{r.work_date} · {r.project}</div><div className="mt-1 text-xs text-muted-foreground">{fmtTime(r.clock_in_at)} – {fmtTime(r.clock_out_at)}{r.task_coverage_percent!=null?` · ${Math.round(Number(r.task_coverage_percent))}% work identified`:''}</div></div><Badge appearance="outline" className={r.requires_review?'border-warning/30 bg-warning/10 text-warning':r.status==='approved'?'border-success/30 bg-success/10 text-success':'text-muted-foreground'}>{r.requires_review?'Needs Review':r.status==='submitted'?'Submitted':r.status}</Badge></div>)}</div>}</div></Card>
 </div>;
}
