'use client';
import {useMemo,useState} from 'react';
import {createClient} from '@/lib/supabase/client';

type PortalState={
 employee:{id:string;name:string;role:string;can_report_production?:boolean};projects:any[];tasks:any[];assigned_schedule:any[];suggested_tasks?:any[];
 active_shift:any|null;active_task:any|null;active_break:any|null;work_tracking?:any;today_reports?:any[];recent:any[]
};
function position(){return new Promise<GeolocationPosition>((resolve,reject)=>{if(!navigator.geolocation){reject(new Error('This phone does not support GPS.'));return;}navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0});});}
function fmtTime(v?:string|null){if(!v)return '—';if(/^\d{2}:\d{2}/.test(v)){const [h,m]=v.split(':').map(Number);const d=new Date();d.setHours(h,m||0,0,0);return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(d);}return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(v));}
function fmtDay(v:string){return new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric'}).format(new Date(`${v}T12:00:00`));}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function q(v:any,u?:string){return v==null?'':`${Number(v).toLocaleString(undefined,{maximumFractionDigits:2})}${u?` ${u}`:''}`;}

export function EmployeeClockClient({initial}:{initial:PortalState}){
 const [state,setState]=useState(initial);const [projectId,setProjectId]=useState(initial.active_shift?.project_id||'');const [taskId,setTaskId]=useState(initial.active_task?.production_task_id||'');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const supabase=useMemo(()=>createClient(),[]);
 const project=state.projects.find((p:any)=>p.id===state.active_shift?.project_id);const schedule=state.assigned_schedule||[];const todayRows=schedule.filter((s:any)=>s.schedule_date===today());const suggested=state.suggested_tasks||[];const tracking=state.work_tracking||{};
 async function refresh(){const {data,error}=await supabase.rpc('employee_portal_state');if(error)throw error;const next=data as PortalState;setState(next);if(next.active_task?.production_task_id)setTaskId(next.active_task.production_task_id);}
 async function withGps(fn:(lat:number,lng:number,acc:number)=>Promise<void>){setBusy(true);setMessage('Getting GPS location...');try{const p=await position();await fn(p.coords.latitude,p.coords.longitude,p.coords.accuracy);await refresh();setMessage('');}catch(e:any){setMessage(e?.message||'Could not get your location. Turn on location access and try again.');}finally{setBusy(false);}}
 async function clockIn(id=projectId){if(!id){setMessage('Choose today’s job first.');return;}setProjectId(id);await withGps(async(lat,lng,acc)=>{const {error}=await supabase.rpc('employee_clock_in',{p_project_id:id,p_lat:lat,p_lng:lng,p_accuracy_m:acc,p_device_label:navigator.userAgent.slice(0,180)});if(error)throw error;});}
 async function clockOut(){await withGps(async(lat,lng,acc)=>{const {error}=await supabase.rpc('employee_clock_out',{p_lat:lat,p_lng:lng,p_accuracy_m:acc,p_note:note||null});if(error)throw error;setNote('');});}
 async function startTask(id=taskId){if(!id){setMessage('Choose what you are working on.');return;}setTaskId(id);await withGps(async(lat,lng,acc)=>{const {error}=await supabase.rpc('employee_start_task',{p_task_id:id,p_lat:lat,p_lng:lng,p_accuracy_m:acc});if(error)throw error;});}
 async function startAssignedWork(work:any){if(work.work_package_operation_id){await withGps(async(lat,lng,acc)=>{const {error}=await supabase.rpc('employee_start_work',{p_work_package_operation_id:work.work_package_operation_id,p_lat:lat,p_lng:lng,p_accuracy_m:acc});if(error)throw error;});return;}await startTask(work.id);}
 async function completeAssignedWork(){const id=state.active_task?.work_package_operation_id;if(!id)return;const label=state.active_task?.work_package_name||state.active_task?.task_name||'this work';if(!window.confirm(`Mark ${label} finished? Carez will credit the quantity already defined by the office.`))return;setBusy(true);setMessage('');try{const {error}=await supabase.rpc('employee_complete_work_package_operation',{p_work_package_operation_id:id});if(error)throw error;await refresh();setMessage('Work package finished. Quantity was recorded automatically.');}catch(e:any){setMessage(e?.message||'Could not finish this work package.');}finally{setBusy(false);}}
 async function simpleRpc(name:string,errorText:string){setBusy(true);setMessage('');try{const {error}=await supabase.rpc(name);if(error)throw error;await refresh();}catch(e:any){setMessage(e?.message||errorText);}finally{setBusy(false);}}
 const geoText=state.active_shift?.clock_in_inside_geofence===true?`On jobsite · ${Math.round(Number(state.active_shift.clock_in_distance_ft||0))} ft from pin`:state.active_shift?.clock_in_inside_geofence===false?`Outside jobsite · ${Math.round(Number(state.active_shift.clock_in_distance_ft||0))} ft from pin`:'GPS captured · jobsite pin not set';
 return <div className="employee-clock-shell">
  <header className="employee-clock-head"><div className="section-kicker">CAREZ CONCRETE</div><h1>{state.employee.name}</h1><p>Your job and work are already set up. Clock in, keep your current work correct, and mark the physical work finished when it is actually done.</p></header>
  {message&&<div className="alert warn">{message}</div>}

  {!state.active_shift&&todayRows.length>0&&<section className="employee-clock-card today-card"><div className="employee-clock-status">TODAY</div>{todayRows.map((s:any)=><div className="today-assignment" key={s.id}><div className="employee-job">{s.job_number} — {s.project_name}</div><div className="today-task">{s.work_package_name?s.work_package_name:(s.task_name||s.title)}</div>{s.work_package_name&&<div className="employee-help strong-help">{s.task_name}{s.work_package_location?` · ${s.work_package_location}`:''}</div>}<div className="employee-clock-time">{fmtTime(s.start_time)}{s.address?` · ${s.address}`:''}</div><button className="clock-button clock-in" disabled={busy} onClick={()=>clockIn(s.project_id)}>{busy?'CHECKING GPS...':`START MY DAY${s.task_name?` — ${s.task_name.toUpperCase()}`:''}`}</button>{s.task_name&&<div className="employee-help">If this is your only assigned work, it starts automatically when you clock in.</div>}</div>)}</section>}

  {!state.active_shift&&<section className="employee-clock-card"><div className="employee-clock-status">OFF THE CLOCK</div>{todayRows.length===0&&<div className="employee-help strong-help">Nothing is assigned to you today. Choose the job only if you were told to work there.</div>}<details><summary className="employee-secondary-summary">Choose a different job</summary><label className="field"><span>Job</span><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Choose job</option>{state.projects.map((p:any)=><option value={p.id} key={p.id}>{p.job_number} — {p.name}</option>)}</select></label><button className="clock-button secondary" disabled={busy||!projectId} onClick={()=>clockIn()}>{busy?'Checking GPS...':'CLOCK IN TO THIS JOB'}</button></details><div className="employee-help">Location is captured at clock-in and clock-out for jobsite verification.</div></section>}

  {state.active_shift&&<><section className="employee-clock-card active"><div className="employee-clock-status">CLOCKED IN</div><div className="employee-job">{project?.job_number} — {project?.name}</div><div className="employee-clock-time">Since {fmtTime(state.active_shift.clock_in_at)}</div><div className={`gps-chip ${state.active_shift.clock_in_inside_geofence===false?'bad':'good'}`}>{geoText}</div>{Number(tracking.paid_work_minutes||0)>=30&&<div className={`tracking-strip ${tracking.needs_attention?'bad':'good'}`}><strong>{Math.round(Number(tracking.coverage_percent||0))}% work identified</strong><span>{tracking.needs_attention?'Choose your work below so your time is accurate.':'Your time is being tracked correctly.'}</span></div>}</section>

   {state.active_break?<section className="employee-clock-card break"><div className="employee-clock-status">ON BREAK</div><div className="employee-clock-time">Started {fmtTime(state.active_break.started_at)}</div><button className="clock-button" disabled={busy} onClick={()=>simpleRpc('employee_end_break','Could not end break.')}>END BREAK</button><div className="employee-help">Your previous work starts again automatically when the break ends.</div></section>:
   <section className="employee-clock-card"><div className="employee-card-title">What are you working on right now?</div>{state.active_task?<div className="current-work"><span>YOU ARE ON</span><strong>{state.active_task.work_package_name||state.active_task.task_name}</strong>{state.active_task.work_package_name&&<small>{state.active_task.task_name}{state.active_task.work_package_location?` · ${state.active_task.work_package_location}`:''}</small>}<small>Since {fmtTime(state.active_task.started_at)}</small>{state.active_task.work_package_operation_id&&<small>Known scope: {q(state.active_task.planned_quantity,state.active_task.operation_unit)}. You do not need to measure it again.</small>}</div>:<div className="attention-box">No work selected. Tap what you are doing now.</div>}
    {state.active_task?.work_package_operation_id&&<div className="suggested-work"><button type="button" className="clock-button" disabled={busy} onClick={completeAssignedWork}>FINISH THIS WORK</button><div className="employee-help strong-help">Only tap this when the physical package is actually complete. Carez records the known quantity automatically.</div></div>}
    {suggested.length>0&&<div className="suggested-work"><div className="employee-clock-status">TODAY'S WORK</div>{suggested.map((t:any)=>{const selected=t.work_package_operation_id?state.active_task?.work_package_operation_id===t.work_package_operation_id:(!state.active_task?.work_package_operation_id&&state.active_task?.production_task_id===t.id);return <button type="button" className={`work-choice ${selected?'selected':''}`} key={t.work_package_operation_id||t.id} disabled={busy||selected} onClick={()=>startAssignedWork(t)}><strong>{t.work_package_name||t.name}</strong><span>{t.work_package_name?`${t.name}${t.work_package_location?` · ${t.work_package_location}`:''}`:(selected?'Working on this now':state.active_task?'Switch to this':'Start this work')}</span>{t.work_package_operation_id&&<span>{q(t.planned_quantity,t.operation_unit)} already defined · {selected?'Working on this now':state.active_task?'Switch to this':'Start this work'}</span>}</button>})}</div>}
    <details><summary className="employee-secondary-summary">Doing unplanned / different work?</summary><label className="field"><span>What are you doing?</span><select value={taskId} onChange={e=>setTaskId(e.target.value)}><option value="">Choose work</option>{state.tasks.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button className="clock-button secondary" disabled={busy||!taskId} onClick={()=>startTask()}>{state.active_task?'SWITCH TO THIS WORK':'START THIS WORK'}</button><div className="employee-help">Use this only when the planned work package is wrong or the crew was moved to work the office did not schedule.</div></details>
    <button className="clock-button secondary" disabled={busy} onClick={()=>simpleRpc('employee_start_break','Could not start break.')}>START BREAK</button>
   </section>}

   <section className="employee-clock-card"><label className="field"><span>End-of-day note (optional)</span><textarea rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="Anything the office should know?"/></label>{tracking.needs_attention&&<div className="attention-box">Some of your day is not assigned to work. You can still clock out, but the office will be asked to review it.</div>}<button className="clock-button clock-out" disabled={busy} onClick={clockOut}>{busy?'CHECKING GPS...':'CLOCK OUT'}</button></section>
  </>}

  {schedule.length>0&&<section className="employee-clock-card"><div className="employee-card-title">My Schedule</div><div className="list">{schedule.map((s:any)=><div className="row" key={s.id}><div><div className="title">{fmtDay(s.schedule_date)} · {fmtTime(s.start_time)} · {s.job_number||'Carez'}</div><div className="meta">{s.work_package_name?`${s.work_package_name} · ${s.task_name}`:(s.task_name||s.title)}</div></div><span className={`status ${s.operation_status==='completed'?'completed':s.status==='confirmed'?'active':''}`}>{s.operation_status==='completed'?'finished':s.status}</span></div>)}</div></section>}
  <section className="employee-clock-card"><div className="employee-card-title">My Recent Time</div><div className="list">{state.recent.length===0?<div className="meta">No time submitted yet.</div>:state.recent.map((r:any)=><div className="row" key={r.id}><div><div className="title">{r.work_date} · {r.project}</div><div className="meta">{fmtTime(r.clock_in_at)} – {fmtTime(r.clock_out_at)}{r.task_coverage_percent!=null?` · ${Math.round(Number(r.task_coverage_percent))}% work identified`:''}</div></div><span className={`status ${r.requires_review?'on-hold':r.status==='approved'?'active':''}`}>{r.requires_review?'Needs Review':r.status==='submitted'?'Submitted':r.status}</span></div>)}</div></section>
 </div>;
}
