import {redirect} from 'next/navigation';
import {AppShell} from '@/components/AppShell';
import {Badge,Button,Field,Input,Select,Textarea} from '@fluentui/react-components';
import {ScopeDriftTabs} from './ScopeDriftTabs';
import {createClient} from '@/lib/supabase/server';
import {captureScopeDriftSignal,addManualScopeDrift,classifyScopeDrift,createDraftChangeOrderFromDrift} from './actions';

const n=(v:any)=>Number(v||0);
const q=(v:any,u?:string)=>v==null?'—':`${n(v).toLocaleString(undefined,{maximumFractionDigits:2})}${u?` ${u}`:''}`;
const selectClass='h-9 w-full rounded-md border border-input bg-background px-3 text-sm text-foreground outline-none transition-shadow focus:border-ring focus:ring-2 focus:ring-ring/20 disabled:cursor-not-allowed disabled:opacity-50';

export default async function ScopeDriftPage(){
 const supabase=await createClient();
 const {data:{user}}=await supabase.auth.getUser();
 if(!user)redirect('/login');
 const {data:p}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();
 if(!p?.company_id)redirect('/login');
 if(p.role==='employee')redirect('/employee');
 const [{data:signals},{data:events},{data:projects},{data:ops}]=await Promise.all([
  supabase.from('scope_drift_inbox').select('*').eq('company_id',p.company_id).order('work_date',{ascending:false}),
  supabase.from('scope_drift_events').select('*,projects(job_number,name),change_orders(co_number,title,status)').eq('company_id',p.company_id).order('detected_at',{ascending:false}).limit(100),
  supabase.from('projects').select('id,job_number,name').eq('company_id',p.company_id).in('status',['active','on_hold']).order('job_number'),
  supabase.from('work_package_start_readiness').select('operation_id,project_id,job_number,package_name,field_label,task_name').eq('company_id',p.company_id).in('operation_status',['planned','in_progress','on_hold']).order('job_number').order('package_name')
 ]);
 const inbox=(signals||[]).filter((x:any)=>x.uncaptured),captured=events||[],potential=captured.filter((x:any)=>x.status==='potential_change'),linked=captured.filter((x:any)=>x.status==='linked_change_order'),internal=captured.filter((x:any)=>['explained','dismissed'].includes(x.status));

 return <AppShell userName={p.full_name||user.email||'Owner'}>
  <div className="mx-auto flex min-h-0 w-full max-w-screen-2xl flex-col gap-3 lg:h-full">
   <header className="carez-page-heading flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
    <div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Change protection</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Scope Drift</h1><p className="mt-1 max-w-5xl text-sm text-muted-foreground">Carez watches unplanned crew work, labor overruns and quantity changes, then separates real contract changes from rework, productivity problems and estimate misses.</p></div>
    <div className="flex flex-wrap gap-2"><Button as="a" href="/change-orders" appearance="secondary" size="small">Change Orders</Button><Button as="a" href="/production" appearance="secondary" size="small">Production</Button></div>
   </header>

   <section className="grid shrink-0 gap-2 md:grid-cols-2 xl:grid-cols-4"><Metric label="New Signals" value={inbox.length} help="Field facts not yet classified." tone={inbox.length?'destructive':'success'}/><Metric label="Potential CO" value={potential.length} help="Classified as contract-scope change." tone={potential.length?'warning':'success'}/><Metric label="Linked CO" value={linked.length} help="Protected with a draft or active change order."/><Metric label="Internal / Explained" value={internal.length} help="Kept for learning, not billed to the customer."/></section>

   <ScopeDriftTabs defaultTab={inbox.length?'signals':'reviewed'} signalsCount={inbox.length} reviewedCount={captured.length}>
   <div className="min-h-0 p-3">
   <article className="border border-border bg-card p-4"><header><h3>Record Field Change</h3><p>Use this when a superintendent, owner, plan revision or unforeseen condition changes the work before automatic signals catch it.</p></header><div><form action={addManualScopeDrift} className="grid gap-3"><div className="grid gap-3 md:grid-cols-2"><Field label="Job"><Select name="project_id" required defaultValue="" className={selectClass}><option value="" disabled>Choose job</option>{(projects||[]).map((x:any)=><option key={x.id} value={x.id}>{x.job_number} — {x.name}</option>)}</Select></Field><Field label="Work Package Operation (optional)"><Select name="work_package_operation_id" defaultValue="" className={selectClass}><option value="">General project change</option>{(ops||[]).map((x:any)=><option key={x.operation_id} value={x.operation_id}>{x.job_number} — {x.package_name} — {x.field_label||x.task_name}</option>)}</Select></Field></div><div className="grid gap-3 md:grid-cols-3"><Field label="What Happened?"><Input appearance="underline" name="title" required placeholder="GC directed thicker slab at loading area"/></Field><Field label="Classification"><Select name="classification" defaultValue="gc_direction" className={selectClass}><option value="customer_change">Customer change</option><option value="gc_direction">GC direction</option><option value="design_change">Design change</option><option value="unforeseen_condition">Unforeseen condition</option><option value="unknown">Need review</option></Select></Field><Field label="Date"><Input appearance="underline" type="date" name="work_date" defaultValue={new Date().toISOString().slice(0,10)}/></Field></div><Field label="Details / Direction Received"><Textarea name="details" rows={2}/></Field><div><Button type="submit">Record Potential Change</Button></div></form></div></article>
   </div>

   <div className="min-h-0 p-3">
   {inbox.length>0&&<section className="space-y-4"><SectionHeading kicker="Automatic detection" title="New Field Signals" description="A cost overrun is not automatically a change order. Capture the signal, then classify why it happened."/><div className="grid gap-4">{inbox.map((x:any)=><article key={x.signal_key} className="border border-border bg-card px-4"><header className="grid gap-3 border-b py-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-start"><div><h3>{x.title}</h3><p className="mt-1">{x.work_date} · {String(x.source_type).replaceAll('_',' ')}</p></div><SignalBadge severity={x.severity}/></header><div className="space-y-4 py-4"><p className="text-sm text-muted-foreground">{x.details}</p><div className="grid gap-3 sm:grid-cols-2">{x.labor_hours!=null&&<MiniMetric label="Labor Signal" value={q(x.labor_hours,'MH')}/>} {x.quantity_variance!=null&&<MiniMetric label="Quantity Variance" value={q(x.quantity_variance,x.unit)}/>}</div><form action={captureScopeDriftSignal}><input type="hidden" name="signal_key" value={x.signal_key}/><input type="hidden" name="project_id" value={x.project_id}/><input type="hidden" name="work_package_operation_id" value={x.work_package_operation_id||''}/><input type="hidden" name="source_type" value={x.source_type}/><input type="hidden" name="work_date" value={x.work_date||''}/><input type="hidden" name="severity" value={x.severity}/><input type="hidden" name="title" value={x.title}/><input type="hidden" name="details" value={x.details||''}/><input type="hidden" name="labor_hours" value={x.labor_hours??''}/><input type="hidden" name="quantity_variance" value={x.quantity_variance??''}/><input type="hidden" name="unit" value={x.unit||''}/><Button type="submit" size="small">Review This Signal</Button></form></div></article>)}</div></section>}
   {inbox.length===0?<div className="min-h-44 border border-border bg-muted/10"><div><h3>No new field signals</h3></div></div>:null}
   </div>

   <div className="min-h-0 p-3">
   <section className="space-y-4"><SectionHeading kicker="Classify before billing" title="Reviewed Scope Drift" description="Customer, GC, design and unforeseen changes can become a draft CO. Rework, estimate misses and productivity issues stay internal and feed learning instead."/>{captured.length===0?<div className="min-h-44 border border-border bg-muted/10"><div><h3>No reviewed events yet</h3></div></div>:<div className="grid gap-4">{captured.map((e:any)=><article key={e.id} className="border border-border bg-card px-4"><header className="grid gap-3 border-b py-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-start"><div><h3>{e.projects?.job_number} — {e.title}</h3><p className="mt-1">{e.projects?.name} · {String(e.source_type).replaceAll('_',' ')}</p></div><EventStatus status={e.status}/></header><div className="space-y-4 py-4"><p className="text-sm text-muted-foreground">{e.details||'No additional detail recorded.'}</p>{e.change_orders&&<div className="rounded-lg border border-primary/20 bg-primary/5 px-3 py-2 text-sm"><strong>{e.change_orders.co_number} — {e.change_orders.title}</strong><div className="mt-1 text-xs text-muted-foreground">Status: {e.change_orders.status}</div></div>}<form action={classifyScopeDrift} className="grid gap-3"><input type="hidden" name="event_id" value={e.id}/><div className="grid gap-3 md:grid-cols-2"><Field label="Why did this happen?"><Select name="classification" defaultValue={e.classification} className={selectClass}><option value="unknown">Need review</option><option value="customer_change">Customer changed scope</option><option value="gc_direction">GC directed extra/different work</option><option value="design_change">Plan / design changed</option><option value="unforeseen_condition">Unforeseen condition</option><option value="rework">Rework</option><option value="estimate_miss">Estimate / takeoff miss</option><option value="productivity">Productivity issue</option><option value="internal_error">Carez internal error</option><option value="no_scope_change">No scope change</option></Select></Field><Field label="Resolution Note"><Input appearance="underline" name="resolution_note" defaultValue={e.resolution_note||''} placeholder="Who directed it, why it is internal, etc."/></Field></div><div><Button type="submit" appearance="secondary" size="small">Save Classification</Button></div></form>{e.status==='potential_change'&&!e.change_order_id&&<form action={createDraftChangeOrderFromDrift}><input type="hidden" name="event_id" value={e.id}/><Button type="submit" size="small">Create Draft Change Order</Button></form>}</div></article>)}</div>}</section>
   </div>
   </ScopeDriftTabs>
  </div>
 </AppShell>;
}

function SectionHeading({kicker,title,description}:{kicker:string;title:string;description:string}){return <div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{kicker}</p><h2 className="mt-1 text-lg font-semibold">{title}</h2><p className="mt-1 max-w-5xl text-sm text-muted-foreground">{description}</p></div>;}
function Metric({label,value,help,tone='default'}:{label:string;value:number;help:string;tone?:'default'|'success'|'warning'|'destructive'}){const toneClass=tone==='success'?'text-success':tone==='warning'?'text-warning':tone==='destructive'?'text-destructive':'text-foreground';return <article className={`border border-border bg-card py-4 shadow-none ${tone==='warning'?'border-warning/30':tone==='destructive'?'border-destructive/30':''}`}><header className="gap-1 px-4"><p className="text-xs font-medium">{label}</p><h3 className={`font-mono text-2xl font-semibold tabular-nums ${toneClass}`}>{value}</h3></header><div className="px-4 text-xs text-muted-foreground">{help}</div></article>;}
function MiniMetric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-border p-3"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 font-mono text-lg font-semibold tabular-nums">{value}</div></div>;}
function SignalBadge({severity}:{severity:string}){const cls=severity==='critical'?'border-destructive/30 bg-destructive/10 text-destructive':severity==='high'?'border-warning/30 bg-warning/10 text-warning':'text-muted-foreground';return <Badge appearance="outline" className={cls}>{severity}</Badge>;}
function EventStatus({status}:{status:string}){const cls=status==='linked_change_order'?'border-success/30 bg-success/10 text-success':status==='potential_change'?'border-warning/30 bg-warning/10 text-warning':status==='open'?'border-destructive/30 bg-destructive/10 text-destructive':'text-muted-foreground';return <Badge appearance="outline" className={cls}>{String(status).replaceAll('_',' ')}</Badge>;}
