import {redirect} from 'next/navigation';
import Link from 'next/link';
import {Badge} from '@/components/ui/badge';
import {Button,buttonVariants} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle,SheetTrigger} from '@/components/ui/sheet';
import {Empty,EmptyDescription,EmptyHeader,EmptyTitle} from '@/components/ui/empty';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {createClient} from '@/lib/supabase/server';
import {createPayrollRun,approvePayrollRun,processPayrollRun,voidPayrollRun} from '@/app/payroll/actions';

const money=(n:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const num=(n:any)=>Number(n||0);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());

function Metric({label,value}:{label:string;value:string}){return <div className="min-w-0 bg-card px-3 py-2"><span className="text-xs text-muted-foreground">{label}</span><strong className="block font-mono text-base tabular-nums sm:text-lg">{value}</strong></div>;}

export default async function PayrollPage(){
  const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser();
  if(!user)redirect('/login');
  const {data:p}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();
  if(!p?.company_id)redirect('/login');
  if(p.role==='employee')redirect('/employee');

  const [{data:s},{data:workers},{data:runs},{data:lines}]=await Promise.all([
    supabase.from('company_payroll_cash_summary').select('*').eq('company_id',p.company_id).maybeSingle(),
    supabase.from('payroll_unprocessed_worker_summary').select('*').eq('company_id',p.company_id).order('worker_name'),
    supabase.from('payroll_run_financial_summary').select('*').eq('company_id',p.company_id).order('period_end',{ascending:false}),
    supabase.from('payroll_run_lines').select('*').eq('company_id',p.company_id).order('work_date'),
  ]);

  const runLines=new Map<string,any[]>();
  for(const l of lines||[]){const a=runLines.get(l.payroll_run_id)||[];a.push(l);runLines.set(l.payroll_run_id,a);}
  const funding=num(s?.total_open_payroll_requirement);
  const gross=num(s?.unprocessed_gross_wages);
  const taxes=num(s?.unprocessed_employer_payroll_taxes);
  const li=num(s?.unprocessed_li);

  return <><div className="mx-auto flex w-full max-w-screen-2xl flex-col gap-4">
    <header className="carez-page-heading flex flex-wrap items-center justify-between gap-3"><h1>Crew pay</h1><div className="flex flex-wrap gap-2"><Link className={buttonVariants({variant:'outline',size:'sm'})} href="/field/review">Time review</Link><Link className={buttonVariants({variant:'outline',size:'sm'})} href="/cashflow">Cash flow</Link><Dialog><DialogTrigger render={<Button size="sm"/>}>Create pay period</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create pay period</DialogTitle><DialogDescription>Group approved W-2 time into a pay period before funding and processing payroll.</DialogDescription></DialogHeader><form action={createPayrollRun} className="grid gap-3"><div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="payroll-period-start">Period Start</Label><Input id="payroll-period-start" type="date" name="period_start" required/></div><div className="grid gap-2"><Label htmlFor="payroll-period-end">Period End</Label><Input id="payroll-period-end" type="date" name="period_end" required/></div></div><div className="grid gap-2"><Label htmlFor="payroll-pay-date">Expected Pay Date</Label><Input id="payroll-pay-date" type="date" name="pay_date" defaultValue={today()}/></div><div className="grid gap-2"><Label htmlFor="payroll-note">Note</Label><Input id="payroll-note" name="notes"/></div><Button type="submit" className="w-fit">Create Pay Period</Button></form></DialogContent></Dialog></div></header>

    <div className="grid grid-cols-2 gap-px border border-border bg-border [&>*:first-child]:col-span-2 sm:grid-cols-3 sm:[&>*:first-child]:col-span-1 xl:grid-cols-5" aria-label="Payroll summary"><Metric label="Payroll cash needed" value={money(funding)}/><Metric label="Gross wages" value={money(gross)}/><Metric label="Employer taxes" value={money(taxes)}/><Metric label="L&I cost" value={money(li)}/><Metric label="Workers waiting" value={String((workers||[]).length)}/></div>

    <section className="space-y-2" aria-labelledby="payroll-ready"><div className="carez-page-heading"><h2 id="payroll-ready">Approved time waiting</h2></div>{(workers||[]).length===0?<Empty className="border border-border"><EmptyHeader><EmptyTitle>No approved W-2 time waiting for payroll</EmptyTitle><EmptyDescription>Employees clock time, you approve it in Field, then it appears here.</EmptyDescription></EmptyHeader></Empty>:<><div className="hidden overflow-x-auto border border-border md:block"><Table><TableHeader><TableRow><TableHead>Worker</TableHead><TableHead>Hours</TableHead><TableHead>Gross Wages</TableHead><TableHead>Employer Taxes</TableHead><TableHead>L&amp;I</TableHead><TableHead>Cash to Protect</TableHead></TableRow></TableHeader><TableBody>{(workers||[]).map((w:any)=><TableRow key={w.crew_member_id}><TableCell><div className="font-medium">{w.worker_name}</div><div className="mt-1 text-xs text-muted-foreground">{w.first_unprocessed_date} – {w.last_unprocessed_date}</div></TableCell><TableCell className="tabular-nums">{(num(w.regular_hours)+num(w.overtime_hours)).toFixed(2)}<div className="mt-1 text-xs text-muted-foreground">OT {num(w.overtime_hours).toFixed(2)}</div></TableCell><TableCell className="tabular-nums">{money(w.gross_wages)}</TableCell><TableCell className="tabular-nums">{money(w.employer_payroll_taxes)}</TableCell><TableCell className="tabular-nums">{money(w.employer_li)}</TableCell><TableCell className="font-semibold tabular-nums">{money(w.payroll_funding_requirement)}</TableCell></TableRow>)}</TableBody></Table></div><div className="divide-y border border-border md:hidden">{(workers||[]).map((w:any)=><div key={w.crew_member_id} className="flex items-center justify-between gap-3 px-3 py-2"><div className="min-w-0"><strong className="block truncate text-sm">{w.worker_name}</strong><span className="block text-xs text-muted-foreground">{(num(w.regular_hours)+num(w.overtime_hours)).toFixed(2)} hr · OT {num(w.overtime_hours).toFixed(2)}</span></div><strong className="font-mono text-sm tabular-nums">{money(w.payroll_funding_requirement)}</strong></div>)}</div></>}
    </section>

    <section className="space-y-2" aria-labelledby="payroll-history"><div className="carez-page-heading"><h2 id="payroll-history">Pay periods</h2></div>{(runs||[]).length===0?<Empty className="border border-border"><EmptyHeader><EmptyTitle>No pay periods yet</EmptyTitle><EmptyDescription>Created pay periods will appear here.</EmptyDescription></EmptyHeader></Empty>:<div className="divide-y border border-border">{(runs||[]).map((r:any)=>{const rows=(runLines.get(r.payroll_run_id)||[]).filter((x:any)=>x.active);return <Sheet key={r.payroll_run_id}><div className="flex flex-wrap items-center justify-between gap-3 px-3 py-2"><div className="min-w-0"><strong className="block truncate text-sm">{r.period_start} – {r.period_end}</strong><span className="block truncate text-xs text-muted-foreground">Pay date {r.pay_date||'not set'} · {r.worker_count} workers · {r.timecard_count} timecards</span></div><div className="flex items-center gap-2"><strong className="font-mono text-xs tabular-nums">{money(r.payroll_funding_requirement)}</strong><Badge variant="outline" className={r.status==='processed'?'border-success/30 bg-success/10 text-success':r.status==='approved'?'border-primary/30 bg-primary/10 text-primary':r.status==='void'?'border-destructive/30 bg-destructive/10 text-destructive':'text-muted-foreground'}>{r.status}</Badge><SheetTrigger render={<Button variant="outline" size="sm"/>}>View / Review</SheetTrigger></div></div><SheetContent className="w-full overflow-hidden sm:max-w-3xl"><SheetHeader><SheetTitle>{r.period_start} – {r.period_end}</SheetTitle><SheetDescription>Pay date {r.pay_date||'not set'} · {r.worker_count} workers</SheetDescription></SheetHeader><div className="grid min-h-0 gap-4 overflow-y-auto px-4 pb-6">
          <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-lg border border-border bg-muted/20 p-3"><div className="text-xs font-medium text-muted-foreground">Gross Wages</div><div className="mt-1 text-lg font-semibold tabular-nums">{money(r.gross_wages)}</div></div><div className="rounded-lg border border-border bg-muted/20 p-3"><div className="text-xs font-medium text-muted-foreground">Employer Taxes</div><div className="mt-1 text-lg font-semibold tabular-nums">{money(r.employer_payroll_taxes)}</div></div><div className="rounded-lg border border-border bg-muted/20 p-3"><div className="text-xs font-medium text-muted-foreground">L&amp;I</div><div className="mt-1 text-lg font-semibold tabular-nums">{money(r.employer_li)}</div></div><div className={`rounded-lg border border-border bg-muted/20 p-3 ${r.status==='processed'?'text-success':'text-primary'}`}><div className="text-xs font-medium text-muted-foreground">Cash Requirement</div><div className="mt-1 text-lg font-semibold tabular-nums">{money(r.payroll_funding_requirement)}</div></div></div>

          {rows.length>0&&<details className="rounded-lg border border-border"><summary className="cursor-pointer list-none px-3 py-3 text-sm font-medium">Show Worker Detail</summary><div className="overflow-x-auto border-t border-border"><Table><TableHeader><TableRow><TableHead>Worker</TableHead><TableHead>Date</TableHead><TableHead>Hours</TableHead><TableHead>Gross</TableHead><TableHead>Funding</TableHead></TableRow></TableHeader><TableBody>{rows.map((x:any)=><TableRow key={x.id}><TableCell>{x.worker_name}</TableCell><TableCell>{x.work_date}</TableCell><TableCell className="tabular-nums">{(num(x.regular_hours)+num(x.overtime_hours)).toFixed(2)}</TableCell><TableCell className="tabular-nums">{money(x.gross_wages)}</TableCell><TableCell className="tabular-nums">{money(x.payroll_funding_requirement)}</TableCell></TableRow>)}</TableBody></Table></div></details>}

          <div className="flex flex-wrap gap-2 border-t border-border pt-3">{r.status==='draft'&&<Dialog><DialogTrigger render={<Button size="sm"/>}>Approve funding</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Approve payroll funding?</DialogTitle><DialogDescription>Approve {money(r.payroll_funding_requirement)} for this pay period after reviewing the worker detail.</DialogDescription></DialogHeader><form action={approvePayrollRun}><input type="hidden" name="payroll_run_id" value={r.payroll_run_id}/><Button type="submit">Approve payroll funding</Button></form></DialogContent></Dialog>}{r.status==='approved'&&<Dialog><DialogTrigger render={<Button size="sm"/>}>Mark processed</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Mark payroll processed</DialogTitle><DialogDescription>Use only after this payroll run has actually been processed.</DialogDescription></DialogHeader><form action={processPayrollRun} className="grid gap-3"><input type="hidden" name="payroll_run_id" value={r.payroll_run_id}/><div className="grid gap-2"><Label htmlFor={`payroll-cash-${r.payroll_run_id}`}>Actual Cash Paid (optional)</Label><Input id={`payroll-cash-${r.payroll_run_id}`} type="number" min="0" step="0.01" name="actual_cash_paid" placeholder={num(r.payroll_funding_requirement).toFixed(2)}/></div><div className="grid gap-2"><Label htmlFor={`payroll-reference-${r.payroll_run_id}`}>Payroll / Check Reference</Label><Input id={`payroll-reference-${r.payroll_run_id}`} name="reference_number"/></div><Button type="submit" className="w-fit">Mark Payroll Processed</Button></form></DialogContent></Dialog>}{['draft','approved'].includes(r.status)&&<Dialog><DialogTrigger render={<Button variant="outline" size="sm"/>}>Void</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Void pay period?</DialogTitle><DialogDescription>This removes the run from active funding while preserving the underlying approved time.</DialogDescription></DialogHeader><form action={voidPayrollRun}><input type="hidden" name="payroll_run_id" value={r.payroll_run_id}/><Button type="submit" variant="destructive">Void pay period</Button></form></DialogContent></Dialog>}</div></div></SheetContent></Sheet>;})}</div>}</section>
  </div></>;
}
