'use server';
import {revalidatePath} from 'next/cache';
import {createClient} from '@/lib/supabase/server';
async function ownerContext(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Not signed in');const {data:profile}=await supabase.from('profiles').select('company_id,role').eq('id',user.id).single();if(!profile?.company_id||profile.role==='employee')throw new Error('Owner access required');return{supabase,user,companyId:profile.company_id};}
export async function createScheduleItem(formData:FormData){
 let projectId=String(formData.get('project_id')||''),title=String(formData.get('title')||'').trim(),productionTaskId=String(formData.get('production_task_id')||'');const scheduleDate=String(formData.get('schedule_date')||''),itemType=String(formData.get('item_type')||'work'),operationId=String(formData.get('work_package_operation_id')||'');if(!projectId||!scheduleDate)return;
 const {supabase,user,companyId}=await ownerContext();
 if(operationId){const {data:op}=await supabase.from('work_package_operations').select('id,production_task_id,field_label,planned_quantity,unit,work_packages!inner(project_id,name,location),production_tasks!inner(name)').eq('id',operationId).eq('company_id',companyId).single();if(!op)throw new Error('Work package operation not found.');const pkg:any=op.work_packages,task:any=op.production_tasks;if(pkg?.project_id!==projectId)throw new Error('The selected work package belongs to a different job.');productionTaskId=op.production_task_id;title=title||op.field_label||`${task?.name||'Work'} — ${pkg?.name||'Work Package'}`;}
 if(!title){if(itemType==='work')throw new Error('Choose a work package or describe what the crew is doing.');return;}
 if(itemType==='work'&&!productionTaskId)throw new Error('Choose a work package operation or the plain-language work the crew will do.');
 const {data:readiness}=await supabase.from('project_job_readiness_summary').select('award_setup_applies,job_ready,readiness_reason').eq('project_id',projectId).eq('company_id',companyId).maybeSingle();if(readiness?.award_setup_applies&&!readiness.job_ready)throw new Error(`Job is on setup hold: ${readiness.readiness_reason||'finish Job Setup first'}.`);
 const {data:item,error}=await supabase.from('work_schedule_items').insert({company_id:companyId,project_id:projectId,schedule_date:scheduleDate,item_type:itemType,title,production_task_id:productionTaskId||null,work_package_operation_id:operationId||null,pour_plan_id:String(formData.get('pour_plan_id')||'')||null,start_time:String(formData.get('start_time')||'')||null,end_time:String(formData.get('end_time')||'')||null,crew_needed:Number(formData.get('crew_needed')||0),status:String(formData.get('status')||'planned'),notes:String(formData.get('notes')||'').trim()||null,created_by:user.id}).select('id').single();if(error)throw new Error(error.message);
 const crewIds=formData.getAll('crew_member_ids').map(String).filter(Boolean);if(item&&crewIds.length){const {error:assignmentError}=await supabase.from('work_schedule_assignments').insert(crewIds.map(crew_member_id=>({company_id:companyId,schedule_item_id:item.id,crew_member_id})));if(assignmentError)throw new Error(assignmentError.message);}
 for(const p of ['/schedule','/projects','/employee','/production','/production/work-packages','/'])revalidatePath(p);
}
export async function updateScheduleStatus(formData:FormData){const id=String(formData.get('id')||''),status=String(formData.get('status')||'planned');if(!id)return;const {supabase,companyId}=await ownerContext();await supabase.from('work_schedule_items').update({status,updated_at:new Date().toISOString()}).eq('id',id).eq('company_id',companyId);revalidatePath('/schedule');revalidatePath('/employee');revalidatePath('/production/work-packages');}
export async function deleteScheduleItem(formData:FormData){const id=String(formData.get('id')||'');if(!id)return;const {supabase,companyId}=await ownerContext();await supabase.from('work_schedule_items').delete().eq('id',id).eq('company_id',companyId);revalidatePath('/schedule');revalidatePath('/employee');revalidatePath('/production/work-packages');}
