/** @type {import('next').NextConfig} */
const nextConfig = {
  async redirects() {
    return [
      {source:'/leads/inbox',destination:'/opportunities?view=intake',permanent:false},
      {source:'/leads/:id',destination:'/opportunities?lead=:id&tab=scope',permanent:false},
      {source:'/leads',destination:'/opportunities',permanent:false},
      {source:'/estimates/audit',destination:'/opportunities?view=audit',permanent:false},
      {source:'/estimates/:estimateId',destination:'/opportunities?estimate=:estimateId&tab=worksheet',permanent:false},
      {source:'/estimates',destination:'/opportunities',permanent:false},
      {source:'/proposals/:estimateId',destination:'/opportunities?estimate=:estimateId&tab=proposal',permanent:false},
      {source:'/proposals',destination:'/opportunities',permanent:false},
      {source:'/bid-intelligence',destination:'/opportunities?view=intelligence',permanent:false},
      {source:'/field/review',destination:'/field?tab=production&view=time-review',permanent:false},
      {source:'/pour-control/deliveries',destination:'/field?tab=dispatch&view=deliveries',permanent:false},
      {source:'/pour-control',destination:'/financials?tab=ledger&view=pour-funding',permanent:false},
      {source:'/schedule',destination:'/field?tab=schedule&view=schedule',permanent:false},
      {source:'/look-ahead',destination:'/field?tab=schedule&view=look-ahead',permanent:false},
      {source:'/readiness/resources',destination:'/field?tab=schedule&view=resources',permanent:false},
      {source:'/readiness',destination:'/field?tab=schedule&view=readiness',permanent:false},
      {source:'/production/work-packages/financials',destination:'/financials?tab=labor&view=work-package-financials',permanent:false},
      {source:'/production/work-packages',destination:'/field?tab=production&view=work-packages',permanent:false},
      {source:'/production',destination:'/field?tab=production&view=production',permanent:false},
      {source:'/crew/access',destination:'/field?tab=crew&view=employee-access',permanent:false},
      {source:'/crew',destination:'/field?tab=crew&view=crew',permanent:false},
      {source:'/equipment',destination:'/field?tab=crew&view=equipment',permanent:false},
      {source:'/banking/reconcile',destination:'/financials?tab=ledger&view=reconcile',permanent:false},
      {source:'/banking/rules',destination:'/financials?tab=ledger&view=bank-rules',permanent:false},
      {source:'/banking',destination:'/financials?tab=ledger&view=banking',permanent:false},
      {source:'/cashflow/accounts',destination:'/financials?tab=ledger&view=cash-accounts',permanent:false},
      {source:'/cashflow/expenses',destination:'/financials?tab=ledger&view=expenses',permanent:false},
      {source:'/cashflow/reserves',destination:'/financials?tab=ledger&view=reserves',permanent:false},
      {source:'/cashflow',destination:'/financials?tab=ledger&view=ledger',permanent:false},
      {source:'/billing/invoices',destination:'/financials?tab=billing&view=invoices',permanent:false},
      {source:'/billing/payments',destination:'/financials?tab=billing&view=payments',permanent:false},
      {source:'/billing/retainage',destination:'/financials?tab=billing&view=retainage',permanent:false},
      {source:'/billing/setup',destination:'/financials?tab=billing&view=billing-setup',permanent:false},
      {source:'/billing',destination:'/financials?tab=billing&view=billing',permanent:false},
      {source:'/payables',destination:'/financials?tab=procurement&view=payables',permanent:false},
      {source:'/procurement/bills',destination:'/financials?tab=procurement&view=bills',permanent:false},
      {source:'/procurement/orders',destination:'/financials?tab=procurement&view=orders',permanent:false},
      {source:'/procurement/vendors',destination:'/financials?tab=procurement&view=vendors',permanent:false},
      {source:'/procurement/quotes',destination:'/financials?tab=procurement&view=quotes',permanent:false},
      {source:'/procurement',destination:'/financials?tab=procurement&view=procurement',permanent:false},
      {source:'/payroll',destination:'/financials?tab=labor&view=payroll',permanent:false},
      {source:'/costs/catalog',destination:'/financials?tab=labor&view=catalog',permanent:false},
      {source:'/costs',destination:'/financials?tab=labor&view=costs',permanent:false},
    ];
  },
};

export default nextConfig;
