import {redirect} from 'next/navigation';
import {headers} from 'next/headers';
import Link from 'next/link';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';
import {createProposalLink,revokeProposalLink} from './actions';

const money=(n:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));

export default async function ProposalsPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(!profile?.company_id)redirect('/login');if(profile.role==='employee')redirect('/employee');
 const [{data:estimates},{data:summaries},{data:tokens},{data:acceptances},{data:projects}]=await Promise.all([
  supabase.from('estimates').select('id,estimate_number,opportunity_number,version,name,status,project_id,lead_id,created_at').eq('company_id',profile.company_id).order('created_at',{ascending:false}),
  supabase.from('estimate_financial_summary').select('*').eq('company_id',profile.company_id),
  supabase.from('proposal_access_tokens').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false}),
  supabase.from('proposal_acceptances').select('*').eq('company_id',profile.company_id).order('accepted_at',{ascending:false}),
  supabase.from('projects').select('id,job_number,name').eq('company_id',profile.company_id)
 ]);
 const summaryMap=new Map((summaries||[]).map((s:any)=>[s.estimate_id,s])),projectMap=new Map((projects||[]).map((p:any)=>[p.id,p])),tokenMap=new Map<string,any>(),acceptanceMap=new Map<string,any>();for(const t of tokens||[])if(!tokenMap.has(t.estimate_id)&&!t.revoked_at)tokenMap.set(t.estimate_id,t);for(const a of acceptances||[])if(!acceptanceMap.has(a.estimate_id))acceptanceMap.set(a.estimate_id,a);
 const h=await headers();const host=h.get('x-forwarded-host')||h.get('host')||'',proto=h.get('x-forwarded-proto')||'https',origin=host?`${proto}://${host}`:'';
 const accepted=(estimates||[]).filter((e:any)=>acceptanceMap.has(e.id)),sent=(estimates||[]).filter((e:any)=>tokenMap.has(e.id)&&!acceptanceMap.has(e.id)),ready=(estimates||[]).filter((e:any)=>!['accepted','approved','declined'].includes(e.status));
 return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page">
  <div className="command-hero"><div><h1>Proposals</h1><p>Carez keeps the same opportunity number from estimate to proposal to awarded job. Customer acceptance creates the job and freezes the original budget automatically.</p></div><div className="command-actions"><Link className="button secondary" href="/estimates">Estimates</Link></div></div>
  <div className="command-grid"><div className="command-card"><div className="command-label">Ready to Send</div><div className="command-value">{ready.length}</div><div className="command-help">Draft/ready estimates that can become proposals.</div></div><div className={`command-card ${sent.length?'watch':''}`}><div className="command-label">Waiting on Customer</div><div className="command-value">{sent.length}</div></div><div className={`command-card ${accepted.length?'good':''}`}><div className="command-label">Accepted / Awarded</div><div className="command-value">{accepted.length}</div><div className="command-help">Accepted proposals automatically become jobs.</div></div></div>
  <section className="section"><div className="section-heading"><div><div className="section-kicker">Send Work</div><div className="section-title">Proposal Board</div><div className="section-heading-meta">E-26-001-R0 becomes P-26-001-R0. When accepted, Job 26-001 is created.</div></div></div>
   {(estimates||[]).length===0?<div className="empty-state"><div><div className="title">No estimates yet</div><div className="meta">Start from a Lead so Carez carries the number through automatically.</div></div></div>:<div className="project-list">{(estimates||[]).map((e:any)=>{const s:any=summaryMap.get(e.id)||{},t:any=tokenMap.get(e.id),a:any=acceptanceMap.get(e.id),project:any=projectMap.get(e.project_id),link=t?`${origin}/proposal/${t.token}`:'',estimateDisplay=`${e.estimate_number}-R${Number(e.version||0)}`,proposalDisplay=t?.proposal_number||`P-${e.opportunity_number||String(e.estimate_number).replace(/^E-/,'')}-R${Number(e.version||0)}`;return <article className="project-card" key={e.id}><header className="project-header"><div><div className="project-name">{proposalDisplay} — {e.name}</div><div className="project-location">From {estimateDisplay}{project?` · Job ${project.job_number}`:''}</div></div><span className={`status ${a?'completed':t?'active':''}`}>{a?'Accepted / Awarded':t?'Sent / Shareable':'Not Sent'}</span></header><section className="project-section">
    <div className="metric-grid"><div className="metric-card"><div className="label">Direct Cost</div><div className="metric-value">{money(s.total_direct_cost)}</div></div><div className="metric-card brand"><div className="label">Customer Price</div><div className="metric-value">{money(s.selected_sell_price||s.recommended_sell_price)}</div></div><div className="metric-card"><div className="label">Projected Profit</div><div className="metric-value">{money(s.projected_profit)}</div></div><div className="metric-card"><div className="label">Margin</div><div className="metric-value">{Number(s.projected_margin_percent||0).toFixed(1)}%</div></div></div>
    {a?<div className="alert success section"><strong>{project?`Job ${project.job_number} created automatically.`:'Proposal accepted.'}</strong><div className="meta">Accepted by {a.accepted_name} · {new Date(a.accepted_at).toLocaleString()}{a.accepted_email?` · ${a.accepted_email}`:''}</div><div className="meta">The accepted estimate is locked and the original project budget is frozen.</div>{project&&<div className="action-row section"><Link className="button" href={`/projects/${project.id}`}>Open Job {project.job_number}</Link></div>}</div>:t?<div className="surface section"><div className="surface-body"><div className="field"><span>{proposalDisplay} Customer Link</span><input readOnly value={link}/></div><div className="meta">Expires {t.expires_at?new Date(t.expires_at).toLocaleDateString():'never'}.</div><div className="action-row"><a className="button" href={link} target="_blank" rel="noreferrer">Open Proposal</a><form action={revokeProposalLink}><input type="hidden" name="id" value={t.id}/><button className="button secondary">Turn Link Off</button></form></div></div></div>:<form action={createProposalLink} className="section"><input type="hidden" name="estimate_id" value={e.id}/><button className="button" disabled={['accepted','approved','declined'].includes(e.status)}>Create {proposalDisplay}</button></form>}
   </section></article>})}</div>}
  </section>
 </div></AppShell>;
}
