import {redirect} from 'next/navigation';
import {headers} from 'next/headers';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';
import {createProposalLink,revokeProposalLink} from './actions';

const money=(n:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));

export default async function ProposalsPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(!profile?.company_id)redirect('/login');if(profile.role==='employee')redirect('/employee');
 const [{data:estimates},{data:summaries},{data:tokens},{data:acceptances}]=await Promise.all([supabase.from('estimates').select('id,estimate_number,name,status,project_id,created_at').eq('company_id',profile.company_id).order('created_at',{ascending:false}),supabase.from('estimate_financial_summary').select('*'),supabase.from('proposal_access_tokens').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false}),supabase.from('proposal_acceptances').select('*').eq('company_id',profile.company_id).order('accepted_at',{ascending:false})]);
 const summaryMap=new Map((summaries||[]).map((s:any)=>[s.estimate_id,s]));const tokenMap=new Map<string,any>();for(const t of tokens||[])if(!tokenMap.has(t.estimate_id)&&!t.revoked_at)tokenMap.set(t.estimate_id,t);const acceptanceMap=new Map<string,any>();for(const a of acceptances||[])if(!acceptanceMap.has(a.estimate_id))acceptanceMap.set(a.estimate_id,a);
 const h=await headers();const host=h.get('x-forwarded-host')||h.get('host')||'';const proto=h.get('x-forwarded-proto')||'https';const origin=host?`${proto}://${host}`:'';
 const accepted=(estimates||[]).filter((e:any)=>acceptanceMap.has(e.id));const sent=(estimates||[]).filter((e:any)=>tokenMap.has(e.id)&&!acceptanceMap.has(e.id));
 return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page"><div className="command-hero"><div><h1>Proposals</h1><p>Turn a finished estimate into a clean customer link, then know when they accept it.</p></div></div><div className="command-grid"><div className="command-card"><div className="command-label">Ready / Draft Estimates</div><div className="command-value">{(estimates||[]).filter((e:any)=>!['approved','declined'].includes(e.status)).length}</div><div className="command-help">Estimates that can still be sent or accepted.</div></div><div className={`command-card ${sent.length?'watch':''}`}><div className="command-label">Waiting on Customer</div><div className="command-value">{sent.length}</div><div className="command-help">Proposal links sent but not accepted.</div></div><div className={`command-card ${accepted.length?'good':''}`}><div className="command-label">Accepted</div><div className="command-value">{accepted.length}</div><div className="command-help">Customer acceptance captured in Carez.</div></div></div>
 <section className="section"><div className="section-heading"><div><div className="section-kicker">Send Work</div><div className="section-title">Proposal Board</div><div className="section-heading-meta">Create a share link only after the estimate is ready to show the customer.</div></div></div>{(estimates||[]).length===0?<div className="empty-state"><div><div className="title">No estimates yet</div><div className="meta">Build the estimate first, then send it from here.</div></div></div>:<div className="project-list">{(estimates||[]).map((e:any)=>{const s:any=summaryMap.get(e.id)||{},t:any=tokenMap.get(e.id),a:any=acceptanceMap.get(e.id);const link=t?`${origin}/proposal/${t.token}`:'';return <article className="project-card" key={e.id}><header className="project-header"><div><div className="project-name">{e.estimate_number} — {e.name}</div><div className="project-location">Estimate status: {e.status.replaceAll('_',' ')}</div></div><span className={`status ${a?'completed':t?'active':''}`}>{a?'Accepted':t?'Sent / Shareable':'Not Sent'}</span></header><section className="project-section"><div className="metric-grid"><div className="metric-card"><div className="label">Direct Cost</div><div className="metric-value">{money(s.total_direct_cost)}</div></div><div className="metric-card brand"><div className="label">Customer Price</div><div className="metric-value">{money(s.recommended_sell_price||s.proposed_sell_price)}</div></div><div className="metric-card"><div className="label">Projected Profit</div><div className="metric-value">{money(s.projected_profit)}</div></div><div className="metric-card"><div className="label">Margin</div><div className="metric-value">{Number(s.projected_margin_percent||0).toFixed(1)}%</div></div></div>{a?<div className="alert success section"><strong>Accepted by {a.accepted_name}</strong><div className="meta">{new Date(a.accepted_at).toLocaleString()}{a.accepted_email?` · ${a.accepted_email}`:''}</div>{a.acceptance_note&&<div>{a.acceptance_note}</div>}</div>:t?<div className="surface section"><div className="surface-body"><div className="field"><span>Customer Proposal Link</span><input readOnly value={link}/></div><div className="meta">Expires {t.expires_at?new Date(t.expires_at).toLocaleDateString():'never'}.</div><div className="action-row"><a className="button" href={link} target="_blank" rel="noreferrer">Open Proposal</a><form action={revokeProposalLink}><input type="hidden" name="id" value={t.id}/><button className="button secondary">Turn Link Off</button></form></div></div></div>:<form action={createProposalLink} className="section"><input type="hidden" name="estimate_id" value={e.id}/><button className="button" disabled={e.status==='approved'||e.status==='declined'}>Create Customer Link</button></form>}</section></article>})}</div>}</section></div></AppShell>;
}
