import { redirect } from 'next/navigation';
import Link from 'next/link';
import { AppShell } from '@/components/AppShell';
import { createClient } from '@/lib/supabase/server';
import { analyzeBankFeed,acceptBankCandidate,rejectBankCandidate,reconcileInvoicePayment,reconcileVendorBillPayment,reconcileCompanyExpense,reconcileJobCost,reconcilePayroll,reconcileTax,reconcileTransfer,ignoreBankTransaction } from '../actions';

const money=(n:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const scoreTone=(n:number)=>n>=95?'completed':n>=80?'active':'draft';
const canQuickAccept=(type:string)=>['existing_customer_payment','invoice_payment','existing_vendor_payment','vendor_bill_payment','existing_company_expense','company_expense','existing_payroll','payroll_run','existing_tax_remittance','internal_transfer','ignore'].includes(type);

export default async function BankReconcilePage(){
  const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
  const {data:profile}=await supabase.from('profiles').select('full_name,company_id').eq('id',user.id).single();if(!profile?.company_id)redirect('/login');const companyId=profile.company_id;
  const [{data:summary},{data:txs},{data:candidates},{data:accounts},{data:invoices},{data:bills},{data:projects},{data:costCodes},{data:vendors},{data:overhead},{data:payroll}]=await Promise.all([
    supabase.from('bank_reconciliation_summary').select('*').eq('company_id',companyId).maybeSingle(),
    supabase.from('plaid_transaction_feed').select('*').eq('company_id',companyId).eq('removed',false).eq('review_status','unreviewed').eq('pending',false).order('transaction_date',{ascending:false}).limit(150),
    supabase.from('bank_reconciliation_candidates').select('*').eq('company_id',companyId).eq('status','active').order('confidence',{ascending:false}),
    supabase.from('plaid_bank_account_summary').select('account_id,name,mask,institution_name').eq('company_id',companyId),
    supabase.from('invoice_financial_summary').select('invoice_id,invoice_number,bill_to_name,balance_due,project_id').eq('company_id',companyId).eq('status','sent').gt('balance_due',0).order('issue_date'),
    supabase.from('vendor_bill_ap_summary').select('vendor_bill_id,vendor_name,vendor_bill_number,balance_due,job_number,project_name').eq('company_id',companyId).eq('status','posted').gt('balance_due',0).order('due_date'),
    supabase.from('projects').select('id,job_number,name,status').eq('company_id',companyId).in('status',['active','on_hold']).order('job_number'),
    supabase.from('cost_codes').select('id,code,name,cost_type').eq('company_id',companyId).eq('active',true).order('sort_order'),
    supabase.from('vendors').select('id,name').eq('company_id',companyId).eq('active',true).order('name'),
    supabase.from('overhead_items').select('id,category,name,business_use_percent').eq('company_id',companyId).eq('active',true).order('sort_order'),
    supabase.from('payroll_run_financial_summary').select('payroll_run_id,period_start,period_end,pay_date,status,actual_cash_paid,payroll_funding_requirement').eq('company_id',companyId).in('status',['approved','processed']).order('pay_date',{ascending:false})
  ]);
  const candidateMap=new Map<string,any[]>();for(const c of candidates||[]){if(!candidateMap.has(c.bank_transaction_id))candidateMap.set(c.bank_transaction_id,[]);candidateMap.get(c.bank_transaction_id)!.push(c);}
  const accountMap=new Map((accounts||[]).map((a:any)=>[a.account_id,a]));
  const sorted=(txs||[]).map((t:any)=>({t,best:(candidateMap.get(t.id)||[])[0]||null})).sort((a:any,b:any)=>Number(b.best?.confidence||0)-Number(a.best?.confidence||0)||String(b.t.transaction_date).localeCompare(String(a.t.transaction_date)));
  const s:any=summary||{};

  return <AppShell userName={profile.full_name||user.email||'Owner'}>
    <div className="page-heading"><div><h1 className="page-title">Bank Reconciliation</h1><p className="subtitle">Match imported bank activity to Carez records once, then let learned rules handle the repetitive work.</p></div><div className="action-row"><form action={analyzeBankFeed}><button className="button">Analyze Feed</button></form><Link className="button secondary" href="/banking">Banking</Link><Link className="button secondary" href="/cashflow">Cashflow</Link></div></div>

    <div className="grid grid4">
      <div className="card"><div className="label">Needs Review</div><div className="value">{Number(s.needs_review_count||0)}</div><div className="meta">Unreconciled non-pending transactions.</div></div>
      <div className="card"><div className="label">High Confidence</div><div className="value">{Number(s.high_confidence_count||0)}</div><div className="meta">95%+ suggestions ready for a quick decision.</div></div>
      <div className="card"><div className="label">Suggested</div><div className="value">{Number(s.suggested_count||0)}</div><div className="meta">80–94% likely matches.</div></div>
      <div className="card"><div className="label">Reconciled</div><div className="value">{Number(s.matched_count||0)}</div><div className="meta">Bank rows already tied to Carez records.</div></div>
    </div>

    <div className="alert info"><strong>Automation guardrail:</strong> exact matches to financial records already entered in Carez may reconcile automatically. Creating a new payment, expense, job cost, payroll event or tax payment requires your approval unless you explicitly teach that merchant an auto-apply rule.</div>

    <section className="section"><div className="section-heading"><div><div className="section-kicker">Work Queue</div><div className="section-title">Transactions Requiring Attention</div><div className="section-heading-meta">Highest-confidence suggestions are shown first.</div></div></div>
      {sorted.length===0?<div className="empty-state"><div><div className="title">Bank feed is reconciled</div><div className="meta">There are no non-pending transactions waiting for review.</div></div></div>:
      <div className="data-table-wrap"><table className="data-table" style={{minWidth:1000}}><thead><tr><th>Date</th><th>Bank Transaction</th><th>Account</th><th>Amount</th><th>Carez Recommendation</th><th>Confidence</th><th>Action</th></tr></thead><tbody>{sorted.map(({t,best}:any)=>{const acc:any=accountMap.get(t.account_id)||{};const cash=Number(t.cash_amount||0);const possibleTransfers=(candidateMap.get(t.id)||[]).filter((c:any)=>c.candidate_type==='internal_transfer');return <tr key={t.id}>
        <td>{t.transaction_date}</td>
        <td><strong>{t.merchant_name||t.name}</strong><div className="meta">{t.name!==t.merchant_name?t.name:''}</div></td>
        <td>{t.account_name||acc.name||'Bank'}<div className="meta">{t.account_mask||acc.mask?`•••• ${t.account_mask||acc.mask}`:''}</div></td>
        <td style={{fontWeight:850,color:cash>=0?'#73daa0':'#ff978f'}}>{cash>=0?'+':''}{money(cash)}</td>
        <td>{best?<><strong>{best.proposed_action||best.candidate_type.replaceAll('_',' ')}</strong><div className="meta">{best.reason}</div></>:<><strong>Classification required</strong><div className="meta">No reliable match found.</div></>}</td>
        <td>{best?<span className={`status ${scoreTone(Number(best.confidence))}`}>{best.confidence}%</span>:<span className="status">—</span>}</td>
        <td><div className="action-row" style={{marginTop:0}}>
          {best&&canQuickAccept(best.candidate_type)&&<form action={acceptBankCandidate}><input type="hidden" name="candidate_id" value={best.id}/><button className="button">Confirm</button></form>}
          {best&&<form action={rejectBankCandidate}><input type="hidden" name="candidate_id" value={best.id}/><button className="button secondary">Not This</button></form>}
          <details className="controls-disclosure create-disclosure"><summary>Review Transaction</summary><div className="controls-body">
            <div className="surface"><div className="surface-header"><div><div className="surface-title">{t.merchant_name||t.name}</div><div className="surface-subtitle">{t.transaction_date} · {t.account_name||acc.name||'Bank'} · {cash>=0?'+':''}{money(cash)}</div></div></div>{best&&<div className="surface-body"><div className="label">Best Suggestion · {best.confidence}%</div><div className="title" style={{marginTop:5}}>{best.proposed_action}</div><div className="meta">{best.reason}</div></div>}</div>

            {cash>0&&<div className="surface section"><div className="surface-header"><div><div className="surface-title">Customer Payment</div><div className="surface-subtitle">Apply this deposit to a sent Carez invoice.</div></div></div><div className="surface-body"><form action={reconcileInvoicePayment} className="form"><input type="hidden" name="transaction_id" value={t.id}/><label className="field"><span>Invoice</span><select name="invoice_id" required defaultValue=""><option value="" disabled>Select invoice</option>{(invoices||[]).map((i:any)=><option key={i.invoice_id} value={i.invoice_id}>{i.invoice_number} — {i.bill_to_name||'Customer'} — balance {money(i.balance_due)}</option>)}</select></label><button className="button">Record Customer Payment</button></form></div></div>}

            {cash<0&&<div className="surface section"><div className="surface-header"><div><div className="surface-title">Vendor Bill / Accounts Payable</div><div className="surface-subtitle">Use when this withdrawal paid a bill already posted in Carez.</div></div></div><div className="surface-body"><form action={reconcileVendorBillPayment} className="form"><input type="hidden" name="transaction_id" value={t.id}/><label className="field"><span>Vendor Bill</span><select name="vendor_bill_id" required defaultValue=""><option value="" disabled>Select vendor bill</option>{(bills||[]).map((x:any)=><option key={x.vendor_bill_id} value={x.vendor_bill_id}>{x.vendor_name} · {x.vendor_bill_number} · {x.job_number||x.project_name||''} · balance {money(x.balance_due)}</option>)}</select></label><button className="button">Record Vendor Payment</button></form></div></div>}

            {cash<0&&<div className="surface section"><div className="surface-header"><div><div className="surface-title">Company Expense</div><div className="surface-subtitle">General Carez overhead such as software, truck, insurance, banking or office expense.</div></div></div><div className="surface-body"><form action={reconcileCompanyExpense} className="form"><input type="hidden" name="transaction_id" value={t.id}/><label className="field"><span>Planned Overhead Item</span><select name="overhead_item_id" defaultValue={best?.metadata?.overhead_item_id||''}><option value="">Unlinked / other overhead</option>{(overhead||[]).map((o:any)=><option key={o.id} value={o.id}>{o.category} — {o.name}</option>)}</select></label><div className="grid grid2"><label className="field"><span>Category Override</span><input name="category" defaultValue={best?.metadata?.expense_category||''} placeholder="Uses overhead category if blank"/></label><label className="field"><span>Business Use %</span><input type="number" min="0" max="100" step="0.01" name="business_use_percent" defaultValue={best?.metadata?.business_use_percent??''} placeholder="Uses overhead setting"/></label></div><label className="field"><span>Description</span><input name="description" defaultValue={t.merchant_name||t.name}/></label><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" name="remember_rule"/> Remember this merchant's overhead coding</label><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" name="auto_apply"/> Automatically apply that rule to future matching transactions</label><button className="button">Record Company Expense</button></form></div></div>}

            {cash<0&&<div className="surface section"><div className="surface-header"><div><div className="surface-title">Direct Job Cost</div><div className="surface-subtitle">Project-specific material, fuel, rental, tools or other direct cost.</div></div></div><div className="surface-body"><form action={reconcileJobCost} className="form"><input type="hidden" name="transaction_id" value={t.id}/><div className="grid grid2"><label className="field"><span>Project</span><select name="project_id" required defaultValue=""><option value="" disabled>Select project</option>{(projects||[]).map((p:any)=><option key={p.id} value={p.id}>{p.job_number} — {p.name}</option>)}</select></label><label className="field"><span>Cost Code</span><select name="cost_code_id" required defaultValue={best?.metadata?.cost_code_id||''}><option value="" disabled>Select cost code</option>{(costCodes||[]).map((c:any)=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></label></div><label className="field"><span>Vendor (optional)</span><select name="vendor_id" defaultValue={best?.metadata?.vendor_id||''}><option value="">Use bank merchant</option>{(vendors||[]).map((v:any)=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label className="field"><span>Description</span><input name="description" defaultValue={t.merchant_name||t.name}/></label><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" name="remember_cost_code"/> Remember this merchant's cost code for future suggestions</label><button className="button">Post to Job Cost</button></form></div></div>}

            {cash<0&&(payroll||[]).length>0&&<div className="surface section"><div className="surface-header"><div><div className="surface-title">Payroll Withdrawal</div><div className="surface-subtitle">Match a processed run or confirm an approved run was actually processed.</div></div></div><div className="surface-body"><form action={reconcilePayroll} className="form"><input type="hidden" name="transaction_id" value={t.id}/><label className="field"><span>Payroll Run</span><select name="payroll_run_id" required defaultValue=""><option value="" disabled>Select payroll run</option>{(payroll||[]).map((p:any)=><option key={p.payroll_run_id} value={p.payroll_run_id}>{p.period_start} – {p.period_end} · {p.status} · {money(p.status==='processed'?p.actual_cash_paid:p.payroll_funding_requirement)}</option>)}</select></label><button className="button">Reconcile Payroll</button></form></div></div>}

            {cash<0&&<div className="surface section"><div className="surface-header"><div><div className="surface-title">Tax Payment</div><div className="surface-subtitle">Record money paid to a tax agency without treating it as operating revenue or duplicate job cost.</div></div></div><div className="surface-body"><form action={reconcileTax} className="form"><input type="hidden" name="transaction_id" value={t.id}/><label className="field"><span>Tax Type</span><select name="tax_type" defaultValue="sales_tax"><option value="sales_tax">Sales Tax</option><option value="bo">B&O Tax</option><option value="payroll">Payroll Tax</option><option value="li">L&I</option><option value="other">Other Tax</option></select></label><button className="button">Record Tax Payment</button></form></div></div>}

            {possibleTransfers.length>0&&<div className="surface section"><div className="surface-header"><div><div className="surface-title">Internal Transfer</div><div className="surface-subtitle">Moves money between Carez accounts without creating revenue or expense.</div></div></div><div className="surface-body"><form action={reconcileTransfer} className="form"><input type="hidden" name="transaction_id" value={t.id}/><label className="field"><span>Matching Bank Entry</span><select name="other_transaction_id" required defaultValue={possibleTransfers[0]?.entity_id||''}>{possibleTransfers.map((x:any)=><option key={x.id} value={x.entity_id}>{x.metadata?.other_name||'Other account transaction'} · {money(x.metadata?.amount)}</option>)}</select></label><button className="button">Mark Internal Transfer</button></form></div></div>}

            <div className="surface section"><div className="surface-header"><div><div className="surface-title">Ignore / Non-Accounting Activity</div><div className="surface-subtitle">Use for duplicates, non-business activity or bank entries that should not create a Carez financial record.</div></div></div><div className="surface-body"><form action={ignoreBankTransaction} className="form"><input type="hidden" name="transaction_id" value={t.id}/><label className="field"><span>Reason</span><input name="note" placeholder="Why this should be ignored"/></label><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" name="remember_rule"/> Remember this merchant as ignored</label><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" name="auto_apply"/> Automatically ignore future matching transactions</label><button className="button secondary">Ignore Transaction</button></form></div></div>
          </div></details>
        </div></td>
      </tr>})}</tbody></table></div>}
    </section>
  </AppShell>;
}
