import { redirect } from 'next/navigation';
import Link from 'next/link';
import { AppShell } from '@/components/AppShell';
import { Badge } from '@/components/ui/badge';
import { Button,buttonVariants } from '@/components/ui/button';
import { Card,CardContent } from '@/components/ui/card';
import { Empty,EmptyDescription,EmptyHeader,EmptyTitle } from '@/components/ui/empty';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { createClient } from '@/lib/supabase/server';
import { analyzeBankFeed,acceptBankCandidate,rejectBankCandidate,reconcileInvoicePayment,reconcileVendorBillPayment,reconcileCompanyExpense,reconcileJobCost,reconcilePayroll,reconcileTax,reconcileTransfer,ignoreBankTransaction } from '../actions';

const money=(n:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const confidenceClass=(n:number)=>n>=95?'border-success/30 bg-success/10 text-success':n>=80?'border-primary/30 bg-primary/10 text-primary':'text-muted-foreground';
const canQuickAccept=(type:string)=>['existing_customer_payment','invoice_payment','existing_vendor_payment','vendor_bill_payment','existing_company_expense','company_expense','existing_payroll','payroll_run','existing_tax_remittance','internal_transfer','ignore'].includes(type);
const selectClass='h-9 w-full rounded-md border border-input bg-background px-3 text-sm text-foreground outline-none transition-shadow focus:border-ring focus:ring-3 focus:ring-ring/20';

function Metric({label,value,detail}:{label:string;value:string|number;detail:string}){
  return <Card size="sm"><CardContent className="h-full space-y-1"><div className="text-xs font-medium text-muted-foreground">{label}</div><div className="text-2xl font-semibold tabular-nums">{value}</div><div className="text-xs text-muted-foreground">{detail}</div></CardContent></Card>;
}

export default async function BankReconcilePage(){
  const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser();
  if(!user)redirect('/login');
  const {data:profile}=await supabase.from('profiles').select('full_name,company_id').eq('id',user.id).single();
  if(!profile?.company_id)redirect('/login');
  const companyId=profile.company_id;

  const [{data:summary},{data:txs},{data:candidates},{data:accounts},{data:invoices},{data:bills},{data:projects},{data:costCodes},{data:vendors},{data:overhead},{data:payroll}]=await Promise.all([
    supabase.from('bank_reconciliation_summary').select('*').eq('company_id',companyId).maybeSingle(),
    supabase.from('plaid_transaction_feed').select('*').eq('company_id',companyId).eq('removed',false).eq('review_status','unreviewed').eq('pending',false).order('transaction_date',{ascending:false}).limit(150),
    supabase.from('bank_reconciliation_candidates').select('*').eq('company_id',companyId).eq('status','active').order('confidence',{ascending:false}),
    supabase.from('plaid_bank_account_summary').select('account_id,name,mask,institution_name').eq('company_id',companyId),
    supabase.from('invoice_financial_summary').select('invoice_id,invoice_number,bill_to_name,balance_due,project_id').eq('company_id',companyId).eq('status','sent').gt('balance_due',0).order('issue_date'),
    supabase.from('vendor_bill_ap_summary').select('vendor_bill_id,vendor_name,vendor_bill_number,balance_due,job_number,project_name').eq('company_id',companyId).eq('status','posted').gt('balance_due',0).order('due_date'),
    supabase.from('projects').select('id,job_number,name,status').eq('company_id',companyId).in('status',['active','on_hold']).order('job_number'),
    supabase.from('cost_codes').select('id,code,name,cost_type').eq('company_id',companyId).eq('active',true).order('sort_order'),
    supabase.from('vendors').select('id,name').eq('company_id',companyId).eq('active',true).order('name'),
    supabase.from('overhead_items').select('id,category,name,business_use_percent').eq('company_id',companyId).eq('active',true).order('sort_order'),
    supabase.from('payroll_run_financial_summary').select('payroll_run_id,period_start,period_end,pay_date,status,actual_cash_paid,payroll_funding_requirement').eq('company_id',companyId).in('status',['approved','processed']).order('pay_date',{ascending:false})
  ]);

  const candidateMap=new Map<string,any[]>();
  for(const c of candidates||[]){if(!candidateMap.has(c.bank_transaction_id))candidateMap.set(c.bank_transaction_id,[]);candidateMap.get(c.bank_transaction_id)!.push(c);}
  const accountMap=new Map((accounts||[]).map((a:any)=>[a.account_id,a]));
  const sorted=(txs||[]).map((t:any)=>({t,best:(candidateMap.get(t.id)||[])[0]||null})).sort((a:any,b:any)=>Number(b.best?.confidence||0)-Number(a.best?.confidence||0)||String(b.t.transaction_date).localeCompare(String(a.t.transaction_date)));
  const s:any=summary||{};

  return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="mx-auto flex w-full max-w-screen-2xl flex-col gap-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><header><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Banking</div><h1 className="mt-1 text-2xl font-semibold tracking-tight">Bank Reconciliation</h1><p className="mt-1 max-w-4xl text-sm text-muted-foreground">Match imported bank activity to Carez records once, then let learned rules handle the repetitive work.</p></header><div className="flex flex-wrap gap-2"><form action={analyzeBankFeed}><Button type="submit">Analyze Feed</Button></form><Link className={buttonVariants({variant:'outline'})} href="/banking">Banking</Link><Link className={buttonVariants({variant:'outline'})} href="/cashflow">Cashflow</Link></div></div>

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Needs Review" value={Number(s.needs_review_count||0)} detail="Unreconciled non-pending transactions."/><Metric label="High Confidence" value={Number(s.high_confidence_count||0)} detail="95%+ suggestions ready for a quick decision."/><Metric label="Suggested" value={Number(s.suggested_count||0)} detail="80–94% likely matches."/><Metric label="Reconciled" value={Number(s.matched_count||0)} detail="Bank rows already tied to Carez records."/></div>

    <div className="rounded-lg border border-primary/20 bg-primary/5 px-4 py-3 text-sm text-muted-foreground"><strong className="text-foreground">Automation guardrail:</strong> exact matches to financial records already entered in Carez may reconcile automatically. Creating a new payment, expense, job cost, payroll event or tax payment requires your approval unless you explicitly teach that merchant an auto-apply rule.</div>

    <section className="space-y-4" aria-labelledby="reconciliation-queue"><div><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Work queue</div><h2 id="reconciliation-queue" className="mt-1 text-lg font-semibold">Transactions Requiring Attention</h2><p className="mt-1 text-sm text-muted-foreground">Highest-confidence suggestions are shown first.</p></div>
      {sorted.length===0?<Empty className="border border-border"><EmptyHeader><EmptyTitle>Bank feed is reconciled</EmptyTitle><EmptyDescription>There are no non-pending transactions waiting for review.</EmptyDescription></EmptyHeader></Empty>:<div className="overflow-x-auto rounded-lg border border-border"><Table className="min-w-[1000px]"><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Bank Transaction</TableHead><TableHead>Account</TableHead><TableHead>Amount</TableHead><TableHead>Carez Recommendation</TableHead><TableHead>Confidence</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{sorted.map(({t,best}:any)=>{
        const acc:any=accountMap.get(t.account_id)||{};
        const cash=Number(t.cash_amount||0);
        const possibleTransfers=(candidateMap.get(t.id)||[]).filter((c:any)=>c.candidate_type==='internal_transfer');
        return <TableRow key={t.id} className="align-top">
          <TableCell>{t.transaction_date}</TableCell>
          <TableCell><div className="font-medium">{t.merchant_name||t.name}</div><div className="mt-1 text-xs text-muted-foreground">{t.name!==t.merchant_name?t.name:''}</div></TableCell>
          <TableCell>{t.account_name||acc.name||'Bank'}<div className="mt-1 text-xs text-muted-foreground">{t.account_mask||acc.mask?`•••• ${t.account_mask||acc.mask}`:''}</div></TableCell>
          <TableCell className={`font-semibold tabular-nums ${cash>=0?'text-success':'text-destructive'}`}>{cash>=0?'+':''}{money(cash)}</TableCell>
          <TableCell>{best?<><div className="font-medium">{best.proposed_action||best.candidate_type.replaceAll('_',' ')}</div><div className="mt-1 max-w-xs text-xs text-muted-foreground">{best.reason}</div></>:<><div className="font-medium">Classification required</div><div className="mt-1 text-xs text-muted-foreground">No reliable match found.</div></>}</TableCell>
          <TableCell>{best?<Badge variant="outline" className={confidenceClass(Number(best.confidence))}>{best.confidence}%</Badge>:<Badge variant="outline">—</Badge>}</TableCell>
          <TableCell><div className="flex min-w-48 flex-wrap gap-2">{best&&canQuickAccept(best.candidate_type)&&<form action={acceptBankCandidate}><input type="hidden" name="candidate_id" value={best.id}/><Button type="submit" size="sm">Confirm</Button></form>}{best&&<form action={rejectBankCandidate}><input type="hidden" name="candidate_id" value={best.id}/><Button type="submit" variant="outline" size="sm">Not This</Button></form>}
            <details className="w-full rounded-lg border border-border"><summary className="cursor-pointer list-none px-3 py-2 text-sm font-medium">Review Transaction</summary><div className="grid gap-3 border-t border-border p-3">
              <Card className="shadow-none"><CardContent className="space-y-2"><div><div className="font-semibold">{t.merchant_name||t.name}</div><div className="mt-1 text-xs text-muted-foreground">{t.transaction_date} · {t.account_name||acc.name||'Bank'} · {cash>=0?'+':''}{money(cash)}</div></div>{best&&<div className="rounded-lg border border-border bg-muted/20 p-3"><div className="text-xs font-medium text-muted-foreground">Best Suggestion · {best.confidence}%</div><div className="mt-1 font-medium">{best.proposed_action}</div><div className="mt-1 text-xs text-muted-foreground">{best.reason}</div></div>}</CardContent></Card>

              {cash>0&&<Card className="shadow-none"><CardContent className="space-y-3"><div><div className="font-semibold">Customer Payment</div><div className="mt-1 text-xs text-muted-foreground">Apply this deposit to a sent Carez invoice.</div></div><form action={reconcileInvoicePayment} className="grid gap-3"><input type="hidden" name="transaction_id" value={t.id}/><div className="grid gap-2"><Label>Invoice</Label><select className={selectClass} name="invoice_id" required defaultValue=""><option value="" disabled>Select invoice</option>{(invoices||[]).map((i:any)=><option key={i.invoice_id} value={i.invoice_id}>{i.invoice_number} — {i.bill_to_name||'Customer'} — balance {money(i.balance_due)}</option>)}</select></div><Button type="submit" className="w-fit">Record Customer Payment</Button></form></CardContent></Card>}

              {cash<0&&<Card className="shadow-none"><CardContent className="space-y-3"><div><div className="font-semibold">Vendor Bill / Accounts Payable</div><div className="mt-1 text-xs text-muted-foreground">Use when this withdrawal paid a bill already posted in Carez.</div></div><form action={reconcileVendorBillPayment} className="grid gap-3"><input type="hidden" name="transaction_id" value={t.id}/><div className="grid gap-2"><Label>Vendor Bill</Label><select className={selectClass} name="vendor_bill_id" required defaultValue=""><option value="" disabled>Select vendor bill</option>{(bills||[]).map((x:any)=><option key={x.vendor_bill_id} value={x.vendor_bill_id}>{x.vendor_name} · {x.vendor_bill_number} · {x.job_number||x.project_name||''} · balance {money(x.balance_due)}</option>)}</select></div><Button type="submit" className="w-fit">Record Vendor Payment</Button></form></CardContent></Card>}

              {cash<0&&<Card className="shadow-none"><CardContent className="space-y-3"><div><div className="font-semibold">Company Expense</div><div className="mt-1 text-xs text-muted-foreground">General Carez overhead such as software, truck, insurance, banking or office expense.</div></div><form action={reconcileCompanyExpense} className="grid gap-3"><input type="hidden" name="transaction_id" value={t.id}/><div className="grid gap-2"><Label>Planned Overhead Item</Label><select className={selectClass} name="overhead_item_id" defaultValue={best?.metadata?.overhead_item_id||''}><option value="">Unlinked / other overhead</option>{(overhead||[]).map((o:any)=><option key={o.id} value={o.id}>{o.category} — {o.name}</option>)}</select></div><div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label>Category Override</Label><Input name="category" defaultValue={best?.metadata?.expense_category||''} placeholder="Uses overhead category if blank"/></div><div className="grid gap-2"><Label>Business Use %</Label><Input type="number" min="0" max="100" step="0.01" name="business_use_percent" defaultValue={best?.metadata?.business_use_percent??''} placeholder="Uses overhead setting"/></div></div><div className="grid gap-2"><Label>Description</Label><Input name="description" defaultValue={t.merchant_name||t.name}/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="remember_rule" className="size-4 rounded border-input accent-primary"/> Remember this merchant&apos;s overhead coding</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="auto_apply" className="size-4 rounded border-input accent-primary"/> Automatically apply that rule to future matching transactions</label><Button type="submit" className="w-fit">Record Company Expense</Button></form></CardContent></Card>}

              {cash<0&&<Card className="shadow-none"><CardContent className="space-y-3"><div><div className="font-semibold">Direct Job Cost</div><div className="mt-1 text-xs text-muted-foreground">Project-specific material, fuel, rental, tools or other direct cost.</div></div><form action={reconcileJobCost} className="grid gap-3"><input type="hidden" name="transaction_id" value={t.id}/><div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label>Project</Label><select className={selectClass} name="project_id" required defaultValue=""><option value="" disabled>Select project</option>{(projects||[]).map((p:any)=><option key={p.id} value={p.id}>{p.job_number} — {p.name}</option>)}</select></div><div className="grid gap-2"><Label>Cost Code</Label><select className={selectClass} name="cost_code_id" required defaultValue={best?.metadata?.cost_code_id||''}><option value="" disabled>Select cost code</option>{(costCodes||[]).map((c:any)=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></div></div><div className="grid gap-2"><Label>Vendor (optional)</Label><select className={selectClass} name="vendor_id" defaultValue={best?.metadata?.vendor_id||''}><option value="">Use bank merchant</option>{(vendors||[]).map((v:any)=><option key={v.id} value={v.id}>{v.name}</option>)}</select></div><div className="grid gap-2"><Label>Description</Label><Input name="description" defaultValue={t.merchant_name||t.name}/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="remember_cost_code" className="size-4 rounded border-input accent-primary"/> Remember this merchant&apos;s cost code for future suggestions</label><Button type="submit" className="w-fit">Post to Job Cost</Button></form></CardContent></Card>}

              {cash<0&&(payroll||[]).length>0&&<Card className="shadow-none"><CardContent className="space-y-3"><div><div className="font-semibold">Payroll Withdrawal</div><div className="mt-1 text-xs text-muted-foreground">Match a processed run or confirm an approved run was actually processed.</div></div><form action={reconcilePayroll} className="grid gap-3"><input type="hidden" name="transaction_id" value={t.id}/><div className="grid gap-2"><Label>Payroll Run</Label><select className={selectClass} name="payroll_run_id" required defaultValue=""><option value="" disabled>Select payroll run</option>{(payroll||[]).map((p:any)=><option key={p.payroll_run_id} value={p.payroll_run_id}>{p.period_start} – {p.period_end} · {p.status} · {money(p.status==='processed'?p.actual_cash_paid:p.payroll_funding_requirement)}</option>)}</select></div><Button type="submit" className="w-fit">Reconcile Payroll</Button></form></CardContent></Card>}

              {cash<0&&<Card className="shadow-none"><CardContent className="space-y-3"><div><div className="font-semibold">Tax Payment</div><div className="mt-1 text-xs text-muted-foreground">Record money paid to a tax agency without treating it as operating revenue or duplicate job cost.</div></div><form action={reconcileTax} className="grid gap-3"><input type="hidden" name="transaction_id" value={t.id}/><div className="grid gap-2"><Label>Tax Type</Label><select className={selectClass} name="tax_type" defaultValue="sales_tax"><option value="sales_tax">Sales Tax</option><option value="bo">B&amp;O Tax</option><option value="payroll">Payroll Tax</option><option value="li">L&amp;I</option><option value="other">Other Tax</option></select></div><Button type="submit" className="w-fit">Record Tax Payment</Button></form></CardContent></Card>}

              {possibleTransfers.length>0&&<Card className="shadow-none"><CardContent className="space-y-3"><div><div className="font-semibold">Internal Transfer</div><div className="mt-1 text-xs text-muted-foreground">Moves money between Carez accounts without creating revenue or expense.</div></div><form action={reconcileTransfer} className="grid gap-3"><input type="hidden" name="transaction_id" value={t.id}/><div className="grid gap-2"><Label>Matching Bank Entry</Label><select className={selectClass} name="other_transaction_id" required defaultValue={possibleTransfers[0]?.entity_id||''}>{possibleTransfers.map((x:any)=><option key={x.id} value={x.entity_id}>{x.metadata?.other_name||'Other account transaction'} · {money(x.metadata?.amount)}</option>)}</select></div><Button type="submit" className="w-fit">Mark Internal Transfer</Button></form></CardContent></Card>}

              <Card className="shadow-none"><CardContent className="space-y-3"><div><div className="font-semibold">Ignore / Non-Accounting Activity</div><div className="mt-1 text-xs text-muted-foreground">Use for duplicates, non-business activity or bank entries that should not create a Carez financial record.</div></div><form action={ignoreBankTransaction} className="grid gap-3"><input type="hidden" name="transaction_id" value={t.id}/><div className="grid gap-2"><Label>Reason</Label><Input name="note" placeholder="Why this should be ignored"/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="remember_rule" className="size-4 rounded border-input accent-primary"/> Remember this merchant as ignored</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="auto_apply" className="size-4 rounded border-input accent-primary"/> Automatically ignore future matching transactions</label><Button type="submit" variant="outline" className="w-fit">Ignore Transaction</Button></form></CardContent></Card>
            </div></details>
          </div></TableCell>
        </TableRow>;
      })}</TableBody></Table></div>}
    </section>
  </div></AppShell>;
}
