import { redirect,notFound } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import PrintButton from './PrintButton';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const num=(v:any)=>Number(v||0);
export default async function PurchaseOrderDocument({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
  const {data:profile}=await supabase.from('profiles').select('company_id').eq('id',user.id).single();if(!profile?.company_id)redirect('/login');const companyId=profile.company_id;
  const [{data:po},{data:lines},{data:vendor},{data:project},{data:billingProfile}]=await Promise.all([
    supabase.from('purchase_orders').select('*').eq('id',id).eq('company_id',companyId).maybeSingle(),
    supabase.from('purchase_order_lines').select('*').eq('purchase_order_id',id).eq('company_id',companyId).order('sort_order'),
    supabase.from('vendors').select('*').eq('company_id',companyId).eq('id',(await supabase.from('purchase_orders').select('vendor_id').eq('id',id).eq('company_id',companyId).maybeSingle()).data?.vendor_id||'00000000-0000-0000-0000-000000000000').maybeSingle(),
    supabase.from('projects').select('id,job_number,name,address,city,state').eq('id',(await supabase.from('purchase_orders').select('project_id').eq('id',id).eq('company_id',companyId).maybeSingle()).data?.project_id||'00000000-0000-0000-0000-000000000000').maybeSingle(),
    supabase.from('company_billing_profiles').select('*').eq('company_id',companyId).maybeSingle()
  ]);
  if(!po)notFound();
  const subtotal=(lines||[]).reduce((s:number,l:any)=>s+num(l.subtotal),0),tax=(lines||[]).reduce((s:number,l:any)=>s+num(l.sales_tax),0),total=(lines||[]).reduce((s:number,l:any)=>s+num(l.total_cost),0);
  const carezName=po.from_name_snapshot||billingProfile?.display_name||'Carez Concrete';
  const carezAddress=po.from_address_snapshot||[billingProfile?.address_line1,billingProfile?.address_line2,billingProfile?.city,billingProfile?.state,billingProfile?.postal_code].filter(Boolean).join(', ');
  const vendorName=po.vendor_name_snapshot||vendor?.name||'Vendor';
  const vendorAddress=po.vendor_address_snapshot||[vendor?.address_line1,vendor?.address_line2,vendor?.city,vendor?.state,vendor?.postal_code].filter(Boolean).join(', ');
  return <div style={{minHeight:'100vh',background:'#e9edf3',padding:'24px',fontFamily:'Arial,Helvetica,sans-serif',color:'#111827'}}>
    <style>{`@media print{body{margin:0}.po-actions{display:none!important}.po-sheet{box-shadow:none!important;margin:0!important;max-width:none!important}.po-bg{padding:0!important;background:white!important}}`}</style>
    <div className="po-bg" style={{maxWidth:960,margin:'0 auto'}}><div className="po-actions" style={{display:'flex',justifyContent:'flex-end',gap:10,marginBottom:12}}><PrintButton/></div>
      <main className="po-sheet" style={{background:'#fff',boxShadow:'0 12px 40px rgba(15,23,42,.16)',padding:'42px 46px'}}>
        <header style={{display:'flex',justifyContent:'space-between',gap:30,borderBottom:'3px solid #244ca6',paddingBottom:24}}><div><img src="/brand/carez-wordmark.png" alt="Carez Concrete" style={{width:220,maxWidth:'100%',filter:'brightness(0.7) saturate(1.2)'}}/><div style={{marginTop:10,fontSize:13,lineHeight:1.6,color:'#475569'}}><strong>{carezName}</strong><br/>{carezAddress||''}<br/>{po.from_phone_snapshot||billingProfile?.phone||''}{(po.from_email_snapshot||billingProfile?.email)?<><br/>{po.from_email_snapshot||billingProfile?.email}</>:null}{(po.from_ubi_snapshot||billingProfile?.ubi_number)?<><br/>WA UBI: {po.from_ubi_snapshot||billingProfile?.ubi_number}</>:null}{(po.from_license_snapshot||billingProfile?.contractor_license_number)?<><br/>Contractor Lic: {po.from_license_snapshot||billingProfile?.contractor_license_number}</>:null}</div></div><div style={{textAlign:'right'}}><div style={{fontSize:13,fontWeight:800,letterSpacing:'.14em',color:'#64748b'}}>PURCHASE ORDER</div><div style={{fontSize:34,fontWeight:900,color:'#0f172a',marginTop:5}}>{po.po_number}</div><div style={{marginTop:12,fontSize:13,lineHeight:1.7}}><strong>Status:</strong> {String(po.status).toUpperCase()}<br/><strong>Issue Date:</strong> {po.issue_date||'Draft'}<br/><strong>Expected Delivery:</strong> {po.expected_delivery_date||'—'}</div></div></header>
        <section style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:36,padding:'28px 0'}}><div><div style={{fontSize:11,fontWeight:900,letterSpacing:'.12em',color:'#64748b',marginBottom:8}}>VENDOR</div><div style={{fontSize:18,fontWeight:800}}>{vendorName}</div><div style={{fontSize:13,lineHeight:1.6,color:'#475569',marginTop:5}}>{po.vendor_contact_snapshot||vendor?.contact_name||''}<br/>{vendorAddress||''}{(po.vendor_phone_snapshot||vendor?.phone)?<><br/>{po.vendor_phone_snapshot||vendor?.phone}</>:null}{(po.vendor_email_snapshot||vendor?.email)?<><br/>{po.vendor_email_snapshot||vendor?.email}</>:null}</div></div><div><div style={{fontSize:11,fontWeight:900,letterSpacing:'.12em',color:'#64748b',marginBottom:8}}>PROJECT / DELIVERY</div><div style={{fontSize:18,fontWeight:800}}>{project?.job_number||''} — {project?.name||''}</div><div style={{fontSize:13,lineHeight:1.6,color:'#475569',marginTop:5}}>{[project?.address,project?.city,project?.state].filter(Boolean).join(', ')}</div>{po.delivery_instructions&&<div style={{marginTop:10,fontSize:13}}><strong>Delivery:</strong> {po.delivery_instructions}</div>}</div></section>
        <table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr style={{background:'#eef3fb',borderTop:'1px solid #cbd5e1',borderBottom:'1px solid #cbd5e1'}}><th style={{textAlign:'left',padding:'11px 8px'}}>Description</th><th style={{textAlign:'right',padding:'11px 8px'}}>Qty</th><th style={{textAlign:'left',padding:'11px 8px'}}>Unit</th><th style={{textAlign:'right',padding:'11px 8px'}}>Unit Cost</th><th style={{textAlign:'right',padding:'11px 8px'}}>Tax</th><th style={{textAlign:'right',padding:'11px 8px'}}>Total</th></tr></thead><tbody>{(lines||[]).map((l:any)=><tr key={l.id} style={{borderBottom:'1px solid #e2e8f0'}}><td style={{padding:'12px 8px'}}><strong>{l.description}</strong>{l.notes&&<div style={{fontSize:11,color:'#64748b',marginTop:3}}>{l.notes}</div>}</td><td style={{padding:'12px 8px',textAlign:'right'}}>{num(l.quantity).toFixed(2)}</td><td style={{padding:'12px 8px'}}>{l.unit}</td><td style={{padding:'12px 8px',textAlign:'right'}}>{money(num(l.unit_cost))}</td><td style={{padding:'12px 8px',textAlign:'right'}}>{money(num(l.sales_tax))}</td><td style={{padding:'12px 8px',textAlign:'right',fontWeight:800}}>{money(num(l.total_cost))}</td></tr>)}</tbody></table>
        <section style={{display:'flex',justifyContent:'flex-end',paddingTop:22}}><div style={{width:320,fontSize:14}}><div style={{display:'flex',justifyContent:'space-between',padding:'6px 0'}}><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div style={{display:'flex',justifyContent:'space-between',padding:'6px 0'}}><span>Estimated Sales Tax</span><strong>{money(tax)}</strong></div><div style={{display:'flex',justifyContent:'space-between',padding:'12px 0',borderTop:'2px solid #0f172a',fontSize:20}}><strong>PO Total</strong><strong>{money(total)}</strong></div></div></section>
        {(po.terms||po.notes)&&<section style={{marginTop:30,paddingTop:20,borderTop:'1px solid #cbd5e1',fontSize:12,lineHeight:1.6,color:'#475569'}}>{po.terms&&<div><strong>Terms:</strong> {po.terms}</div>}{po.notes&&<div style={{marginTop:8}}><strong>Notes:</strong> {po.notes}</div>}</section>}
      </main></div>
  </div>;
}
