import {redirect} from 'next/navigation';
import Link from 'next/link';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';
import {saveProductionQuantity,setProductionReporter,verifyProductionReport} from './actions';

const n=(v:any)=>Number(v||0);const rate=(v:any,u:string)=>v==null?'—':`${n(v).toFixed(2)} ${u}/MH`;const mh=(v:any,u:string)=>v==null?'—':`${n(v).toFixed(3)} MH/${u}`;
const statusLabel=(s:string)=>s==='needs_quantity'?'Need Quantity':s==='needs_report_review'?'Review Report':s==='waiting_time_approval'?'Approve Time':s==='quantity_no_task_time'?'Check Time':'Rate Ready';
export default async function ProductionPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(!profile?.company_id)redirect('/login');if(profile.role==='employee')redirect('/employee');const companyId=profile.company_id;
 const [{data:queue},{data:summary},{data:jobs},{data:history},{data:crew},{data:reports}]=await Promise.all([
  supabase.from('production_work_queue').select('*').eq('company_id',companyId).order('work_date',{ascending:false}).limit(100),
  supabase.from('production_task_rate_summary').select('*').eq('company_id',companyId).order('task_name'),
  supabase.from('project_production_rate_summary').select('*').eq('company_id',companyId).order('latest_work_date',{ascending:false}).limit(100),
  supabase.from('production_rate_history').select('*').eq('company_id',companyId).order('work_date',{ascending:false}).limit(25),
  supabase.from('crew_members').select('id,name,role,can_report_production,profile_id,active').eq('company_id',companyId).eq('active',true).order('name'),
  supabase.from('daily_production_records').select('id,project_id,work_date,production_task_id,quantity_completed,unit,notes,source,review_status,projects(job_number,name),production_tasks(name)').eq('company_id',companyId).eq('review_status','needs_review').order('work_date',{ascending:false})
 ]);
 const needsQty=(queue||[]).filter((x:any)=>x.production_status==='needs_quantity');const reportReview=(queue||[]).filter((x:any)=>x.production_status==='needs_report_review');const waiting=(queue||[]).filter((x:any)=>x.production_status==='waiting_time_approval');const ready=(queue||[]).filter((x:any)=>x.production_status==='rate_ready');
 return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page">
  <div className="command-hero"><div><div className="section-kicker">FIELD INTELLIGENCE</div><h1>Production Control</h1><p>Employees identify plain-language work. One crew lead records the quantity once. Carez combines approved task time and quantity into measured production rates.</p></div><div className="command-actions"><Link className="button secondary" href="/schedule">Schedule Work</Link><Link className="button secondary" href="/field/review">Review Time</Link></div></div>
  <div className="command-grid"><div className={`command-card ${needsQty.length?'watch':'good'}`}><div className="command-label">Need Crew Quantity</div><div className="command-value">{needsQty.length}</div><div className="command-help">Task time exists but no completed quantity is recorded.</div></div><div className={`command-card ${reportReview.length?'watch':'good'}`}><div className="command-label">Field Reports to Review</div><div className="command-value">{reportReview.length}</div><div className="command-help">Unusual crew-lead entries are excluded from rates until verified.</div></div><div className={`command-card ${waiting.length?'watch':'good'}`}><div className="command-label">Waiting on Time</div><div className="command-value">{waiting.length}</div><div className="command-help">Quantity exists; employee time still needs approval.</div></div><div className="command-card good"><div className="command-label">Rates Ready</div><div className="command-value">{ready.length}</div><div className="command-help">Trusted job/task/day production samples.</div></div></div>

  {(reports||[]).length>0&&<section className="section"><div className="section-heading"><div><div className="section-kicker">EXCEPTIONS</div><div className="section-title">Crew Reports Needing Review</div><div className="section-heading-meta">Normal reports tied to scheduled work are accepted automatically. Off-schedule or unusual reports cannot affect measured rates until you verify them.</div></div></div><div className="project-list">{(reports||[]).map((r:any)=><article className="project-card" key={r.id}><section className="project-section"><div className="row"><div><div className="title">{r.projects?.job_number} — {r.production_tasks?.name}</div><div className="meta">{r.work_date} · {n(r.quantity_completed).toFixed(2)} {r.unit}{r.notes?` · ${r.notes}`:''}</div></div><form action={verifyProductionReport}><input type="hidden" name="record_id" value={r.id}/><button className="button">Verify Quantity</button></form></div></section></article>)}</div></section>}

  <section className="section"><div className="section-heading"><div><div className="section-kicker">WORK QUEUE</div><div className="section-title">What Is Missing?</div><div className="section-heading-meta">Carez tells you why a rate is not ready instead of making you hunt through timecards.</div></div></div>{(queue||[]).length===0?<div className="empty-state"><div><div className="title">No production activity yet</div><div className="meta">Schedule a crew task and employee task time will begin feeding this screen.</div></div></div>:<div className="project-list">{(queue||[]).slice(0,40).map((x:any)=><article className="project-card" key={`${x.project_id}-${x.work_date}-${x.production_task_id}`}><header className="project-header"><div><div className="project-name">{x.job_number} — {x.task_name}</div><div className="project-location">{x.work_date} · {x.project_name}</div></div><span className={`status ${x.production_status==='rate_ready'?'completed':x.production_status==='needs_quantity'||x.production_status==='needs_report_review'?'on-hold':''}`}>{statusLabel(x.production_status)}</span></header><section className="project-section"><div className="metric-grid"><div className="metric-card"><div className="label">Tracked Crew Hours</div><div className="metric-value">{n(x.tracked_man_hours).toFixed(2)} MH</div></div><div className="metric-card"><div className="label">Completed</div><div className="metric-value">{x.quantity_completed==null?'—':`${n(x.quantity_completed).toFixed(2)} ${x.unit}`}</div></div><div className="metric-card brand"><div className="label">Trusted Actual Rate</div><div className="metric-value">{x.production_status==='needs_report_review'?'Held for Review':rate(x.units_per_man_hour,x.unit)}</div></div></div>{x.production_status==='needs_quantity'&&<form action={saveProductionQuantity} className="form section"><input type="hidden" name="project_id" value={x.project_id}/><input type="hidden" name="work_date" value={x.work_date}/><input type="hidden" name="production_task_id" value={x.production_task_id}/><div className="grid grid2"><label className="field"><span>Crew quantity completed ({x.unit})</span><input type="number" min="0" step="0.01" name="quantity_completed" required/></label><label className="field"><span>Note</span><input name="notes" placeholder="North wall, garage slab, etc."/></label></div><button className="button">Save Quantity</button></form>}{x.production_status==='needs_report_review'&&<div className="alert warning section"><strong>This quantity is not in Carez production history yet.</strong><div>Verify it in the exception section above or replace it with the office-corrected quantity.</div></div>}{x.production_status==='quantity_no_task_time'&&<div className="alert warning section"><strong>Quantity exists but no matching task time exists.</strong><div>Check employee task clocking or a manually entered timecard before using this result.</div></div>}</section></article>)}</div>}</section>

  <section className="section"><div className="section-heading"><div><div className="section-kicker">CAREZ ACTUALS</div><div className="section-title">Measured Production Rates</div><div className="section-heading-meta">Weighted actual rates from approved task time and trusted quantities only. These become the basis for better estimating after enough history exists.</div></div></div>{(summary||[]).length===0?<div className="empty-state"><div><div className="title">No measured rates yet</div><div className="meta">Rates appear after approved task time and a trusted daily crew quantity exist.</div></div></div>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Work</th><th>Samples</th><th>Total Qty</th><th>Crew MH</th><th>Actual Rate</th><th>MH / Unit</th></tr></thead><tbody>{(summary||[]).map((x:any)=><tr key={x.production_task_id}><td><strong>{x.task_name}</strong></td><td>{x.sample_days}</td><td>{n(x.total_quantity).toFixed(2)} {x.unit}</td><td>{n(x.total_man_hours).toFixed(2)}</td><td>{rate(x.weighted_units_per_man_hour,x.unit)}</td><td>{mh(x.weighted_man_hours_per_unit,x.unit)}</td></tr>)}</tbody></table></div>}</section>

  <section className="section"><div className="section-heading"><div><div className="section-kicker">ACCOUNTABILITY</div><div className="section-title">Who Reports Crew Quantity?</div><div className="section-heading-meta">Use one responsible lead or foreman per crew. Regular employees never see production quantities, rates or cost codes.</div></div></div><div className="grid grid2">{(crew||[]).map((c:any)=><div className="card" key={c.id}><div className="row"><div><div className="title">{c.name}</div><div className="meta">{c.role}{!c.profile_id?' · No employee login yet':''}</div></div><span className={`status ${c.can_report_production?'completed':''}`}>{c.can_report_production?'Crew Reporter':'Time Only'}</span></div><form action={setProductionReporter} className="section"><input type="hidden" name="crew_member_id" value={c.id}/><label className="meta"><input type="checkbox" name="enabled" defaultChecked={Boolean(c.can_report_production)}/> Can report the crew's completed quantity</label><div><button className="button secondary">Save Responsibility</button></div></form></div>)}</div></section>

  {(jobs||[]).length>0&&<section className="section"><div className="section-heading"><div><div className="section-kicker">BY JOB</div><div className="section-title">Project Production Rates</div><div className="section-heading-meta">See whether the same work performs differently from job to job.</div></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Job</th><th>Work</th><th>Samples</th><th>Quantity</th><th>Crew MH</th><th>Rate</th></tr></thead><tbody>{(jobs||[]).slice(0,50).map((x:any)=><tr key={`${x.project_id}-${x.production_task_id}`}><td>{x.job_number} — {x.project_name}</td><td>{x.task_name}</td><td>{x.sample_days}</td><td>{n(x.total_quantity).toFixed(2)} {x.unit}</td><td>{n(x.total_man_hours).toFixed(2)}</td><td>{rate(x.units_per_man_hour,x.unit)}</td></tr>)}</tbody></table></div></section>}

  {(history||[]).length>0&&<section className="section"><div className="section-heading"><div><div className="section-kicker">RECENT SAMPLES</div><div className="section-title">Field Rate History</div></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Work</th><th>Quantity</th><th>Crew MH</th><th>Rate</th></tr></thead><tbody>{(history||[]).map((x:any)=><tr key={`${x.project_id}-${x.work_date}-${x.production_task_id}`}><td>{x.work_date}</td><td>{x.task_name}</td><td>{n(x.quantity_completed).toFixed(2)} {x.unit}</td><td>{n(x.man_hours).toFixed(2)}</td><td>{rate(x.units_per_man_hour,x.unit)}</td></tr>)}</tbody></table></div></section>}
 </div></AppShell>;
}
