import {redirect} from 'next/navigation';
import Link from 'next/link';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';
import {saveProductionQuantity,verifyProductionReport} from './actions';

const n=(v:any)=>Number(v||0);const rate=(v:any,u:string)=>v==null?'—':`${n(v).toFixed(2)} ${u}/MH`;const mh=(v:any,u:string)=>v==null?'—':`${n(v).toFixed(4)} MH/${u}`;const q=(v:any,u:string)=>`${n(v).toLocaleString(undefined,{maximumFractionDigits:2})} ${u}`;const riskLabel=(r:string)=>r==='no_budget'?'No Labor Plan':r==='critical'?'Critical':r==='over_budget'?'Over Budget':r==='watch'?'Watch':'On Track';
export default async function ProductionPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(!profile?.company_id)redirect('/login');if(profile.role==='employee')redirect('/employee');const companyId=profile.company_id;
 const [{data:packageOps},{data:learning},{data:earnedHistory},{data:legacyQueue},{data:reports}]=await Promise.all([
  supabase.from('production_operation_risk').select('*').eq('company_id',companyId).order('job_number').order('package_name').limit(150),
  supabase.from('carez_production_learning_summary').select('*').eq('company_id',companyId).order('task_name'),
  supabase.from('earned_production_rate_history').select('*').eq('company_id',companyId).order('completed_at',{ascending:false}).limit(40),
  supabase.from('production_work_queue').select('*').eq('company_id',companyId).in('production_status',['needs_quantity','needs_report_review','quantity_no_task_time']).order('work_date',{ascending:false}).limit(40),
  supabase.from('daily_production_records').select('id,project_id,work_date,production_task_id,quantity_completed,unit,notes,source,review_status,projects(job_number,name),production_tasks(name)').eq('company_id',companyId).eq('review_status','needs_review').order('work_date',{ascending:false})
 ]);
 const open=(packageOps||[]).filter((x:any)=>!['completed','cancelled'].includes(x.operation_status));const active=open.filter((x:any)=>x.operation_status==='in_progress');const laborRisk=open.filter((x:any)=>x.needs_attention);const overBudget=open.filter((x:any)=>['over_budget','critical'].includes(x.labor_risk));const noBudget=open.filter((x:any)=>x.labor_risk==='no_budget');
 return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page">
  <div className="command-hero"><div><div className="section-kicker">FIELD INTELLIGENCE</div><h1>Production Control</h1><p>Carez measures production from physical work packages and warns you when labor is being consumed faster than the package budget—before the work is finished.</p></div><div className="command-actions"><Link className="button" href="/production/work-packages">Work Packages</Link><Link className="button secondary" href="/schedule">Schedule Work</Link><Link className="button secondary" href="/field/review">Review Time</Link></div></div>
  <div className="command-grid"><div className={`command-card ${laborRisk.length?'bad':'good'}`}><div className="command-label">Need Attention</div><div className="command-value">{laborRisk.length}</div><div className="command-help">Open work at 80%+ labor burn or past planned finish.</div></div><div className={`command-card ${overBudget.length?'bad':'good'}`}><div className="command-label">Over Labor Budget</div><div className="command-value">{overBudget.length}</div><div className="command-help">Packages still open after using 100%+ of planned man-hours.</div></div><div className={`command-card ${noBudget.length?'watch':'good'}`}><div className="command-label">Need Labor Plan</div><div className="command-value">{noBudget.length}</div><div className="command-help">Known scopes that cannot be monitored until expected MH is seeded.</div></div><div className="command-card good"><div className="command-label">Learned Work Types</div><div className="command-value">{(learning||[]).length}</div><div className="command-help">Production categories with trusted Carez field samples.</div></div></div>

  {laborRisk.length>0&&<section className="section"><div className="section-heading"><div><div className="section-kicker">EARLY WARNING</div><div className="section-title">Production Risk Before Completion</div><div className="section-heading-meta">Carez does not ask the foreman for percent complete. It knows the labor allowance and watches real employee man-hours as they accumulate.</div></div><Link className="button secondary" href="/production/work-packages">Adjust Labor Plans</Link></div><div className="project-list">{laborRisk.map((x:any)=><article className="project-card" key={`risk-${x.operation_id}`}><header className="project-header"><div><div className="project-name">{x.job_number} — {x.package_name}</div><div className="project-location">{x.field_label||x.task_name}{x.location?` · ${x.location}`:''}</div></div><div className="action-row">{x.schedule_risk==='overdue'&&<span className="status on-hold">Overdue</span>}<span className={`status ${['critical','over_budget'].includes(x.labor_risk)?'on-hold':'active'}`}>{riskLabel(x.labor_risk)}</span></div></header><section className="project-section"><div className="metric-grid"><div className={`metric-card ${n(x.budget_hours_used_percent)>=100?'danger-metric':'brand'}`}><div className="label">Labor Budget Used</div><div className="metric-value">{x.budget_hours_used_percent==null?'—':`${n(x.budget_hours_used_percent).toFixed(0)}%`}</div><div className="metric-detail">{n(x.tracked_man_hours).toFixed(2)} MH used of {n(x.budgeted_man_hours).toFixed(2)} MH</div></div><div className="metric-card"><div className="label">Budget Hours Left</div><div className="metric-value">{x.budget_man_hours_remaining==null?'—':`${n(x.budget_man_hours_remaining).toFixed(2)} MH`}</div><div className="metric-detail">Work is still {String(x.operation_status).replace('_',' ')}.</div></div><div className="metric-card"><div className="label">Known Scope</div><div className="metric-value">{q(x.planned_quantity,x.unit)}</div><div className="metric-detail">No daily field quantity calculation required.</div></div></div>{n(x.over_budget_man_hours)>0&&<div className="alert warning section"><strong>{n(x.over_budget_man_hours).toFixed(2)} man-hours beyond the labor plan and the operation is not finished.</strong><div>This is the point Carez should trigger a management conversation—not after job-cost reports arrive weeks later.</div></div>}</section></article>)}</div></section>}

  <section className="section"><div className="section-heading"><div><div className="section-kicker">EARNED PRODUCTION</div><div className="section-title">Physical Work in the Field</div><div className="section-heading-meta">Known takeoff quantity + automatic employee time + finish confirmation. The same record becomes production history for future estimates.</div></div><Link className="button secondary" href="/production/work-packages">Manage Packages</Link></div>{(packageOps||[]).length===0?<div className="empty-state"><div><div className="title">No work packages yet</div><div className="meta">Create a physical package such as Basement North Wall and define Form, Rebar, Place and Strip quantities once.</div><div className="action-row"><Link className="button" href="/production/work-packages">Create First Package</Link></div></div></div>:<div className="project-list">{(packageOps||[]).filter((x:any)=>x.operation_status!=='cancelled').slice(0,50).map((x:any)=><article className="project-card" key={x.operation_id}><header className="project-header"><div><div className="project-name">{x.job_number} — {x.package_name}</div><div className="project-location">{x.field_label||x.task_name}{x.location?` · ${x.location}`:''}</div></div><div className="action-row">{x.operation_status!=='completed'&&<span className={`status ${['critical','over_budget'].includes(x.labor_risk)?'on-hold':x.labor_risk==='watch'?'active':''}`}>{riskLabel(x.labor_risk)}</span>}<span className={`status ${x.operation_status==='completed'?'completed':x.operation_status==='in_progress'?'active':''}`}>{x.operation_status.replace('_',' ')}</span></div></header><section className="project-section"><div className="metric-grid"><div className="metric-card brand"><div className="label">Known Quantity</div><div className="metric-value">{q(x.planned_quantity,x.unit)}</div><div className="metric-detail">Earned automatically when this operation is finished.</div></div><div className="metric-card"><div className="label">Tracked Crew Time</div><div className="metric-value">{n(x.tracked_man_hours).toFixed(2)} MH</div><div className="metric-detail">Approved: {n(x.approved_man_hours).toFixed(2)} MH</div></div><div className={`metric-card ${x.budget_hours_used_percent!=null&&n(x.budget_hours_used_percent)>=100?'danger-metric':'positive'}`}><div className="label">Labor Budget Used</div><div className="metric-value">{x.budget_hours_used_percent==null?'—':`${n(x.budget_hours_used_percent).toFixed(0)}%`}</div><div className="metric-detail">Budget: {x.budgeted_man_hours==null?'not seeded yet':`${n(x.budgeted_man_hours).toFixed(2)} MH`}</div></div></div></section></article>)}</div>}</section>

  <section className="section"><div className="section-heading"><div><div className="section-kicker">CAREZ LEARNING ENGINE</div><div className="section-title">Measured Company Production</div><div className="section-heading-meta">The future estimator can gradually trust these company-specific results more than generic assumptions as confidence grows.</div></div></div>{(learning||[]).length===0?<div className="empty-state"><div><div className="title">Learning starts after the first completed package</div><div className="meta">Finish a defined package, approve the employee time, and Carez has its first real production sample.</div></div></div>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Work</th><th>Packages</th><th>Jobs</th><th>Total Qty</th><th>Crew MH</th><th>Actual Rate</th><th>MH / Unit</th><th>Confidence</th></tr></thead><tbody>{(learning||[]).map((x:any)=><tr key={x.production_task_id}><td><strong>{x.task_name}</strong></td><td>{x.sample_packages}</td><td>{x.sample_projects}</td><td>{q(x.total_quantity,x.unit)}</td><td>{n(x.total_man_hours).toFixed(2)}</td><td>{rate(x.weighted_units_per_man_hour,x.unit)}</td><td>{mh(x.weighted_man_hours_per_unit,x.unit)}</td><td><span className={`status ${x.confidence==='high'?'completed':x.confidence==='medium'?'active':''}`}>{x.confidence}</span></td></tr>)}</tbody></table></div>}</section>

  {(earnedHistory||[]).length>0&&<section className="section"><div className="section-heading"><div><div className="section-kicker">AUDIT TRAIL</div><div className="section-title">Recent Completed Packages</div><div className="section-heading-meta">Every learned rate traces back to a physical scope, exact earned quantity and approved employee man-hours.</div></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Completed</th><th>Job / Package</th><th>Work</th><th>Quantity</th><th>MH</th><th>Actual</th><th>Source</th></tr></thead><tbody>{(earnedHistory||[]).map((x:any)=><tr key={x.operation_id}><td>{x.completed_date}</td><td>{x.job_number} — {x.package_name}</td><td>{x.task_name}</td><td>{q(x.quantity_completed,x.unit)}</td><td>{n(x.man_hours).toFixed(2)}</td><td>{mh(x.man_hours_per_unit,x.unit)}</td><td>{String(x.completion_source||'confirmed').replaceAll('_',' ')}</td></tr>)}</tbody></table></div></section>}

  {((reports||[]).length>0||(legacyQueue||[]).length>0)&&<section className="section"><div className="section-heading"><div><div className="section-kicker">EXCEPTIONS ONLY</div><div className="section-title">Unplanned / Legacy Production Entries</div><div className="section-heading-meta">Manual quantities remain available for unusual work, but they are no longer the normal field workflow.</div></div></div>{(reports||[]).length>0&&<div className="project-list">{(reports||[]).map((r:any)=><article className="project-card" key={r.id}><section className="project-section"><div className="row"><div><div className="title">{r.projects?.job_number} — {r.production_tasks?.name}</div><div className="meta">{r.work_date} · {q(r.quantity_completed,r.unit)}{r.notes?` · ${r.notes}`:''}</div></div><form action={verifyProductionReport}><input type="hidden" name="record_id" value={r.id}/><button className="button secondary">Verify Exception</button></form></div></section></article>)}</div>}{(legacyQueue||[]).filter((x:any)=>x.production_status==='needs_quantity').map((x:any)=><div className="surface section" key={`${x.project_id}-${x.work_date}-${x.production_task_id}`}><div className="surface-body"><div className="title">{x.job_number} — {x.task_name} · {x.work_date}</div><div className="meta">Unplanned task time has {n(x.tracked_man_hours).toFixed(2)} MH but no physical package quantity.</div><details className="section"><summary className="title" style={{cursor:'pointer'}}>Enter manual exception quantity</summary><form action={saveProductionQuantity} className="form" style={{marginTop:12}}><input type="hidden" name="project_id" value={x.project_id}/><input type="hidden" name="work_date" value={x.work_date}/><input type="hidden" name="production_task_id" value={x.production_task_id}/><div className="grid grid2"><label className="field"><span>Completed quantity ({x.unit})</span><input type="number" min="0" step="0.01" name="quantity_completed" required/></label><label className="field"><span>Why was this outside a package?</span><input name="notes" required placeholder="Change order, repair, unexpected extra work..."/></label></div><button className="button secondary">Save Exception Quantity</button></form></details></div></div>)}</section>}

  <section className="section"><div className="surface"><div className="surface-body"><div className="row"><div><div className="title">Closed-loop rule</div><div className="meta">Estimate/takeoff quantity → labor plan → physical package → employee time → live labor-burn warning → finish confirmation → earned quantity → approved MH → Carez production rate → better future estimate.</div></div><span className="status completed">No Re-entry</span></div></div></div></section>
 </div></AppShell>;
}
