'use server';
import {revalidatePath} from 'next/cache';
import {createClient} from '@/lib/supabase/server';

async function ctx(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Not signed in');const {data:p}=await supabase.from('profiles').select('company_id,role').eq('id',user.id).single();if(!p?.company_id||p.role==='employee')throw new Error('Owner access required');return {supabase,user,companyId:p.company_id};}
const num=(v:FormDataEntryValue|null)=>{const x=Number(String(v??'').replace(/[$,% ,]/g,''));return Number.isFinite(x)?x:null;};

export async function createEquipmentAsset(fd:FormData){const name=String(fd.get('name')||'').trim();if(!name)return;const {supabase,companyId}=await ctx();const {error}=await supabase.from('equipment_assets').insert({company_id:companyId,name,asset_number:String(fd.get('asset_number')||'').trim()||null,category:String(fd.get('category')||'tool'),make:String(fd.get('make')||'').trim()||null,model:String(fd.get('model')||'').trim()||null,serial_number:String(fd.get('serial_number')||'').trim()||null,purchase_date:String(fd.get('purchase_date')||'')||null,purchase_cost:num(fd.get('purchase_cost')),status:'available',service_interval_hours:num(fd.get('service_interval_hours')),current_meter_hours:num(fd.get('current_meter_hours'))||0,next_service_date:String(fd.get('next_service_date')||'')||null,notes:String(fd.get('notes')||'').trim()||null});if(error)throw new Error(error.message);revalidatePath('/equipment');}

export async function assignEquipment(fd:FormData){const id=String(fd.get('id')||'');if(!id)return;const {supabase,companyId}=await ctx();const project=String(fd.get('assigned_project_id')||'')||null,crew=String(fd.get('assigned_crew_member_id')||'')||null,status=String(fd.get('status')||'available');const {error}=await supabase.from('equipment_assets').update({assigned_project_id:project,assigned_crew_member_id:crew,status,updated_at:new Date().toISOString()}).eq('id',id).eq('company_id',companyId);if(error)throw new Error(error.message);revalidatePath('/equipment');}

export async function recordEquipmentService(fd:FormData){const equipment_id=String(fd.get('equipment_id')||''),description=String(fd.get('description')||'').trim();if(!equipment_id||!description)return;const {supabase,companyId}=await ctx();const serviceDate=String(fd.get('service_date')||new Date().toISOString().slice(0,10)),meter=num(fd.get('meter_hours')),next=String(fd.get('next_service_date')||'')||null;const {error}=await supabase.from('equipment_service_logs').insert({company_id:companyId,equipment_id,service_date:serviceDate,meter_hours:meter,description,cost:num(fd.get('cost'))||0,vendor:String(fd.get('vendor')||'').trim()||null,next_service_date:next,notes:String(fd.get('notes')||'').trim()||null});if(error)throw new Error(error.message);await supabase.from('equipment_assets').update({current_meter_hours:meter??undefined,next_service_date:next,updated_at:new Date().toISOString()}).eq('id',equipment_id).eq('company_id',companyId);revalidatePath('/equipment');}

export async function createInventoryItem(fd:FormData){const name=String(fd.get('name')||'').trim();if(!name)return;const {supabase,companyId}=await ctx();const {error}=await supabase.from('inventory_items').insert({company_id:companyId,name,category:String(fd.get('category')||'formwork'),unit:String(fd.get('unit')||'EA'),quantity_on_hand:num(fd.get('quantity_on_hand'))||0,reorder_point:num(fd.get('reorder_point'))||0,target_quantity:num(fd.get('target_quantity')),average_unit_cost:num(fd.get('average_unit_cost'))||0,storage_location:String(fd.get('storage_location')||'').trim()||null,notes:String(fd.get('notes')||'').trim()||null});if(error)throw new Error(error.message);revalidatePath('/equipment');}

export async function adjustInventory(fd:FormData){const inventory_item_id=String(fd.get('inventory_item_id')||''),qty=num(fd.get('quantity'));if(!inventory_item_id||qty===null||qty===0)return;const {supabase,user,companyId}=await ctx();const {data:item}=await supabase.from('inventory_items').select('quantity_on_hand').eq('id',inventory_item_id).eq('company_id',companyId).single();if(!item)throw new Error('Inventory item not found');const type=String(fd.get('transaction_type')||'adjustment');const delta=type==='out'? -Math.abs(qty):type==='in'?Math.abs(qty):qty;const next=Number(item.quantity_on_hand||0)+delta;if(next<0)throw new Error('Inventory cannot go below zero');const {error}=await supabase.from('inventory_transactions').insert({company_id:companyId,inventory_item_id,project_id:String(fd.get('project_id')||'')||null,transaction_type:type,quantity:delta,unit_cost:num(fd.get('unit_cost')),transaction_date:String(fd.get('transaction_date')||new Date().toISOString().slice(0,10)),note:String(fd.get('note')||'').trim()||null,created_by:user.id});if(error)throw new Error(error.message);await supabase.from('inventory_items').update({quantity_on_hand:next,updated_at:new Date().toISOString()}).eq('id',inventory_item_id).eq('company_id',companyId);revalidatePath('/equipment');}
