import Link from 'next/link';
import {redirect} from 'next/navigation';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';
import {outlookConfigured} from '@/lib/outlook';
import {createLeadFromCandidate,disconnectOutlook,ignoreLeadCandidate,syncOutlookNow} from './actions';

const pct=(n:any)=>`${Math.round(Number(n||0)*100)}%`;

export default async function LeadInboxPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const {data:p}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(!p?.company_id)redirect('/login');if(p.role==='employee')redirect('/employee');
 const [{data:connection},{data:candidates},{data:messages}]=await Promise.all([
  supabase.from('outlook_connections').select('*').eq('company_id',p.company_id).maybeSingle(),
  supabase.from('lead_inbox_candidates').select('*,outlook_messages(subject,sender_name,sender_email,received_at,web_link)').eq('company_id',p.company_id).eq('status','pending').order('created_at',{ascending:false}),
  supabase.from('outlook_messages').select('id,subject,sender_name,sender_email,received_at,classification,confidence,lead_id,leads(opportunity_number,project_name)').eq('company_id',p.company_id).not('lead_id','is',null).order('received_at',{ascending:false}).limit(20)
 ]);
 const configured=outlookConfigured(),connected=connection?.status==='active',background=Boolean(connection?.subscription_id&&connection?.subscription_expires_at&&new Date(connection.subscription_expires_at).getTime()>Date.now());
 return <AppShell userName={p.full_name||user.email||'Owner'}><div className="contractor-page">
  <div className="command-hero"><div><h1>Lead Inbox</h1><p>Outlook watches for real concrete opportunities. Clear leads can be created automatically; uncertain emails wait here for your approval.</p></div><div className="command-actions">{connected?<form action={syncOutlookNow}><button className="button">Check Outlook Now</button></form>:<a className="button" href="/api/outlook/connect">Connect Outlook</a>}<Link className="button secondary" href="/leads">Job Pipeline</Link></div></div>
  <div className="command-grid"><div className={`command-card ${connected?'good':'watch'}`}><div className="command-label">Outlook</div><div className="command-value">{connected?'Connected':'Not Connected'}</div><div className="command-help">{connection?.mailbox_email||'Connect the Carez mailbox.'}</div></div><div className={`command-card ${(candidates||[]).length?'watch':'good'}`}><div className="command-label">Needs Your Review</div><div className="command-value">{(candidates||[]).length}</div><div className="command-help">Possible jobs Carez was not confident enough to create automatically.</div></div><div className="command-card"><div className="command-label">Auto-Created From Email</div><div className="command-value">{(messages||[]).length}</div><div className="command-help">Recent Outlook messages already tied to numbered leads.</div></div><div className={`command-card ${connected&&background?'good':connected?'watch':''}`}><div className="command-label">Background Watch</div><div className="command-value">{connected?(background?'On':'Needs Attention'):'Off'}</div><div className="command-help">{background?`Microsoft subscription through ${new Date(connection.subscription_expires_at).toLocaleDateString()}.`:'Manual sync still works; background notification setup needs attention.'}</div></div></div>
  {!configured&&<div className="alert warn"><strong>Microsoft app setup is not finished.</strong> Carez needs MICROSOFT_CLIENT_ID and MICROSOFT_CLIENT_SECRET in Vercel before the Connect Outlook button can authorize the mailbox.</div>}
  {connection?.last_error&&<div className="alert warn"><strong>Outlook needs attention:</strong> {connection.last_error}</div>}
  <section className="section"><div className="section-heading"><div><div className="section-kicker">Review</div><div className="section-title">Possible Leads</div><div className="section-heading-meta">Create it if this is real work. Ignore it if it is vendor mail, spam or an existing-job conversation.</div></div></div>
   {(candidates||[]).length===0?<div className="empty-state"><div><div className="title">Nothing waiting for review</div><div className="meta">New uncertain Outlook opportunities will land here.</div></div></div>:<div className="project-list">{(candidates||[]).map((c:any)=>{const m:any=c.outlook_messages||{};return <article className="project-card" key={c.id}><header className="project-header"><div><div className="project-name">{m.subject||c.project_name||'Possible concrete job'}</div><div className="project-location">{m.sender_name||c.contact_name||'Unknown sender'} · {m.sender_email||c.email||'No email'} · {pct(c.confidence)} confidence</div></div><span className="status on-hold">Review</span></header><section className="project-section"><div className="metric-grid"><div className="metric-card"><div className="label">Customer / GC</div><div className="metric-value" style={{fontSize:18}}>{c.customer_name||'Not clear'}</div></div><div className="metric-card"><div className="label">Phone</div><div className="metric-value" style={{fontSize:18}}>{c.phone||'Not found'}</div></div><div className="metric-card"><div className="label">Jobsite</div><div className="metric-value" style={{fontSize:18}}>{c.address||c.city||'Not found'}</div></div></div><div className="next-action section"><div><div className="next-action-label">What the Email Says</div><div className="next-action-text">{c.scope||'No useful preview was available.'}</div></div></div><div className="action-row"><form action={createLeadFromCandidate}><input type="hidden" name="candidate_id" value={c.id}/><button className="button">Create Numbered Lead</button></form><form action={ignoreLeadCandidate}><input type="hidden" name="candidate_id" value={c.id}/><button className="button secondary">Not a Lead</button></form>{m.web_link&&<a className="button secondary" href={m.web_link} target="_blank" rel="noreferrer">Open Email</a>}</div></section></article>})}</div>}
  </section>
  <section className="section"><div className="section-heading"><div><div className="section-kicker">Automation</div><div className="section-title">Recently Created From Outlook</div></div></div><div className="surface"><div className="surface-body"><div className="list">{(messages||[]).length===0?<div className="meta">No Outlook-generated leads yet.</div>:(messages||[]).map((m:any)=><div className="row" key={m.id}><div><div className="title">L-{m.leads?.opportunity_number||'—'} — {m.leads?.project_name||m.subject}</div><div className="meta">{m.sender_name||m.sender_email||'Email'} · {m.received_at?new Date(m.received_at).toLocaleString():''}</div></div><span className="status completed">Created</span></div>)}</div></div></div></section>
  {connected&&<section className="section"><form action={disconnectOutlook}><button className="button secondary">Disconnect Outlook</button></form></section>}
 </div></AppShell>;
}
