'use client';
import {useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {saveDocumentMetadata} from '@/app/documents/actions';

type Opt={id:string;label:string};
export function DocumentUpload({companyId,projects,vendors}:{companyId:string;projects:Opt[];vendors:Opt[]}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const supabase=createClient();
 async function submit(fd:FormData){const file=fd.get('file') as File;if(!file||file.size===0){setMessage('Choose a file or take a photo.');return;}setBusy(true);setMessage('Uploading...');let path='';try{const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');path=`${companyId}/${crypto.randomUUID()}-${safe}`;const {error}=await supabase.storage.from('carez-documents').upload(path,file,{contentType:file.type||undefined,upsert:false});if(error)throw error;fd.set('storage_path',path);fd.set('mime_type',file.type||'application/octet-stream');fd.delete('file');await saveDocumentMetadata(fd);setMessage('Saved.');location.reload();}catch(e:any){if(path)await supabase.storage.from('carez-documents').remove([path]);setMessage(e?.message||'Upload failed.');}finally{setBusy(false);}}
 return <form action={submit} className="form"><label className="field"><span>Photo / File</span><input name="file" type="file" accept="image/*,.pdf" capture="environment" required/></label><div className="grid grid2"><label className="field"><span>Type</span><select name="document_type" defaultValue="receipt"><option value="receipt">Receipt</option><option value="delivery_ticket">Delivery Ticket</option><option value="concrete_ticket">Concrete Ticket</option><option value="vendor_invoice">Vendor Invoice</option><option value="plan">Plan / Drawing</option><option value="inspection">Inspection</option><option value="proposal">Proposal / Contract</option><option value="photo">Job Photo</option><option value="other">Other</option></select></label><label className="field"><span>Date</span><input type="date" name="document_date" defaultValue={new Date().toISOString().slice(0,10)}/></label></div><label className="field"><span>Title</span><input name="title" required placeholder="Home Depot receipt / Concrete ticket #..."/></label><div className="grid grid2"><label className="field"><span>Job</span><select name="project_id" defaultValue=""><option value="">Company / no job</option>{projects.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label className="field"><span>Vendor</span><select name="vendor_id" defaultValue=""><option value="">None</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select></label></div><div className="grid grid2"><label className="field"><span>Amount (optional)</span><input type="number" step="0.01" min="0" name="amount"/></label><label className="field"><span>Receipt / Ticket #</span><input name="reference_number"/></label></div><label className="field"><span>Note</span><input name="notes" placeholder="What is this for?"/></label>{message&&<div className="meta">{message}</div>}<button className="button" disabled={busy}>{busy?'Saving...':'Save Document'}</button></form>;
}
