'use server';
import {revalidatePath} from 'next/cache';
import {createClient} from '@/lib/supabase/server';

async function ctx(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Not signed in');const {data:p}=await supabase.from('profiles').select('company_id,role').eq('id',user.id).single();if(!p?.company_id||p.role==='employee')throw new Error('Owner access required');return {supabase,user,companyId:p.company_id};}

export async function ensureCloseout(fd:FormData){const project_id=String(fd.get('project_id')||'');if(!project_id)return;const {supabase,companyId}=await ctx();await supabase.from('project_closeouts').upsert({company_id:companyId,project_id},{onConflict:'project_id'});revalidatePath('/closeout');}

export async function saveCloseoutChecklist(fd:FormData){const project_id=String(fd.get('project_id')||'');if(!project_id)return;const {supabase,companyId}=await ctx();const b=(n:string)=>fd.get(n)==='on';const payload={company_id:companyId,project_id,punch_complete:b('punch_complete'),timecards_complete:b('timecards_complete'),purchase_orders_closed:b('purchase_orders_closed'),vendor_bills_complete:b('vendor_bills_complete'),change_orders_complete:b('change_orders_complete'),customer_billed_complete:b('customer_billed_complete'),customer_paid_complete:b('customer_paid_complete'),documents_complete:b('documents_complete'),warranty_sent:b('warranty_sent'),closeout_notes:String(fd.get('closeout_notes')||'').trim()||null,updated_at:new Date().toISOString()};const {error}=await supabase.from('project_closeouts').upsert(payload,{onConflict:'project_id'});if(error)throw new Error(error.message);revalidatePath('/closeout');}

export async function completeProjectCloseout(fd:FormData){const project_id=String(fd.get('project_id')||'');if(!project_id)return;const {supabase,user,companyId}=await ctx();const [{data:c},{data:openPO},{data:draftBills},{data:openCO},{data:openShifts},{data:billing}]=await Promise.all([supabase.from('project_closeouts').select('*').eq('project_id',project_id).eq('company_id',companyId).maybeSingle(),supabase.from('purchase_orders').select('id',{count:'exact',head:true}).eq('project_id',project_id).in('status',['draft','issued']),supabase.from('vendor_bills').select('id',{count:'exact',head:true}).eq('project_id',project_id).eq('status','draft'),supabase.from('change_orders').select('id',{count:'exact',head:true}).eq('project_id',project_id).in('status',['draft','submitted']),supabase.from('employee_shift_sessions').select('id',{count:'exact',head:true}).eq('project_id',project_id).in('status',['open','submitted']),supabase.from('project_billing_summary').select('outstanding_ar,unbilled_contract').eq('project_id',project_id).maybeSingle()]);if(!c)throw new Error('Start the closeout checklist first.');const checks=['punch_complete','timecards_complete','purchase_orders_closed','vendor_bills_complete','change_orders_complete','customer_billed_complete','customer_paid_complete','documents_complete'];for(const x of checks)if(!c[x])throw new Error('Finish every required closeout checkbox first.');if((openPO.count||0)>0||(draftBills.count||0)>0||(openCO.count||0)>0||(openShifts.count||0)>0)throw new Error('Carez still sees open field or purchasing records on this job.');if(Number(billing?.outstanding_ar||0)>0||Number(billing?.unbilled_contract||0)>0)throw new Error('The customer still has money to be billed or collected.');const now=new Date().toISOString();await supabase.from('project_closeouts').update({status:'completed',completed_at:now,completed_by:user.id,updated_at:now}).eq('project_id',project_id).eq('company_id',companyId);await supabase.from('projects').update({status:'completed',completed_at:now,updated_at:now}).eq('id',project_id).eq('company_id',companyId);revalidatePath('/closeout');revalidatePath('/projects');revalidatePath('/');}
