import {redirect} from 'next/navigation';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';

const money=(n:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0));
const num=(n:any)=>Number(n||0);

export default async function ReportsPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(!profile?.company_id)redirect('/login');if(profile.role==='employee')redirect('/employee');
 const [{data:projects},{data:financial},{data:budgets},{data:billing},{data:production}]=await Promise.all([supabase.from('projects').select('id,job_number,name,status,contract_value,target_margin_percent,completed_at').eq('company_id',profile.company_id).order('completed_at',{ascending:false,nullsFirst:false}),supabase.from('project_financial_summary').select('*'),supabase.from('project_budget_actual_summary').select('*'),supabase.from('project_billing_summary').select('*'),supabase.from('production_rate_history').select('*').eq('company_id',profile.company_id).order('work_date',{ascending:false}).limit(1000)]);
 const fMap=new Map((financial||[]).map((x:any)=>[x.project_id,x])),bMap=new Map((budgets||[]).map((x:any)=>[x.project_id,x])),billMap=new Map((billing||[]).map((x:any)=>[x.project_id,x]));const completed=(projects||[]).filter((p:any)=>p.status==='completed');const active=(projects||[]).filter((p:any)=>p.status==='active');
 const taskMap=new Map<string,{task:string,unit:string,qty:number,mh:number,samples:number}>();for(const r of production||[]){const key=`${r.task_name}|${r.unit}`;const x=taskMap.get(key)||{task:r.task_name,unit:r.unit,qty:0,mh:0,samples:0};x.qty+=num(r.quantity_completed);x.mh+=num(r.man_hours);x.samples++;taskMap.set(key,x);}const taskRates=[...taskMap.values()].filter(x=>x.qty>0&&x.mh>0).sort((a,b)=>b.samples-a.samples);
 const revenue=completed.reduce((s:number,p:any)=>s+num(fMap.get(p.id)?.adjusted_contract||p.contract_value),0);const cost=completed.reduce((s:number,p:any)=>s+num(bMap.get(p.id)?.actual_total_company_cost),0);const margin=revenue>0?(revenue-cost)/revenue*100:0;const ar=(billing||[]).reduce((s:number,x:any)=>s+num(x.outstanding_ar),0);
 return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page"><div className="command-hero"><div><h1>Owner Reports</h1><p>Answers to contractor questions: which jobs made money, where labor went, and what Carez actually produces in the field.</p></div></div><div className="command-grid"><div className="command-card"><div className="command-label">Completed Job Revenue</div><div className="command-value">{money(revenue)}</div><div className="command-help">Authorized value of jobs marked complete.</div></div><div className="command-card"><div className="command-label">Completed Job Cost</div><div className="command-value">{money(cost)}</div><div className="command-help">Actual company cost captured against completed work.</div></div><div className={`command-card ${margin>=30?'good':margin>0?'watch':''}`}><div className="command-label">Actual Completed Margin</div><div className="command-value">{margin.toFixed(1)}%</div><div className="command-help">Revenue left after captured job costs.</div></div><div className={`command-card ${ar>0?'watch':'good'}`}><div className="command-label">Customers Still Owe Us</div><div className="command-value">{money(ar)}</div><div className="command-help">Outstanding invoices across all jobs.</div></div></div>
 <section className="section"><div className="section-heading"><div><div className="section-kicker">Jobs</div><div className="section-title">Job Scorecards</div><div className="section-heading-meta">Estimate/budget against actual performance.</div></div></div>{(projects||[]).length===0?<div className="empty-state"><div><div className="title">No project history yet</div></div></div>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Job</th><th>Status</th><th>Contract</th><th>Actual Cost</th><th>Budget Used</th><th>Labor</th><th>Customer Owes</th></tr></thead><tbody>{(projects||[]).map((p:any)=>{const f:any=fMap.get(p.id)||{},b:any=bMap.get(p.id)||{},bill:any=billMap.get(p.id)||{};return <tr key={p.id}><td><strong>{p.job_number} — {p.name}</strong></td><td>{p.status.replaceAll('_',' ')}</td><td>{money(f.adjusted_contract||p.contract_value)}</td><td>{money(b.actual_total_company_cost)}</td><td>{b.project_id?`${num(b.budget_cost_used_percent).toFixed(1)}%`:'No baseline'}</td><td>{num(b.actual_labor_hours).toFixed(1)} hr</td><td>{money(bill.outstanding_ar)}</td></tr>})}</tbody></table></div>}</section>
 <section className="section"><div className="section-heading"><div><div className="section-kicker">Production</div><div className="section-title">Carez Production Database</div><div className="section-heading-meta">Weighted actual production from approved employee task time and verified quantities. These are the numbers the future Takeoff engine should learn from.</div></div></div>{taskRates.length===0?<div className="empty-state"><div><div className="title">No measured production yet</div><div className="meta">Task clocking + verified quantities will build this automatically.</div></div></div>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Task</th><th>Samples</th><th>Total Built</th><th>Total MH</th><th>Units / MH</th><th>MH / Unit</th></tr></thead><tbody>{taskRates.map(r=><tr key={`${r.task}-${r.unit}`}><td><strong>{r.task}</strong></td><td>{r.samples}</td><td>{r.qty.toFixed(1)} {r.unit}</td><td>{r.mh.toFixed(1)} MH</td><td>{(r.qty/r.mh).toFixed(2)} {r.unit}/MH</td><td>{(r.mh/r.qty).toFixed(3)} MH/{r.unit}</td></tr>)}</tbody></table></div>}</section>
 <section className="section"><div className="section-heading"><div><div className="section-kicker">Current Work</div><div className="section-title">Jobs Still Running</div></div></div><div className="project-list">{active.length===0?<div className="card"><div className="meta">No active jobs.</div></div>:active.map((p:any)=>{const b:any=bMap.get(p.id)||{},bill:any=billMap.get(p.id)||{};return <article className="project-card" key={p.id}><header className="project-header"><div><div className="project-name">{p.job_number} — {p.name}</div><div className="project-location">{num(b.actual_labor_hours).toFixed(1)} labor hr used · {money(bill.outstanding_ar)} customer balance</div></div><span className={`status ${num(b.budget_cost_used_percent)>=100?'on-hold':'active'}`}>{b.project_id?`${num(b.budget_cost_used_percent).toFixed(0)}% budget used`:'No budget'}</span></header></article>})}</div></section></div></AppShell>;
}
