import { redirect } from 'next/navigation';
import Link from 'next/link';
import { AppShell } from '@/components/AppShell';
import { createClient } from '@/lib/supabase/server';
import { createProject,updateLaborBudget,updateProjectEconomics } from './actions';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);const num=(v:any)=>Number(v||0);
export default async function ProjectsPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
 const {data:profile}=await supabase.from('profiles').select('full_name,company_id').eq('id',user.id).maybeSingle();
 const [{data:projects},{data:financials},{data:company}]=await Promise.all([
  supabase.from('projects').select('*,customers(name)').order('created_at',{ascending:false}),
  supabase.from('project_financial_summary').select('*'),
  profile?.company_id?supabase.from('companies').select('card_processing_reference_percent').eq('id',profile.company_id).single():Promise.resolve({data:null})
 ]);
 const fMap=new Map((financials||[]).map((f:any)=>[f.project_id,f]));
 return <AppShell userName={profile?.full_name||user.email||'Owner'}><h1 className="page-title">Projects</h1><p className="subtitle">Actual job cost, overhead recovery and project profitability.</p>
 <div className="card"><div className="title">Add Project</div><form action={createProject} className="form" style={{marginTop:12}}><div className="grid grid2"><label className="field"><span>Job Number</span><input name="job_number" required placeholder="D58"/></label><label className="field"><span>Project Name</span><input name="name" required placeholder="307 NW 52nd St"/></label></div><label className="field"><span>Address</span><input name="address"/></label><div className="grid grid2"><label className="field"><span>City</span><input name="city"/></label><label className="field"><span>Contract Value</span><input name="contract_value" inputMode="decimal"/></label></div><div className="grid grid2"><label className="field"><span>Estimated Labor Hours</span><input name="estimated_labor_hours" type="number" min="0" step="0.25"/></label><label className="field"><span>Estimated Labor Cost</span><input name="estimated_labor_cost" inputMode="decimal"/></label></div><label className="field"><span>Next Action</span><input name="next_action"/></label><button className="button">Create Project</button></form></div>
 <div className="alert success section"><strong>Profitability Engine active.</strong> Direct costs + snapshotted overhead recovery + B&O/payment reserves now produce true company cost. Active jobs are shown as cost-to-date, not final profit.</div>
 <div className="grid section">{(projects||[]).map((p:any)=>{const f:any=fMap.get(p.id)||{};const adjusted=num(f.adjusted_contract),direct=num(f.total_direct_cost),oh=num(f.overhead_recovery),rev=num(f.revenue_cost_reserve),trueCost=num(f.true_company_cost),profit=num(f.profit_if_complete_now),margin=num(f.margin_if_complete_now),target=num(f.target_margin_percent),room=num(f.cost_room_to_target),isComplete=p.status==='completed';return <div className="card" key={p.id}><div className="row"><div><div className="title">{p.job_number} — {p.name}</div><div className="meta">{p.customers?.name||'Direct / customer not linked'} · {[p.address,p.city,p.state].filter(Boolean).join(', ')}</div></div><span className="status">{p.status}</span></div>
 <div className="grid grid4 section"><div><div className="label">Adjusted Contract</div><strong>{money(adjusted)}</strong></div><div><div className="label">Direct Cost</div><strong>{money(direct)}</strong><div className="meta">Labor {money(num(f.direct_labor_cost))} · Other {money(num(f.nonlabor_direct_cost))}</div></div><div><div className="label">Overhead Recovery</div><strong>{money(oh)}</strong><div className="meta">{num(f.labor_hours).toFixed(1)} productive hr</div></div><div><div className="label">Revenue Costs</div><strong>{money(rev)}</strong><div className="meta">B&O {money(num(f.bo_cost_reserve))} · Processing {money(num(f.payment_processing_cost_reserve))}</div></div></div>
 <div className="grid grid4 section"><div><div className="label">True Company Cost</div><div className="value">{money(trueCost)}</div></div><div><div className="label">{isComplete?'Actual Profit':'Profit If Complete Now'}</div><div className="value">{money(profit)}</div></div><div><div className="label">{isComplete?'Actual Margin':'Margin If Complete Now'}</div><div className="value">{margin.toFixed(1)}%</div><div className="meta">Target {target.toFixed(1)}%</div></div><div><div className="label">Cost Room to Target</div><div className="value">{money(room)}</div><div className="meta">Target cost ceiling {money(num(f.target_cost_ceiling))}</div></div></div>
 {!isComplete&&<div className="alert warn"><strong>Cost-to-date only.</strong> This is not final job profit until the job is complete and all labor, invoices, equipment and subcontractor costs are entered.</div>}
 {isComplete&&margin<target&&<div className="alert danger"><strong>Closed below target.</strong> Final margin is {margin.toFixed(1)}% versus {target.toFixed(1)}% target.</div>}
 {isComplete&&margin>=target&&<div className="alert success"><strong>Closed at/above target.</strong> Final margin is {margin.toFixed(1)}%.</div>}
 <div className="split section"><form action={updateLaborBudget} className="form"><input type="hidden" name="project_id" value={p.id}/><div className="title">Labor Budget</div><div className="grid grid2"><label className="field"><span>Est. Labor Hours</span><input name="estimated_labor_hours" type="number" min="0" step="0.25" defaultValue={num(p.estimated_labor_hours)}/></label><label className="field"><span>Est. Direct Labor Cost</span><input name="estimated_labor_cost" type="number" min="0" step="0.01" defaultValue={num(p.estimated_labor_cost)}/></label></div><button className="button secondary">Update Labor Budget</button></form>
 <form action={updateProjectEconomics} className="form"><input type="hidden" name="project_id" value={p.id}/><div className="title">Project Economics</div><div className="grid grid2"><label className="field"><span>Target Margin %</span><input name="target_margin_percent" type="number" min="0" max="80" step="0.1" defaultValue={target}/></label><label className="field"><span>B&O Classification</span><select name="bo_classification" defaultValue={p.bo_classification||'retailing'}><option value="retailing">Retailing — 0.471%</option><option value="wholesaling">Wholesaling — 0.484%</option></select></label></div><div className="grid grid2"><label className="field"><span>Payment Processing Reserve %</span><input name="payment_processing_rate_percent" type="number" min="0" step="0.01" defaultValue={num(p.payment_processing_rate_percent)} placeholder={String(num(company?.card_processing_reference_percent))}/></label><label className="field"><span>Project Status</span><select name="status" defaultValue={p.status}><option value="active">Active</option><option value="completed">Completed</option><option value="on_hold">On Hold</option></select></label></div><button className="button secondary">Save Project Economics</button></form></div>
 <div className="alert warn"><strong>Next action:</strong> {p.next_action||'No action assigned'}</div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="button secondary" href="/field">Enter Labor</Link><Link className="button secondary" href="/costs">Enter Job Cost</Link></div></div>})}</div></AppShell>;
}
