import { redirect } from 'next/navigation';
import Link from 'next/link';
import { AppShell } from '@/components/AppShell';
import { createClient } from '@/lib/supabase/server';
import { createVendor,createVendorQuote,addVendorQuoteLine,deleteVendorQuoteLine,setVendorQuoteStatus,convertQuoteToPurchaseOrder,createPurchaseOrder,addPurchaseOrderLine,deletePurchaseOrderLine,issuePurchaseOrder,closePurchaseOrder,recordPurchaseOrderReceipt,createVendorBill,addVendorBillLine,deleteVendorBillLine,postVendorBill,voidVendorBill } from './actions';

const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const num=(v:any)=>Number(v||0);
const today=()=>new Date().toISOString().slice(0,10);
const units=['LS','EA','CY','LF','SF','LB','HR','DAY','TON','GAL'];
const vendorTypes=[['concrete_supplier','Concrete Supplier'],['pump','Concrete Pump'],['rebar_supplier','Rebar Supplier'],['building_materials','Building Materials'],['equipment_rental','Equipment Rental'],['trucking','Trucking / Hauling'],['traffic_control','Traffic Control'],['subcontractor','Subcontractor'],['other','Other']];

export default async function ProcurementPage(){
  const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
  const {data:profile}=await supabase.from('profiles').select('full_name,company_id').eq('id',user.id).single();if(!profile?.company_id)redirect('/login');
  const companyId=profile.company_id;
  const [{data:projects},{data:vendors},{data:quotes},{data:quoteLines},{data:pos},{data:poLines},{data:receipts},{data:bills},{data:billLines},{data:costCodes},{data:catalog},{data:budgets},{data:sections},{data:changeOrders},{data:pourPlans},{data:pourItems}]=await Promise.all([
    supabase.from('projects').select('id,job_number,name,status').in('status',['active','on_hold','completed']).order('job_number'),
    supabase.from('vendors').select('*').eq('company_id',companyId).order('active',{ascending:false}).order('name'),
    supabase.from('vendor_quote_financial_summary').select('*').order('quote_date',{ascending:false}),
    supabase.from('vendor_quote_lines').select('*').order('sort_order'),
    supabase.from('purchase_order_financial_summary').select('*').order('created_at',{ascending:false}),
    supabase.from('purchase_order_line_financial_summary').select('*'),
    supabase.from('purchase_order_receipts').select('*').order('received_date',{ascending:false}),
    supabase.from('vendor_bill_financial_summary').select('*').order('bill_date',{ascending:false}),
    supabase.from('vendor_bill_lines').select('*').order('sort_order'),
    supabase.from('cost_codes').select('id,code,name,cost_type,default_unit').eq('company_id',companyId).eq('active',true).order('sort_order'),
    supabase.from('cost_catalog_items').select('id,cost_code_id,name,default_unit,default_unit_cost,vendor_name').eq('company_id',companyId).eq('active',true).order('name'),
    supabase.from('project_budgets').select('id,project_id,status,label').eq('status','active'),
    supabase.from('project_budget_sections').select('id,budget_id,name').order('sort_order'),
    supabase.from('change_orders').select('id,project_id,co_number,title,status').eq('status','approved').order('requested_date'),
    supabase.from('pour_plans').select('id,project_id,name,status,scheduled_date').not('status','eq','cancelled').order('scheduled_date'),
    supabase.from('pour_cost_items').select('id,pour_plan_id,description,expected_cost,item_type').order('sort_order')
  ]);

  const projectMap=new Map((projects||[]).map((p:any)=>[p.id,p]));
  const vendorMap=new Map((vendors||[]).map((v:any)=>[v.id,v]));
  const budgetProject=new Map((budgets||[]).map((b:any)=>[b.id,b.project_id]));
  const sectionOptions=(sections||[]).map((s:any)=>({...s,project_id:budgetProject.get(s.budget_id)})).filter((s:any)=>s.project_id);
  const planMap=new Map((pourPlans||[]).map((p:any)=>[p.id,p]));
  const pourItemOptions=(pourItems||[]).map((i:any)=>({...i,plan:planMap.get(i.pour_plan_id)})).filter((i:any)=>i.plan);
  const quoteLineMap=new Map<string,any[]>();for(const l of quoteLines||[]){if(!quoteLineMap.has(l.vendor_quote_id))quoteLineMap.set(l.vendor_quote_id,[]);quoteLineMap.get(l.vendor_quote_id)!.push(l);}
  const poLineMap=new Map<string,any[]>();for(const l of poLines||[]){if(!poLineMap.has(l.purchase_order_id))poLineMap.set(l.purchase_order_id,[]);poLineMap.get(l.purchase_order_id)!.push(l);}
  const receiptMap=new Map<string,any[]>();for(const x of receipts||[]){if(!receiptMap.has(x.purchase_order_id))receiptMap.set(x.purchase_order_id,[]);receiptMap.get(x.purchase_order_id)!.push(x);}
  const billLineMap=new Map<string,any[]>();for(const l of billLines||[]){if(!billLineMap.has(l.vendor_bill_id))billLineMap.set(l.vendor_bill_id,[]);billLineMap.get(l.vendor_bill_id)!.push(l);}
  const openCommitment=(pos||[]).filter((p:any)=>p.status==='issued').reduce((s:number,p:any)=>s+num(p.open_commitment),0);
  const issuedPOs=(pos||[]).filter((p:any)=>p.status==='issued').length;
  const draftBills=(bills||[]).filter((b:any)=>b.status==='draft').reduce((s:number,b:any)=>s+num(b.total_cost),0);
  const postedBills=(bills||[]).filter((b:any)=>b.status==='posted').reduce((s:number,b:any)=>s+num(b.total_cost),0);

  return <AppShell userName={profile.full_name||user.email||'Owner'}>
    <div className="page-heading"><div><h1 className="page-title">Procurement</h1><p className="subtitle">Vendor quotes, purchase orders, delivery receipts and vendor bills tied directly to project cost and pour cash exposure.</p></div></div>
    <div className="grid grid4">
      <div className="card"><div className="label">Open PO Commitments</div><div className="value">{money(openCommitment)}</div><div className="meta">Issued commitments not yet converted to actual cost.</div></div>
      <div className="card"><div className="label">Issued POs</div><div className="value">{issuedPOs}</div></div>
      <div className="card"><div className="label">Draft Vendor Bills</div><div className="value">{money(draftBills)}</div><div className="meta">Not yet posted to Job Cost.</div></div>
      <div className="card"><div className="label">Posted Vendor Bills</div><div className="value">{money(postedBills)}</div></div>
    </div>
    <div className="alert info"><strong>Financial flow:</strong> a quote is informational, an issued PO becomes a cash commitment, and a posted vendor bill becomes actual project cost. Carez OS reduces the PO commitment as actual cost is posted so the same purchase is not counted twice.</div>

    <div className="split section">
      <details className="controls-disclosure create-disclosure"><summary>Add Vendor</summary><div className="controls-body"><form action={createVendor} className="form">
        <div className="grid grid2"><label className="field"><span>Vendor Name</span><input name="name" required/></label><label className="field"><span>Vendor Type</span><select name="vendor_type" defaultValue="other">{vendorTypes.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div>
        <div className="grid grid2"><label className="field"><span>Contact</span><input name="contact_name"/></label><label className="field"><span>Phone</span><input name="phone"/></label></div>
        <label className="field"><span>Email</span><input type="email" name="email"/></label><label className="field"><span>Address</span><input name="address_line1"/></label>
        <div className="grid grid2"><label className="field"><span>City</span><input name="city"/></label><label className="field"><span>State</span><input name="state" defaultValue="WA"/></label></div>
        <div className="grid grid2"><label className="field"><span>ZIP</span><input name="postal_code"/></label><label className="field"><span>Payment Terms</span><input name="payment_terms" placeholder="Net 30, COD..."/></label></div>
        <label className="field"><span>Account #</span><input name="account_number"/></label><label className="field"><span>Notes</span><input name="notes"/></label><button className="button">Save Vendor</button>
      </form></div></details>

      <details className="controls-disclosure"><summary>Vendor Directory</summary><div className="controls-body"><div className="list">{(vendors||[]).length===0?<div className="meta">No vendors yet.</div>:(vendors||[]).map((v:any)=><div className="row" key={v.id}><div><div className="title">{v.name}</div><div className="meta">{String(v.vendor_type).replaceAll('_',' ')} · {v.contact_name||'No contact'} · {v.phone||v.email||'No contact info'}</div></div><span className={`status ${v.active?'active':''}`}>{v.active?'active':'inactive'}</span></div>)}</div></div></details>
    </div>

    <div className="split section">
      <details className="controls-disclosure create-disclosure"><summary>Record Vendor Quote</summary><div className="controls-body"><form action={createVendorQuote} className="form">
        <div className="grid grid2"><label className="field"><span>Project</span><select name="project_id" required defaultValue=""><option value="" disabled>Select project</option>{(projects||[]).map((p:any)=><option key={p.id} value={p.id}>{p.job_number} — {p.name}</option>)}</select></label><label className="field"><span>Vendor</span><select name="vendor_id" required defaultValue=""><option value="" disabled>Select vendor</option>{(vendors||[]).filter((v:any)=>v.active).map((v:any)=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label></div>
        <div className="grid grid2"><label className="field"><span>Vendor Quote #</span><input name="vendor_quote_number"/></label><label className="field"><span>Quote Date</span><input type="date" name="quote_date" defaultValue={today()}/></label></div>
        <label className="field"><span>Expires</span><input type="date" name="expires_on"/></label><label className="field"><span>Budget Scope (optional)</span><select name="budget_section_id" defaultValue=""><option value="">None</option>{sectionOptions.map((s:any)=>{const p:any=projectMap.get(s.project_id)||{};return <option key={s.id} value={s.id}>{p.job_number} — {s.name}</option>})}</select></label>
        <label className="field"><span>Pour Plan (optional)</span><select name="pour_plan_id" defaultValue=""><option value="">None</option>{(pourPlans||[]).map((p:any)=>{const j:any=projectMap.get(p.project_id)||{};return <option key={p.id} value={p.id}>{j.job_number} — {p.name}</option>})}</select></label>
        <label className="field"><span>Approved Change Order (optional)</span><select name="change_order_id" defaultValue=""><option value="">None</option>{(changeOrders||[]).map((co:any)=>{const p:any=projectMap.get(co.project_id)||{};return <option key={co.id} value={co.id}>{p.job_number} · {co.co_number} — {co.title}</option>})}</select></label>
        <label className="field"><span>Notes</span><input name="notes"/></label><button className="button">Create Quote Record</button>
      </form></div></details>

      <details className="controls-disclosure create-disclosure"><summary>Create Purchase Order Directly</summary><div className="controls-body"><form action={createPurchaseOrder} className="form">
        <div className="grid grid2"><label className="field"><span>Project</span><select name="project_id" required defaultValue=""><option value="" disabled>Select project</option>{(projects||[]).map((p:any)=><option key={p.id} value={p.id}>{p.job_number} — {p.name}</option>)}</select></label><label className="field"><span>Vendor</span><select name="vendor_id" required defaultValue=""><option value="" disabled>Select vendor</option>{(vendors||[]).filter((v:any)=>v.active).map((v:any)=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label></div>
        <label className="field"><span>Expected Delivery</span><input type="date" name="expected_delivery_date"/></label><label className="field"><span>Budget Scope</span><select name="budget_section_id" defaultValue=""><option value="">None</option>{sectionOptions.map((s:any)=>{const p:any=projectMap.get(s.project_id)||{};return <option key={s.id} value={s.id}>{p.job_number} — {s.name}</option>})}</select></label>
        <label className="field"><span>Pour Plan</span><select name="pour_plan_id" defaultValue=""><option value="">None</option>{(pourPlans||[]).map((p:any)=>{const j:any=projectMap.get(p.project_id)||{};return <option key={p.id} value={p.id}>{j.job_number} — {p.name}</option>})}</select></label>
        <label className="field"><span>Approved Change Order</span><select name="change_order_id" defaultValue=""><option value="">None</option>{(changeOrders||[]).map((co:any)=>{const p:any=projectMap.get(co.project_id)||{};return <option key={co.id} value={co.id}>{p.job_number} · {co.co_number} — {co.title}</option>})}</select></label>
        <label className="field"><span>Delivery Instructions</span><input name="delivery_instructions" placeholder="Call 30 min before delivery..."/></label><label className="field"><span>Terms</span><input name="terms"/></label><label className="field"><span>Notes</span><input name="notes"/></label><button className="button">Create Draft PO</button>
      </form></div></details>
    </div>

    <div className="section"><div className="section-heading"><div><div className="section-kicker">Quotes</div><div className="section-title">Vendor Quotes</div></div></div><div className="project-list">{(quotes||[]).length===0?<div className="card"><div className="meta">No vendor quotes recorded.</div></div>:(quotes||[]).map((q:any)=>{const lines=quoteLineMap.get(q.vendor_quote_id)||[];return <article className="project-card" key={q.vendor_quote_id}><header className="project-header"><div><div className="project-name">{q.internal_quote_number} — {q.vendor_name}</div><div className="project-location">{q.job_number} · Vendor quote {q.vendor_quote_number||'not provided'} · {q.quote_date}</div></div><span className={`status ${q.status==='accepted'||q.status==='converted'?'completed':q.status==='rejected'?'on-hold':'active'}`}>{q.status}</span></header><section className="project-section"><div className="metric-grid"><div className="metric-card"><div className="label">Subtotal</div><div className="metric-value">{money(num(q.subtotal))}</div></div><div className="metric-card"><div className="label">Tax</div><div className="metric-value">{money(num(q.sales_tax))}</div></div><div className="metric-card brand"><div className="label">Quoted Total</div><div className="metric-value">{money(num(q.total_cost))}</div></div><div className="metric-card"><div className="label">Lines</div><div className="metric-value">{q.line_count}</div></div></div>
          <div className="list section">{lines.map((l:any)=><div className="row" key={l.id}><div><div className="title">{l.description}</div><div className="meta">{num(l.quantity).toFixed(2)} {l.unit} × {money(num(l.unit_cost))} · Tax {money(num(l.sales_tax))}</div></div><div style={{textAlign:'right'}}><strong>{money(num(l.total_cost))}</strong>{q.status==='received'&&<form action={deleteVendorQuoteLine}><input type="hidden" name="vendor_quote_id" value={q.vendor_quote_id}/><input type="hidden" name="line_id" value={l.id}/><button className="button secondary" style={{marginTop:6}}>Delete</button></form>}</div></div>)}</div>
          {q.status==='received'&&<details className="controls-disclosure section"><summary>Add Quote Line</summary><div className="controls-body"><form action={addVendorQuoteLine} className="form"><input type="hidden" name="vendor_quote_id" value={q.vendor_quote_id}/><label className="field"><span>Cost Code</span><select name="cost_code_id" required defaultValue=""><option value="" disabled>Select cost code</option>{(costCodes||[]).map((c:any)=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></label><label className="field"><span>Catalog Item</span><select name="catalog_item_id" defaultValue=""><option value="">Custom / none</option>{(catalog||[]).map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field"><span>Planned Pour Item (optional)</span><select name="pour_cost_item_id" defaultValue=""><option value="">None</option>{pourItemOptions.map((i:any)=>{const p:any=projectMap.get(i.plan.project_id)||{};return <option key={i.id} value={i.id}>{p.job_number} · {i.plan.name} — {i.description}</option>})}</select></label><label className="field"><span>Description</span><input name="description" required/></label><div className="grid grid2"><label className="field"><span>Quantity</span><input type="number" min="0" step="0.01" name="quantity" defaultValue="1"/></label><label className="field"><span>Unit</span><select name="unit" defaultValue="EA">{units.map(u=><option key={u}>{u}</option>)}</select></label></div><div className="grid grid2"><label className="field"><span>Unit Cost</span><input type="number" min="0" step="0.01" name="unit_cost" required/></label><label className="field"><span>Sales Tax</span><input type="number" min="0" step="0.01" name="sales_tax" defaultValue="0"/></label></div><label className="field"><span>Notes</span><input name="notes"/></label><button className="button">Add Quote Line</button></form></div></details>}
          {q.status==='received'&&<div className="action-row section"><form action={setVendorQuoteStatus}><input type="hidden" name="vendor_quote_id" value={q.vendor_quote_id}/><input type="hidden" name="status" value="accepted"/><button className="button secondary">Accept Quote</button></form><form action={setVendorQuoteStatus}><input type="hidden" name="vendor_quote_id" value={q.vendor_quote_id}/><input type="hidden" name="status" value="rejected"/><button className="button secondary">Reject</button></form>{lines.length>0&&<form action={convertQuoteToPurchaseOrder}><input type="hidden" name="vendor_quote_id" value={q.vendor_quote_id}/><button className="button">Convert to Draft PO</button></form>}</div>}
          {q.status==='accepted'&&<form action={convertQuoteToPurchaseOrder} className="section"><input type="hidden" name="vendor_quote_id" value={q.vendor_quote_id}/><button className="button">Convert Accepted Quote to PO</button></form>}
        </section></article>})}</div></div>

    <div className="section"><div className="section-heading"><div><div className="section-kicker">Commitments</div><div className="section-title">Purchase Orders</div></div></div><div className="project-list">{(pos||[]).length===0?<div className="card"><div className="meta">No purchase orders yet.</div></div>:(pos||[]).map((po:any)=>{const lines=poLineMap.get(po.purchase_order_id)||[];const delivery=receiptMap.get(po.purchase_order_id)||[];const locked=po.status!=='draft';return <article className="project-card" key={po.purchase_order_id}><header className="project-header"><div><div className="project-name">{po.po_number} — {po.vendor_name}</div><div className="project-location">{po.job_number} — {po.project_name} · {po.issue_date?`Issued ${po.issue_date}`:'Draft'}</div></div><span className={`status ${po.status==='issued'?'active':po.status==='closed'?'completed':po.status==='cancelled'?'on-hold':''}`}>{po.status}</span></header><section className="project-section tinted"><div className="metric-grid"><div className="metric-card brand"><div className="label">PO Total</div><div className="metric-value">{money(num(po.po_total))}</div></div><div className="metric-card"><div className="label">Actual Cost Posted</div><div className="metric-value">{money(num(po.actual_cost))}</div></div><div className={`metric-card ${num(po.open_commitment)>0?'warning':''}`}><div className="label">Open Commitment</div><div className="metric-value">{money(num(po.open_commitment))}</div></div><div className={`metric-card ${num(po.actual_vs_po_variance)>0?'danger-metric':num(po.actual_vs_po_variance)<0?'positive':''}`}><div className="label">Actual vs PO</div><div className="metric-value">{money(num(po.actual_vs_po_variance))}</div></div></div></section>
          <section className="project-section"><div className="list">{lines.map((l:any)=><div className="row" key={l.purchase_order_line_id}><div><div className="title">{l.description}</div><div className="meta">Ordered {num(l.quantity).toFixed(2)} {l.unit} · Received {num(l.received_quantity).toFixed(2)} · Actual {money(num(l.actual_cost))}</div></div><div style={{textAlign:'right'}}><strong>{money(num(l.total_cost))}</strong>{!locked&&<form action={deletePurchaseOrderLine}><input type="hidden" name="purchase_order_id" value={po.purchase_order_id}/><input type="hidden" name="line_id" value={l.purchase_order_line_id}/><button className="button secondary" style={{marginTop:6}}>Delete</button></form>}</div></div>)}</div>
            {!locked&&<details className="controls-disclosure section"><summary>Add PO Line</summary><div className="controls-body"><form action={addPurchaseOrderLine} className="form"><input type="hidden" name="purchase_order_id" value={po.purchase_order_id}/><label className="field"><span>Cost Code</span><select name="cost_code_id" required defaultValue=""><option value="" disabled>Select cost code</option>{(costCodes||[]).map((c:any)=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></label><label className="field"><span>Catalog Item</span><select name="catalog_item_id" defaultValue=""><option value="">Custom / none</option>{(catalog||[]).map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field"><span>Planned Pour Item</span><select name="pour_cost_item_id" defaultValue=""><option value="">None</option>{pourItemOptions.filter((i:any)=>i.plan.project_id===po.project_id).map((i:any)=><option key={i.id} value={i.id}>{i.plan.name} — {i.description}</option>)}</select></label><label className="field"><span>Description</span><input name="description" required/></label><div className="grid grid2"><label className="field"><span>Quantity</span><input type="number" min="0" step="0.01" name="quantity" defaultValue="1"/></label><label className="field"><span>Unit</span><select name="unit" defaultValue="EA">{units.map(u=><option key={u}>{u}</option>)}</select></label></div><div className="grid grid2"><label className="field"><span>Unit Cost</span><input type="number" min="0" step="0.01" name="unit_cost" required/></label><label className="field"><span>Expected Sales Tax</span><input type="number" min="0" step="0.01" name="sales_tax" defaultValue="0"/></label></div><label className="field"><span>Notes</span><input name="notes"/></label><button className="button">Add PO Line</button></form></div></details>}
            <div className="action-row section"><Link className="button secondary" href={`/procurement/purchase-orders/${po.purchase_order_id}`}>Vendor PO / Print</Link>{po.status==='draft'&&lines.length>0&&<form action={issuePurchaseOrder}><input type="hidden" name="purchase_order_id" value={po.purchase_order_id}/><input type="hidden" name="issue_date" value={today()}/><button className="button">Issue PO — Commit Cost</button></form>}{po.status==='draft'&&<form action={closePurchaseOrder}><input type="hidden" name="purchase_order_id" value={po.purchase_order_id}/><input type="hidden" name="status" value="cancelled"/><button className="button secondary">Cancel Draft</button></form>}{po.status==='issued'&&<form action={closePurchaseOrder}><input type="hidden" name="purchase_order_id" value={po.purchase_order_id}/><input type="hidden" name="status" value="closed"/><button className="button secondary">Close PO</button></form>}</div>
            {po.status==='issued'&&lines.length>0&&<details className="controls-disclosure section"><summary>Receive Delivery / Ticket</summary><div className="controls-body"><form action={recordPurchaseOrderReceipt} className="form"><input type="hidden" name="purchase_order_id" value={po.purchase_order_id}/><label className="field"><span>PO Line</span><select name="purchase_order_line_id" required defaultValue=""><option value="" disabled>Select line</option>{lines.map((l:any)=><option key={l.purchase_order_line_id} value={l.purchase_order_line_id}>{l.description} · Ordered {num(l.quantity).toFixed(2)} {l.unit}</option>)}</select></label><div className="grid grid2"><label className="field"><span>Received Date</span><input type="date" name="received_date" defaultValue={today()}/></label><label className="field"><span>Quantity Received</span><input type="number" min="0.01" step="0.01" name="quantity_received" required/></label></div><label className="field"><span>Delivery Ticket #</span><input name="delivery_ticket"/></label><label className="field"><span>Notes</span><input name="notes"/></label><button className="button secondary">Record Receipt</button></form><div className="list section">{delivery.slice(0,6).map((x:any)=><div className="row" key={x.id}><div><div className="title">{x.received_date} · {x.delivery_ticket||'No ticket #'}</div><div className="meta">Qty {num(x.quantity_received).toFixed(2)}</div></div></div>)}</div></div></details>}
          </section></article>})}</div></div>

    <div className="section"><div className="section-heading"><div><div className="section-kicker">Actual Cost</div><div className="section-title">Vendor Bills</div><div className="section-heading-meta">Post a vendor bill once reviewed; its lines become actual Job Costs and reduce the corresponding PO commitment.</div></div></div>
      <details className="controls-disclosure create-disclosure"><summary>Create Vendor Bill</summary><div className="controls-body"><form action={createVendorBill} className="form"><label className="field"><span>Purchase Order (recommended when applicable)</span><select name="purchase_order_id" defaultValue=""><option value="">No PO / direct vendor bill</option>{(pos||[]).filter((p:any)=>['issued','closed'].includes(p.status)).map((p:any)=><option key={p.purchase_order_id} value={p.purchase_order_id}>{p.po_number} — {p.vendor_name} · {p.job_number}</option>)}</select></label><div className="grid grid2"><label className="field"><span>Project (required if no PO)</span><select name="project_id" defaultValue=""><option value="">Select project</option>{(projects||[]).map((p:any)=><option key={p.id} value={p.id}>{p.job_number} — {p.name}</option>)}</select></label><label className="field"><span>Vendor (required if no PO)</span><select name="vendor_id" defaultValue=""><option value="">Select vendor</option>{(vendors||[]).map((v:any)=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label></div><div className="grid grid2"><label className="field"><span>Vendor Invoice #</span><input name="vendor_bill_number" required/></label><label className="field"><span>Bill Date</span><input type="date" name="bill_date" defaultValue={today()}/></label></div><label className="field"><span>Due Date</span><input type="date" name="due_date"/></label><label className="field"><span>Notes</span><input name="notes"/></label><button className="button">Create Draft Vendor Bill</button></form></div></details>
      <div className="project-list section">{(bills||[]).length===0?<div className="card"><div className="meta">No vendor bills yet.</div></div>:(bills||[]).map((b:any)=>{const lines=billLineMap.get(b.vendor_bill_id)||[];const po:any=(pos||[]).find((p:any)=>p.purchase_order_id===b.purchase_order_id);const availablePOLines=po?poLineMap.get(po.purchase_order_id)||[]:[];return <article className="project-card" key={b.vendor_bill_id}><header className="project-header"><div><div className="project-name">{b.vendor_bill_number} — {b.vendor_name}</div><div className="project-location">{b.job_number} — {b.project_name} · Bill date {b.bill_date}{po?` · ${po.po_number}`:''}</div></div><span className={`status ${b.status==='posted'?'completed':b.status==='void'?'on-hold':'active'}`}>{b.status}</span></header><section className="project-section tinted"><div className="metric-grid"><div className="metric-card"><div className="label">Subtotal</div><div className="metric-value">{money(num(b.subtotal))}</div></div><div className="metric-card"><div className="label">Sales Tax</div><div className="metric-value">{money(num(b.sales_tax))}</div></div><div className="metric-card brand"><div className="label">Vendor Bill Total</div><div className="metric-value">{money(num(b.total_cost))}</div></div><div className="metric-card"><div className="label">Lines</div><div className="metric-value">{b.line_count}</div></div></div></section><section className="project-section"><div className="list">{lines.map((l:any)=><div className="row" key={l.id}><div><div className="title">{l.description}</div><div className="meta">{num(l.quantity).toFixed(2)} {l.unit} × {money(num(l.unit_cost))} · Tax {money(num(l.sales_tax))}</div></div><div style={{textAlign:'right'}}><strong>{money(num(l.total_cost))}</strong>{b.status==='draft'&&<form action={deleteVendorBillLine}><input type="hidden" name="vendor_bill_id" value={b.vendor_bill_id}/><input type="hidden" name="line_id" value={l.id}/><button className="button secondary" style={{marginTop:6}}>Delete</button></form>}</div></div>)}</div>
          {b.status==='draft'&&<details className="controls-disclosure section"><summary>Add Vendor Bill Line</summary><div className="controls-body"><form action={addVendorBillLine} className="form"><input type="hidden" name="vendor_bill_id" value={b.vendor_bill_id}/>{po&&<label className="field"><span>PO Line</span><select name="purchase_order_line_id" defaultValue=""><option value="">Not tied to a PO line</option>{availablePOLines.map((l:any)=><option key={l.purchase_order_line_id} value={l.purchase_order_line_id}>{l.description} · PO {money(num(l.total_cost))} · Open {money(num(l.open_commitment))}</option>)}</select></label>}<label className="field"><span>Cost Code (if no PO line)</span><select name="cost_code_id" defaultValue=""><option value="">Select cost code</option>{(costCodes||[]).map((c:any)=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></label><label className="field"><span>Description</span><input name="description" placeholder="Can be blank when using a PO line"/></label><div className="grid grid2"><label className="field"><span>Actual Quantity</span><input type="number" min="0" step="0.01" name="quantity" defaultValue="1"/></label><label className="field"><span>Unit</span><select name="unit" defaultValue="EA">{units.map(u=><option key={u}>{u}</option>)}</select></label></div><div className="grid grid2"><label className="field"><span>Actual Unit Cost</span><input type="number" min="0" step="0.01" name="unit_cost" required/></label><label className="field"><span>Sales Tax</span><input type="number" min="0" step="0.01" name="sales_tax" defaultValue="0"/></label></div><label className="field"><span>Notes</span><input name="notes"/></label><button className="button">Add Bill Line</button></form></div></details>}
          {b.status==='draft'&&<div className="action-row section">{lines.length>0&&<form action={postVendorBill}><input type="hidden" name="vendor_bill_id" value={b.vendor_bill_id}/><button className="button">Post to Job Cost</button></form>}<form action={voidVendorBill}><input type="hidden" name="vendor_bill_id" value={b.vendor_bill_id}/><button className="button secondary">Void Draft</button></form></div>}
          {b.status==='posted'&&<div className="alert success section" style={{marginBottom:0}}><strong>Posted.</strong> These costs are now included in Project Job Cost, Forecast and Pour Control.</div>}
        </section></article>})}</div>
    </div>
  </AppShell>;
}
