import { redirect } from 'next/navigation';
import { AppShell } from '@/components/AppShell';
import { Accordion, AccordionHeader, AccordionItem, AccordionPanel, Badge, Button, Dialog, DialogBody, DialogContent, DialogSurface, DialogTitle, DialogTrigger, Input, Label, Select, Textarea } from '@fluentui/react-components';
import { ChangeOrderDrawer } from './ChangeOrderDrawer';
import { createClient } from '@/lib/supabase/server';
import { createChangeOrder,addChangeOrderItem,updateChangeOrder,approveChangeOrder,rejectChangeOrder,returnChangeOrderToDraft,voidChangeOrder,deleteChangeOrderItem } from './actions';

const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const num=(v:any)=>Number(v||0);
const today=()=>new Date().toISOString().slice(0,10);
const units=['CY','LF','SF','LB','EA','HR','DAY','TON','GAL','LS'];
const selectClass='h-9 w-full rounded-md border border-input bg-background px-3 text-sm text-foreground outline-none transition-shadow focus:border-ring focus:ring-3 focus:ring-ring/20';

export default async function ChangeOrdersPage(){
  const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
  const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();
  if(!profile?.company_id||!['owner','office'].includes(profile.role))redirect('/employee');
  const [{data:projects},{data:summaries},{data:items},{data:codes},{data:catalog},{data:crew},{data:riskClasses},{data:baselineItems}]=await Promise.all([
    supabase.from('projects').select('id,job_number,name,status').order('job_number'),
    supabase.from('change_order_financial_summary').select('*').order('requested_date',{ascending:false}),
    supabase.from('change_order_items').select('*').order('sort_order'),
    supabase.from('cost_codes').select('id,code,name,cost_type').eq('active',true).order('sort_order'),
    supabase.from('cost_catalog_items').select('id,name,cost_code_id,default_unit,default_unit_cost').eq('active',true).order('name'),
    supabase.from('crew_members').select('id,name,is_owner,hourly_rate').eq('active',true).order('name'),
    profile?.company_id?supabase.from('li_risk_classes').select('code,name').eq('company_id',profile.company_id).eq('tax_year',2026).eq('active',true).order('code'):Promise.resolve({data:[]}),
    supabase.from('commercial_baseline_item_references').select('id,project_id,description,quantity,unit').order('description')
  ]);
  const projectMap=new Map((projects||[]).map((p:any)=>[p.id,p]));
  const openProjects=(projects||[]).filter((p:any)=>['active','on_hold'].includes(p.status));
  const itemMap=new Map<string,any[]>();for(const i of items||[]){if(!itemMap.has(i.change_order_id))itemMap.set(i.change_order_id,[]);itemMap.get(i.change_order_id)!.push(i);}
  const pendingExposure=(summaries||[]).filter((c:any)=>c.status!=='approved'&&c.status!=='rejected'&&c.status!=='void').reduce((s:number,c:any)=>s+Math.max(0,num(c.actual_company_exposure)),0);
  const approvedValue=(summaries||[]).filter((c:any)=>c.status==='approved').reduce((s:number,c:any)=>s+num(c.selected_sell_price),0);
  const submitted=(summaries||[]).filter((c:any)=>c.status==='submitted').length;
  const activeCOs=(summaries||[]).filter((c:any)=>!['rejected','void'].includes(c.status)).length;

  return <AppShell userName={profile?.full_name||user.email||'Owner'}><div className="carez-change-orders mx-auto flex w-full min-w-0 max-w-screen-2xl flex-col gap-3 lg:h-full lg:min-h-0 lg:overflow-hidden">
    <header className="flex shrink-0 flex-wrap items-center justify-between gap-3 border border-border bg-card px-4 py-3 shadow-sm"><h1 className="text-lg font-semibold tracking-tight">Change orders</h1><Dialog><DialogTrigger disableButtonEnhancement><Button size="small">New change order</Button></DialogTrigger><DialogSurface className="max-h-[88vh] overflow-y-auto sm:max-w-2xl"><DialogBody><DialogTitle>New change order</DialogTitle><DialogContent>Create a draft for added, deleted, or changed project scope.</DialogContent></DialogBody><form action={createChangeOrder} className="grid gap-4">

      <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="co-project">Project</Label><Select id="co-project" className={selectClass} name="project_id" required defaultValue=""><option value="" disabled>Select project</option>{openProjects.map((p:any)=><option key={p.id} value={p.id}>{p.job_number} — {p.name}</option>)}</Select></div><div className="grid gap-2"><Label htmlFor="co-type">Change Type</Label><Select id="co-type" className={selectClass} name="change_type" defaultValue="additive"><option value="additive">Additive — increases contract</option><option value="deductive">Deductive — customer credit</option><option value="no_cost">No-cost — Carez absorbs cost</option></Select></div></div>
      <div className="grid gap-2"><Label htmlFor="co-reversal">Reverse an Approved Change Order (optional)</Label><Select id="co-reversal" className={selectClass} name="reversal_of_change_order_id" defaultValue=""><option value="">New commercial change</option>{(summaries||[]).filter((c:any)=>c.status==='approved'&&!c.reversal_of_change_order_id).map((c:any)=>{const p:any=projectMap.get(c.project_id)||{};return <option key={c.change_order_id} value={c.change_order_id}>{p.job_number||'Job'} — {c.co_number} · {money(num(c.selected_sell_price))}</option>;})}</Select><p className="text-xs text-muted-foreground">A reversal must use the countering change type and exactly offset the approved Sell value.</p></div>
      <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="co-title">Title</Label><Input appearance="underline" id="co-title" name="title" required placeholder="Additional patio extension"/></div><div className="grid gap-2"><Label htmlFor="co-requested-date">Requested Date</Label><Input appearance="underline" id="co-requested-date" type="date" name="requested_date" defaultValue={today()} required/></div></div>
      <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="co-requested-by">Requested By</Label><Input appearance="underline" id="co-requested-by" name="requested_by" placeholder="Owner, GC, architect..."/></div><div className="grid gap-2"><Label htmlFor="co-reason">Reason</Label><Input appearance="underline" id="co-reason" name="reason" placeholder="Owner request, unforeseen condition..."/></div></div>
      <div className="grid gap-2"><Label htmlFor="co-description">Scope Description</Label><Textarea id="co-description" name="description" rows={3} placeholder="Describe exactly what is being added, removed or changed."/></div>
      <Button type="submit" className="w-fit">Create Draft Change Order</Button>
    </form></DialogSurface></Dialog></header>

    <div className="carez-summary-ledger grid shrink-0 grid-cols-2 gap-px xl:grid-cols-4">
      <div className="min-w-0 bg-card px-3 py-2"><div className="space-y-1"><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Active change orders</div><div className="font-mono text-xl font-semibold tabular-nums">{activeCOs}</div></div></div>
      <div className="min-w-0 bg-card px-3 py-2"><div className={submitted?'space-y-1 text-warning':'space-y-1'}><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Awaiting approval</div><div className="font-mono text-xl font-semibold tabular-nums">{submitted}</div></div></div>
      <div className="min-w-0 bg-card px-3 py-2"><div className="space-y-1"><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Approved contract changes</div><div className="font-mono text-xl font-semibold tabular-nums">{money(approvedValue)}</div></div></div>
      <div className="min-w-0 bg-card px-3 py-2"><div className={pendingExposure>0?'space-y-1 text-destructive':'space-y-1'}><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Unapproved field exposure</div><div className="font-mono text-xl font-semibold tabular-nums">{money(pendingExposure)}</div></div></div>
    </div>

    <section className="carez-register min-h-0 flex-1 space-y-2 overflow-auto border border-border bg-card/40 p-3" aria-labelledby="change-orders-list"><div className="carez-section-heading"><h2 id="change-orders-list">Change order register</h2></div>
    {(summaries||[]).length===0?<div className="border border-border"><div><h3>No change orders yet</h3><p>Create one when project scope changes after the original estimate is approved.</p></div></div>:<div className="space-y-4">{(summaries||[]).map((co:any)=>{
      const project:any=projectMap.get(co.project_id)||{};
      const coItems=itemMap.get(co.change_order_id)||[];
      const locked=['approved','rejected','void'].includes(co.status);
      const exposure=num(co.actual_company_exposure);
      const selected=num(co.selected_sell_price);
      const recommended=num(co.recommended_sell_price);
      const profitImpact=num(co.projected_profit_impact);
      const typeLabel=co.change_type==='deductive'?'Deductive':co.change_type==='no_cost'?'No Cost':'Additive';
      const statusClass=co.status==='approved'?'border-success/30 bg-success/10 text-success':co.status==='submitted'?'border-warning/30 bg-warning/10 text-warning':co.status==='rejected'?'border-destructive/30 bg-destructive/10 text-destructive':'text-muted-foreground';
      return <ChangeOrderDrawer key={co.change_order_id} title={`${co.co_number} — ${co.title}`} description={`${project.job_number||'Job'} · ${typeLabel} · ${co.status}`} leading={<><div className="carez-co-row-title">{co.co_number} — {co.title}</div><div className="carez-co-row-description">{project.job_number||'Job'} — {project.name||'Project'} · {typeLabel} · requested {co.requested_date}</div></>} trailing={<><strong className="font-mono tabular-nums">{money(selected)}</strong><Badge appearance="outline" className={statusClass}>{co.status}</Badge></>}><div className="space-y-6 px-4 pb-6">

        <section className="space-y-4"><div><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Commercial impact</div><h4 className="mt-1 font-semibold">Change Order Economics</h4><p className="mt-1 text-sm text-muted-foreground">Original project budget remains frozen. Approved COs become separate authorized budgets.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
          <div className="rounded-lg border border-border bg-muted/20 p-3"><div className="text-xs font-medium text-muted-foreground">Direct Cost Impact</div><div className="mt-1 text-lg font-semibold tabular-nums">{money(num(co.total_direct_cost))}</div><div className="mt-1 text-xs text-muted-foreground">Labor {money(num(co.direct_labor_cost))} · Other {money(num(co.total_direct_cost)-num(co.direct_labor_cost))}</div></div>
          <div className="rounded-lg border border-border bg-muted/20 p-3"><div className="text-xs font-medium text-muted-foreground">Overhead Impact</div><div className="mt-1 text-lg font-semibold tabular-nums">{money(num(co.overhead_cost))}</div><div className="mt-1 text-xs text-muted-foreground">{Math.abs(num(co.labor_hours)).toFixed(1)} labor hr × snapshotted OH rate</div></div>
          <div className="rounded-lg border border-primary/25 bg-primary/5 p-3"><div className="text-xs font-medium text-muted-foreground">Recommended Price</div><div className="mt-1 text-lg font-semibold tabular-nums">{money(recommended)}</div><div className="mt-1 text-xs text-muted-foreground">Target margin {num(co.target_margin_percent).toFixed(1)}%</div></div>
          <div className={`rounded-lg border bg-muted/20 p-3 ${profitImpact>=0?'border-success/30 text-success':'border-destructive/30 text-destructive'}`}><div className="text-xs font-medium text-muted-foreground">Selected Price / Profit Impact</div><div className="mt-1 text-lg font-semibold tabular-nums">{money(selected)}</div><div className="mt-1 text-xs text-muted-foreground">Projected profit impact {money(profitImpact)}</div></div>
        </div>
        {co.status!=='approved'&&exposure>0&&<div className="rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-3 text-sm text-destructive"><strong>Unapproved exposure: {money(exposure)}.</strong> Carez has already incurred cost against this change before customer approval.</div>}
        {co.change_type==='no_cost'&&<div className="rounded-lg border border-warning/30 bg-warning/10 px-3 py-3 text-sm text-warning"><strong>No-cost change.</strong> Revenue remains $0 while actual/budgeted cost still reduces project profit.</div>}</section>

        <section className="space-y-4 border-t border-border pt-5"><div><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Scope</div><h4 className="mt-1 font-semibold">Cost Build-Up</h4><p className="mt-1 text-sm text-muted-foreground">Each line can be a real cost or a credit / avoided cost.</p></div>
          {coItems.length===0?<div className="text-sm text-muted-foreground">No scope items entered yet.</div>:<div className="divide-y rounded-lg border border-border">{coItems.map((i:any)=><div className="flex flex-col gap-3 px-3 py-3 sm:flex-row sm:items-center sm:justify-between" key={i.id}><div><div className="font-medium">{i.description}</div><div className="mt-1 text-xs text-muted-foreground">{i.item_type} · {i.cost_effect==='credit'?'Credit / avoided cost':'Cost'} · {Math.abs(num(i.quantity)).toFixed(2)} {i.unit}{i.item_type==='labor'&&i.labor_task?` · ${i.labor_task}`:''}</div></div><div className="flex items-center gap-2 sm:flex-col sm:items-end"><strong className="tabular-nums">{money(num(i.direct_cost))}</strong>{co.status==='draft'&&<form action={deleteChangeOrderItem}><input type="hidden" name="item_id" value={i.id}/><input type="hidden" name="change_order_id" value={co.change_order_id}/><Button type="submit" appearance="secondary" size="small">Delete</Button></form>}</div></div>)}</div>}

          {!locked&&co.status==='draft'&&<Accordion collapsible className="grid gap-3 xl:grid-cols-2">
            <AccordionItem value="labor" className="rounded-lg border border-border"><AccordionHeader>Add Labor</AccordionHeader><AccordionPanel><form action={addChangeOrderItem} className="grid gap-4"><input type="hidden" name="change_order_id" value={co.change_order_id}/><input type="hidden" name="item_type" value="labor"/><div className="grid gap-2"><Label htmlFor={`labor-baseline-${co.change_order_id}`}>Affected Original Scope Item (optional)</Label><Select id={`labor-baseline-${co.change_order_id}`} className={selectClass} name="affected_commercial_baseline_item_id" defaultValue=""><option value="">New / unallocated scope</option>{(baselineItems||[]).filter((b:any)=>b.project_id===co.project_id).map((b:any)=><option key={b.id} value={b.id}>{b.description} · {num(b.quantity)} {b.unit}</option>)}</Select></div>
              <div className="grid gap-2"><Label htmlFor={`labor-description-${co.change_order_id}`}>Description</Label><Input appearance="underline" id={`labor-description-${co.change_order_id}`} name="description" required placeholder="Form additional wall"/></div>
              <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`labor-worker-${co.change_order_id}`}>Worker</Label><Select id={`labor-worker-${co.change_order_id}`} className={selectClass} name="crew_member_id" required defaultValue=""><option value="" disabled>Select worker</option>{(crew||[]).map(c=><option key={c.id} value={c.id}>{c.name}{c.is_owner?' — Owner':` — $${num(c.hourly_rate).toFixed(2)}/hr`}</option>)}</Select></div><div className="grid gap-2"><Label htmlFor={`labor-effect-${co.change_order_id}`}>Cost Effect</Label><Select id={`labor-effect-${co.change_order_id}`} className={selectClass} name="cost_effect" defaultValue={co.change_type==='deductive'?'credit':'cost'}><option value="cost">Cost — work Carez must perform</option><option value="credit">Credit — work/cost being removed</option></Select></div></div>
              <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`labor-operation-${co.change_order_id}`}>Operation</Label><Select id={`labor-operation-${co.change_order_id}`} className={selectClass} name="labor_task" defaultValue="Formwork"><option>Formwork</option><option>Rebar</option><option>Placement</option><option>Finishing</option><option>Strip</option><option>Cleanup</option><option>Layout</option><option>General</option></Select></div><div className="grid gap-2"><Label htmlFor={`labor-risk-${co.change_order_id}`}>L&amp;I Risk Class</Label><Select id={`labor-risk-${co.change_order_id}`} className={selectClass} name="risk_class_code" defaultValue="0217-01">{(riskClasses||[]).map(r=><option key={r.code} value={r.code}>{r.code} — {r.name}</option>)}</Select></div></div>
              <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`labor-regular-${co.change_order_id}`}>Regular Hours</Label><Input appearance="underline" id={`labor-regular-${co.change_order_id}`} type="number" min="0" step="0.25" name="regular_hours" required defaultValue="8"/></div><div className="grid gap-2"><Label htmlFor={`labor-overtime-${co.change_order_id}`}>Overtime Hours</Label><Input appearance="underline" id={`labor-overtime-${co.change_order_id}`} type="number" min="0" step="0.25" name="overtime_hours" defaultValue="0"/></div></div>
              <Button type="submit" className="w-fit">Add Labor</Button>
            </form></AccordionPanel></AccordionItem>

            <AccordionItem value="material" className="rounded-lg border border-border"><AccordionHeader>Add Material / Equipment / Sub</AccordionHeader><AccordionPanel><form action={addChangeOrderItem} className="grid gap-4"><input type="hidden" name="change_order_id" value={co.change_order_id}/><div className="grid gap-2"><Label htmlFor={`cost-baseline-${co.change_order_id}`}>Affected Original Scope Item (optional)</Label><Select id={`cost-baseline-${co.change_order_id}`} className={selectClass} name="affected_commercial_baseline_item_id" defaultValue=""><option value="">New / unallocated scope</option>{(baselineItems||[]).filter((b:any)=>b.project_id===co.project_id).map((b:any)=><option key={b.id} value={b.id}>{b.description} · {num(b.quantity)} {b.unit}</option>)}</Select></div>
              <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`cost-type-${co.change_order_id}`}>Type</Label><Select id={`cost-type-${co.change_order_id}`} className={selectClass} name="item_type" defaultValue="material"><option value="material">Material</option><option value="equipment">Equipment</option><option value="subcontractor">Subcontractor</option><option value="other">Other Direct</option></Select></div><div className="grid gap-2"><Label htmlFor={`cost-effect-${co.change_order_id}`}>Cost Effect</Label><Select id={`cost-effect-${co.change_order_id}`} className={selectClass} name="cost_effect" defaultValue={co.change_type==='deductive'?'credit':'cost'}><option value="cost">Cost — Carez will incur</option><option value="credit">Credit — avoided cost</option></Select></div></div>
              <div className="grid gap-2"><Label htmlFor={`cost-code-${co.change_order_id}`}>Cost Code</Label><Select id={`cost-code-${co.change_order_id}`} className={selectClass} name="cost_code_id" defaultValue=""><option value="">Select if applicable</option>{(codes||[]).map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</Select></div>
              <div className="grid gap-2"><Label htmlFor={`catalog-item-${co.change_order_id}`}>Catalog Item</Label><Select id={`catalog-item-${co.change_order_id}`} className={selectClass} name="catalog_item_id" defaultValue=""><option value="">Custom / not cataloged</option>{(catalog||[]).map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</Select></div>
              <div className="grid gap-2"><Label htmlFor={`cost-description-${co.change_order_id}`}>Description</Label><Input appearance="underline" id={`cost-description-${co.change_order_id}`} name="description" required placeholder="4000 PSI ready-mix, pump, #4 rebar..."/></div>
              <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`cost-quantity-${co.change_order_id}`}>Quantity</Label><Input appearance="underline" id={`cost-quantity-${co.change_order_id}`} type="number" min="0" step="0.01" name="quantity" defaultValue="1" required/></div><div className="grid gap-2"><Label htmlFor={`cost-unit-${co.change_order_id}`}>Unit</Label><Select id={`cost-unit-${co.change_order_id}`} className={selectClass} name="unit" defaultValue="LS">{units.map(u=><option key={u}>{u}</option>)}</Select></div></div>
              <div className="grid gap-2"><Label htmlFor={`cost-unit-cost-${co.change_order_id}`}>Unit Cost</Label><Input appearance="underline" id={`cost-unit-cost-${co.change_order_id}`} type="number" min="0" step="0.01" name="unit_cost" required/></div>
              <Button type="submit" className="w-fit">Add Cost Item</Button>
            </form></AccordionPanel></AccordionItem>
          </Accordion>}
        </section>

        <section className="space-y-4 border-t border-border pt-5">
          {!locked&&co.status==='draft'?<><div><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Workflow</div><h4 className="mt-1 font-semibold">Commercial Controls</h4></div><form action={updateChangeOrder} className="grid gap-4"><input type="hidden" name="change_order_id" value={co.change_order_id}/><input type="hidden" name="change_type" value={co.change_type}/>
            <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`margin-${co.change_order_id}`}>Target Margin %</Label><Input appearance="underline" id={`margin-${co.change_order_id}`} type="number" min="0" max="80" step="0.1" name="target_margin_percent" defaultValue={String(num(co.target_margin_percent))}/></div><div className="grid gap-2"><Label htmlFor={`price-${co.change_order_id}`}>Price Override</Label><Input appearance="underline" id={`price-${co.change_order_id}`} type="number" min="0" step="0.01" name="proposed_sell_price" defaultValue={co.proposed_sell_price==null?'':String(Math.abs(num(co.proposed_sell_price)))} placeholder={Math.abs(recommended).toFixed(2)}/></div></div>
            <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`processing-${co.change_order_id}`}>Payment Processing Reserve %</Label><Input appearance="underline" id={`processing-${co.change_order_id}`} type="number" min="0" step="0.01" name="payment_processing_rate_percent" defaultValue={String(num(co.payment_processing_rate_percent))}/></div><div className="grid gap-2"><Label htmlFor={`field-status-${co.change_order_id}`}>Field Work Status</Label><Select id={`field-status-${co.change_order_id}`} className={selectClass} name="field_work_status" defaultValue={co.field_work_status}><option value="not_started">Not Started</option><option value="directed">Directed / Proceeding Before Approval</option><option value="in_progress">In Progress</option><option value="complete">Complete</option></Select></div></div>
            <div className="grid gap-2"><Label htmlFor={`workflow-status-${co.change_order_id}`}>Workflow Status</Label><Select id={`workflow-status-${co.change_order_id}`} className={selectClass} name="status" defaultValue="draft"><option value="draft">Save Draft</option><option value="submitted">Submit for Approval</option></Select></div>
            <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`auth-kind-${co.change_order_id}`}>Authorization Basis</Label><Select id={`auth-kind-${co.change_order_id}`} className={selectClass} name="authorization_kind" defaultValue={co.change_type==='no_cost'?'internal_no_cost':'external_customer'}><option value="external_customer">Customer authorization</option><option value="external_gc">GC authorization</option><option value="internal_no_cost">Internal no-cost exposure</option></Select></div><div className="grid gap-2"><Label htmlFor={`auth-ref-${co.change_order_id}`}>Authorization Reference</Label><Input appearance="underline" id={`auth-ref-${co.change_order_id}`} name="authorization_reference" placeholder="Signed CO / email / directive number"/></div></div>
            <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`auth-by-${co.change_order_id}`}>Externally Authorized By</Label><Input appearance="underline" id={`auth-by-${co.change_order_id}`} name="external_authorized_by" placeholder="Customer / GC representative"/></div><div className="grid gap-2"><Label htmlFor={`auth-at-${co.change_order_id}`}>External Authorization Date</Label><Input appearance="underline" id={`auth-at-${co.change_order_id}`} type="date" name="external_authorized_at"/></div></div>
            <div className="grid gap-2"><Label htmlFor={`auth-note-${co.change_order_id}`}>Authorization Note / Document Reference</Label><Input appearance="underline" id={`auth-note-${co.change_order_id}`} name="authorization_note"/><Input appearance="underline" aria-label="Authorization document reference" name="authorization_document_reference" placeholder="Optional document reference"/></div>
            <Button type="submit" appearance="secondary" className="w-fit">Save Change Order</Button>
          </form><form action={voidChangeOrder}><input type="hidden" name="change_order_id" value={co.change_order_id}/><Button type="submit" appearance="secondary" size="small">Void Draft</Button></form>
          </>:co.status==='submitted'?<><div className="rounded-lg border border-warning/30 bg-warning/10 px-3 py-3 text-sm"><strong>Submitted and frozen.</strong> Return it to Draft explicitly before editing. Authorization: {co.authorization_kind||'missing'}{co.authorization_reference?` · ${co.authorization_reference}`:''}</div><div className="flex flex-wrap gap-2"><form action={approveChangeOrder}><input type="hidden" name="change_order_id" value={co.change_order_id}/><Button type="submit">Approve & Freeze CO Budget</Button></form><form action={rejectChangeOrder}><input type="hidden" name="change_order_id" value={co.change_order_id}/><Button type="submit" appearance="secondary">Mark Rejected</Button></form><form action={returnChangeOrderToDraft}><input type="hidden" name="change_order_id" value={co.change_order_id}/><Button type="submit" appearance="secondary">Return to Draft</Button></form><form action={voidChangeOrder}><input type="hidden" name="change_order_id" value={co.change_order_id}/><Button type="submit" appearance="secondary">Void</Button></form></div></>:<div className={`rounded-lg border px-3 py-3 text-sm ${co.status==='approved'?'border-success/30 bg-success/10 text-success':'border-warning/30 bg-warning/10 text-warning'}`}><strong>{co.status==='approved'?'Approved and frozen.':'Change order closed.'}</strong> {co.status==='approved'?'Contract value and authorized budget now include this change.':'This change no longer affects the authorized project budget.'}</div>}
        </section>
      </div></ChangeOrderDrawer>;
    })}</div>}
    </section>

  </div></AppShell>;
}
