import {redirect} from 'next/navigation';
import Link from 'next/link';
import {AlertTriangle,ArrowRight,BriefcaseBusiness,CalendarDays,CheckCircle2,Clock3,FileText,HardHat,ListChecks,PhoneCall,Wallet} from 'lucide-react';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';

const money=(n:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0));
const num=(n:any)=>Number(n||0);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const addDays=(date:string,n:number)=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10);};
const fmtDate=(v:string)=>new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric'}).format(new Date(`${v}T12:00:00`));
const fmtTime=(v?:string|null)=>{if(!v)return '';const [h,m]=String(v).split(':').map(Number);const d=new Date();d.setHours(h,m||0,0,0);return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(d);};

type Attention={priority:number;tone:'danger'|'warning'|'info';title:string;copy:string;href:string;action:string};

export default async function HomePage(){
  const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
  const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(!profile?.company_id)redirect('/login');if(profile.role==='employee')redirect('/employee');
  const companyId=profile.company_id,start=today(),weekEnd=addDays(start,6);
  const [{data:projects},{data:workReady},{data:billing},{data:shifts},{data:schedule},{data:operationReady},{data:proposals},{data:leads},{data:cash}]=await Promise.all([
    supabase.from('projects').select('id,job_number,name,status,next_action,address,city,state').eq('company_id',companyId).in('status',['active','on_hold','planning']).order('created_at',{ascending:false}),
    supabase.from('project_work_readiness_summary').select('*').eq('company_id',companyId),
    supabase.from('project_billing_summary').select('*'),
    supabase.from('employee_shift_sessions').select('id,project_id,status').eq('company_id',companyId).in('status',['active','open','submitted']),
    supabase.from('work_schedule_items').select('id,project_id,title,schedule_date,start_time,status,item_type,work_package_operation_id,projects(job_number,name)').eq('company_id',companyId).gte('schedule_date',start).lte('schedule_date',weekEnd).neq('status','cancelled').order('schedule_date').order('start_time'),
    supabase.from('work_package_start_readiness').select('operation_id,ready_to_start_all,start_next_action').eq('company_id',companyId),
    supabase.from('proposal_conversion_queue').select('estimate_id,presentation_id,proposal_number,customer_name,project_name,conversion_stage,next_action,follow_up_due,follow_up_due_now,base_sell_price').eq('company_id',companyId),
    supabase.from('leads').select('id,opportunity_number,customer_name,project_name,status,follow_up').eq('company_id',companyId).not('status','in','("won","lost","closed")'),
    supabase.from('cashflow_calendar').select('id,event_date,event_type,description,cash_in,cash_out,status,urgency').eq('company_id',companyId).gte('event_date',start).lte('event_date',weekEnd).order('event_date'),
  ]);
  const projectMap=new Map((projects||[]).map((row:any)=>[row.id,row])),readyMap=new Map((workReady||[]).map((row:any)=>[row.project_id,row])),billMap=new Map((billing||[]).map((row:any)=>[row.project_id,row])),opReady=new Map((operationReady||[]).map((row:any)=>[row.operation_id,row]));
  const fieldMap=new Map<string,{working:number;review:number}>();for(const shift of shifts||[]){const x=fieldMap.get(shift.project_id)||{working:0,review:0};if(['active','open'].includes(shift.status))x.working++;if(shift.status==='submitted')x.review++;fieldMap.set(shift.project_id,x);}
  const activeProjects=(projects||[]).map((project:any)=>{const r:any=readyMap.get(project.id)||{},bill:any=billMap.get(project.id)||{},field=fieldMap.get(project.id)||{working:0,review:0};const ready=num(r.ready_operations),blocked=num(r.blocked_operations),failed=num(r.failed_inspection_operations);const hardHold=failed>0||(blocked>0&&ready===0)||project.status==='on_hold';const state=hardHold?'hold':ready>0?'ready':'planning';const next=(schedule||[]).find((item:any)=>item.project_id===project.id&&item.item_type==='work');return{project,r,bill,field,state,next};});
  const jobsHeld=activeProjects.filter((row:any)=>row.state==='hold').length,jobsReady=activeProjects.filter((row:any)=>row.state==='ready').length;
  const crewWorking=(shifts||[]).filter((row:any)=>['active','open'].includes(row.status)).length,timeReview=(shifts||[]).filter((row:any)=>row.status==='submitted').length;
  const ar=(billing||[]).reduce((sum:number,row:any)=>sum+Math.max(0,num(row.outstanding_ar)),0),overdue=(billing||[]).reduce((sum:number,row:any)=>sum+Math.max(0,num(row.overdue_ar)),0);
  const cashOut=(cash||[]).filter((row:any)=>row.status!=='paid'&&row.status!=='cleared').reduce((sum:number,row:any)=>sum+num(row.cash_out),0),cashIn=(cash||[]).filter((row:any)=>row.status!=='paid'&&row.status!=='cleared').reduce((sum:number,row:any)=>sum+num(row.cash_in),0);
  const todaySchedule=(schedule||[]).filter((item:any)=>item.schedule_date===start);
  const attention:Attention[]=[];
  for(const item of todaySchedule){if(item.item_type==='work'&&item.work_package_operation_id){const r:any=opReady.get(item.work_package_operation_id);if(r?.ready_to_start_all===false)attention.push({priority:1,tone:'danger',title:`${item.projects?.job_number||'Job'} — scheduled work is on HOLD`,copy:r.start_next_action||item.title,href:'/readiness',action:'Clear Hold'});}}
  for(const row of activeProjects){if(row.state==='hold'&&!todaySchedule.some((item:any)=>item.project_id===row.project.id&&item.item_type==='work'))attention.push({priority:2,tone:'danger',title:`${row.project.job_number} — ${row.project.name}`,copy:num(row.r.failed_inspection_operations)>0?'Failed inspection is blocking work':num(row.r.blocked_operations)>0?'Open physical work is blocked':row.project.next_action||'Job is on hold',href:'/readiness',action:'Work Readiness'});}
  if(timeReview)attention.push({priority:3,tone:'warning',title:`${timeReview} timecard${timeReview===1?' needs':'s need'} review`,copy:'Approve or correct field time before payroll and job costing.',href:'/field/review',action:'Review Time'});
  if(overdue>0)attention.push({priority:4,tone:'warning',title:`${money(overdue)} customer balance is past due`,copy:`Total customer receivables are ${money(ar)}.`,href:'/billing',action:'Open Billing'});
  for(const proposal of proposals||[]){if(proposal.conversion_stage==='needs_reply')attention.push({priority:5,tone:'warning',title:`${proposal.proposal_number} needs a reply`,copy:proposal.next_action||`${proposal.customer_name||'Customer'} responded to the proposal.`,href:`/proposals/${proposal.estimate_id}`,action:'Open Proposal'});else if(proposal.follow_up_due_now)attention.push({priority:6,tone:'info',title:`Follow up on ${proposal.proposal_number}`,copy:`${proposal.customer_name||'Customer'} · ${proposal.project_name||'Proposal'}`,href:`/proposals/${proposal.estimate_id}`,action:'Follow Up'});}
  for(const lead of leads||[]){if(lead.follow_up&&lead.follow_up<=start)attention.push({priority:7,tone:'info',title:`Follow up: ${lead.customer_name||lead.opportunity_number}`,copy:lead.project_name||'Open opportunity',href:`/leads/${lead.id}`,action:'Open Lead'});}
  for(const event of cash||[]){if(event.urgency==='overdue'||event.urgency==='critical')attention.push({priority:8,tone:'warning',title:event.description||'Cash obligation',copy:`${fmtDate(event.event_date)} · ${event.cash_out>0?`${money(event.cash_out)} out`:`${money(event.cash_in)} in`}`,href:'/cashflow',action:'Cashflow'});}
  attention.sort((a,b)=>a.priority-b.priority);
  const openProposals=(proposals||[]).filter((row:any)=>['sent','viewed','needs_reply'].includes(row.conversion_stage)),openProposalValue=openProposals.reduce((sum:number,row:any)=>sum+num(row.base_sell_price),0),openLeads=(leads||[]).length;

  return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page owner-home-v3">
    <div className="owner-today-head"><div><div className="section-kicker">CAREZ CONCRETE · TODAY</div><h1>{fmtDate(start)}</h1><p>{attention.length?`${attention.length} item${attention.length===1?'':'s'} need attention. Handle the field blockers first.`:'No urgent exception is waiting. Keep the planned work moving.'}</p></div><div className="owner-today-actions"><Link className="button" href="/projects"><BriefcaseBusiness size={15}/> Jobs</Link><Link className="button secondary" href="/schedule"><CalendarDays size={15}/> Schedule</Link></div></div>

    <div className="command-grid"><div className={`command-card ${jobsHeld?'bad':jobsReady?'good':''}`}><div className="command-label">Jobs</div><div className="command-value">{jobsReady} ready · {jobsHeld} hold</div><div className="command-help">Physical readiness across active jobs.</div></div><div className={`command-card ${timeReview?'watch':crewWorking?'good':''}`}><div className="command-label">Crew</div><div className="command-value">{crewWorking} working</div><div className="command-help">{timeReview?`${timeReview} timecard${timeReview===1?'':'s'} waiting review.`:'No submitted time waiting review.'}</div></div><div className={`command-card ${overdue?'bad':ar?'watch':''}`}><div className="command-label">Customers Owe</div><div className="command-value">{money(ar)}</div><div className="command-help">{overdue?`${money(overdue)} past due.`:'No past-due balance.'}</div></div><div className={`command-card ${cashOut>cashIn?'watch':''}`}><div className="command-label">Next 7 Days</div><div className="command-value">{money(cashIn-cashOut)}</div><div className="command-help">{money(cashIn)} expected in · {money(cashOut)} expected out.</div></div></div>

    <section className="section owner-home-grid"><div className="surface owner-attention"><div className="surface-header"><div><div className="surface-title">Handle First</div><div className="surface-subtitle">Carez sorts today's exceptions by what can stop work or cash first.</div></div><span className="owner-count">{attention.length}</span></div><div className="surface-body">{attention.length===0?<div className="owner-clear"><CheckCircle2/><div><strong>No urgent exception</strong><span>Today's jobs can run from the current plan.</span></div></div>:<div className="owner-attention-list">{attention.slice(0,8).map((item,index)=><Link href={item.href} key={`${item.title}-${index}`} className={item.tone}><span className="owner-attention-icon">{item.tone==='danger'?<AlertTriangle/>:item.tone==='warning'?<Clock3/>:<PhoneCall/>}</span><span><strong>{item.title}</strong><small>{item.copy}</small></span><b>{item.action}<ArrowRight/></b></Link>)}</div>}</div></div>

      <div className="surface"><div className="surface-header"><div><div className="surface-title">Today's Field Plan</div><div className="surface-subtitle">What is expected to happen today and whether the physical work is actually clear.</div></div><Link href="/schedule">Full Schedule</Link></div><div className="surface-body">{todaySchedule.length===0?<div className="owner-clear muted"><CalendarDays/><div><strong>Nothing scheduled today</strong><span>Use Schedule to plan the next ready package.</span></div></div>:<div className="owner-day-list">{todaySchedule.map((item:any)=>{const rr:any=item.work_package_operation_id?opReady.get(item.work_package_operation_id):null;const blocked=item.item_type==='work'&&rr?.ready_to_start_all===false;return <div key={item.id}><span className={`owner-day-state ${blocked?'hold':item.status==='confirmed'?'ready':''}`}>{blocked?'HOLD':item.status==='confirmed'?'READY':item.item_type.toUpperCase()}</span><div><strong>{item.projects?.job_number} — {item.title}</strong><small>{item.projects?.name}{item.start_time?` · ${fmtTime(item.start_time)}`:''}{blocked?` · ${rr.start_next_action}`:''}</small></div></div>;})}</div>}</div></div></section>

    <section className="section"><div className="section-heading"><div><div className="section-kicker">ACTIVE JOBS</div><div className="section-title">What moves next</div><div className="section-heading-meta">A compact operating view. Open the job only when you need the deeper financial or field controls.</div></div><Link className="button secondary" href="/projects">All Jobs</Link></div><div className="owner-job-strip">{activeProjects.slice(0,6).map((row:any)=>{const p=row.project,ready=num(row.r.ready_operations),blocked=num(row.r.blocked_operations);return <Link href={`/projects/${p.id}`} key={p.id} className={row.state}><span>{p.job_number}</span><strong>{p.name}</strong><small>{row.state==='hold'?`${blocked} work hold${blocked===1?'':'s'}`:row.next?`${row.next.title} · ${fmtDate(row.next.schedule_date)}`:ready?`${ready} operation${ready===1?'':'s'} ready`:(p.next_action||'Plan next work')}</small><b>{row.state==='hold'?'HOLD':row.state==='ready'?'READY':'PLAN'} <ArrowRight/></b></Link>;})}</div></section>

    <section className="section"><div className="owner-pipeline-strip"><div><div className="section-kicker">SALES PIPELINE</div><div className="section-title">{openLeads} open lead{openLeads===1?'':'s'} · {openProposals.length} proposal{openProposals.length===1?'':'s'} in market</div><div className="section-heading-meta">Open proposal value: {money(openProposalValue)}. Sales stays visible without taking over the operating dashboard.</div></div><div className="action-row"><Link className="button secondary" href="/leads">Leads</Link><Link className="button secondary" href="/proposals"><FileText size={14}/> Proposals</Link><Link className="button secondary" href="/cashflow"><Wallet size={14}/> Cashflow</Link></div></div></section>
  </div></AppShell>;
}
