'use client';

import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import {BriefcaseBusiness,ChevronDown,Menu,Search} from 'lucide-react';
import {BankSyncPulse} from '@/components/PlaidBankControls';
import {OutlookSyncPulse} from '@/components/OutlookSyncPulse';
import {CarezProjectContextBar} from '@/components/carez/project-context';
export {CarezProjectSwitcher} from '@/components/carez/project-context';
import {Button} from '@/components/ui/button';
import {Command,CommandDialog,CommandEmpty,CommandGroup,CommandInput,CommandItem,CommandList} from '@/components/ui/command';
import {NavigationMenu,NavigationMenuContent,NavigationMenuItem,NavigationMenuLink,NavigationMenuList,NavigationMenuTrigger,NavigationMenuViewport} from '@/components/ui/navigation-menu';
import {Sheet,SheetContent,SheetHeader,SheetTitle} from '@/components/ui/sheet';
import {cn} from '@/lib/utils';
import {createClient} from '@/lib/supabase/client';
import {COMPANY_BRANDING_CHANGED_EVENT,FALLBACK_COMPANY_LOGO,companyLogoPublicUrl} from '@/lib/companyBranding';
import {NAVIGATION_DESTINATIONS,WORKSPACE_PRESENTATION_SURFACES,buildProjectSwitchHref,getDestinationById,getWorkspacePresentationForDestination,resolveActiveDestination,resolveProjectRoute,type NavigationDestination} from '@/lib/ui/navigation';

type ProjectOption={id:string;jobNumber:string;name:string;status:string|null;location:string};
type ProjectRow={id:string;job_number:string|null;name:string|null;status:string|null;address:string|null;city:string|null;state:string|null};
const GLOBAL_DESTINATIONS:Record<string,readonly string[]>={preconstruction:['leads','takeoff','estimates','proposals'],projects:['projects','job-setup','documents','change-orders'],field:['schedule','readiness','crew','field'],production:['production','work-packages','pour-control','forecast'],finance:['cashflow','billing','payables','procurement','banking','payroll','costs'],system:['settings']};
function isDestination(value:NavigationDestination|null):value is NavigationDestination{return Boolean(value)}
function destinationsFor(ids:readonly string[]){return ids.map(getDestinationById).filter(isDestination)}
function isWorkstation(pathname:string){const segment=pathname.match(/^\/takeoff\/([^/]+)/)?.[1];return Boolean(segment&&!['assemblies','intelligence','plans'].includes(segment));}
function activeSurface(pathname:string){return getWorkspacePresentationForDestination(resolveActiveDestination(pathname)?.id||'')?.surface.id||null;}
function navClass(active:boolean){return cn('inline-flex h-9 items-center border-b-2 border-transparent px-2.5 text-sm font-medium text-muted-foreground outline-none transition-colors hover:bg-accent/70 hover:text-foreground focus-visible:ring-[3px] focus-visible:ring-ring/50',active&&'border-primary text-foreground')}
function dropdownLayout(destinationCount:number){return destinationCount>4?'grid-cols-2 min-w-[28rem]':'grid-cols-1 min-w-[14rem]';}

function DesktopNavigation({pathname}:{pathname:string}){
  const surface=activeSurface(pathname),activeId=resolveActiveDestination(pathname)?.id;
  return <NavigationMenu aria-label="Primary navigation" className="hidden min-w-0 xl:flex"><NavigationMenuList><NavigationMenuItem><NavigationMenuLink asChild active={pathname==='/' }><Link href="/" prefetch={false} aria-current={pathname==='/'?'page':undefined} className={navClass(pathname==='/')}>Today</Link></NavigationMenuLink></NavigationMenuItem>{WORKSPACE_PRESENTATION_SURFACES.filter(item=>item.id!=='today').map(item=>{const destinations=destinationsFor(GLOBAL_DESTINATIONS[item.id]||[]);return <NavigationMenuItem key={item.id}>{destinations.length===1?<NavigationMenuLink asChild active={surface===item.id}><Link href={item.href} prefetch={false} aria-current={surface===item.id?'page':undefined} className={navClass(surface===item.id)}>{item.label}</Link></NavigationMenuLink>:<><NavigationMenuTrigger className={surface===item.id?'border-primary text-foreground':''}>{item.label}</NavigationMenuTrigger><NavigationMenuContent><ul className={cn('grid gap-0.5',dropdownLayout(destinations.length))}>{destinations.map(destination=><li key={destination.id} className="min-w-0"><NavigationMenuLink asChild active={activeId===destination.id}><Link href={destination.href} prefetch={false} aria-current={activeId===destination.id?'page':undefined} className={cn('block whitespace-nowrap rounded-sm px-3 py-2 text-sm font-medium outline-none hover:bg-accent/70 focus-visible:ring-[3px] focus-visible:ring-ring/50',activeId===destination.id&&'bg-primary/10 text-foreground')}>{destination.label}</Link></NavigationMenuLink></li>)}</ul></NavigationMenuContent></>}</NavigationMenuItem>})}</NavigationMenuList><NavigationMenuViewport/></NavigationMenu>;
}

function MobileDomain({id,label,pathname,onNavigate}:{id:string;label:string;pathname:string;onNavigate:()=>void}){
  const [open,setOpen]=useState(activeSurface(pathname)===id),activeId=resolveActiveDestination(pathname)?.id;
  return <section className="border-t border-border"><button type="button" aria-expanded={open} onClick={()=>setOpen(value=>!value)} className={cn('flex min-h-11 w-full items-center justify-between px-3 text-left text-sm font-medium outline-none hover:bg-accent/70 focus-visible:ring-[3px] focus-visible:ring-ring/50',activeSurface(pathname)===id&&'text-primary')}>{label}<ChevronDown className={cn('size-4 transition-transform',open&&'rotate-180')}/></button>{open?<div className="pb-2">{destinationsFor(GLOBAL_DESTINATIONS[id]||[]).map(destination=><Link key={destination.id} href={destination.href} prefetch={false} onClick={onNavigate} aria-current={activeId===destination.id?'page':undefined} className={cn('ml-3 flex min-h-10 items-center border-l-2 border-transparent px-3 text-sm text-muted-foreground outline-none hover:bg-accent/70 hover:text-foreground focus-visible:ring-[3px] focus-visible:ring-ring/50',activeId===destination.id&&'border-primary bg-primary/10 text-foreground')}>{destination.label}</Link>)}</div>:null}</section>;
}

function MobileNavigation({open,onOpenChange,pathname}:{open:boolean;onOpenChange:(open:boolean)=>void;pathname:string}){
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="left" className="w-[90vw] max-w-sm p-0 xl:hidden"><SheetHeader className="border-b border-border"><SheetTitle>Menu</SheetTitle></SheetHeader><nav aria-label="Mobile primary navigation" className="min-h-0 overflow-y-auto px-3 py-2"><Link href="/" prefetch={false} onClick={()=>onOpenChange(false)} aria-current={pathname==='/'?'page':undefined} className={cn('flex min-h-11 items-center border-l-2 border-transparent px-3 text-sm font-medium outline-none hover:bg-accent/70 focus-visible:ring-[3px] focus-visible:ring-ring/50',pathname==='/'&&'border-primary bg-primary/10 text-foreground')}>Today</Link>{WORKSPACE_PRESENTATION_SURFACES.filter(surface=>surface.id!=='today').map(surface=><MobileDomain key={surface.id} id={surface.id} label={surface.label} pathname={pathname} onNavigate={()=>onOpenChange(false)}/>)}</nav></SheetContent></Sheet>;
}

function CarezTopShell({userName,logoUrl,pathname,onOpenCommand}:{userName:string;logoUrl:string;pathname:string;onOpenCommand:()=>void}){
  const [mobileOpen,setMobileOpen]=useState(false);
  return <header className="carez-masthead flex min-h-14 items-center gap-2 border-b border-border px-4 xl:px-6"><Link href="/" prefetch={false} aria-label="Carez home" className="carez-brand shrink-0"><img src={logoUrl} alt="Company logo"/><span>CAREZ</span></Link><DesktopNavigation pathname={pathname}/><div className="ml-auto flex items-center gap-1.5"><Button type="button" variant="ghost" size="sm" onClick={onOpenCommand} aria-label="Search Carez" className="gap-2 text-muted-foreground"><Search className="size-4"/><span className="hidden xl:inline">Search</span><kbd className="hidden text-[10px] text-muted-foreground xl:inline">⌘K</kbd></Button><Link href="/settings" prefetch={false} aria-label={`Settings for ${userName}`} className="carez-account"><span>{userName.trim().charAt(0).toUpperCase()||'C'}</span><span className="hidden xl:inline">{userName}</span></Link><Button type="button" variant="ghost" size="icon" className="xl:hidden" aria-label="Open menu" onClick={()=>setMobileOpen(true)}><Menu/></Button></div><MobileNavigation open={mobileOpen} onOpenChange={setMobileOpen} pathname={pathname}/></header>;
}

function CarezCommandMenu({open,onOpenChange,onNavigate,projects}:{open:boolean;onOpenChange:(open:boolean)=>void;onNavigate:(href:string)=>void;projects:ProjectOption[]}){
  return <CommandDialog open={open} onOpenChange={onOpenChange} title="Search Carez" description="Find a project or operating surface"><Command><CommandInput placeholder="Search Carez..." autoFocus/><CommandList className="max-h-[min(65vh,32rem)]"><CommandEmpty>No matching result.</CommandEmpty><CommandGroup heading="Surfaces and tools">{NAVIGATION_DESTINATIONS.map(destination=><CommandItem key={destination.id} value={`${destination.label} ${destination.hint}`} onSelect={()=>onNavigate(destination.href)}><span className="font-medium">{destination.label}</span></CommandItem>)}</CommandGroup>{projects.length?<CommandGroup heading="Projects">{projects.map(project=><CommandItem key={project.id} value={`${project.jobNumber} ${project.name} ${project.location}`} onSelect={()=>onNavigate(`/projects/${encodeURIComponent(project.id)}`)}><BriefcaseBusiness/><span className="truncate font-medium">{project.jobNumber?`${project.jobNumber} · `:''}{project.name}</span></CommandItem>)}</CommandGroup>:null}</CommandList></Command></CommandDialog>;
}

function CarezProjectPicker({open,onOpenChange,projects,activeProjectId,onSelect}:{open:boolean;onOpenChange:(open:boolean)=>void;projects:ProjectOption[];activeProjectId:string;onSelect:(projectId:string)=>void}){
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" className="w-[92vw] gap-0 p-0 sm:max-w-md"><SheetHeader className="border-b border-border"><SheetTitle>Switch project</SheetTitle></SheetHeader><Command className="min-h-0 flex-1 rounded-none"><CommandInput placeholder="Search project name or job number..." autoFocus/><CommandList className="max-h-none flex-1"><CommandEmpty>No accessible project found.</CommandEmpty><CommandGroup heading="Projects">{projects.map(project=><CommandItem key={project.id} value={`${project.jobNumber} ${project.name} ${project.location}`} data-checked={project.id===activeProjectId} onSelect={()=>onSelect(project.id)}><BriefcaseBusiness/><span className="truncate font-medium">{project.jobNumber?`${project.jobNumber} · `:''}{project.name}</span></CommandItem>)}</CommandGroup></CommandList></Command></SheetContent></Sheet>;
}

export function AppShell({children,userName,immersive=false}:{children:React.ReactNode;userName:string;immersive?:boolean}){
  const pathname=usePathname(),router=useRouter(),supabase=useMemo(()=>createClient(),[]);
  const [commandOpen,setCommandOpen]=useState(false),[projectSwitcherOpen,setProjectSwitcherOpen]=useState(false),[logoUrl,setLogoUrl]=useState(FALLBACK_COMPANY_LOGO),[projects,setProjects]=useState<ProjectOption[]>([]);
  const workstation=isWorkstation(pathname),activeDestination=useMemo(()=>resolveActiveDestination(pathname),[pathname]),projectContext=useMemo(()=>resolveProjectRoute(pathname),[pathname]),activeProject=useMemo(()=>projectContext?projects.find(project=>project.id===projectContext.projectId)||null:null,[projectContext,projects]);
  useEffect(()=>{let cancelled=false;async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user||cancelled)return;const {data:profile}=await supabase.from('profiles').select('company_id').eq('id',user.id).maybeSingle();if(!profile?.company_id||cancelled)return;const companyId=String(profile.company_id);const [branding,projectRows]=await Promise.all([supabase.from('company_branding').select('logo_path').eq('company_id',companyId).maybeSingle(),supabase.from('projects').select('id,job_number,name,status,address,city,state,created_at').eq('company_id',companyId).order('created_at',{ascending:false})]);if(cancelled)return;setLogoUrl(companyLogoPublicUrl(supabase,branding.data?.logo_path||null));setProjects(((projectRows.data||[]) as ProjectRow[]).map(row=>({id:String(row.id),jobNumber:row.job_number||'',name:row.name||'Untitled project',status:row.status||null,location:[row.address,row.city,row.state].filter(Boolean).join(', ')})));}void load();const onBranding=(event:Event)=>setLogoUrl(companyLogoPublicUrl(supabase,(event as CustomEvent<{logoPath?:string|null}>).detail?.logoPath||null));window.addEventListener(COMPANY_BRANDING_CHANGED_EVENT,onBranding);return()=>{cancelled=true;window.removeEventListener(COMPANY_BRANDING_CHANGED_EVENT,onBranding)};},[supabase]);
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setCommandOpen(value=>!value)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);
  useEffect(()=>setProjectSwitcherOpen(false),[pathname]);
  if(immersive)return <div className="min-h-svh bg-background text-foreground">{children}</div>;
  const navigate=(href:string)=>{setCommandOpen(false);router.push(href)};
  return <div className="carez-app flex min-h-svh flex-col bg-background text-foreground"><a href="#carez-workspace" className="carez-skip-link">Skip to workspace</a><BankSyncPulse/><OutlookSyncPulse/><div className="carez-shell relative z-40 shrink-0 bg-background"><CarezTopShell userName={userName} logoUrl={logoUrl} pathname={pathname} onOpenCommand={()=>setCommandOpen(true)}/>{projectContext&&activeProject?<CarezProjectContextBar projectName={activeProject.name} projectDetail={activeProject.jobNumber||activeProject.location||'Project'} workspaceLabel={projectContext.workspaceLabel} onOpenProjectSwitcher={()=>setProjectSwitcherOpen(true)}/>:null}</div><main id="carez-workspace" tabIndex={-1} aria-label={activeDestination?.label||'Carez workspace'} className={workstation?'carez-workstation min-h-0 min-w-0 flex-1 overflow-hidden':'carez-workspace min-h-0 min-w-0 flex-1 overflow-auto bg-background'}>{children}</main><CarezCommandMenu open={commandOpen} onOpenChange={setCommandOpen} onNavigate={navigate} projects={projects}/>{projectContext&&activeProject?<CarezProjectPicker open={projectSwitcherOpen} onOpenChange={setProjectSwitcherOpen} projects={projects} activeProjectId={activeProject.id} onSelect={projectId=>{setProjectSwitcherOpen(false);router.push(buildProjectSwitchHref(pathname,projectId))}}/>:null}</div>;
}
