'use client';

import Link from 'next/link';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import {Banknote,BriefcaseBusiness,Building2,Calculator,CalendarDays,ChevronRight,ClipboardCheck,ClipboardList,CreditCard,FileText,Gauge,Hammer,HardHat,Home,Inbox,Key,Landmark,Library,ListChecks,Menu,Moon,Package,Receipt,ReceiptText,Ruler,Search,Settings,ShieldCheck,ShoppingCart,Sliders,Sun,TrendingUp,Users,Wallet,Wrench} from 'lucide-react';
import {BrandLogo} from '@/components/brand/BrandLogo';
import {useCarezAppearance} from '@/components/carez/appearance-provider';
import {CarezProjectContextBar} from '@/components/carez/project-context';
export {CarezProjectSwitcher} from '@/components/carez/project-context';
import {Button} from '@/components/ui/button';
import {Command,CommandDialog,CommandEmpty,CommandGroup,CommandInput,CommandItem,CommandList} from '@/components/ui/command';
import {Sheet,SheetContent,SheetHeader,SheetTitle} from '@/components/ui/sheet';
import {cn} from '@/lib/utils';
import {createClient} from '@/lib/supabase/client';
import {COMPANY_BRANDING_CHANGED_EVENT,FALLBACK_COMPANY_LOGO,companyLogoPublicUrl} from '@/lib/companyBranding';
import {WORKSPACE_PRESENTATION_SURFACES,getDestinationById,navigationCommandValue,resolveActiveDestination,resolveActiveWorkspacePresentationSurface,resolveProjectRoute,buildProjectSwitchHref,type NavigationDestination,type WorkspacePresentationSurface,type WorkspaceSurfaceId} from '@/lib/ui/navigation';

type ProjectOption={id:string;jobNumber:string;name:string;status:string|null;location:string};
type ProjectRow={id:string;job_number:string|null;name:string|null;status:string|null;address:string|null;city:string|null;state:string|null};
const DOMAIN_ICONS={today:Home,preconstruction:Building2,projects:BriefcaseBusiness,finance:Landmark,system:Settings} as const;
const DESTINATION_ICONS={home:Home,reports:FileText,users:Users,inbox:Inbox,trending:TrendingUp,ruler:Ruler,calculator:Calculator,file:FileText,shield:ShieldCheck,library:Library,gauge:Gauge,briefcase:BriefcaseBusiness,'clipboard-check':ClipboardCheck,calendar:CalendarDays,'list-checks':ListChecks,package:Package,'clipboard-list':ClipboardList,hammer:Hammer,'hard-hat':HardHat,key:Key,wrench:Wrench,'receipt-text':ReceiptText,wallet:Wallet,'credit-card':CreditCard,landmark:Landmark,banknote:Banknote,receipt:Receipt,sliders:Sliders,'shopping-cart':ShoppingCart,settings:Settings} as const;
const DOMAIN_DECK_STYLES=`
@keyframes carez-domain-deck-in{from{opacity:0;transform:translateX(-4px);clip-path:inset(0 0 0 10px)}to{opacity:1;transform:translateX(0);clip-path:inset(0)}}
@keyframes carez-domain-deck-out{from{opacity:1;transform:translateX(0)}to{opacity:0;transform:translateX(-2px)}}
@keyframes carez-domain-row-in{from{opacity:0;transform:translateX(-4px)}to{opacity:1;transform:translateX(0)}}
@keyframes carez-domain-content-in{from{opacity:0;transform:translateX(2px)}to{opacity:1;transform:translateX(0)}}
.carez-domain-deck{animation:carez-domain-deck-in 220ms cubic-bezier(.16,1,.3,1) both}
.carez-domain-deck-exit{animation:carez-domain-deck-out 120ms cubic-bezier(.16,1,.3,1) both}
.carez-domain-row{animation:carez-domain-row-in 160ms cubic-bezier(.16,1,.3,1) both;animation-delay:calc(var(--carez-row-index)*18ms + 34ms)}
.carez-domain-content-switch{animation:carez-domain-content-in 100ms cubic-bezier(.16,1,.3,1) both}
.carez-domain-content-switch .carez-domain-row{animation:none}
.carez-projects-deck{animation:carez-domain-deck-in 220ms cubic-bezier(.16,1,.3,1) both}
.carez-projects-deck-exit{animation:carez-domain-deck-out 120ms cubic-bezier(.16,1,.3,1) both}
.carez-projects-menu-row{animation:carez-domain-row-in 160ms cubic-bezier(.16,1,.3,1) both;animation-delay:calc(var(--carez-row-index)*18ms + 34ms)}
@media (prefers-reduced-motion:reduce){.carez-domain-deck,.carez-domain-deck-exit,.carez-projects-deck,.carez-projects-deck-exit,.carez-projects-menu-row,.carez-domain-row,.carez-domain-row[data-active="true"],.carez-domain-content-switch{animation-duration:1ms;animation-delay:0ms}.carez-domain-row .carez-domain-arrow{transform:none!important}}
`;
const PRIMARY_DESTINATIONS:Record<WorkspaceSurfaceId,readonly string[]>={today:['today','reports'],preconstruction:['leads','lead-inbox','takeoff','estimates','proposals'],projects:['projects','schedule','field','production','documents'],finance:['billing','payables','costs','cashflow','banking'],system:['settings','crew','employee-access','equipment']};
const allDestinationsFor=(surface:WorkspacePresentationSurface)=>surface.sections.flatMap(section=>section.destinations.map(destination=>getDestinationById(destination.id)).filter((destination):destination is NavigationDestination=>Boolean(destination)&&destination?.id!=='pour-control'));
const destinationsFor=(surface:WorkspacePresentationSurface)=>PRIMARY_DESTINATIONS[surface.id].map(id=>getDestinationById(id)).filter((destination):destination is NavigationDestination=>Boolean(destination));
const isWorkstation=(pathname:string)=>{const segment=pathname.match(/^\/takeoff\/([^/]+)/)?.[1];return Boolean(segment&&!['assemblies','intelligence','plans'].includes(segment));};
const railButtonClass=(active:boolean)=>cn('carez-nav-button relative inline-flex h-8 shrink-0 items-center gap-2 rounded-md border border-[var(--shell-border)] bg-[var(--shell-surface)] px-3 text-xs font-semibold text-[var(--shell-muted)] outline-none transition-colors hover:bg-[var(--shell-accent)] hover:text-[var(--shell-foreground)] focus-visible:ring-2 focus-visible:ring-[var(--pt-logo)]',active&&'carez-nav-button-active text-[var(--shell-foreground)]');

function CarezDomainDeck({domain,pathname,phase,contentVersion,left,onClose,onNavigate,triggerRefs,projects}:{domain:WorkspacePresentationSurface|null;pathname:string;phase:'open'|'closing';contentVersion:number;left:number;onClose:()=>void;onNavigate:(href:string)=>void;triggerRefs:React.MutableRefObject<Record<string,HTMLButtonElement|null>>;projects:ProjectOption[]}){
  const deckRef=useRef<HTMLElement>(null),domainRef=useRef(domain),closeRef=useRef(onClose),activeId=resolveActiveDestination(pathname)?.id;
  domainRef.current=domain;closeRef.current=onClose;
  useEffect(()=>{if(!domainRef.current)return;const outside=(event:PointerEvent)=>{const target=event.target as Node,currentDomain=domainRef.current;if(!deckRef.current?.contains(target)&&!triggerRefs.current[currentDomain?.id||'']?.contains(target))closeRef.current();};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')closeRef.current();};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);const frame=requestAnimationFrame(()=>deckRef.current?.querySelector<HTMLAnchorElement>('[data-domain-link]')?.focus());return()=>{cancelAnimationFrame(frame);document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape);};},[triggerRefs,domain?.id,contentVersion]);
  if(!domain)return null;
  return <DomainMegaMenu deckRef={deckRef} domain={domain} pathname={pathname} phase={phase} contentVersion={contentVersion} left={left} onNavigate={onNavigate} projects={projects}/>;
}

function DomainMegaMenu({deckRef,domain,pathname,phase,contentVersion,left,onNavigate,projects}:{deckRef:React.RefObject<HTMLElement|null>;domain:WorkspacePresentationSurface;pathname:string;phase:'open'|'closing';contentVersion:number;left:number;onNavigate:(href:string)=>void;projects:ProjectOption[]}){
  const destinations=destinationsFor(domain);
  const activeId=resolveActiveDestination(pathname)?.id;
  const contextual:Record<WorkspaceSurfaceId,{heading:string;empty:string;items:{badge:string;label:string;href:string}[]}>= {
    today:{heading:'Recent Reports',empty:'No report history loaded.',items:[{badge:'SAMPLE',label:'Daily operations report',href:'/reports'},{badge:'SAMPLE',label:'Project health summary',href:'/reports'},{badge:'SAMPLE',label:'Cash position recap',href:'/reports'}]},
    preconstruction:{heading:'Recent Bids',empty:'No bid history loaded.',items:[{badge:'SAMPLE',label:'Eastside Pump Station estimate',href:'/estimates'},{badge:'SAMPLE',label:'Cedar Plaza proposal',href:'/proposals'},{badge:'SAMPLE',label:'Warehouse slab estimate',href:'/estimates'}]},
    projects:{heading:'Recent Jobs',empty:'No recent jobs yet.',items:projects.slice(0,3).map(project=>({badge:project.jobNumber||'JOB',label:project.name,href:`/projects/${encodeURIComponent(project.id)}`}))},
    finance:{heading:'Pending Approvals',empty:'No approvals loaded.',items:[{badge:'SAMPLE',label:'Invoice #4022',href:'/billing'},{badge:'SAMPLE',label:'Change Order - Job 2026',href:'/change-orders'}]},
    system:{heading:'Quick Actions',empty:'No quick actions available.',items:[{badge:'+',label:'Invite new employee',href:'/crew/access'},{badge:'+',label:'Add equipment record',href:'/equipment'}]},
  };
  const context=contextual[domain.id];
  return <aside ref={deckRef} id="carez-domain-deck" aria-label={`${domain.label} navigation`} style={{left}} className={cn('fixed top-14 z-50 max-h-[calc(100svh-4rem)] w-[min(502px,calc(100vw-2rem))] overflow-hidden rounded-md border border-[#D4DBD7] bg-[#FFFFFF] text-[#171B19] shadow-md dark:border-[#343A3F] dark:bg-[#1E2123] dark:text-[#F4F6F5]',phase==='closing'?'carez-projects-deck-exit':'carez-projects-deck')}>
    <style>{DOMAIN_DECK_STYLES}</style>
    <div key={contentVersion} className="grid grid-cols-[250px_250px] overflow-hidden rounded-md p-0">
      <nav aria-label={`${domain.label} destinations`} className="max-h-[calc(100svh-4rem)] space-y-1 overflow-y-auto p-3" onKeyDown={event=>{if(!['ArrowDown','ArrowUp'].includes(event.key))return;const links=[...event.currentTarget.querySelectorAll<HTMLAnchorElement>('[data-domain-link]')],index=links.indexOf(document.activeElement as HTMLAnchorElement);if(index<0)return;event.preventDefault();links[(index+(event.key==='ArrowDown' ? 1 : -1)+links.length)%links.length]?.focus();}}>
        {destinations.map((destination,index)=>{const Icon=DESTINATION_ICONS[destination.icon],active=activeId===destination.id;return <Link key={destination.id} data-domain-link data-active={active} style={{'--carez-row-index':index} as React.CSSProperties} href={destination.href} prefetch={false} aria-current={active?'page':undefined} onClick={event=>{event.preventDefault();onNavigate(destination.href);}} className={cn('carez-projects-menu-row group flex min-h-12 items-center gap-2 border-l-2 border-l-transparent px-2 py-1.5 outline-none transition-colors hover:bg-[#E9EDEA] focus-visible:border-l-[#007A52] focus-visible:bg-[#E9EDEA] dark:hover:bg-[#32383C] dark:focus-visible:border-l-[#009966] dark:focus-visible:bg-[#32383C]',active&&'border-l-[#007A52] bg-[#009966]/10 hover:bg-[#009966]/10 focus-visible:bg-[#009966]/10 dark:border-l-[#009966] dark:bg-[#009966]/10 dark:hover:bg-[#009966]/10 dark:focus-visible:bg-[#009966]/10')}>
          <Icon aria-hidden="true" className="size-4 shrink-0 text-[#525C57] dark:text-[#B6BEBA]"/>
          <span className="min-w-0 flex-1"><span className="block text-sm font-medium text-[#171B19] dark:text-[#F4F6F5]">{destination.label}</span><span className="block truncate text-xs text-muted-foreground">{destination.id==='costs'?'Track labor and material expenses':destination.hint}</span></span>
          {domain.id==='projects'&&destination.id==='field'?<span aria-label="Sample field alert indicator" title="Sample alert indicator" className="rounded-full bg-[#E06B74] px-1.5 py-0.5 text-[10px] font-bold text-white">!</span>:null}
          {domain.id==='projects'&&destination.id==='schedule'?<kbd className="rounded border border-[#D4DBD7] bg-[#EFF2F0] px-1 font-mono text-[10px] text-muted-foreground dark:border-[#343A3F] dark:bg-[#25292C]">⌘S</kbd>:null}
        </Link>;})}
      </nav>
      <div className="min-w-0 border-l border-[#D4DBD7] bg-[#F5F7F6] p-4 dark:border-[#343A3F] dark:bg-[#181A1B]">
        <h2 className="mb-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{context.heading}</h2>
        {context.items.length?<ul className="space-y-1">{context.items.map((item,index)=><li key={`${item.href}-${index}`}><Link href={item.href} prefetch={false} onClick={event=>{event.preventDefault();onNavigate(item.href);}} className="flex min-w-0 items-center gap-2 rounded-sm px-1 py-2 text-sm outline-none hover:bg-[#E9EDEA] focus-visible:outline-1 focus-visible:outline-[#007A52] dark:hover:bg-[#25292C] dark:focus-visible:outline-[#009966]"><span className="shrink-0 rounded-sm border border-[#D4DBD7] px-1.5 py-0.5 font-mono text-[10px] dark:border-[#343A3F]">{item.badge}</span><span className="min-w-0 truncate hover:underline">{item.label}</span></Link></li>)}</ul>:<p className="text-xs text-muted-foreground">{context.empty}</p>}
      </div>
    </div>
  </aside>;
}

function CarezCommandRail({pathname,onNavigate,userName,onOpenCommand,onOpenMobile,projects}:{pathname:string;onNavigate:(href:string)=>void;userName:string;onOpenCommand:()=>void;onOpenMobile:()=>void;projects:ProjectOption[]}){
  const {resolvedTheme,setThemePreference}=useCarezAppearance();
  const [deck,setDeck]=useState<{id:WorkspaceSurfaceId;phase:'open'|'closing';contentVersion:number}|null>(null),closeTimer=useRef<ReturnType<typeof setTimeout>|null>(null),triggerRefs=useRef<Record<string,HTMLButtonElement|null>>({}),activeDomain=resolveActiveWorkspacePresentationSurface(pathname),domain=deck?WORKSPACE_PRESENTATION_SURFACES.find(item=>item.id===deck.id)||null:null;
  const [deckLeft,setDeckLeft]=useState(16);
  const positionDeck=useCallback((id:WorkspaceSurfaceId)=>{const trigger=triggerRefs.current[id];if(!trigger)return;const width=502;setDeckLeft(Math.max(16,Math.min(trigger.getBoundingClientRect().left,window.innerWidth-width-16)));},[]);
  useEffect(()=>{if(!deck)return;const reposition=()=>positionDeck(deck.id);window.addEventListener('resize',reposition);return()=>window.removeEventListener('resize',reposition);},[deck?.id,positionDeck]);
  useEffect(()=>{if(deck?.id!=='projects'||deck.phase!=='open')return;const shortcut=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='s'){event.preventDefault();onNavigate('/schedule');setDeck(null);}};window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut);},[deck?.id,deck?.phase,onNavigate]);
  const cancelClose=useCallback(()=>{if(closeTimer.current){clearTimeout(closeTimer.current);closeTimer.current=null;}},[]);
  const closeDeck=useCallback(()=>{if(!deck||deck.phase==='closing')return;const closingId=deck.id;setDeck(current=>current?{...current,phase:'closing'}:null);closeTimer.current=setTimeout(()=>setDeck(current=>{if(!current||current.phase!=='closing'||current.id!==closingId)return current;requestAnimationFrame(()=>triggerRefs.current[closingId]?.focus());return null;}),120);},[deck]);
  useEffect(()=>()=>cancelClose(),[cancelClose]);
  const selectDomain=(id:WorkspaceSurfaceId)=>{if(deck?.id===id&&deck.phase==='open'){closeDeck();return;}cancelClose();positionDeck(id);setDeck(current=>({id,phase:'open',contentVersion:(current?.contentVersion||0)+(current?1:0)}));};
  return <>
    <header aria-label="Pourtrace global navigation" className="carez-command-bar carez-top-nav sticky top-0 z-40 flex h-14 w-full shrink-0 items-center justify-between gap-2 border-b border-border bg-background px-3 text-[var(--shell-foreground)] lg:grid lg:grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)] lg:px-4">
      <div className="flex min-w-0 items-center gap-1">
        <Button type="button" variant="ghost" size="icon" className="shrink-0 lg:hidden" aria-label="Open navigation" onClick={onOpenMobile}><Menu className="size-4"/></Button>
        <Link href="/" prefetch={false} aria-label="Pourtrace home" className="pt-brand-logo-link relative inline-flex shrink-0 items-center outline-none focus-visible:ring-2 focus-visible:ring-[var(--pt-logo)]"><BrandLogo size="md" className="max-sm:h-[31px] max-sm:w-[128px]"/></Link>
      </div>
      <nav aria-label="Primary domains" className="hidden min-w-0 items-center justify-center gap-1 lg:flex">{WORKSPACE_PRESENTATION_SURFACES.map(item=>{const Icon=DOMAIN_ICONS[item.id];return <button key={item.id} ref={element=>{triggerRefs.current[item.id]=element;}} type="button" aria-label={`${item.label} navigation`} aria-expanded={deck?.phase==='open'&&deck.id===item.id} aria-controls="carez-domain-deck" onClick={()=>selectDomain(item.id)} className={railButtonClass(activeDomain?.id===item.id)}><Icon className="size-3.5"/><span>{item.label}</span></button>;})}</nav>
      <div className="flex shrink-0 items-center justify-end gap-1"><Button type="button" variant="ghost" size="sm" onClick={onOpenCommand} aria-label="Search Pourtrace" className="gap-2 text-muted-foreground"><Search className="size-4"/><span className="hidden xl:inline">Search</span><kbd className="hidden text-[10px] text-muted-foreground 2xl:inline">⌘K</kbd></Button><Button type="button" variant="ghost" size="icon" onClick={()=>setThemePreference(resolvedTheme==='dark'?'light':'dark')} aria-label={resolvedTheme==='dark'?'Switch to light mode':'Switch to dark mode'} title={resolvedTheme==='dark'?'Switch to light mode':'Switch to dark mode'}>{resolvedTheme==='dark'?<Sun className="size-4"/>:<Moon className="size-4"/>}</Button><Link href="/settings" prefetch={false} aria-label={`Settings for ${userName}`} className="flex size-8 items-center justify-center border-l border-border text-xs font-medium text-muted-foreground outline-none hover:bg-accent/60 focus-visible:ring-[3px] focus-visible:ring-ring/50">{userName.trim().charAt(0).toUpperCase()||'C'}</Link></div>
    </header>
    <CarezDomainDeck domain={domain} pathname={pathname} phase={deck?.phase||'open'} contentVersion={deck?.contentVersion||0} left={deckLeft} onClose={closeDeck} onNavigate={href=>{closeDeck();onNavigate(href);}} triggerRefs={triggerRefs} projects={projects}/>
  </>;
}
function MobileNavigation({open,onOpenChange,pathname,onNavigate}:{open:boolean;onOpenChange:(open:boolean)=>void;pathname:string;onNavigate:(href:string)=>void}){
  const activeSurface=resolveActiveWorkspacePresentationSurface(pathname)?.id;
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="left" className="w-[90vw] max-w-sm gap-0 rounded-none p-0 lg:hidden"><SheetHeader className="border-b border-border"><SheetTitle>Navigation</SheetTitle></SheetHeader><nav aria-label="Mobile primary navigation" className="min-h-0 overflow-y-auto py-2">{WORKSPACE_PRESENTATION_SURFACES.map(domain=><Link key={domain.id} href={domain.href} prefetch={false} aria-current={activeSurface===domain.id?'page':undefined} onClick={event=>{event.preventDefault();onOpenChange(false);onNavigate(domain.href);}} className={cn('flex min-h-14 items-center justify-between border-b border-border px-4 text-sm font-semibold outline-none hover:bg-accent/60 focus-visible:bg-accent focus-visible:ring-[3px] focus-visible:ring-ring/50',activeSurface===domain.id&&'border-l-2 border-l-primary bg-primary/5 text-primary')}>{domain.label}<ChevronRight className="size-4" aria-hidden="true"/></Link>)}</nav><p className="border-t border-border px-4 py-3 text-xs text-muted-foreground">Use Search for a specific tool or record.</p></SheetContent></Sheet>;
}

function CarezCommandMenu({open,onOpenChange,onNavigate,projects,pathname}:{open:boolean;onOpenChange:(open:boolean)=>void;onNavigate:(href:string)=>void;projects:ProjectOption[];pathname:string}){
  const activeId=resolveActiveDestination(pathname)?.id;
  return <CommandDialog open={open} onOpenChange={onOpenChange} title="Search Pourtrace" description="Navigate Pourtrace operating surfaces"><Command><CommandInput placeholder="Search Pourtrace..." autoFocus/><CommandList className="max-h-[min(65vh,32rem)]"><CommandEmpty>No matching result.</CommandEmpty>{WORKSPACE_PRESENTATION_SURFACES.map(domain=><CommandGroup key={domain.id} heading={domain.label}>{allDestinationsFor(domain).map(destination=><CommandItem key={destination.id} value={navigationCommandValue(destination)} onSelect={()=>onNavigate(destination.href)}><span className={cn('font-medium',activeId===destination.id&&'text-primary')}>{destination.label}</span></CommandItem>)}</CommandGroup>)}{projects.length?<CommandGroup heading="Projects">{projects.map(project=><CommandItem key={project.id} value={`${project.jobNumber} ${project.name} ${project.location}`} onSelect={()=>onNavigate(`/projects/${encodeURIComponent(project.id)}`)}><BriefcaseBusiness/><span className="truncate font-medium">{project.jobNumber?`${project.jobNumber} · `:''}{project.name}</span></CommandItem>)}</CommandGroup>:null}</CommandList></Command></CommandDialog>;
}

function CarezProjectPicker({open,onOpenChange,projects,activeProjectId,onSelect}:{open:boolean;onOpenChange:(open:boolean)=>void;projects:ProjectOption[];activeProjectId:string;onSelect:(projectId:string)=>void}){
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" className="w-[92vw] gap-0 p-0 sm:max-w-md"><SheetHeader className="border-b border-border"><SheetTitle>Switch project</SheetTitle></SheetHeader><Command className="min-h-0 flex-1 rounded-none"><CommandInput placeholder="Search project name or job number..." autoFocus/><CommandList className="max-h-none flex-1"><CommandEmpty>No accessible project found.</CommandEmpty><CommandGroup heading="Projects">{projects.map(project=><CommandItem key={project.id} value={`${project.jobNumber} ${project.name} ${project.location}`} data-checked={project.id===activeProjectId} onSelect={()=>onSelect(project.id)}><BriefcaseBusiness/><span className="truncate font-medium">{project.jobNumber?`${project.jobNumber} · `:''}{project.name}</span></CommandItem>)}</CommandGroup></CommandList></Command></SheetContent></Sheet>;
}

export function AppShell({children,userName,immersive=false}:{children:React.ReactNode;userName:string;immersive?:boolean}){
  const pathname=usePathname(),router=useRouter(),supabase=useMemo(()=>createClient(),[]);
  const [commandOpen,setCommandOpen]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[projectSwitcherOpen,setProjectSwitcherOpen]=useState(false),[logoUrl,setLogoUrl]=useState(FALLBACK_COMPANY_LOGO),[projects,setProjects]=useState<ProjectOption[]>([]);
  const workstation=isWorkstation(pathname),activeDestination=useMemo(()=>resolveActiveDestination(pathname),[pathname]),projectContext=useMemo(()=>resolveProjectRoute(pathname),[pathname]),activeProject=useMemo(()=>projectContext?projects.find(project=>project.id===projectContext.projectId)||null:null,[projectContext,projects]);
  useEffect(()=>{let cancelled=false;async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user||cancelled)return;const {data:profile}=await supabase.from('profiles').select('company_id').eq('id',user.id).maybeSingle();if(!profile?.company_id||cancelled)return;const companyId=String(profile.company_id);const [branding,projectRows]=await Promise.all([supabase.from('company_branding').select('logo_path').eq('company_id',companyId).maybeSingle(),supabase.from('projects').select('id,job_number,name,status,address,city,state,created_at').eq('company_id',companyId).order('created_at',{ascending:false})]);if(cancelled)return;setLogoUrl(companyLogoPublicUrl(supabase,branding.data?.logo_path||null));setProjects(((projectRows.data||[]) as ProjectRow[]).map(row=>({id:String(row.id),jobNumber:row.job_number||'',name:row.name||'Untitled project',status:row.status||null,location:[row.address,row.city,row.state].filter(Boolean).join(', ')})));}void load();const onBranding=(event:Event)=>setLogoUrl(companyLogoPublicUrl(supabase,(event as CustomEvent<{logoPath?:string|null}>).detail?.logoPath||null));window.addEventListener(COMPANY_BRANDING_CHANGED_EVENT,onBranding);return()=>{cancelled=true;window.removeEventListener(COMPANY_BRANDING_CHANGED_EVENT,onBranding)};},[supabase]);
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setCommandOpen(value=>!value)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);
  useEffect(()=>{setMobileOpen(false);setProjectSwitcherOpen(false);},[pathname]);
  if(immersive)return <div className="min-h-svh bg-background text-foreground">{children}</div>;
  const navigate=(href:string)=>{setCommandOpen(false);setMobileOpen(false);router.push(href)};
  return <div className="carez-app flex min-h-svh flex-col bg-background text-foreground"><a href="#carez-workspace" className="carez-skip-link">Skip to workspace</a><CarezCommandRail pathname={pathname} onNavigate={navigate} userName={userName} onOpenCommand={()=>setCommandOpen(true)} onOpenMobile={()=>setMobileOpen(true)} projects={projects}/><div className="flex min-w-0 flex-1 flex-col">{projectContext&&activeProject?<CarezProjectContextBar projectName={activeProject.name} projectDetail={activeProject.jobNumber||activeProject.location||'Project'} workspaceLabel={projectContext.workspaceLabel} onOpenProjectSwitcher={()=>setProjectSwitcherOpen(true)}/>:null}<main id="carez-workspace" tabIndex={-1} aria-label={activeDestination?.label||'Pourtrace workspace'} className={workstation?'carez-workstation min-h-0 min-w-0 flex-1 overflow-hidden':'carez-workspace min-h-0 min-w-0 flex-1 overflow-auto bg-background'}>{children}</main></div><MobileNavigation open={mobileOpen} onOpenChange={setMobileOpen} pathname={pathname} onNavigate={navigate}/><CarezCommandMenu open={commandOpen} onOpenChange={setCommandOpen} onNavigate={navigate} projects={projects} pathname={pathname}/>{projectContext&&activeProject?<CarezProjectPicker open={projectSwitcherOpen} onOpenChange={setProjectSwitcherOpen} projects={projects} activeProjectId={activeProject.id} onSelect={projectId=>{setProjectSwitcherOpen(false);router.push(buildProjectSwitchHref(pathname,projectId))}}/>:null}</div>;
}
