'use server';
import {revalidatePath} from 'next/cache';
import {createClient} from '@/lib/supabase/server';
async function ctx(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Not signed in');const {data:p}=await supabase.from('profiles').select('company_id,role').eq('id',user.id).single();if(!p?.company_id||p.role==='employee')throw new Error('Owner access required');return{supabase,user,companyId:p.company_id};}
const s=(fd:FormData,k:string)=>String(fd.get(k)||'').trim();const n=(fd:FormData,k:string)=>{const raw=s(fd,k);if(!raw)return null;const v=Number(raw.replace(/[$,% ,]/g,''));return Number.isFinite(v)?v:null;};const score=(fd:FormData,k:string)=>Math.min(5,Math.max(1,Number(fd.get(k)||3)));
const refresh=()=>{for(const p of ['/bid-intelligence','/leads','/estimates','/proposals','/'])revalidatePath(p);};

export async function saveBidProfile(fd:FormData){const leadId=s(fd,'lead_id');if(!leadId)throw new Error('Choose a lead.');const {supabase,user,companyId}=await ctx();const {data:lead}=await supabase.from('leads').select('id').eq('id',leadId).eq('company_id',companyId).single();if(!lead)throw new Error('Lead not found.');const patch={company_id:companyId,lead_id:leadId,bid_type:s(fd,'bid_type')||'private_competitive',relationship_strength:s(fd,'relationship_strength')||'new',estimated_competitor_count:n(fd,'estimated_competitor_count'),customer_budget:n(fd,'customer_budget'),customer_budget_source:s(fd,'customer_budget_source')||null,project_fit_score:score(fd,'project_fit_score'),relationship_score:score(fd,'relationship_score'),scope_clarity_score:score(fd,'scope_clarity_score'),capacity_score:score(fd,'capacity_score'),margin_potential_score:score(fd,'margin_potential_score'),payment_confidence_score:score(fd,'payment_confidence_score'),competition_score:score(fd,'competition_score'),risk_score:score(fd,'risk_score'),estimator_effort_hours:n(fd,'estimator_effort_hours'),pursuit_decision:s(fd,'pursuit_decision')||'review',pass_reason:s(fd,'pass_reason')||null,created_by:user.id,updated_at:new Date().toISOString()};const {error}=await supabase.from('lead_bid_intelligence').upsert(patch,{onConflict:'lead_id'});if(error)throw new Error(error.message);refresh();}

export async function recordCompetitorFeedback(fd:FormData){const leadId=s(fd,'lead_id'),source=s(fd,'feedback_source');if(!leadId||!source)throw new Error('Choose a lead and feedback source.');const {supabase,user,companyId}=await ctx();const {error}=await supabase.from('bid_price_feedback').insert({company_id:companyId,lead_id:leadId,estimate_id:s(fd,'estimate_id')||null,feedback_source:source,competitor_name:s(fd,'competitor_name')||null,competitor_price:n(fd,'competitor_price'),scope_comparable:s(fd,'scope_comparable')||'unknown',note:s(fd,'note')||null,created_by:user.id});if(error)throw new Error(error.message);refresh();}

export async function addScopeComparisonItem(fd:FormData){const leadId=s(fd,'lead_id'),feedbackId=s(fd,'bid_price_feedback_id'),description=s(fd,'description');if(!leadId||!feedbackId||!description)throw new Error('Choose competitor feedback and enter the scope item.');const {supabase,user,companyId}=await ctx();const {error}=await supabase.from('bid_scope_comparison_items').insert({company_id:companyId,lead_id:leadId,estimate_id:s(fd,'estimate_id')||null,bid_price_feedback_id:feedbackId,description,carez_status:s(fd,'carez_status')||'included',competitor_status:s(fd,'competitor_status')||'unknown',equalization_amount:n(fd,'equalization_amount')||0,note:s(fd,'note')||null,sort_order:Date.now()%1000000,created_by:user.id});if(error)throw new Error(error.message);refresh();}

export async function deleteScopeComparisonItem(fd:FormData){const id=s(fd,'item_id');if(!id)return;const {supabase,companyId}=await ctx();await supabase.from('bid_scope_comparison_items').delete().eq('id',id).eq('company_id',companyId);refresh();}

export async function addValueOption(fd:FormData){const leadId=s(fd,'lead_id'),name=s(fd,'name'),description=s(fd,'customer_description');if(!leadId||!name||!description)throw new Error('Choose a lead and describe the customer option.');const {supabase,user,companyId}=await ctx();const {error}=await supabase.from('bid_value_options').insert({company_id:companyId,lead_id:leadId,estimate_id:s(fd,'estimate_id')||null,name,customer_description:description,sell_price_change:n(fd,'sell_price_change')||0,company_cost_change:n(fd,'company_cost_change')||0,schedule_days_change:n(fd,'schedule_days_change')||0,function_quality_note:s(fd,'function_quality_note')||null,approval_required:s(fd,'approval_required')||null,status:'suggested',created_by:user.id});if(error)throw new Error(error.message);refresh();}

export async function updateValueOptionStatus(fd:FormData){const id=s(fd,'option_id'),status=s(fd,'status');if(!id||!['suggested','presented','accepted','rejected','withdrawn'].includes(status))return;const {supabase,companyId}=await ctx();const {error}=await supabase.from('bid_value_options').update({status,updated_at:new Date().toISOString()}).eq('id',id).eq('company_id',companyId);if(error)throw new Error(error.message);refresh();}

export async function recordBidFollowUp(fd:FormData){const leadId=s(fd,'lead_id'),note=s(fd,'note'),next=s(fd,'next_follow_up')||null;if(!leadId||!note)throw new Error('Choose a lead and record what happened.');const {supabase,user,companyId}=await ctx();const now=new Date().toISOString();const {error}=await supabase.from('lead_activities').insert({company_id:companyId,lead_id:leadId,activity_type:'follow_up',activity_date:now,note,next_follow_up:next,created_by:user.id});if(error)throw new Error(error.message);await supabase.from('leads').update({follow_up:next,status:'follow_up',updated_at:now}).eq('id',leadId).eq('company_id',companyId).not('status','in','("won","lost")');await supabase.from('lead_bid_intelligence').update({last_follow_up_at:now,updated_at:now}).eq('lead_id',leadId).eq('company_id',companyId);refresh();}

export async function markProposalSent(fd:FormData){const leadId=s(fd,'lead_id');if(!leadId)return;const {supabase,companyId}=await ctx();const now=new Date().toISOString();await supabase.from('lead_bid_intelligence').update({proposal_sent_at:now,updated_at:now}).eq('lead_id',leadId).eq('company_id',companyId);await supabase.from('leads').update({status:'proposal_sent',updated_at:now}).eq('id',leadId).eq('company_id',companyId);refresh();}

export async function recordBidOutcome(fd:FormData){const leadId=s(fd,'lead_id'),outcome=s(fd,'outcome');if(!leadId||!['won','lost','no_decision','withdrawn'].includes(outcome))throw new Error('Choose a bid outcome.');const {supabase,companyId}=await ctx();const lostReason=outcome==='lost'?(s(fd,'lost_reason')||'unknown'):null,note=s(fd,'outcome_note')||null;const {error}=await supabase.from('lead_bid_intelligence').update({outcome,lost_reason:lostReason,outcome_note:note,updated_at:new Date().toISOString()}).eq('lead_id',leadId).eq('company_id',companyId);if(error)throw new Error(error.message);if(outcome==='won'||outcome==='lost')await supabase.from('leads').update({status:outcome,updated_at:new Date().toISOString()}).eq('id',leadId).eq('company_id',companyId);refresh();}
