import { redirect } from 'next/navigation';
import { AppShell } from '@/components/AppShell';
import { Badge } from '@/components/ui/badge';
import { Button, buttonVariants } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { createClient } from '@/lib/supabase/server';
import { createPourPlan,updatePourPlan,addPourCostItem,addPourLaborItem,deletePourCostItem,recordPourAuthorization,closePourPlan } from './actions';

const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const num=(v:any)=>Number(v||0);
const today=()=>new Date().toISOString().slice(0,10);
const year=new Date().getFullYear();
const units=['LS','EA','CY','LF','SF','HR','DAY','TON','GAL'];
const selectClass='h-9 w-full rounded-md border border-input bg-background px-3 text-sm text-foreground outline-none transition-shadow focus:border-ring focus:ring-3 focus:ring-ring/20';

function Metric({label,value,detail,tone='default'}:{label:string;value:string;detail?:string;tone?:'default'|'success'|'warning'|'danger'}){
  return <div className={`rounded-lg border border-border bg-muted/20 p-3 ${tone==='success'?'text-success':tone==='warning'?'text-warning':tone==='danger'?'text-destructive':''}`}><div className="text-xs font-medium text-muted-foreground">{label}</div><div className="mt-1 text-lg font-semibold tabular-nums">{value}</div>{detail&&<div className="mt-1 text-xs text-muted-foreground">{detail}</div>}</div>;
}

export default async function PourControlPage(){
  const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
  const {data:profile}=await supabase.from('profiles').select('full_name,company_id').eq('id',user.id).single();
  if(!profile?.company_id)redirect('/login');
  const companyId=profile.company_id;

  const [{data:projects},{data:funding},{data:plans},{data:items},{data:reviews},{data:sections},{data:budgets},{data:changeOrders},{data:crew},{data:risks},{data:costCodes},{data:catalog}]=await Promise.all([
    supabase.from('projects').select('id,job_number,name,status').in('status',['active','on_hold']).order('job_number'),
    supabase.from('project_cash_funding_summary').select('*').in('status',['active','on_hold']).order('job_number'),
    supabase.from('pour_plan_financial_summary').select('*').order('scheduled_date',{ascending:true,nullsFirst:false}).order('name'),
    supabase.from('pour_cost_items').select('*').order('sort_order'),
    supabase.from('pour_authorization_snapshots').select('*').order('reviewed_at',{ascending:false}),
    supabase.from('project_budget_sections').select('id,budget_id,name,scope_type').order('sort_order'),
    supabase.from('project_budgets').select('id,project_id,status,budget_type,label').eq('status','active'),
    supabase.from('change_orders').select('id,project_id,co_number,title,status').eq('status','approved').order('requested_date'),
    supabase.from('crew_members').select('id,name,hourly_rate,internal_field_rate,is_owner,active').eq('active',true).order('name'),
    supabase.from('li_risk_classes').select('code,name').eq('company_id',companyId).eq('tax_year',year).eq('active',true).order('code'),
    supabase.from('cost_codes').select('id,code,name,cost_type,default_unit').eq('company_id',companyId).eq('active',true).order('sort_order'),
    supabase.from('cost_catalog_items').select('id,cost_code_id,name,default_unit,default_unit_cost,vendor_name').eq('company_id',companyId).eq('active',true).order('name')
  ]);

  const projectMap=new Map((projects||[]).map((p:any)=>[p.id,p]));
  const budgetProject=new Map((budgets||[]).map((b:any)=>[b.id,b.project_id]));
  const sectionOptions=(sections||[]).filter((s:any)=>budgetProject.has(s.budget_id)).map((s:any)=>({...s,project_id:budgetProject.get(s.budget_id)}));
  const itemsByPlan=new Map<string,any[]>();for(const i of items||[]){if(!itemsByPlan.has(i.pour_plan_id))itemsByPlan.set(i.pour_plan_id,[]);itemsByPlan.get(i.pour_plan_id)!.push(i);}
  const reviewsByPlan=new Map<string,any[]>();for(const r of reviews||[]){if(!reviewsByPlan.has(r.pour_plan_id))reviewsByPlan.set(r.pour_plan_id,[]);reviewsByPlan.get(r.pour_plan_id)!.push(r);}
  const latestReview=new Map<string,any>();for(const r of reviews||[]){if(!latestReview.has(r.pour_plan_id))latestReview.set(r.pour_plan_id,r);}
  const totalRisk=(funding||[]).reduce((s:number,f:any)=>s+num(f.carez_cash_at_risk_to_date),0);
  const totalProtected=(funding||[]).reduce((s:number,f:any)=>s+Math.max(0,num(f.project_funding_balance)),0);
  const holdPlans=(plans||[]).filter((p:any)=>p.status!=='completed'&&p.status!=='cancelled'&&p.system_recommendation==='hold').length;
  const openExposure=(plans||[]).filter((p:any)=>p.status!=='completed'&&p.status!=='cancelled').reduce((s:number,p:any)=>s+num(p.total_exposure_with_contingency),0);

  return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="mx-auto flex w-full max-w-screen-2xl flex-col gap-6">
    <header><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Field finance</div><h1 className="mt-1 text-2xl font-semibold tracking-tight">Pour Control</h1><p className="mt-1 max-w-4xl text-sm text-muted-foreground">Cash exposure, protected project funding and authorization before Carez commits to concrete, pumps, payroll and other pour costs.</p></header>

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Metric label="Protected Project Funding" value={money(totalProtected)} detail="Collected customer cash after sales-tax reserve, fees and incurred direct cost." tone="success"/>
      <Metric label="Carez Cash at Risk To Date" value={money(totalRisk)} detail="Direct job cost not yet covered by usable customer cash." tone={totalRisk>0?'danger':'success'}/>
      <Metric label="Open Pour Exposure" value={money(openExposure)} detail="Current planned pour costs including contingency."/>
      <Metric label="Cash Holds" value={String(holdPlans)} detail="Pour plans that currently need additional funding." tone={holdPlans>0?'warning':'success'}/>
    </div>

    <div className="rounded-lg border border-primary/20 bg-primary/5 px-4 py-3 text-sm text-muted-foreground"><strong className="text-foreground">Cash safety rule:</strong> unpaid A/R, unbilled contract value and retainage still held by the customer are visible but do not count as funding available to authorize a pour.</div>

    <section className="space-y-4" aria-labelledby="funding-title"><div><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Funding</div><h2 id="funding-title" className="mt-1 text-lg font-semibold">Project Cash Position</h2><p className="mt-1 text-sm text-muted-foreground">This is a project-funding control, not a live bank-account balance.</p></div>
      <div className="space-y-3">{(funding||[]).map((f:any)=>{const balance=num(f.project_funding_balance),risk=num(f.carez_cash_at_risk_to_date);return <Card key={f.project_id}><header className="carez-page-heading flex flex-col gap-3 border-b border-border px-4 pb-4 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-semibold">{f.job_number} — {f.name}</h3><p className="mt-1 text-sm text-muted-foreground">Only collected customer cash is counted.</p></div><Badge variant="outline" className={balance>=0?'border-success/30 bg-success/10 text-success':'border-destructive/30 bg-destructive/10 text-destructive'}>{balance>=0?'Funded to date':'Carez funded'}</Badge></header><CardContent className="space-y-3"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Gross Customer Cash" value={money(num(f.gross_customer_cash))} tone="success"/><Metric label="Sales Tax Reserved" value={money(num(f.sales_tax_cash_reserved))} detail="Not treated as spendable project funding"/><Metric label="Incurred Direct Cost" value={money(num(f.incurred_direct_cost))} detail={`Labor ${money(num(f.incurred_labor_cost))} · Other ${money(num(f.incurred_nonlabor_cost))}`}/><Metric label="Protected Funding Balance" value={money(balance)} detail={`Carez cash at risk ${money(risk)}`} tone={balance>=0?'success':'danger'}/></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Processing Fees Paid" value={money(num(f.processing_fees_paid))}/><Metric label="Outstanding A/R — Not Counted" value={money(num(f.outstanding_ar_not_counted))}/><Metric label="Unbilled Contract — Not Counted" value={money(num(f.unbilled_contract_not_counted))}/><Metric label="Retainage Held — Not Counted" value={money(num(f.retainage_held_not_counted))}/></div></CardContent></Card>;})}</div>
    </section>

    <details className="rounded-lg border border-border bg-card"><summary className="cursor-pointer list-none px-4 py-3 font-medium">Create Pour Plan</summary><div className="border-t border-border p-4"><form action={createPourPlan} className="grid gap-4">
      <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="new-pour-project">Project</Label><select id="new-pour-project" className={selectClass} name="project_id" required defaultValue=""><option value="" disabled>Select project</option>{(projects||[]).map((p:any)=><option key={p.id} value={p.id}>{p.job_number} — {p.name}</option>)}</select></div><div className="grid gap-2"><Label htmlFor="new-pour-name">Pour Name / Location</Label><Input id="new-pour-name" name="name" required placeholder="Basement stem walls — Pour 2"/></div></div>
      <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="new-pour-date">Scheduled Pour Date</Label><Input id="new-pour-date" type="date" name="scheduled_date" defaultValue={today()}/></div><div className="grid gap-2"><Label htmlFor="new-pour-cy">Expected Concrete (CY)</Label><Input id="new-pour-cy" type="number" min="0" step="0.01" name="expected_concrete_yards" defaultValue="0"/></div></div>
      <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="new-pour-budget">Budget Scope (optional)</Label><select id="new-pour-budget" className={selectClass} name="budget_section_id" defaultValue=""><option value="">Unassigned</option>{sectionOptions.map((s:any)=>{const p:any=projectMap.get(s.project_id)||{};return <option key={s.id} value={s.id}>{p.job_number||'Job'} — {s.name}</option>;})}</select></div><div className="grid gap-2"><Label htmlFor="new-pour-co">Approved Change Order (optional)</Label><select id="new-pour-co" className={selectClass} name="change_order_id" defaultValue=""><option value="">Original contract work</option>{(changeOrders||[]).map((co:any)=>{const p:any=projectMap.get(co.project_id)||{};return <option key={co.id} value={co.id}>{p.job_number||'Job'} — {co.co_number} · {co.title}</option>;})}</select></div></div>
      <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="new-pour-contingency">Contingency %</Label><Input id="new-pour-contingency" type="number" min="0" max="100" step="0.1" name="contingency_percent" defaultValue="10"/><p className="text-xs text-muted-foreground">Planning safeguard; editable per pour.</p></div><div className="grid gap-2"><Label htmlFor="new-pour-buffer">Minimum Cash Buffer After Pour</Label><Input id="new-pour-buffer" type="number" min="0" step="0.01" name="minimum_cash_buffer" defaultValue="0"/></div></div>
      <div className="grid gap-2"><Label htmlFor="new-pour-support">Company Cash Support Committed</Label><Input id="new-pour-support" type="number" min="0" step="0.01" name="company_cash_support" defaultValue="0"/><p className="text-xs text-muted-foreground">Only enter money Carez is actually willing/able to contribute beyond protected project cash.</p></div>
      <div className="grid gap-2"><Label htmlFor="new-pour-notes">Notes</Label><Textarea id="new-pour-notes" rows={2} name="notes"/></div><Button type="submit" className="w-fit">Create Pour Plan</Button>
    </form></div></details>

    <section className="space-y-4" aria-labelledby="plans-title"><div><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Authorization</div><h2 id="plans-title" className="mt-1 text-lg font-semibold">Pour Plans</h2><p className="mt-1 text-sm text-muted-foreground">Any change to planned cost or funding resets the plan to Planning and requires a fresh authorization review.</p></div>
      {(plans||[]).length===0?<Card><CardContent><div className="font-medium">No pour plans yet</div><p className="mt-1 text-sm text-muted-foreground">Create the next planned pour above.</p></CardContent></Card>:<div className="space-y-4">{(plans||[]).map((p:any)=>{
        const planItems=itemsByPlan.get(p.pour_plan_id)||[];const planReviews=reviewsByPlan.get(p.pour_plan_id)||[];const last=latestReview.get(p.pour_plan_id);const gap=num(p.required_additional_cash),clear=p.system_recommendation==='clear';const liveChanged=p.status==='authorized'&&!clear;
        return <Card key={p.pour_plan_id}><header className="flex flex-col gap-3 border-b border-border px-4 pb-4 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-semibold">{p.job_number} — {p.name}</h3><p className="mt-1 text-sm text-muted-foreground">{p.scheduled_date?`Scheduled ${p.scheduled_date}`:'Date not set'} · {num(p.expected_concrete_yards).toFixed(2)} CY planned</p></div><Badge variant="outline" className={p.status==='authorized'||p.status==='completed'?'border-success/30 bg-success/10 text-success':p.status==='hold'?'border-destructive/30 bg-destructive/10 text-destructive':'text-muted-foreground'}>{String(p.status).replace('_',' ')}</Badge></header>

          <CardContent className="space-y-6">
            <section className="space-y-3"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Live cash test</div><h4 className={`mt-1 font-semibold ${clear?'text-success':'text-destructive'}`}>{clear?'CLEAR TO COMMIT':'HOLD — FUNDING REQUIRED'}</h4><p className="mt-1 text-sm text-muted-foreground">Recalculates from current collections, direct costs and this pour plan.</p></div><div className="text-sm font-semibold tabular-nums">{clear?'Covered':`${money(gap)} gap`}</div></div>
              <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Planned Exposure" value={money(num(p.planned_exposure))} detail="Before contingency"/><Metric label="Contingency" value={money(num(p.contingency_amount))} detail={`${num(p.contingency_percent).toFixed(1)}%`}/><Metric label="Protected Project Cash" value={money(num(p.project_funding_balance))} detail="After incurred direct cost" tone={num(p.project_funding_balance)>=0?'success':'danger'}/><Metric label="Required Additional Cash" value={money(gap)} detail={`Includes ${money(num(p.minimum_cash_buffer))} post-pour buffer`} tone={clear?'success':'danger'}/></div>
              <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Concrete" value={money(num(p.concrete_cost))}/><Metric label="Labor" value={money(num(p.labor_cost))}/><Metric label="Pump" value={money(num(p.pump_cost))}/><Metric label="Material / Equipment / Subs / Other" value={money(num(p.material_equipment_cost)+num(p.subcontractor_cost)+num(p.other_cost))}/></div>
              {!clear&&<div className="rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive"><strong>Do not rely on receivables to fund this commitment.</strong> Collect at least {money(gap)} more, reduce planned exposure, or explicitly commit company cash support before authorizing.</div>}
              {liveChanged&&<div className="rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive"><strong>Authorization is no longer cash-cleared.</strong> Funding/cost conditions changed after the last authorization. Re-review this pour before committing additional money.</div>}
            </section>

            <section className="space-y-3 border-t border-border pt-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Exposure build-up</div><h4 className="mt-1 font-semibold">Planned Cash Requirements</h4></div><div className="text-sm font-semibold tabular-nums">Total + contingency {money(num(p.total_exposure_with_contingency))}</div></div>
              <div className="divide-y rounded-lg border border-border">{planItems.length===0?<div className="px-3 py-3 text-sm text-muted-foreground">No costs entered yet. A pour with $0 exposure cannot be cash-cleared.</div>:planItems.map((i:any)=><div className="flex flex-col gap-3 px-3 py-3 sm:flex-row sm:items-center sm:justify-between" key={i.id}><div><div className="font-medium">{i.description}</div><div className="mt-1 text-xs text-muted-foreground">{i.item_type.replace('_',' ')} · {num(i.quantity).toFixed(2)} {i.unit} × {money(num(i.unit_cost))}{i.vendor_name?` · ${i.vendor_name}`:''}{i.committed?' · COMMITTED':''}</div></div><div className="flex items-center gap-2 sm:flex-col sm:items-end"><strong className="tabular-nums">{money(num(i.expected_cost))}</strong>{!['completed','cancelled'].includes(p.status)&&<form action={deletePourCostItem}><input type="hidden" name="item_id" value={i.id}/><input type="hidden" name="pour_plan_id" value={p.pour_plan_id}/><Button type="submit" variant="outline" size="sm">Delete</Button></form>}</div></div>)}</div>

              {!['completed','cancelled'].includes(p.status)&&<div className="grid gap-3 xl:grid-cols-2">
                <details className="rounded-lg border border-border"><summary className="cursor-pointer list-none px-3 py-3 text-sm font-medium">Add Concrete / Pump / Material / Equipment / Sub</summary><div className="border-t border-border p-3"><form action={addPourCostItem} className="grid gap-3"><input type="hidden" name="pour_plan_id" value={p.pour_plan_id}/>
                  <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`cost-type-${p.pour_plan_id}`}>Cost Type</Label><select id={`cost-type-${p.pour_plan_id}`} className={selectClass} name="item_type" defaultValue="concrete"><option value="concrete">Ready-Mix Concrete</option><option value="pump">Concrete Pump</option><option value="material">Material</option><option value="equipment">Equipment</option><option value="subcontractor">Subcontractor</option><option value="other">Other</option></select></div><div className="grid gap-2"><Label htmlFor={`cost-code-${p.pour_plan_id}`}>Cost Code</Label><select id={`cost-code-${p.pour_plan_id}`} className={selectClass} name="cost_code_id" defaultValue=""><option value="">Optional</option>{(costCodes||[]).map((c:any)=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></div></div>
                  <div className="grid gap-2"><Label htmlFor={`catalog-${p.pour_plan_id}`}>Catalog Item</Label><select id={`catalog-${p.pour_plan_id}`} className={selectClass} name="catalog_item_id" defaultValue=""><option value="">Optional</option>{(catalog||[]).map((c:any)=><option key={c.id} value={c.id}>{c.name}{c.vendor_name?` — ${c.vendor_name}`:''}</option>)}</select></div>
                  <div className="grid gap-2"><Label htmlFor={`description-${p.pour_plan_id}`}>Description</Label><Input id={`description-${p.pour_plan_id}`} name="description" required placeholder="4000 PSI ready-mix"/></div>
                  <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`vendor-${p.pour_plan_id}`}>Vendor</Label><Input id={`vendor-${p.pour_plan_id}`} name="vendor_name"/></div><div className="grid gap-2"><Label htmlFor={`unit-${p.pour_plan_id}`}>Unit</Label><select id={`unit-${p.pour_plan_id}`} className={selectClass} name="unit" defaultValue="LS">{units.map(u=><option key={u}>{u}</option>)}</select></div></div>
                  <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`quantity-${p.pour_plan_id}`}>Quantity</Label><Input id={`quantity-${p.pour_plan_id}`} type="number" min="0" step="0.01" name="quantity" defaultValue="1" required/></div><div className="grid gap-2"><Label htmlFor={`unit-cost-${p.pour_plan_id}`}>Unit Cost</Label><Input id={`unit-cost-${p.pour_plan_id}`} type="number" min="0" step="0.01" name="unit_cost" required/></div></div>
                  <label className="flex items-center gap-2 text-sm"><input type="checkbox" name="committed" className="size-4 rounded border-input accent-primary"/><span>Already ordered / financially committed</span></label><div className="grid gap-2"><Label htmlFor={`cost-notes-${p.pour_plan_id}`}>Notes</Label><Input id={`cost-notes-${p.pour_plan_id}`} name="notes"/></div><Button type="submit" className="w-fit">Add Planned Cost</Button>
                </form></div></details>

                <details className="rounded-lg border border-border"><summary className="cursor-pointer list-none px-3 py-3 text-sm font-medium">Add Loaded Labor</summary><div className="border-t border-border p-3"><form action={addPourLaborItem} className="grid gap-3"><input type="hidden" name="pour_plan_id" value={p.pour_plan_id}/>
                  <div className="grid gap-2"><Label htmlFor={`worker-${p.pour_plan_id}`}>Worker</Label><select id={`worker-${p.pour_plan_id}`} className={selectClass} name="crew_member_id" required defaultValue=""><option value="" disabled>Select worker</option>{(crew||[]).map((c:any)=><option key={c.id} value={c.id}>{c.name}{c.is_owner?' — Owner':` — $${num(c.hourly_rate).toFixed(2)}/hr`}</option>)}</select></div>
                  <div className="grid gap-2"><Label htmlFor={`labor-description-${p.pour_plan_id}`}>Operation / Description</Label><Input id={`labor-description-${p.pour_plan_id}`} name="description" placeholder="Place and finish concrete"/></div><div className="grid gap-2"><Label htmlFor={`risk-${p.pour_plan_id}`}>L&I Risk Class</Label><select id={`risk-${p.pour_plan_id}`} className={selectClass} name="risk_class_code" defaultValue="0217-01"><option value="">Owner / not applicable</option>{(risks||[]).map((x:any)=><option key={x.code} value={x.code}>{x.code} — {x.name}</option>)}</select></div>
                  <div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`regular-${p.pour_plan_id}`}>Regular Hours</Label><Input id={`regular-${p.pour_plan_id}`} type="number" min="0" step="0.25" name="regular_hours" defaultValue="8"/></div><div className="grid gap-2"><Label htmlFor={`ot-${p.pour_plan_id}`}>OT Hours</Label><Input id={`ot-${p.pour_plan_id}`} type="number" min="0" step="0.25" name="overtime_hours" defaultValue="0"/></div></div>
                  <label className="flex items-center gap-2 text-sm"><input type="checkbox" name="committed" className="size-4 rounded border-input accent-primary"/><span>Labor commitment already made</span></label><div className="grid gap-2"><Label htmlFor={`labor-notes-${p.pour_plan_id}`}>Notes</Label><Input id={`labor-notes-${p.pour_plan_id}`} name="notes"/></div><Button type="submit" className="w-fit">Add Loaded Labor</Button>
                </form></div></details>
              </div>}
            </section>

            {!['completed','cancelled'].includes(p.status)&&<section className="grid gap-4 border-t border-border pt-5 xl:grid-cols-2">
              <Card className="shadow-none"><CardContent className="space-y-4"><div className="font-semibold">Plan & Funding Settings</div><form action={updatePourPlan} className="grid gap-3"><input type="hidden" name="pour_plan_id" value={p.pour_plan_id}/><div className="grid gap-2"><Label htmlFor={`plan-name-${p.pour_plan_id}`}>Pour Name</Label><Input id={`plan-name-${p.pour_plan_id}`} name="name" defaultValue={p.name} required/></div><div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`plan-date-${p.pour_plan_id}`}>Date</Label><Input id={`plan-date-${p.pour_plan_id}`} type="date" name="scheduled_date" defaultValue={p.scheduled_date||''}/></div><div className="grid gap-2"><Label htmlFor={`plan-cy-${p.pour_plan_id}`}>Expected CY</Label><Input id={`plan-cy-${p.pour_plan_id}`} type="number" min="0" step="0.01" name="expected_concrete_yards" defaultValue={num(p.expected_concrete_yards)}/></div></div><div className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor={`plan-contingency-${p.pour_plan_id}`}>Contingency %</Label><Input id={`plan-contingency-${p.pour_plan_id}`} type="number" min="0" max="100" step="0.1" name="contingency_percent" defaultValue={num(p.contingency_percent)}/></div><div className="grid gap-2"><Label htmlFor={`plan-buffer-${p.pour_plan_id}`}>Cash Buffer</Label><Input id={`plan-buffer-${p.pour_plan_id}`} type="number" min="0" step="0.01" name="minimum_cash_buffer" defaultValue={num(p.minimum_cash_buffer)}/></div></div><div className="grid gap-2"><Label htmlFor={`plan-support-${p.pour_plan_id}`}>Company Cash Support</Label><Input id={`plan-support-${p.pour_plan_id}`} type="number" min="0" step="0.01" name="company_cash_support" defaultValue={num(p.company_cash_support)}/></div><div className="grid gap-2"><Label htmlFor={`plan-notes-${p.pour_plan_id}`}>Notes</Label><Input id={`plan-notes-${p.pour_plan_id}`} name="notes" defaultValue={p.notes||''}/></div><Button type="submit" variant="outline" className="w-fit">Save & Require Re-Review</Button></form></CardContent></Card>

              <Card className="shadow-none"><CardContent className="space-y-4"><div className="font-semibold">Authorization Decision</div><div className={`rounded-lg border px-3 py-2 text-sm ${clear?'border-success/30 bg-success/10 text-success':'border-destructive/30 bg-destructive/10 text-destructive'}`}>{clear?<><strong>System recommendation: CLEAR.</strong> Current protected funding plus committed company support covers the modeled pour exposure and cash buffer.</>:<><strong>System recommendation: HOLD.</strong> Additional required cash: {money(gap)}.</>}</div><form action={recordPourAuthorization} className="grid gap-3"><input type="hidden" name="pour_plan_id" value={p.pour_plan_id}/><div className="grid gap-2"><Label htmlFor={`decision-${p.pour_plan_id}`}>Decision</Label><select id={`decision-${p.pour_plan_id}`} className={selectClass} name="decision" defaultValue={clear?'authorized':'hold'}><option value="authorized">Authorize Pour</option><option value="hold">Place / Keep on Hold</option></select></div><div className="grid gap-2"><Label htmlFor={`override-${p.pour_plan_id}`}>Override Reason</Label><Textarea id={`override-${p.pour_plan_id}`} rows={2} name="override_reason" placeholder={clear?'Optional':'Required if authorizing despite a funding gap'}/></div><div className="grid gap-2"><Label htmlFor={`review-notes-${p.pour_plan_id}`}>Review Notes</Label><Input id={`review-notes-${p.pour_plan_id}`} name="notes"/></div><Button type="submit" className="w-fit">Record Authorization Snapshot</Button></form>{last&&<div className="text-xs text-muted-foreground">Last decision: <strong className="text-foreground">{String(last.decision).toUpperCase()}</strong> · system {String(last.system_recommendation).toUpperCase()} · gap {money(num(last.funding_gap))}{last.override_used?' · OVERRIDE USED':''}</div>}</CardContent></Card>
            </section>}

            {!['completed','cancelled'].includes(p.status)&&<div className="flex flex-wrap gap-2 border-t border-border pt-5"><form action={closePourPlan}><input type="hidden" name="pour_plan_id" value={p.pour_plan_id}/><input type="hidden" name="status" value="completed"/><Button type="submit" variant="outline">Mark Pour Completed</Button></form><form action={closePourPlan}><input type="hidden" name="pour_plan_id" value={p.pour_plan_id}/><input type="hidden" name="status" value="cancelled"/><Button type="submit" variant="outline">Cancel Plan</Button></form></div>}

            {planReviews.length>0&&<section className="border-t border-border pt-5"><details className="rounded-lg border border-border"><summary className="cursor-pointer list-none px-3 py-3 text-sm font-medium">Authorization History ({planReviews.length})</summary><div className="divide-y border-t border-border">{planReviews.map((x:any)=><div className="px-3 py-3" key={x.id}><div className="text-sm font-medium">{new Date(x.reviewed_at).toLocaleString()} · {String(x.decision).toUpperCase()}</div><div className="mt-1 text-xs text-muted-foreground">System {String(x.system_recommendation).toUpperCase()} · Exposure {money(num(x.planned_exposure)+num(x.contingency_amount))} · Protected {money(num(x.project_funding_balance))} · Gap {money(num(x.funding_gap))}{x.override_used?` · Override: ${x.override_reason||'No reason recorded'}`:''}</div></div>)}</div></details></section>}
          </CardContent>
        </Card>;
      })}</div>}
    </section>
  </div></AppShell>;
}
