import {redirect} from 'next/navigation';
import Link from 'next/link';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';
import {clearReadinessHold,createInspection,placeReadinessHold,recordInspectionResult,scheduleInspection,setPriorOperationRule} from './actions';

const n=(v:any)=>Number(v||0);
const qty=(v:any,u:string)=>`${n(v).toLocaleString(undefined,{maximumFractionDigits:2})} ${u||''}`.trim();
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const addDays=(d:string,x:number)=>{const v=new Date(`${d}T12:00:00`);v.setDate(v.getDate()+x);return v.toISOString().slice(0,10);};
const statusLabel=(s:string)=>({waiting_prior_work:'PRIOR WORK',waiting_inspection:'INSPECTION',inspection_failed:'FAILED INSPECTION',waiting_pour_link:'POUR LINK',waiting_pour_authorization:'POUR HOLD',waiting_concrete_order:'CONCRETE ORDER',job_setup_hold:'JOB SETUP',management_hold:'MANAGEMENT HOLD',ready:'READY'} as Record<string,string>)[s]||String(s||'').replaceAll('_',' ').toUpperCase();

export default async function ReadinessPage(){
  const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
  const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(!profile?.company_id)redirect('/login');if(profile.role==='employee')redirect('/employee');const companyId=profile.company_id;
  const [{data:readiness,error},{data:inspections}]=await Promise.all([
    supabase.from('work_package_operation_readiness').select('*').eq('company_id',companyId).order('job_number').order('package_name').order('sequence'),
    supabase.from('project_inspections').select('*,projects(job_number,name),work_package_operations(id,field_label,production_tasks(name),work_packages(name,location))').eq('company_id',companyId).order('created_at',{ascending:false})
  ]);
  const open=(readiness||[]).filter((r:any)=>!['completed','cancelled'].includes(r.operation_status));const ready=open.filter((r:any)=>r.ready_to_start);const blocked=open.filter((r:any)=>!r.ready_to_start);const pendingInspections=(inspections||[]).filter((i:any)=>!['passed','waived','cancelled'].includes(i.status));const failed=(inspections||[]).filter((i:any)=>i.status==='failed');const start=today(),week=addDays(start,7);const scheduledSoon=open.filter((r:any)=>r.scheduled_work_date&&r.scheduled_work_date>=start&&r.scheduled_work_date<=week);const blockedSoon=scheduledSoon.filter((r:any)=>!r.ready_to_start);const sorted=[...open].sort((a:any,b:any)=>String(a.scheduled_work_date||'9999-12-31').localeCompare(String(b.scheduled_work_date||'9999-12-31'))||String(a.job_number).localeCompare(String(b.job_number))||n(a.sequence)-n(b.sequence));
  return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page">
    <div className="command-hero"><div><div className="section-kicker">PRE-START CONTROL</div><h1>Work Readiness</h1><p>Carez decides whether the next physical package can actually start before crew hours begin burning.</p></div><div className="command-actions"><Link className="button secondary" href="/schedule">Schedule</Link><Link className="button secondary" href="/production/work-packages">Work Packages</Link></div></div>
    {error&&<div className="alert danger"><strong>Readiness could not be loaded.</strong> {error.message}</div>}
    <div className="command-grid"><div className={`command-card ${blockedSoon.length?'bad':'good'}`}><div className="command-label">Scheduled Soon + Blocked</div><div className="command-value">{blockedSoon.length}</div><div className="command-help">Work in the next 7 days that should not start yet.</div></div><div className={`command-card ${blocked.length?'watch':'good'}`}><div className="command-label">All Readiness Holds</div><div className="command-value">{blocked.length}</div><div className="command-help">Open operations with at least one blocking fact.</div></div><div className={`command-card ${pendingInspections.length?'watch':'good'}`}><div className="command-label">Inspections Open</div><div className="command-value">{pendingInspections.length}</div><div className="command-help">Required, scheduled or failed inspections still blocking work.</div></div><div className={`command-card ${failed.length?'bad':'good'}`}><div className="command-label">Failed Inspections</div><div className="command-value">{failed.length}</div><div className="command-help">Corrections required before the linked operation can start.</div></div></div>

    {blockedSoon.length>0&&<section className="section"><div className="section-heading"><div><div className="section-kicker">CREW PROTECTION</div><div className="section-title">Scheduled Work That Is Not Ready</div><div className="section-heading-meta">These assignments may stay on the planning board, but employees cannot start the blocked work and it cannot be confirmed until the gate clears.</div></div></div><div className="project-list">{blockedSoon.map((r:any)=><article className="project-card" key={`soon-${r.operation_id}`}><header className="project-header"><div><div className="project-name">{r.job_number} — {r.package_name}</div><div className="project-location">{r.scheduled_work_date} · {r.field_label||r.task_name}{r.location?` · ${r.location}`:''}</div></div><span className="status on-hold">{statusLabel(r.readiness_status)}</span></header><section className="project-section"><div className="alert danger"><strong>Do not start:</strong> {r.next_action}</div>{(r.blocking_reasons||[]).length>1&&<div className="meta">Also blocked by: {(r.blocking_reasons||[]).slice(1).join(' · ')}</div>}</section></article>)}</div></section>}

    <section className="section"><div className="section-heading"><div><div className="section-kicker">AUTOMATIC GATES</div><div className="section-title">Open Physical Work</div><div className="section-heading-meta">Job setup, earlier work, inspections, management holds and concrete-pour facts are evaluated continuously.</div></div></div>{sorted.length===0?<div className="empty-state"><div><div className="title">No open work packages yet</div><div className="meta">Create physical Work Packages first. Readiness begins as soon as operations exist.</div></div></div>:<div className="project-list">{sorted.map((r:any)=><article className="project-card" key={r.operation_id}><header className="project-header"><div><div className="project-name">{r.job_number} — {r.package_name}</div><div className="project-location">#{r.sequence} · {r.field_label||r.task_name}{r.location?` · ${r.location}`:''}{r.scheduled_work_date?` · Scheduled ${r.scheduled_work_date}`:''}</div></div><span className={`status ${r.ready_to_start?'completed':'on-hold'}`}>{r.ready_to_start?'READY':statusLabel(r.readiness_status)}</span></header><section className="project-section"><div className="metric-grid"><div className="metric-card brand"><div className="label">Physical Scope</div><div className="metric-value">{qty(r.planned_quantity,r.unit)}</div><div className="metric-detail">{r.task_name}</div></div><div className={`metric-card ${n(r.prior_open_count)>0?'danger-metric':'positive'}`}><div className="label">Prior Work Open</div><div className="metric-value">{r.requires_prior_operations?n(r.prior_open_count):0}</div><div className="metric-detail">{r.requires_prior_operations?'Earlier package operations must finish first.':'Parallel start allowed.'}</div></div><div className={`metric-card ${n(r.inspection_blocking_count)>0?'danger-metric':'positive'}`}><div className="label">Inspection Gate</div><div className="metric-value">{n(r.inspection_clear_count)}/{n(r.inspection_count)}</div><div className="metric-detail">Required inspections cleared.</div></div>{r.measurement_method==='ticket'&&<div className={`metric-card ${['authorized','completed'].includes(r.pour_status)&&n(r.ordered_cy)>0?'positive':'danger-metric'}`}><div className="label">Concrete Ready</div><div className="metric-value">{n(r.ordered_cy).toFixed(1)} CY</div><div className="metric-detail">{r.pour_name||'No pour linked'} · {String(r.pour_status||'not linked').replaceAll('_',' ')}</div></div>}</div>
      {!r.ready_to_start&&<div className="alert danger section"><strong>{r.next_action}</strong>{(r.blocking_reasons||[]).length>1&&<div>{(r.blocking_reasons||[]).slice(1).join(' · ')}</div>}</div>}{(r.warning_reasons||[]).length>0&&<div className="alert warning section"><strong>Warning:</strong> {(r.warning_reasons||[]).join(' · ')}</div>}
      <div className="action-row section"><details><summary className="button secondary">Inspection</summary><form action={createInspection} className="form surface-body"><input type="hidden" name="operation_id" value={r.operation_id}/><div className="grid grid2"><label className="field"><span>Inspection</span><select name="inspection_type" defaultValue="rebar"><option value="rebar">Rebar / pre-pour</option><option value="forms">Forms / footing</option><option value="special">Special inspection</option><option value="row">ROW / civil</option><option value="subgrade">Subgrade / compaction</option><option value="general">Other</option></select></label><label className="field"><span>Custom Name (optional)</span><input name="title" placeholder="NW footing epoxy special inspection"/></label></div><div className="grid grid2"><label className="field"><span>Inspector / Authority</span><input name="authority" placeholder="City, county, special inspector..."/></label><label className="field"><span>Reference / Permit #</span><input name="reference_number"/></label></div><div className="grid grid2"><label className="field"><span>Scheduled Date</span><input type="date" name="scheduled_date"/></label><label className="field"><span>Time</span><input type="time" name="scheduled_time"/></label></div><label className="field"><span>Note</span><input name="notes" placeholder="Scope or inspector instructions"/></label><button className="button">Add Required Inspection</button></form></details>{r.readiness_hold_reason?<form action={clearReadinessHold}><input type="hidden" name="operation_id" value={r.operation_id}/><button className="button secondary">Clear Management Hold</button></form>:<details><summary className="button secondary">Management Hold</summary><form action={placeReadinessHold} className="form surface-body"><input type="hidden" name="operation_id" value={r.operation_id}/><label className="field"><span>Why must this work not start?</span><input name="reason" required placeholder="Pump unavailable, material missing, field condition..."/></label><button className="button">Place Hold</button></form></details>}<form action={setPriorOperationRule}><input type="hidden" name="operation_id" value={r.operation_id}/><input type="hidden" name="requires_prior_operations" value={r.requires_prior_operations?'false':'true'}/><button className="button secondary">{r.requires_prior_operations?'Allow Parallel Start':'Require Prior Work'}</button></form></div>
    </section></article>)}</div>}</section>

    <section className="section"><div className="section-heading"><div><div className="section-kicker">INSPECTIONS</div><div className="section-title">Required Inspection Queue</div><div className="section-heading-meta">Scheduling an inspection automatically puts it on the Schedule. Passing or waiving it automatically clears that readiness gate.</div></div></div>{(inspections||[]).length===0?<div className="empty-state"><div><div className="title">No inspections recorded</div><div className="meta">Add an inspection directly to the operation it must clear. Employees never have to track the inspection status themselves.</div></div></div>:<div className="project-list">{(inspections||[]).map((i:any)=>{const op=i.work_package_operations,pkg=op?.work_packages;return <article className="project-card" key={i.id}><header className="project-header"><div><div className="project-name">{i.projects?.job_number} — {i.title}</div><div className="project-location">{pkg?.name||'Project inspection'}{op?.production_tasks?.name?` · ${op.production_tasks.name}`:''}{i.authority?` · ${i.authority}`:''}</div></div><span className={`status ${i.status==='passed'||i.status==='waived'?'completed':i.status==='failed'?'on-hold':i.status==='scheduled'?'active':''}`}>{String(i.status).replaceAll('_',' ')}</span></header><section className="project-section"><div className="grid grid4"><div><div className="label">Scheduled</div><strong>{i.scheduled_date||'Not scheduled'}</strong></div><div><div className="label">Time</div><strong>{i.scheduled_time?String(i.scheduled_time).slice(0,5):'—'}</strong></div><div><div className="label">Reference</div><strong>{i.reference_number||'—'}</strong></div><div><div className="label">Result</div><strong>{i.result_notes||i.waived_reason||'—'}</strong></div></div>
      {!['passed','waived','cancelled'].includes(i.status)&&<div className="action-row section"><details><summary className="button secondary">Schedule / Reschedule</summary><form action={scheduleInspection} className="form surface-body"><input type="hidden" name="inspection_id" value={i.id}/><div className="grid grid2"><label className="field"><span>Date</span><input type="date" name="scheduled_date" defaultValue={i.scheduled_date||''} required/></label><label className="field"><span>Time</span><input type="time" name="scheduled_time" defaultValue={i.scheduled_time?String(i.scheduled_time).slice(0,5):''}/></label></div><label className="field"><span>Inspector / Authority</span><input name="authority" defaultValue={i.authority||''}/></label><label className="field"><span>Reference / Permit #</span><input name="reference_number" defaultValue={i.reference_number||''}/></label><button className="button">Save Inspection Schedule</button></form></details><form action={recordInspectionResult}><input type="hidden" name="inspection_id" value={i.id}/><input type="hidden" name="status" value="passed"/><button className="button">PASS</button></form><details><summary className="button secondary">Fail</summary><form action={recordInspectionResult} className="form surface-body"><input type="hidden" name="inspection_id" value={i.id}/><input type="hidden" name="status" value="failed"/><label className="field"><span>What failed / correction needed?</span><input name="result_notes" required/></label><button className="button">Record Failed Inspection</button></form></details><details><summary className="button secondary">Waive</summary><form action={recordInspectionResult} className="form surface-body"><input type="hidden" name="inspection_id" value={i.id}/><input type="hidden" name="status" value="waived"/><label className="field"><span>Why is this inspection no longer required?</span><input name="waived_reason" required/></label><button className="button">Waive Requirement</button></form></details></div>}
    </section></article>;})}</div>}</section>

    <section className="section"><div className="surface"><div className="surface-body"><div className="row"><div><div className="title">Readiness rule</div><div className="meta">Planning is allowed while blocked. Confirming and starting physical work are not. As soon as the underlying facts clear—prior operation finished, inspection passed, pour authorized, concrete ordered—the hold disappears automatically.</div></div><span className="status completed">FACT DRIVEN</span></div></div></div></section>
  </div></AppShell>;
}
