'use client';
import {useState} from 'react';
import {setProjectJobsite} from '@/app/field/employee-actions';

export function JobsiteLocationSetter({projects}:{projects:{id:string;job_number:string;name:string;site_latitude?:number|null;site_longitude?:number|null;geofence_radius_ft?:number|null}[]}){
 const [projectId,setProjectId]=useState('');const [radius,setRadius]=useState('500');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function save(){if(!projectId){setMessage('Choose a job first.');return;}if(!navigator.geolocation){setMessage('This device does not support GPS.');return;}setBusy(true);setMessage('Getting your current location...');navigator.geolocation.getCurrentPosition(async p=>{try{const fd=new FormData();fd.set('project_id',projectId);fd.set('latitude',String(p.coords.latitude));fd.set('longitude',String(p.coords.longitude));fd.set('radius_ft',radius);await setProjectJobsite(fd);setMessage(`Jobsite pin saved. GPS accuracy ${Math.round(p.coords.accuracy)} m.`);}catch(e:any){setMessage(e?.message||'Could not save jobsite location.');}finally{setBusy(false);}},e=>{setMessage(e.message||'Location permission is required.');setBusy(false);},{enableHighAccuracy:true,timeout:15000,maximumAge:0});}
 return <div className="surface"><div className="surface-header"><div><div className="surface-title">Set Jobsite GPS Pin</div><div className="surface-subtitle">Stand at the job, choose it, and save your phone's location. Employee punches are measured from this pin.</div></div></div><div className="surface-body"><div className="form"><label className="field"><span>Job</span><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Choose job</option>{projects.map(p=><option key={p.id} value={p.id}>{p.job_number} — {p.name}{p.site_latitude?' · Pin set':''}</option>)}</select></label><label className="field"><span>Allowed Jobsite Radius (ft)</span><input type="number" min="50" step="25" value={radius} onChange={e=>setRadius(e.target.value)}/></label><button type="button" className="button" onClick={save} disabled={busy}>{busy?'Getting GPS...':'Use My Current Location'}</button>{message&&<div className="meta">{message}</div>}</div></div></div>;
}
