'use client';
import {useState} from 'react';
import {setProjectJobsite} from '@/app/field/employee-actions';

export function JobsitePinControl({projects}:{projects:{id:string;job_number:string;name:string;site_latitude?:number|null;site_longitude?:number|null;geofence_radius_ft?:number|null}[]}){
 const [projectId,setProjectId]=useState('');const [radius,setRadius]=useState('500');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function save(){if(!projectId){setMessage('Choose a job first.');return;}if(!navigator.geolocation){setMessage('This phone does not support GPS.');return;}setBusy(true);setMessage('Getting your location...');navigator.geolocation.getCurrentPosition(async p=>{try{const fd=new FormData();fd.set('project_id',projectId);fd.set('latitude',String(p.coords.latitude));fd.set('longitude',String(p.coords.longitude));fd.set('radius_ft',radius);await setProjectJobsite(fd);setMessage(`Jobsite pin saved. GPS accuracy about ${Math.round(p.coords.accuracy)} m.`);}catch(e:any){setMessage(e?.message||'Could not save jobsite pin.');}finally{setBusy(false)}},e=>{setMessage(e.message||'Location permission is required.');setBusy(false)},{enableHighAccuracy:true,timeout:15000,maximumAge:0});}
 return <div className="form"><label className="field"><span>Job</span><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Choose job</option>{projects.map(p=><option key={p.id} value={p.id}>{p.job_number} — {p.name}{p.site_latitude?' · PIN SET':''}</option>)}</select></label><label className="field"><span>Allowed Clock-In Radius</span><select value={radius} onChange={e=>setRadius(e.target.value)}><option value="250">250 ft</option><option value="500">500 ft</option><option value="750">750 ft</option><option value="1000">1,000 ft</option></select></label><button type="button" className="button" disabled={busy} onClick={save}>{busy?'Getting GPS...':'Use My Location as Jobsite Pin'}</button>{message&&<div className="meta">{message}</div>}</div>;
}
