import { redirect } from 'next/navigation';
import Link from 'next/link';
import { AppShell } from '@/components/AppShell';
import { createClient } from '@/lib/supabase/server';
import { outlookConfigured } from '@/lib/outlook';
import { signOut } from './actions';

export default async function SettingsPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
 const {data:profile,error}=await supabase.from('profiles').select('full_name,role,company_id').eq('id',user.id).maybeSingle();if(profile?.role==='employee')redirect('/employee');
 const [{data:tax},{data:risks},{data:outlook},{data:plaid}]=profile?.company_id?await Promise.all([
   supabase.from('labor_tax_settings').select('*').eq('company_id',profile.company_id).eq('tax_year',2026).maybeSingle(),
   supabase.from('li_risk_classes').select('code,name,employer_rate_per_hour').eq('company_id',profile.company_id).eq('tax_year',2026).eq('active',true).order('code'),
   supabase.from('outlook_connections').select('mailbox_email,mailbox_name,status,last_sync_at,last_error,subscription_expires_at').eq('company_id',profile.company_id).maybeSingle(),
   supabase.from('plaid_connections').select('id,status,institution_name').eq('company_id',profile.company_id).eq('status','active')
 ]):[{data:null},{data:[]},{data:null},{data:[]}];
 const name=profile?.full_name||user.email||'Owner',outlookReady=outlookConfigured(),outlookConnected=outlook?.status==='active';
 return <AppShell userName={name}><div className="contractor-page">
  <div className="command-hero"><div><h1>Settings</h1><p>Company setup, integrations and the cost rules Carez uses behind the scenes.</p></div></div>
  <section className="section"><div className="section-heading"><div><div className="section-kicker">Connections</div><div className="section-title">Integrations</div><div className="section-heading-meta">Carez connects directly to the services that remove office work.</div></div></div><div className="project-list">
   <article className="project-card"><header className="project-header"><div><div className="project-name">Microsoft Outlook</div><div className="project-location">Automatically identify incoming concrete opportunities and place uncertain emails in Lead Inbox.</div></div><span className={`status ${outlookConnected?'completed':outlookReady?'active':'on-hold'}`}>{outlookConnected?'Connected':outlookReady?'Ready to Connect':'Setup Needed'}</span></header><section className="project-section">{outlookConnected?<div className="list"><div className="row"><span>Mailbox</span><strong>{outlook.mailbox_email||outlook.mailbox_name||'Connected'}</strong></div><div className="row"><span>Last Inbox Scan</span><strong>{outlook.last_sync_at?new Date(outlook.last_sync_at).toLocaleString():'Not yet'}</strong></div></div>:<div className="meta">Microsoft app credentials must be configured once, then the mailbox is authorized through Microsoft sign-in.</div>}{outlook?.last_error&&<div className="alert warn section">{outlook.last_error}</div>}<div className="action-row section"><Link className="button" href="/leads/inbox">{outlookConnected?'Open Lead Inbox':'Set Up Outlook'}</Link></div></section></article>
   <article className="project-card"><header className="project-header"><div><div className="project-name">Banking / Plaid</div><div className="project-location">Bank balances and transactions used by Cash, reconciliation and automation rules.</div></div><span className={`status ${(plaid||[]).length?'completed':'on-hold'}`}>{(plaid||[]).length?'Connected':'Not Connected'}</span></header><section className="project-section"><div className="meta">{(plaid||[]).length?`${(plaid||[]).length} active connection(s)${plaid?.[0]?.institution_name?` · ${plaid[0].institution_name}`:''}`:'Connect through Banking.'}</div><div className="action-row section"><Link className="button secondary" href="/banking">Open Banking</Link></div></section></article>
   <article className="project-card"><header className="project-header"><div><div className="project-name">QuickBooks</div><div className="project-location">Accounting export/integration after the Carez operating workflow is stable.</div></div><span className="status">Later</span></header></article>
  </div></section>
  <div className="card section"><div className="row"><div><div className="title">Database & Login</div><div className="meta">Supabase live company database · private Carez authentication</div></div><span className={`status ${!error&&profile?'completed':'on-hold'}`}>{!error&&profile?'Connected':'Setup Needed'}</span></div></div>
  <div className="card section"><div className="title">2026 Labor Engine</div><p className="subtitle">Timecards snapshot employer payroll taxes, L&I work-class cost and sick-leave reserve.</p>{tax?<div className="list"><div className="row"><span>Employer Social Security</span><strong>{(Number(tax.social_security_rate)*100).toFixed(2)}%</strong></div><div className="row"><span>Employer Medicare</span><strong>{(Number(tax.medicare_rate)*100).toFixed(2)}%</strong></div><div className="row"><span>WA SUI / EAF</span><strong>{(Number(tax.wa_sui_rate)*100).toFixed(2)}%</strong></div><div className="row"><span>FUTA while applicable</span><strong>{(Number(tax.futa_rate)*100).toFixed(2)}%</strong></div><div className="row"><span>Sick leave reserve</span><strong>1 hr / 40 hr</strong></div></div>:<div className="alert danger">2026 tax settings missing.</div>}<div className="list section">{(risks||[]).map(r=><div className="row" key={r.code}><div><div className="title">{r.code}</div><div className="meta">{r.name}</div></div><strong>${Number(r.employer_rate_per_hour).toFixed(5)}/hr ER</strong></div>)}</div></div>
  <div className="card section"><div className="title">Cost to Keep Carez Running</div><p className="subtitle">Owner compensation, capacity, fleet and recurring company cost.</p><Link className="button" href="/overhead">Open Overhead</Link></div>
  <div className="card section"><div className="title">Signed In</div><div className="meta">{name} · {profile?.role||'owner'}</div><form action={signOut} style={{marginTop:14}}><button className="button secondary">Log Out</button></form></div>
 </div></AppShell>;
}
