import {redirect,notFound} from 'next/navigation';
import Link from 'next/link';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';

const money=(n:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0));
const num=(n:any)=>Number(n||0);
const pct=(n:any)=>`${num(n).toFixed(1)}%`;
const hrs=(n:any)=>`${num(n).toFixed(1)} hr`;

export default async function ProjectCommandPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;
 const supabase=await createClient();
 const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
 const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).maybeSingle();
 if(!profile?.company_id)redirect('/login');if(profile.role==='employee')redirect('/employee');
 const [projectR,financialR,budgetR,billingR,commitR,forecastR,prodR,shiftR,coR,pourR]=await Promise.all([
  supabase.from('projects').select('*,customers(name,contact_name,phone,email)').eq('id',id).eq('company_id',profile.company_id).maybeSingle(),
  supabase.from('project_financial_summary').select('*').eq('project_id',id).maybeSingle(),
  supabase.from('project_budget_actual_summary').select('*').eq('project_id',id).maybeSingle(),
  supabase.from('project_billing_summary').select('*').eq('project_id',id).maybeSingle(),
  supabase.from('project_commitment_summary').select('*').eq('project_id',id).maybeSingle(),
  supabase.from('project_cost_to_complete_summary').select('*').eq('project_id',id).maybeSingle(),
  supabase.from('production_rate_history').select('*').eq('project_id',id).order('work_date',{ascending:false}).limit(12),
  supabase.from('employee_shift_sessions').select('id,status,work_date,clock_in_inside_geofence,clock_out_inside_geofence,crew_members(name)').eq('project_id',id).in('status',['open','submitted']).order('work_date',{ascending:false}),
  supabase.from('change_orders').select('id,co_number,title,status,field_work_status,proposed_sell_price,requested_date').eq('project_id',id).in('status',['draft','submitted','approved']).order('requested_date',{ascending:false}),
  supabase.from('pour_plans').select('id,name,scheduled_date,expected_concrete_yards,status').eq('project_id',id).not('status','eq','cancelled').order('scheduled_date',{ascending:true})
 ]);
 const p:any=projectR.data;if(!p)notFound();
 const f:any=financialR.data||{},b:any=budgetR.data||{},bill:any=billingR.data||{},commit:any=commitR.data||{},fc:any=forecastR.data||{};
 const prod:any[]=prodR.data||[],shifts:any[]=shiftR.data||[],cos:any[]=coR.data||[],pours:any[]=pourR.data||[];
 const waiting=shifts.filter(s=>s.status==='submitted');const clocked=shifts.filter(s=>s.status==='open');const gpsFlags=shifts.filter(s=>s.clock_in_inside_geofence===false||s.clock_out_inside_geofence===false).length;
 const budgetUsed=num(b.budget_cost_used_percent);const laborUsed=num(b.budget_labor_hours)>0?num(b.actual_labor_hours)/num(b.budget_labor_hours)*100:0;
 const forecastVariance=num(fc.forecast_variance_to_budget);const forecastMargin=num(fc.forecast_margin_at_completion);const targetMargin=num(f.target_margin_percent||p.target_margin_percent);
 const activeCO=cos.filter(c=>c.status!=='approved').length;const approvedCO=cos.filter(c=>c.status==='approved').length;
 const nextPour=pours.find(x=>x.scheduled_date&&new Date(`${x.scheduled_date}T23:59:59`).getTime()>=Date.now())||pours[0];
 const warnings:any[]=[];
 if(waiting.length)warnings.push({tone:'watch',title:`${waiting.length} timecard${waiting.length===1?'':'s'} waiting for approval`,copy:'Review employee GPS, hours and tasks before payroll/job cost.',href:'/field/review',action:'Review Time'});
 if(gpsFlags)warnings.push({tone:'bad',title:`${gpsFlags} open/submitted shift${gpsFlags===1?'':'s'} need GPS review`,copy:'At least one clock-in or clock-out is outside the jobsite radius.',href:'/field/review',action:'Check GPS'});
 if(num(b.labor_hours_remaining)<0)warnings.push({tone:'bad',title:`Labor is ${Math.abs(num(b.labor_hours_remaining)).toFixed(1)} hours over budget`,copy:'Remaining work needs a production plan before more labor is burned.',href:'/forecast',action:'Review Forecast'});
 if(budgetUsed>=85&&budgetUsed<100)warnings.push({tone:'watch',title:`Job has used ${budgetUsed.toFixed(1)}% of its cost budget`,copy:'Check remaining scope, material commitments and labor before proceeding.',href:'/forecast',action:'Review Job'});
 if(budgetUsed>=100)warnings.push({tone:'bad',title:'Job cost is over the frozen budget',copy:`Current true company cost exceeds the approved baseline by ${money(Math.abs(num(b.total_cost_remaining)))}.`,href:'/forecast',action:'Review Overrun'});
 if(num(bill.overdue_ar)>0)warnings.push({tone:'bad',title:`Customer has ${money(bill.overdue_ar)} past due`,copy:'Collections need attention before more cash is committed.',href:'/billing',action:'Review Billing'});
 if(activeCO)warnings.push({tone:'watch',title:`${activeCO} change order${activeCO===1?' is':'s are'} not approved`,copy:'Track extra work carefully so unapproved scope does not become free work.',href:'/change-orders',action:'Review COs'});

 return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page">
  <div className="command-hero"><div><div className="section-kicker">{p.job_number}</div><h1>{p.name}</h1><p>{[p.address,p.city,p.state].filter(Boolean).join(', ')||'Job address not entered'}{p.customers?.name?` · ${p.customers.name}`:''}</p></div><div className="command-actions"><Link className="button" href="/field/review">Review Crew Time</Link><Link className="button secondary" href="/pour-control">Plan Pour</Link><Link className="button secondary" href="/procurement">Order Materials</Link></div></div>

  <div className="command-grid">
   <div className="command-card"><div className="command-label">Contract</div><div className="command-value">{money(f.adjusted_contract||p.contract_value)}</div><div className="command-help">Original contract plus approved changes.</div></div>
   <div className={`command-card ${budgetUsed>=100?'bad':budgetUsed>=85?'watch':'good'}`}><div className="command-label">Budget Used</div><div className="command-value">{pct(budgetUsed)}</div><div className="command-help">{b.label?`Against ${b.label}.`:'Approve an estimate to establish the baseline.'}</div></div>
   <div className={`command-card ${laborUsed>=100?'bad':laborUsed>=85?'watch':''}`}><div className="command-label">Labor Hours Used</div><div className="command-value">{num(b.budget_labor_hours)>0?pct(laborUsed):'No Budget'}</div><div className="command-help">{hrs(b.actual_labor_hours)} used · {hrs(b.labor_hours_remaining)} remaining.</div></div>
   <div className={`command-card ${num(bill.overdue_ar)>0?'bad':num(bill.outstanding_ar)>0?'watch':''}`}><div className="command-label">Customer Owes Us</div><div className="command-value">{money(bill.outstanding_ar)}</div><div className="command-help">{num(bill.overdue_ar)>0?`${money(bill.overdue_ar)} is past due.`:'No overdue customer balance.'}</div></div>
   <div className="command-card"><div className="command-label">Money Already Ordered</div><div className="command-value">{money(commit.open_po_commitments)}</div><div className="command-help">{num(commit.open_po_count)} open purchase order{num(commit.open_po_count)===1?'':'s'}.</div></div>
   <div className={`command-card ${forecastVariance<0?'bad':forecastMargin<targetMargin?'watch':'good'}`}><div className="command-label">Where Job Is Headed</div><div className="command-value">{fc.project_id?`${forecastMargin.toFixed(1)}% margin`:'Need Progress'}</div><div className="command-help">{fc.project_id?`${money(forecastVariance)} vs budget at completion.`:'Update scope progress to build a forecast.'}</div></div>
  </div>

  <section className="attention-panel"><div className="attention-head"><strong>What Needs Your Attention</strong><span className="attention-count">{warnings.length} item{warnings.length===1?'':'s'}</span></div><div className="attention-list">{warnings.length===0?<div className="attention-item good"><span className="attention-dot"/><div><div className="attention-title">Nothing urgent on this job</div><div className="attention-copy">No payroll, GPS, budget, collections or change-order warnings are showing.</div></div></div>:warnings.map((w:any,i)=><div className={`attention-item ${w.tone}`} key={i}><span className="attention-dot"/><div><div className="attention-title">{w.title}</div><div className="attention-copy">{w.copy}</div></div><Link className="button secondary" href={w.href}>{w.action}</Link></div>)}</div></section>

  <section className="section"><div className="section-heading"><div><div className="section-kicker">Field</div><div className="section-title">Crew Today</div><div className="section-heading-meta">Employee clock status and approvals for this job.</div></div></div><div className="grid grid4"><div className="card"><div className="label">Clocked In Now</div><div className="value">{clocked.length}</div></div><div className={`card ${waiting.length?'warning':''}`}><div className="label">Waiting Approval</div><div className="value">{waiting.length}</div></div><div className={`card ${gpsFlags?'warning':''}`}><div className="label">GPS Flags</div><div className="value">{gpsFlags}</div></div><div className="card"><div className="label">Actual Labor Hours</div><div className="value">{hrs(b.actual_labor_hours)}</div></div></div><div className="action-row"><Link className="button" href="/field/review">Review Employee Time</Link><Link className="button secondary" href="/field">Field Logs</Link></div></section>

  <section className="section"><div className="section-heading"><div><div className="section-kicker">Production</div><div className="section-title">What the Crew Is Actually Producing</div><div className="section-heading-meta">Verified quantities divided by approved crew man-hours.</div></div></div>{prod.length===0?<div className="empty-state"><div><div className="title">No measured production yet</div><div className="meta">When employees clock tasks and you verify quantities, the actual rates appear here.</div></div></div>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Task</th><th>Built</th><th>Crew MH</th><th>Rate</th><th>Estimating Factor</th></tr></thead><tbody>{prod.map(r=><tr key={`${r.work_date}-${r.production_task_id}`}><td>{r.work_date}</td><td>{r.task_name}</td><td>{num(r.quantity_completed).toFixed(1)} {r.unit}</td><td>{num(r.man_hours).toFixed(1)} MH</td><td>{num(r.units_per_man_hour).toFixed(2)} {r.unit}/MH</td><td>{num(r.man_hours_per_unit).toFixed(3)} MH/{r.unit}</td></tr>)}</tbody></table></div>}</section>

  <div className="grid grid2 section">
   <section className="surface"><div className="surface-header"><div><div className="surface-title">Budget vs Actual</div><div className="surface-subtitle">What we estimated compared with what the job has used.</div></div></div><div className="surface-body"><div className="list"><div className="row"><span>Labor</span><strong>{money(b.actual_direct_labor_cost)} / {money(b.budget_direct_labor_cost)}</strong></div><div className="row"><span>Materials</span><strong>{money(b.actual_material_cost)} / {money(b.budget_material_cost)}</strong></div><div className="row"><span>Equipment</span><strong>{money(b.actual_equipment_cost)} / {money(b.budget_equipment_cost)}</strong></div><div className="row"><span>Subs / Other</span><strong>{money(num(b.actual_subcontractor_cost)+num(b.actual_other_direct_cost))} / {money(num(b.budget_subcontractor_cost)+num(b.budget_other_direct_cost))}</strong></div><div className="row"><span>Total Company Cost</span><strong>{money(b.actual_total_company_cost)} / {money(b.budget_total_company_cost)}</strong></div></div></div></section>
   <section className="surface"><div className="surface-header"><div><div className="surface-title">Get Paid</div><div className="surface-subtitle">Customer billing and collections for this job.</div></div></div><div className="surface-body"><div className="list"><div className="row"><span>Authorized Work</span><strong>{money(bill.authorized_contract)}</strong></div><div className="row"><span>Billed</span><strong>{money(bill.billed_contract)}</strong></div><div className="row"><span>Not Yet Billed</span><strong>{money(bill.unbilled_contract)}</strong></div><div className="row"><span>Cash Collected</span><strong>{money(bill.cash_collected)}</strong></div><div className="row"><span>Still Owed</span><strong>{money(bill.outstanding_ar)}</strong></div></div><div className="action-row"><Link className="button" href="/billing">Billing</Link></div></div></section>
  </div>

  <div className="grid grid2 section">
   <section className="surface"><div className="surface-header"><div><div className="surface-title">Change Orders</div><div className="surface-subtitle">Extra work and approval status.</div></div><Link className="button secondary" href="/change-orders">Open COs</Link></div><div className="surface-body"><div className="list">{cos.length===0?<div className="meta">No active change orders.</div>:cos.slice(0,5).map(c=><div className="row" key={c.id}><div><div className="title">{c.co_number} — {c.title}</div><div className="meta">{c.status} · field: {c.field_work_status||'not started'}</div></div><strong>{money(c.proposed_sell_price)}</strong></div>)}</div><div className="meta section">{approvedCO} approved · {activeCO} still awaiting approval</div></div></section>
   <section className="surface"><div className="surface-header"><div><div className="surface-title">Next Pour</div><div className="surface-subtitle">Upcoming concrete placement for this project.</div></div><Link className="button secondary" href="/pour-control">Pour Control</Link></div><div className="surface-body">{!nextPour?<div className="meta">No pour is currently planned.</div>:<div><div className="title">{nextPour.name}</div><div className="value" style={{fontSize:22}}>{nextPour.scheduled_date||'Date not set'}</div><div className="meta">{num(nextPour.expected_concrete_yards).toFixed(1)} CY · {nextPour.status}</div></div>}</div></section>
  </div>

  <section className="section"><div className="next-action"><div><div className="next-action-label">Next Job Action</div><div className="next-action-text">{p.next_action||'No next action entered yet.'}</div></div></div><div className="quick-grid section"><Link className="quick-tile" href="/field/review"><span><div className="quick-title">Approve Crew Time</div><div className="quick-copy">GPS, hours and tasks</div></span></Link><Link className="quick-tile" href="/procurement"><span><div className="quick-title">Buy Materials</div><div className="quick-copy">Quotes, POs and bills</div></span></Link><Link className="quick-tile" href="/change-orders"><span><div className="quick-title">Extra Work</div><div className="quick-copy">Protect change-order work</div></span></Link><Link className="quick-tile" href="/forecast"><span><div className="quick-title">Job Forecast</div><div className="quick-copy">See where cost and margin are headed</div></span></Link><Link className="quick-tile" href="/billing"><span><div className="quick-title">Get Paid</div><div className="quick-copy">Invoice and collect customer money</div></span></Link><Link className="quick-tile" href="/pour-control"><span><div className="quick-title">Plan a Pour</div><div className="quick-copy">Cash and cost check before placement</div></span></Link></div></section>
 </div></AppShell>;
}
