import {redirect} from 'next/navigation';
import Link from 'next/link';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';
import {addWorkPackageOperation,completeWorkPackageOperation,createWorkPackage,linkTicketOperationToPour,reopenWorkPackageOperation,unlinkTicketOperation,updateOperationLaborPlan} from './actions';

const n=(v:any)=>Number(v||0);
const qty=(v:any,u:string)=>`${n(v).toLocaleString(undefined,{maximumFractionDigits:2})} ${u}`;
const mh=(v:any)=>v==null?'—':`${n(v).toFixed(2)} MH`;
const riskLabel=(r:string)=>r==='no_budget'?'Needs Labor Plan':r==='over_budget'?'Over Budget':r==='critical'?'Critical':r==='watch'?'Watch':'On Track';

export default async function WorkPackagesPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
 const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(!profile?.company_id)redirect('/login');if(profile.role==='employee')redirect('/employee');const companyId=profile.company_id;
 const [{data:packages},{data:progress},{data:projects},{data:tasks},{data:learning},{data:pours}]=await Promise.all([
  supabase.from('work_packages').select('*,projects(job_number,name)').eq('company_id',companyId).neq('status','cancelled').order('created_at',{ascending:false}),
  supabase.from('production_operation_risk').select('*').eq('company_id',companyId).order('job_number').order('package_name'),
  supabase.from('projects').select('id,job_number,name').eq('company_id',companyId).in('status',['active','on_hold']).order('job_number'),
  supabase.from('production_tasks').select('id,name,category,production_unit').eq('company_id',companyId).eq('active',true).order('sort_order'),
  supabase.from('carez_production_learning_summary').select('*').eq('company_id',companyId).order('task_name'),
  supabase.from('pour_plans').select('id,project_id,name,scheduled_date,expected_concrete_yards,status,projects(job_number)').eq('company_id',companyId).neq('status','cancelled').order('scheduled_date',{ascending:false,nullsFirst:false})
 ]);
 const opMap=new Map<string,any[]>();for(const o of progress||[]){const a=opMap.get(o.work_package_id)||[];a.push(o);opMap.set(o.work_package_id,a);}
 const pourMap=new Map((pours||[]).map((p:any)=>[p.id,p]));
 const active=(packages||[]).filter((p:any)=>p.status==='active').length;
 const openOps=(progress||[]).filter((o:any)=>!['completed','cancelled'].includes(o.operation_status));
 const atRisk=openOps.filter((o:any)=>o.needs_attention);const noBudget=openOps.filter((o:any)=>o.labor_risk==='no_budget');
 const ticketOps=(progress||[]).filter((o:any)=>o.measurement_method==='ticket');
 const ticketReview=ticketOps.filter((o:any)=>o.quantity_review_status==='needs_review');
 return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page">
  <div className="command-hero"><div><div className="section-kicker">EARNED PRODUCTION</div><h1>Work Packages</h1><p>Known takeoff quantity, crew time and labor budget stay attached to the physical scope. Concrete placement can now take actual CY directly from matched delivery tickets.</p></div><div className="command-actions"><Link className="button secondary" href="/production">Production Control</Link><Link className="button secondary" href="/pour-control/deliveries">Concrete Tickets</Link><Link className="button secondary" href="/schedule">Schedule Crew</Link></div></div>
  <div className="command-grid"><div className="command-card"><div className="command-label">Packages</div><div className="command-value">{(packages||[]).length}</div><div className="command-help">Physical scopes ready to move from estimate to field.</div></div><div className={`command-card ${active?'watch':'good'}`}><div className="command-label">In Progress</div><div className="command-value">{active}</div><div className="command-help">Packages currently consuming crew hours.</div></div><div className={`command-card ${atRisk.length?'bad':'good'}`}><div className="command-label">Labor Risk</div><div className="command-value">{atRisk.length}</div><div className="command-help">Open operations at 80%+ of labor budget or past planned finish.</div></div><div className={`command-card ${ticketReview.length?'bad':'good'}`}><div className="command-label">Ticket Review</div><div className="command-value">{ticketReview.length}</div><div className="command-help">Concrete actuals held out of learning until checked.</div></div><div className={`command-card ${noBudget.length?'watch':'good'}`}><div className="command-label">Need Labor Plan</div><div className="command-value">{noBudget.length}</div><div className="command-help">Open scopes without budgeted man-hours yet.</div></div></div>

  {atRisk.length>0&&<section className="section"><div className="section-heading"><div><div className="section-kicker">EARLY WARNING</div><div className="section-title">Labor Is Burning Before the Work Is Finished</div><div className="section-heading-meta">No foreman percent-complete entry. Carez watches actual crew hours against the labor budget and planned finish date automatically.</div></div></div><div className="project-list">{atRisk.map((o:any)=><article className="project-card" key={`risk-${o.operation_id}`}><header className="project-header"><div><div className="project-name">{o.job_number} — {o.package_name}</div><div className="project-location">{o.field_label||o.task_name}{o.location?` · ${o.location}`:''}</div></div><span className={`status ${['critical','over_budget'].includes(o.labor_risk)?'on-hold':''}`}>{o.schedule_risk==='overdue'?'Overdue':riskLabel(o.labor_risk)}</span></header><section className="project-section"><div className="metric-grid"><div className={`metric-card ${n(o.budget_hours_used_percent)>=100?'danger-metric':'brand'}`}><div className="label">Labor Budget Used</div><div className="metric-value">{o.budget_hours_used_percent==null?'—':`${n(o.budget_hours_used_percent).toFixed(0)}%`}</div><div className="metric-detail">{mh(o.tracked_man_hours)} tracked of {mh(o.budgeted_man_hours)}</div></div><div className="metric-card"><div className="label">Hours Left</div><div className="metric-value">{mh(o.budget_man_hours_remaining)}</div></div><div className="metric-card"><div className="label">Known Scope</div><div className="metric-value">{qty(o.planned_quantity,o.unit)}</div></div></div></section></article>)}</div></section>}

  <section className="section"><div className="surface"><div className="surface-header"><div><div className="surface-title">Create Physical Work Package</div><div className="surface-subtitle">Manual bridge for now. The future takeoff engine will create these automatically.</div></div></div><div className="surface-body"><form action={createWorkPackage} className="form"><div className="grid grid2"><label className="field"><span>Job</span><select name="project_id" defaultValue="" required><option value="" disabled>Choose job</option>{(projects||[]).map((p:any)=><option key={p.id} value={p.id}>{p.job_number} — {p.name}</option>)}</select></label><label className="field"><span>Physical Package</span><input name="name" required placeholder="Basement North Wall"/></label></div><div className="grid grid2"><label className="field"><span>Location</span><input name="location" placeholder="Basement · Grid A-D"/></label><label className="field"><span>Drawing Reference</span><input name="drawing_reference" placeholder="S2.1 · Detail 4"/></label></div><div className="grid grid2"><label className="field"><span>Planned Start</span><input type="date" name="planned_start_date"/></label><label className="field"><span>Planned Finish</span><input type="date" name="planned_end_date"/></label></div><label className="field"><span>Scope Note</span><textarea name="description" rows={2} placeholder="North basement wall from corner to garage connection."/></label><button className="button">Create Work Package</button></form></div></div></section>

  <section className="section"><div className="section-heading"><div><div className="section-kicker">FIELD PLAN</div><div className="section-title">Package Operations</div><div className="section-heading-meta">Normal operations earn the known takeoff quantity on completion. CY concrete placement can use delivery tickets as the actual quantity source.</div></div></div>{(packages||[]).length===0?<div className="empty-state"><div><div className="title">Create the first package</div><div className="meta">Example: Basement North Wall → Form 1,332 SF → Rebar → Place 31.5 CY → Strip 1,332 SF.</div></div></div>:<div className="project-list">{(packages||[]).map((p:any)=>{const ops=opMap.get(p.id)||[];const done=ops.filter((o:any)=>o.operation_status==='completed').length;const risks=ops.filter((o:any)=>o.needs_attention).length;const projectPours=(pours||[]).filter((x:any)=>x.project_id===p.project_id);return <article className="project-card" key={p.id}><header className="project-header"><div><div className="project-name">{p.projects?.job_number} — {p.name}</div><div className="project-location">{p.projects?.name}{p.location?` · ${p.location}`:''}{p.drawing_reference?` · ${p.drawing_reference}`:''}</div></div><div className="action-row">{risks>0&&<span className="status on-hold">{risks} Risk</span>}<span className={`status ${p.status==='completed'?'completed':p.status==='active'?'active':''}`}>{p.status.replace('_',' ')}</span></div></header><section className="project-section"><div className="metric-grid"><div className="metric-card"><div className="label">Operations</div><div className="metric-value">{ops.length}</div></div><div className="metric-card"><div className="label">Completed</div><div className="metric-value">{done}/{ops.length}</div></div><div className="metric-card brand"><div className="label">Data Entry Rule</div><div className="metric-value">Once</div><div className="metric-detail">Use takeoff/tickets instead of field re-entry.</div></div></div>
      <div className="list section">{ops.length===0?<div className="meta">No operations yet. Add the first measurable piece of work below.</div>:ops.map((o:any)=>{const ticket=o.measurement_method==='ticket';const linkedPour=o.pour_plan_id?pourMap.get(o.pour_plan_id):null;return <div className="surface" key={o.operation_id}><div className="surface-body"><div className="row"><div><div className="title">{o.field_label||o.task_name}</div><div className="meta">{qty(o.planned_quantity,o.unit)} planned · {o.worker_count} worker{o.worker_count===1?'':'s'} tracked{o.schedule_risk==='overdue'?' · planned finish overdue':''}</div></div><div className="action-row">{ticket&&<span className="status active">Tickets</span>}{o.operation_status!=='completed'&&<span className={`status ${['critical','over_budget'].includes(o.labor_risk)?'on-hold':o.labor_risk==='watch'?'active':''}`}>{riskLabel(o.labor_risk)}</span>}<span className={`status ${o.operation_status==='completed'?'completed':o.operation_status==='in_progress'?'active':''}`}>{o.operation_status.replace('_',' ')}</span></div></div>
       <div className="grid grid4 section"><div><div className="label">Tracked</div><strong>{mh(o.tracked_man_hours)}</strong></div><div><div className="label">Budget</div><strong>{mh(o.budgeted_man_hours)}</strong></div><div><div className="label">Hours Used</div><strong>{o.budget_hours_used_percent==null?'—':`${n(o.budget_hours_used_percent).toFixed(0)}%`}</strong></div><div><div className="label">Hours Left</div><strong>{mh(o.budget_man_hours_remaining)}</strong></div></div>
       {ticket&&<div className={`alert ${o.quantity_review_status==='needs_review'?'warning':'info'} section`}><strong>Concrete tickets control this quantity.</strong><div>Plan: {qty(o.planned_quantity,o.unit)} · Ticket actual: {o.actual_quantity==null?'waiting':qty(o.actual_quantity,o.unit)}{linkedPour?` · Pour: ${linkedPour.name}`:''}</div>{o.quantity_review_reason&&<div>{o.quantity_review_reason}</div>}<div className="action-row section"><Link className="button secondary" href="/pour-control/deliveries">Open Ticket Automation</Link>{o.operation_status!=='completed'&&<form action={unlinkTicketOperation}><input type="hidden" name="operation_id" value={o.operation_id}/><button className="button secondary">Stop Ticket Automation</button></form>}</div></div>}
       {!ticket&&o.operation_status!=='completed'&&String(o.unit).toUpperCase()==='CY'&&projectPours.length>0&&<details className="section"><summary className="title" style={{cursor:'pointer'}}>Automate Quantity From Concrete Tickets</summary><form action={linkTicketOperationToPour} className="form" style={{marginTop:12}}><input type="hidden" name="operation_id" value={o.operation_id}/><label className="field"><span>Concrete Pour</span><select name="pour_plan_id" defaultValue="" required><option value="" disabled>Choose pour</option>{projectPours.map((pp:any)=><option key={pp.id} value={pp.id}>{pp.name} · {pp.scheduled_date||'date not set'} · {n(pp.expected_concrete_yards).toFixed(2)} CY · {pp.status}</option>)}</select></label><div className="meta">Carez will preserve the {qty(o.planned_quantity,o.unit)} plan and write matched ticket CY as the actual quantity.</div><button className="button secondary">Use Ticket Actuals</button></form></details>}
       {!ticket&&o.operation_status!=='completed'&&<details className="section"><summary className="title" style={{cursor:'pointer'}}>Set / Adjust Labor Plan</summary><form action={updateOperationLaborPlan} className="form" style={{marginTop:12}}><input type="hidden" name="operation_id" value={o.operation_id}/><div className="grid grid2"><label className="field"><span>MH / {o.unit}</span><input name="baseline_man_hours_per_unit" type="number" min="0" step="0.0001" defaultValue={o.baseline_man_hours_per_unit??''}/></label><label className="field"><span>Baseline Source</span><select name="baseline_source" defaultValue={o.baseline_source||'manual'}><option value="manual">Manual / unknown</option><option value="national_estimator">National Estimator</option><option value="carez_blend">Carez blended</option><option value="carez_actual">Carez actual</option></select></label></div><label className="field"><span>Budgeted Man-Hours</span><input name="budgeted_man_hours" type="number" min="0" step="0.01" defaultValue={o.budgeted_man_hours??''} placeholder="Leave blank to calculate quantity × MH/unit"/></label><button className="button secondary">Save Labor Plan</button></form></details>}
       {!ticket&&<div className="action-row section">{o.operation_status==='completed'?<form action={reopenWorkPackageOperation}><input type="hidden" name="operation_id" value={o.operation_id}/><button className="button secondary">Reopen</button></form>:<form action={completeWorkPackageOperation}><input type="hidden" name="operation_id" value={o.operation_id}/><button className="button secondary">Owner Mark Finished</button></form>}</div>}
      </div></div>;})}</div>
      <details className="section"><summary className="title" style={{cursor:'pointer'}}>Add Operation to {p.name}</summary><form action={addWorkPackageOperation} className="form" style={{marginTop:12}}><input type="hidden" name="work_package_id" value={p.id}/><div className="grid grid2"><label className="field"><span>What Work?</span><select name="production_task_id" defaultValue="" required><option value="" disabled>Choose work</option>{(tasks||[]).map((t:any)=><option key={t.id} value={t.id}>{t.name} · {t.production_unit}</option>)}</select></label><label className="field"><span>Known Takeoff Quantity</span><input type="number" min="0.01" step="0.01" name="planned_quantity" required placeholder="1332"/></label></div><div className="grid grid2"><label className="field"><span>Field Label (optional)</span><input name="field_label" placeholder="Form North Basement Wall"/></label><label className="field"><span>How Quantity Is Earned</span><select name="measurement_method" defaultValue="completion"><option value="completion">Known quantity when work is finished</option><option value="ticket">Concrete delivery tickets — CY only</option><option value="plan">Plan/location completion</option><option value="manual">Manual exception</option></select></label></div><label className="field"><span>Concrete Pour (required only for ticket method)</span><select name="pour_plan_id" defaultValue=""><option value="">Not ticket-controlled</option>{projectPours.map((pp:any)=><option key={pp.id} value={pp.id}>{pp.name} · {pp.scheduled_date||'date not set'} · {n(pp.expected_concrete_yards).toFixed(2)} CY</option>)}</select></label><div className="meta">Use ticket measurement only for work whose production unit is CY, such as placing footings or walls. Slab/sidewalk productivity stays SF from the takeoff; ticket CY is a separate material actual.</div><div className="grid grid2"><label className="field"><span>Starting MH / Unit (optional)</span><input type="number" min="0" step="0.0001" name="baseline_man_hours_per_unit" placeholder="National Estimator or known baseline"/></label><label className="field"><span>Baseline Source</span><select name="baseline_source" defaultValue="manual"><option value="manual">Manual / unknown</option><option value="national_estimator">National Estimator</option><option value="carez_blend">Carez blended</option><option value="carez_actual">Carez actual</option></select></label></div><label className="field"><span>Budgeted Man-Hours (optional)</span><input type="number" min="0" step="0.01" name="budgeted_man_hours" placeholder="Auto-calculated from MH/unit if left blank"/></label><label className="field"><span>Note</span><input name="notes" placeholder="Two-sided forms, 9 ft wall, normal access..."/></label><button className="button">Add Operation</button></form></details>
     </section></article>})}</div>}</section>

  {(learning||[]).length>0&&<section className="section"><div className="section-heading"><div><div className="section-kicker">CAREZ LEARNING</div><div className="section-title">What Our Crews Are Teaching the System</div><div className="section-heading-meta">Completed packages with approved employee time and trusted quantities only. Ticket outliers are excluded until verified.</div></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Work</th><th>Packages</th><th>Jobs</th><th>Quantity</th><th>Man-Hours</th><th>Actual</th><th>Confidence</th></tr></thead><tbody>{(learning||[]).map((x:any)=><tr key={x.production_task_id}><td><strong>{x.task_name}</strong></td><td>{x.sample_packages}</td><td>{x.sample_projects}</td><td>{qty(x.total_quantity,x.unit)}</td><td>{n(x.total_man_hours).toFixed(2)}</td><td>{n(x.weighted_man_hours_per_unit).toFixed(4)} MH/{x.unit}</td><td><span className={`status ${x.confidence==='high'?'completed':x.confidence==='medium'?'active':''}`}>{x.confidence}</span></td></tr>)}</tbody></table></div></section>}
 </div></AppShell>;
}
