'use client';

import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useEffect,useMemo,useRef,useState,useTransition} from 'react';
import {Badge,Button,DataGrid,DataGridBody,DataGridCell,DataGridHeader,DataGridHeaderCell,DataGridRow,DrawerBody,DrawerFooter,DrawerHeader,DrawerHeaderTitle,Menu,MenuItem,MenuList,MenuPopover,MenuTrigger,MessageBar,MessageBarActions,MessageBarBody,OverlayDrawer,ProgressBar,Spinner,Toolbar,Tooltip,createTableColumn,tokens} from '@fluentui/react-components';
import {VerticalBarChart} from '@fluentui/react-charts';
import {ArrowClockwiseRegular,ArrowRightRegular,DismissRegular,MoreHorizontalRegular,OpenRegular} from '@fluentui/react-icons';
import type {PourForecast} from '@/lib/weather/pourForecast';
import {TodayNewMenu} from './TodayNewMenu';

type Attention={tone:'danger'|'warning'|'info';subject:string;issue:string;when:string;href:string;action:string;urgent?:boolean;category?:string;facts?:{label:string;value:string}[]};
type PlanningJob={id:string;project:string;nextAction:string;held:boolean;href:string};
type OperationReadiness={status:'ready'|'hold';inspectionClear:number;inspectionCount:number;nextAction:string|null};
export type OverviewScheduleItem={id:string;projectId:string|null;date:string;day:string;time:string;sortTime:string;project:string;title:string;type:string;status:string;yards:number|null;crewNeeded:number|null;href:string;location:string|null;forecast:PourForecast|null;readiness?:OperationReadiness|null};
export type OverviewMetric={label:string;value:string;detail:string;href:string;tooltip?:string};
type ActiveJob={id:string;number:string;name:string;customer:string;location:string;nextPour:string;nextPourDate?:string|null;contract:string;contractValue:number|null;billing:string;billedPercent:number|null;coExposure:string;coExposureValue:number|null;status:string};
type Bid={title:string;due:string;href:string};
type CommercialAction={title:string;detail:string;href:string;label:string};
export type TodaySurfaceProps={date:string;dateISO:string;refreshedAt:string;refreshedLabel:string;weekEnd:string;outlookEnd:string;attention:Attention[];attentionUnavailable:boolean;scheduleItems:OverviewScheduleItem[];scheduleUnavailable:boolean;pourDataUnavailable:boolean;planningJobs:PlanningJob[];operationalMetrics:OverviewMetric[];activeJobs:ActiveJob[]|null;fieldMetrics:OverviewMetric[];fieldSeries:{date:string;label:string;yards:number;plannedYards:number|null}[]|null;bidQueue:Bid[]|null;bidDueQueue:Bid[]|null;pipelineSummary:{count:number;value:string;bidsDue:number;dueThisWeek:number;unavailable:boolean};commercialMetrics:OverviewMetric[];commercialAction:CommercialAction|null;preview?:boolean};
type Detail={eyebrow:string;title:string;lines:string[];href:string;action:string;facts?:{label:string;value:string}[]};
const eyebrow='text-[11px] font-bold uppercase tracking-[0.13em] text-muted-foreground';
const panel='min-w-0';
const linkClass='inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring';
const num=(n:number)=>n.toLocaleString('en-US',{maximumFractionDigits:1});
const compareKnown=(a:number|string|null|undefined,b:number|string|null|undefined,direction:'ascending'|'descending')=>{
  if(a==null||a==='')return b==null||b===''?0:direction==='ascending'?1:-1;
  if(b==null||b==='')return direction==='ascending'?-1:1;
  return typeof a==='number'&&typeof b==='number'?a-b:String(a).localeCompare(String(b));
};

function Heading({id,title,detail,href,linkLabel,emphasis=false}:{id:string;title:string;detail?:string;href?:string;linkLabel?:string;emphasis?:boolean}){
  return <div className="flex min-h-12 flex-wrap items-center justify-between gap-2 border-b border-border px-4 py-2"><div className="flex items-baseline gap-3"><h2 id={id} className={emphasis?'text-xs font-bold uppercase tracking-[0.11em] text-foreground':eyebrow}>{title}</h2>{detail?<span className="text-xs text-muted-foreground">{detail}</span>:null}</div>{href?<Link href={href} className={linkClass}>{linkLabel} <ArrowRightRegular aria-hidden="true"/></Link>:null}</div>;
}

function Chart({points,label}:{points:{date:string;label:string;yards:number}[];label:string}){
  const host=useRef<HTMLDivElement>(null),[width,setWidth]=useState(0);
  useEffect(()=>{const node=host.current;if(!node)return;const observer=new ResizeObserver(entries=>setWidth(Math.floor(entries[0].contentRect.width)));observer.observe(node);return()=>observer.disconnect();},[]);
  return <div ref={host} role="img" aria-label={label} className="min-h-[128px] w-full overflow-hidden">{width>80
    ?<VerticalBarChart width={width} height={128} hideLegend hideTooltip data={points.map(point=>({x:point.label,y:point.yards,color:tokens.colorBrandBackground,legend:`${point.label}: ${num(point.yards)} CY`}))}/>
    :<div className="flex h-[128px] items-center justify-center text-xs text-muted-foreground">Preparing chart…</div>}</div>;
}

function StatusBadge({status}:{status:string}){
  const normalized=status.toLowerCase();
  const color=normalized.includes('hold')||normalized.includes('block')?'danger':normalized.includes('review')||normalized.includes('risk')?'warning':'informative';
  const label=normalized.includes('hold')||normalized.includes('block')?'Hold':normalized.includes('review')||normalized.includes('risk')?'Review':normalized.includes('ready')||normalized.includes('clear')?'Ready':normalized.includes('plan')?'Planned':status;
  return <Badge size="small" appearance="outline" color={color}>{label}</Badge>;
}

function ProjectGrid({jobs,preview=false}:{jobs:ActiveJob[]|null;preview?:boolean}){
  const router=useRouter();
  const [sortState,setSortState]=useState<{sortColumn:string|number|undefined;sortDirection:'ascending'|'descending'}>({sortColumn:undefined,sortDirection:'ascending'});
  const columns=useMemo(()=>[
    createTableColumn<ActiveJob>({columnId:'project',compare:(a,b)=>a.name.localeCompare(b.name),renderHeaderCell:()=> 'Project',renderCell:item=><div className="min-w-0"><Link href={preview?'/projects':`/projects/${item.id}`} className="block truncate font-semibold text-foreground hover:text-primary hover:underline" title={`${item.number} · ${item.name}`}>{item.number} · {item.name}</Link><div className="truncate text-[11px] text-muted-foreground">{item.location}</div></div>}),
    createTableColumn<ActiveJob>({columnId:'customer',compare:(a,b)=>a.customer.localeCompare(b.customer),renderHeaderCell:()=> 'GC / Customer',renderCell:item=>item.customer}),
    createTableColumn<ActiveJob>({columnId:'nextPour',compare:(a,b)=>compareKnown(a.nextPourDate,b.nextPourDate,sortState.sortDirection),renderHeaderCell:()=> 'Next pour',renderCell:item=>item.nextPour}),
    createTableColumn<ActiveJob>({columnId:'contract',compare:(a,b)=>compareKnown(a.contractValue,b.contractValue,sortState.sortDirection),renderHeaderCell:()=> 'Contract',renderCell:item=><span className="font-mono tabular-nums">{item.contract}</span>}),
    createTableColumn<ActiveJob>({columnId:'billing',compare:(a,b)=>compareKnown(a.billedPercent,b.billedPercent,sortState.sortDirection),renderHeaderCell:()=> 'Billed',renderCell:item=><div className="min-w-0"><span className="font-mono tabular-nums">{item.billing}</span>{item.billedPercent!==null?<div className="mt-1 flex items-center gap-2"><ProgressBar value={Math.min(100,item.billedPercent)} max={100} className="min-w-10 max-w-16 flex-1"/><span className="font-mono text-[11px] text-muted-foreground tabular-nums">{item.billedPercent.toFixed(1)}%</span></div>:null}</div>}),
    createTableColumn<ActiveJob>({columnId:'coExposure',compare:(a,b)=>compareKnown(a.coExposureValue,b.coExposureValue,sortState.sortDirection),renderHeaderCell:()=> 'Open COs',renderCell:item=><span className="font-mono tabular-nums">{item.coExposure}</span>}),
    createTableColumn<ActiveJob>({columnId:'status',compare:(a,b)=>a.status.localeCompare(b.status),renderHeaderCell:()=> 'Status',renderCell:item=><StatusBadge status={item.status}/>}),
    createTableColumn<ActiveJob>({columnId:'actions',renderHeaderCell:()=> 'Actions',renderCell:item=><Menu><MenuTrigger disableButtonEnhancement><Button size="small" appearance="subtle" icon={<MoreHorizontalRegular/>} aria-label={`Actions for ${item.name}`}/></MenuTrigger><MenuPopover><MenuList><MenuItem onClick={()=>router.push(preview?'/projects':`/projects/${item.id}`)}>Open project</MenuItem><MenuItem onClick={()=>router.push('/field?view=schedule')}>Open schedule</MenuItem></MenuList></MenuPopover></Menu>}),
  ],[router,preview,sortState.sortDirection]);
  return <div className="overflow-x-auto"><div className="min-w-[1000px]"><DataGrid items={jobs||[]} columns={columns} sortable sortState={sortState} onSortChange={(_,next)=>setSortState(next)} size="small" getRowId={item=>item.id} aria-label="Active projects" className="w-full"><DataGridHeader className="dashboard-project-grid-head"><DataGridRow>{({renderHeaderCell})=><DataGridHeaderCell>{renderHeaderCell()}</DataGridHeaderCell>}</DataGridRow></DataGridHeader><DataGridBody<ActiveJob>>{({item,rowId})=><DataGridRow<ActiveJob> key={rowId}>{({renderCell})=><DataGridCell focusMode="group">{renderCell(item)}</DataGridCell>}</DataGridRow>}</DataGridBody></DataGrid></div>{!jobs?.length?<div className="border-t border-border px-4 py-6"><p className="text-sm font-semibold">{jobs===null?'Projects could not be refreshed.':'No active jobs yet.'}</p><p className="mt-1 text-xs text-muted-foreground">{jobs===null?'Try refreshing the Dashboard.':'Awarded projects and direct work will appear here.'}</p><div className="mt-3 flex gap-4"><Link className={linkClass} href="/projects">Create project <ArrowRightRegular/></Link><Link className={linkClass} href="/opportunities">View opportunities <ArrowRightRegular/></Link></div></div>:null}</div>;
}

export function TodaySurface({date,dateISO,refreshedAt,refreshedLabel,weekEnd,outlookEnd,attention,attentionUnavailable,scheduleItems,scheduleUnavailable,pourDataUnavailable,planningJobs,operationalMetrics,activeJobs,fieldMetrics,fieldSeries,bidQueue,bidDueQueue,pipelineSummary,commercialMetrics,commercialAction,preview=false}:TodaySurfaceProps){
  const router=useRouter(),[refreshing,startRefresh]=useTransition(),[detail,setDetail]=useState<Detail|null>(null);
  const allAttention=[...attention,...planningJobs.map(job=>({tone:job.held?'danger' as const:'info' as const,category:job.held?'Scheduling hold':'Needs scheduling',subject:job.project,issue:job.nextAction,when:'Needs scheduling',href:job.href,action:'Open project'}))];
  const nextPour=scheduleItems.find(item=>item.type==='pour'&&item.date<=new Date(new Date(`${dateISO}T12:00:00`).getTime()+6*86400000).toISOString().slice(0,10));
  const outlook=scheduleItems.filter(item=>item.type==='pour');
  const planned=Array.from({length:14},(_,index)=>{const current=new Date(`${dateISO}T12:00:00`);current.setDate(current.getDate()+index);const day=current.toISOString().slice(0,10);return {date:day,label:new Intl.DateTimeFormat('en-US',{month:'numeric',day:'numeric'}).format(current),yards:outlook.filter(item=>item.date===day).reduce((sum,item)=>sum+(item.yards||0),0)};});
  const fieldHasData=Boolean(fieldSeries?.some(point=>point.yards>0));
  const plannedHasData=planned.some(point=>point.yards>0);
  const showDetail=(item:Attention)=>setDetail({eyebrow:item.category|| (item.tone==='danger'?'Verified hold':'Needs attention'),title:item.issue,lines:[item.subject,item.when],facts:item.facts,href:item.href,action:item.action});
  const showPour=(item:OverviewScheduleItem)=>setDetail({eyebrow:'Pour window',title:item.project,lines:[`${item.day} · ${item.time}`,item.title,item.yards==null?'Planned CY not recorded':`${num(item.yards)} CY planned`,item.crewNeeded==null?'Crew need not recorded':`${item.crewNeeded} crew needed`,item.location||'Location not entered',item.forecast?`${item.forecast.condition} · ${item.forecast.low}–${item.forecast.high}°F`:'Forecast unavailable',item.readiness?`Operation readiness: ${item.readiness.status}${item.readiness.nextAction?` · ${item.readiness.nextAction}`:''}`:'Operation readiness not recorded',`Schedule: ${item.status}`],href:item.href,action:'Open Field schedule'});
  return <div className="pourtrace-dashboard mx-auto w-full max-w-[1600px] space-y-4 px-4 py-4 text-foreground sm:px-5 min-[2200px]:max-w-[1720px] lg:px-6 lg:py-5">
    <header className="border-b border-border pb-3">
      <div><p className={eyebrow}>Dashboard {preview?<span className="ml-2 text-primary">· Sample data preview</span>:null}</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-[30px]">Company Command Center</h1><time dateTime={dateISO} className="mt-1 block text-xs text-muted-foreground">{date}</time>{preview?<p className="mt-1 text-xs text-muted-foreground">Illustrative records only. Links open live workspaces.</p>:null}</div>
    </header>
    <div className="dashboard-command-toolbar sticky top-0 z-30 -mx-4 flex min-h-12 items-center justify-between gap-2 px-4 sm:-mx-5 sm:px-5 lg:-mx-6 lg:px-6">
      <span className="text-[11px] font-bold uppercase tracking-[0.13em] text-muted-foreground">Dashboard</span>
      <Toolbar aria-label="Dashboard commands" className="gap-1">
        <Tooltip content="Refresh recorded company activity" relationship="description"><Button size="small" appearance="subtle" icon={refreshing?<Spinner size="tiny"/>:<ArrowClockwiseRegular/>} disabled={refreshing} onClick={()=>startRefresh(()=>router.refresh())}>Refresh</Button></Tooltip>
        <time dateTime={refreshedAt} className="hidden px-2 text-[11px] text-muted-foreground sm:block">Updated {refreshedLabel}</time>
        <Menu><MenuTrigger disableButtonEnhancement><Button size="small" appearance="subtle" icon={<MoreHorizontalRegular/>} aria-label="More Dashboard actions"/></MenuTrigger><MenuPopover><MenuList><MenuItem onClick={()=>router.push('/reports')}>Open owner reports</MenuItem><MenuItem onClick={()=>router.push('/field?view=schedule')}>Open full schedule</MenuItem></MenuList></MenuPopover></Menu><TodayNewMenu/>
      </Toolbar>
    </div>
    <section aria-label="Live company status" className="dashboard-kpi-rail grid grid-cols-2 border-y sm:grid-cols-3 xl:grid-cols-6">{operationalMetrics.map(metric=>{
      const cell=<Link key={metric.label} href={metric.href} className="group min-w-0 border-b border-r border-border px-4 py-4 outline-none hover:bg-[var(--pt-surface-hover)] focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring xl:border-b-0"><span className="text-[10px] font-bold uppercase tracking-[0.13em] text-muted-foreground">{metric.label}</span><strong className="mt-1 block truncate font-mono text-[28px] font-semibold leading-tight tabular-nums group-hover:text-primary">{metric.value}</strong><span className="mt-1 block truncate text-[11px] text-muted-foreground">{metric.detail}</span></Link>;
      return metric.tooltip?<Tooltip key={metric.label} content={metric.tooltip} relationship="description">{cell}</Tooltip>:cell;
    })}</section>
    <div className="grid min-w-0 grid-cols-12 gap-4">
      <section aria-labelledby="attention-heading" className={`${panel} dashboard-decision col-span-12 lg:col-span-7`} style={{boxShadow:tokens.shadow2}}>
        <Heading id="attention-heading" title="Work requiring attention" detail={attentionUnavailable?'Status incomplete':`${allAttention.length} recorded items`} href="/projects" linkLabel="View work" emphasis/>
        {attentionUnavailable?<MessageBar intent="warning" className="m-3"><MessageBarBody>Some activity could not be refreshed. Check current work before making a decision.</MessageBarBody><MessageBarActions><Button size="small" onClick={()=>startRefresh(()=>router.refresh())}>Retry</Button></MessageBarActions></MessageBar>:null}
        {allAttention.length?<div className="divide-y divide-border">{allAttention.slice(0,6).map((item,index)=><button key={`${item.subject}-${index}`} type="button" onClick={()=>showDetail(item)} className="flex w-full items-start justify-between gap-4 px-4 py-3 text-left hover:bg-[var(--pt-surface-hover)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring"><span className="min-w-0"><span className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-[0.12em] text-primary">{item.category|| (item.tone==='danger'?'Verified hold':'Needs attention')}</span>{item.tone!=='info'?<Badge size="small" appearance="outline" color={item.tone==='danger'?'danger':'warning'}>{item.tone==='danger'?'Hold':'Review'}</Badge>:null}</span><strong className="mt-1 block text-sm">{item.issue}</strong><span className="mt-0.5 block text-xs text-muted-foreground">{item.subject}</span></span><span className="flex shrink-0 items-center gap-2 text-[11px] text-muted-foreground"><span className="hidden sm:inline">{item.when}</span><ArrowRightRegular className="size-3.5" aria-hidden="true"/></span></button>)}</div>:<div className="px-4 py-5"><p className="text-sm font-semibold">{attentionUnavailable?'No recorded attention items are currently available.':'Clear for now'}</p><p className="mt-1 text-xs text-muted-foreground">{attentionUnavailable?'Some project activity could not be refreshed.':'No recorded holds or due actions need attention.'}</p></div>}
      </section>
      <section aria-labelledby="next-pour-heading" className={`${panel} dashboard-decision dashboard-decision--pour col-span-12 lg:col-span-5`} style={{boxShadow:tokens.shadow4}}>
        <Heading id="next-pour-heading" title="Today / next pour" detail={`through ${weekEnd}`}/>
        {scheduleUnavailable||pourDataUnavailable?<MessageBar intent="warning" className="m-3"><MessageBarBody>Some pour windows could not be refreshed.</MessageBarBody></MessageBar>:null}
        {nextPour?<div className="px-4 py-4">
          <div className="flex items-start justify-between gap-3"><div><span className="font-mono text-2xl font-semibold tabular-nums">{nextPour.time}</span><h3 className="mt-2 text-lg font-semibold">{nextPour.project}</h3><p className="mt-0.5 text-sm text-muted-foreground">{nextPour.title} · {nextPour.day}</p></div><StatusBadge status={nextPour.readiness?.status==='hold'?'Hold':nextPour.readiness?.status==='ready'?'Ready':nextPour.status}/></div>
          <div className="mt-4 grid grid-cols-3 divide-x divide-border border-y border-border py-3"><div className="pr-3"><strong className="block font-mono text-lg tabular-nums">{nextPour.yards==null?'—':`${num(nextPour.yards)} CY`}</strong><span className="text-xs text-muted-foreground">Planned concrete</span></div><div className="px-3"><strong className="block font-mono text-lg tabular-nums">{nextPour.crewNeeded==null?'—':nextPour.crewNeeded}</strong><span className="text-xs text-muted-foreground">Crew needed</span></div><div className="min-w-0 pl-3"><strong className="block truncate text-sm font-semibold">{nextPour.location||'—'}</strong><span className="text-xs text-muted-foreground">Location</span></div></div>
          <div className="mt-4"><div className="flex items-center justify-between gap-3"><span className={eyebrow}>Recorded operation prerequisites</span>{nextPour.readiness?<span className="text-xs font-medium">{nextPour.readiness.status==='hold'?'Hold':'Clear'}</span>:null}</div>{nextPour.readiness?.inspectionCount?<div className="mt-2"><div className="flex justify-between text-xs text-muted-foreground"><span>Required inspections</span><span className="font-mono tabular-nums">{nextPour.readiness.inspectionClear} / {nextPour.readiness.inspectionCount} clear</span></div><ProgressBar value={nextPour.readiness.inspectionClear} max={nextPour.readiness.inspectionCount} className="mt-1"/></div>:null}{nextPour.readiness?.status==='hold'&&nextPour.readiness.nextAction?<p className="mt-2 text-xs text-destructive">{nextPour.readiness.nextAction}</p>:null}{!nextPour.readiness?<p className="mt-2 text-xs text-muted-foreground">No linked operation readiness record.</p>:null}</div>
          {nextPour.forecast?<p className="mt-4 border-t border-border pt-3 text-xs text-muted-foreground">Weather · {nextPour.forecast.condition}, {nextPour.forecast.low}–{nextPour.forecast.high}°F · {nextPour.forecast.precipitation}% rain</p>:null}
          <div className="mt-4 flex gap-2"><Button size="small" appearance="primary" onClick={()=>showPour(nextPour)}>Inspect pour</Button><Button size="small" appearance="subtle" onClick={()=>router.push('/field?view=schedule')}>Open schedule</Button></div>
        </div>:<div className="px-4 py-5"><p className="text-sm font-semibold">No concrete scheduled in the next 7 days.</p><p className="mt-1 text-xs text-muted-foreground">Build a pour window when the job is ready to plan.</p><Button size="small" appearance="primary" className="mt-4" onClick={()=>router.push('/field?view=schedule')}>Build pour window</Button></div>}
      </section>
    </div>
    <section aria-labelledby="projects-heading" className={`${panel} dashboard-projects`}><Heading id="projects-heading" title="Active projects" detail={activeJobs==null?'Unavailable':`${activeJobs.length} jobs`} href="/projects" linkLabel="View projects"/><ProjectGrid jobs={activeJobs} preview={preview}/></section>
    <div className="grid min-w-0 grid-cols-12 gap-4">
      <section aria-labelledby="field-heading" className={`${panel} dashboard-field col-span-12 xl:col-span-7`}><Heading id="field-heading" title="Field pulse / last 7 days" href="/field" linkLabel="Open field"/><div className="dashboard-field-metrics grid grid-cols-2 divide-x divide-border border-b border-border sm:grid-cols-4">{fieldMetrics.map(metric=><Link href={metric.href} key={metric.label} className="min-w-0 px-4 py-3 hover:bg-[var(--pt-surface-hover)]"><strong className="block truncate font-mono text-xl font-semibold tabular-nums">{metric.value}</strong><span className="mt-1 block text-[11px] font-semibold text-foreground">{metric.label}</span><span className="block text-[11px] text-muted-foreground">{metric.detail}</span></Link>)}</div><div className="dashboard-field-chart px-4 py-3"><span className={eyebrow}>Concrete placed by day · CY</span>{fieldHasData&&fieldSeries?<><Chart points={fieldSeries} label={`Concrete placed in the last seven days: ${fieldSeries.map(point=>`${point.label}, ${num(point.yards)} CY`).join('; ')}`}/><div className="mt-2 grid grid-cols-7 gap-1 border-t border-border pt-2">{fieldSeries.map(point=><div key={point.date} className="min-w-0 text-center"><span className="block text-[10px] uppercase text-muted-foreground">{new Intl.DateTimeFormat('en-US',{weekday:'short',timeZone:'UTC'}).format(new Date(`${point.date}T12:00:00Z`))}</span><strong className="block truncate font-mono text-xs tabular-nums">{num(point.yards)} CY</strong>{point.plannedYards!==null?<span className="block truncate text-[11px] text-muted-foreground">Plan {num(point.plannedYards)}</span>:null}</div>)}</div></>:<div className="py-4"><p className="text-xs text-muted-foreground">{fieldSeries?'No concrete recorded in the last 7 days.':'Recorded production could not be refreshed.'}</p>{fieldSeries?<Link className={`mt-2 ${linkClass}`} href="/field?view=production">Open field production <ArrowRightRegular/></Link>:null}</div>}</div></section>
      <section aria-labelledby="financial-heading" className={`${panel} dashboard-decision col-span-12 xl:col-span-5`} style={{boxShadow:tokens.shadow2}}>
        <Heading id="financial-heading" title="Financial command" href="/financials?tab=billing&view=billing" linkLabel="Open financials"/>
        <div className="grid grid-cols-2">{commercialMetrics.map((metric,index)=><Link href={metric.href} key={metric.label} className={`min-w-0 border-b border-border px-4 py-4 hover:bg-[var(--pt-surface-hover)] ${index%2?'border-l':''}`}><span className={eyebrow}>{metric.label}</span><strong className="mt-1 block truncate font-mono text-[23px] font-semibold leading-tight tabular-nums">{metric.value}</strong><span className="mt-1 block truncate text-xs text-muted-foreground">{metric.detail}</span></Link>)}</div>
        {commercialAction?<button type="button" onClick={()=>setDetail({eyebrow:'Commercial action',title:commercialAction.title,lines:[commercialAction.detail],href:commercialAction.href,action:commercialAction.label})} className="flex w-full items-center justify-between gap-2 px-4 py-3 text-left text-xs font-semibold text-primary hover:bg-[var(--pt-surface-hover)]">Next financial action · {commercialAction.title}<ArrowRightRegular/></button>:null}
      </section>
    </div>
    <div className="grid min-w-0 grid-cols-12 gap-4 pb-4">
      <section aria-labelledby="pipeline-heading" className={`${panel} dashboard-reference col-span-12 lg:col-span-4`}>
        <Heading id="pipeline-heading" title="Bid pipeline" href="/opportunities" linkLabel="View opportunities"/>
        {pipelineSummary.unavailable?<p className="px-4 py-5 text-xs text-muted-foreground">Bid activity could not be refreshed.</p>:<>
          <div className="grid grid-cols-2 gap-3 border-b border-border px-4 py-4"><div><span className={eyebrow}>Proposals out</span><strong className="mt-1 block font-mono text-2xl">{pipelineSummary.count}</strong></div><div><span className={eyebrow}>Pending value</span><strong className="mt-1 block font-mono text-xl">{pipelineSummary.value}</strong></div></div>
          <div className="px-4 py-3"><span className={eyebrow}>Bids due this week · {pipelineSummary.bidsDue}</span>{bidDueQueue?.length?bidDueQueue.map(bid=><Link key={`${bid.href}-${bid.title}`} href={bid.href} className="flex justify-between gap-2 border-b border-border py-2 text-xs hover:text-primary"><span className="truncate">{bid.title}</span><span className="whitespace-nowrap text-muted-foreground">{bid.due}</span></Link>):<p className="py-3 text-xs text-muted-foreground">No bids due this week.</p>}</div>
          <div className="border-t border-border px-4 py-3"><span className={eyebrow}>Proposal follow-ups · {pipelineSummary.dueThisWeek}</span>{bidQueue?.length?bidQueue.map(bid=><Link key={`${bid.href}-${bid.title}`} href={bid.href} className="flex justify-between gap-2 border-b border-border py-2 text-xs hover:text-primary"><span className="truncate">{bid.title}</span><span className="whitespace-nowrap text-muted-foreground">{bid.due}</span></Link>):<p className="py-3 text-xs text-muted-foreground">No proposal follow-ups due this week.</p>}</div>
        </>}
      </section>
      <section aria-labelledby="outlook-heading" className={`${panel} dashboard-reference col-span-12 lg:col-span-8`}>
        <Heading id="outlook-heading" title="14-day pour / crew outlook" detail={`through ${outlookEnd}`} href="/field?view=schedule" linkLabel="Open schedule"/>
        {scheduleUnavailable||pourDataUnavailable?<p className="px-4 py-5 text-xs text-muted-foreground">Pour outlook could not be refreshed.</p>:<>
          <div className="px-4 py-3"><span className={eyebrow}>Planned concrete · next 14 days</span>{plannedHasData?<Chart points={planned} label={`Planned concrete for the next fourteen days: ${planned.map(point=>`${point.label}, ${num(point.yards)} CY`).join('; ')}`}/>:<div className="py-4"><p className="text-sm font-semibold">{outlook.length?'Planned concrete quantity is not recorded.':'No pour windows scheduled.'}</p><Link className={`mt-2 ${linkClass}`} href="/field?view=schedule">Build pour window <ArrowRightRegular/></Link></div>}</div>
          {outlook.length?<div className="divide-y divide-border border-t border-border">{outlook.slice(0,4).map(pour=><button key={pour.id} type="button" onClick={()=>showPour(pour)} className="flex w-full items-center justify-between gap-3 px-4 py-2 text-left text-xs hover:bg-[var(--pt-surface-hover)]"><span className="min-w-0"><span className="font-mono text-muted-foreground">{pour.day}</span><strong className="ml-3">{pour.project}</strong><span className="ml-2 text-muted-foreground">{pour.title}{pour.crewNeeded==null?'':` · Crew ${pour.crewNeeded}`}</span></span><span className="flex shrink-0 items-center gap-3"><span className="whitespace-nowrap font-mono tabular-nums">{pour.yards==null?'—':`${num(pour.yards)} CY`}</span><StatusBadge status={pour.readiness?.status==='hold'?'Hold':pour.readiness?.status==='ready'?'Ready':pour.status}/></span></button>)}</div>:null}
        </>}
      </section>
    </div>
    <OverlayDrawer open={Boolean(detail)} onOpenChange={(_,data)=>{if(!data.open)setDetail(null)}} position="end" size="medium" style={{boxShadow:tokens.shadow28}}>
      <DrawerHeader><DrawerHeaderTitle action={<Button appearance="subtle" icon={<DismissRegular/>} aria-label="Close detail" onClick={()=>setDetail(null)}/>}>{detail?.title}</DrawerHeaderTitle></DrawerHeader>
      <DrawerBody><p className={eyebrow}>{detail?.eyebrow}</p>{detail?.facts?.length?<dl className="mt-4 grid grid-cols-2 gap-x-4 border-y border-border">{detail.facts.map(fact=><div key={fact.label} className="border-b border-border py-3"><dt className={eyebrow}>{fact.label}</dt><dd className="mt-1 text-sm font-semibold">{fact.value}</dd></div>)}</dl>:null}<div className="mt-4 divide-y divide-border border-y border-border">{detail?.lines.map((line,index)=><p key={index} className="py-3 text-sm">{line}</p>)}</div></DrawerBody>
      <DrawerFooter>{detail?<Button as="a" href={detail.href} appearance="primary" icon={<OpenRegular/>}>{detail.action}</Button>:null}</DrawerFooter>
    </OverlayDrawer>
  </div>;
}
