import Link from 'next/link';
import { ArrowUpRightRegular as ArrowUpRight, MoneyRegular as Banknote, CalendarMonthRegular as CalendarDays, CheckmarkCircleRegular as CheckCheck, PersonWrenchRegular as HardHat, ShieldErrorRegular as ShieldAlert, WalletRegular as Wallet } from '@fluentui/react-icons';
import {MetricBentoTile} from '@/components/projects/MetricBentoTile';
import {PourWeatherBadge} from '@/components/weather/PourWeatherBadge';
import {TodayBusinessPulse} from './TodayBusinessPulse';
import {cn} from '@/lib/utils';

type Attention={tone:'danger'|'warning'|'info';subject:string;issue:string;when:string;href:string;action:string;urgent?:boolean;timestamp?:string};
type FieldWork={id:string;project:string;title:string;time:string;href:string};
type Operation={id:string;time:string;project:string;operation:string;status:string;tone:'success'|'blocked'|'neutral';href:string};
type PlanningJob={id:string;project:string;nextAction:string;held:boolean;href:string};
type Metric={label:string;value:number|null;detail:string;prefix?:string;tone?:'neutral'|'danger'|'warning'|'success'};
type TodaySurfaceProps={date:string;dateISO:string;weekEnd:string;attention:Attention[];fieldWork:FieldWork[];scheduleUnavailable:boolean;operations:Operation[];planningJobs:PlanningJob[];metrics:readonly Metric[];openLeads:string;openProposals:string;proposalValue:string;nextFollowUp:string;customersOwe:string;expectedIn:string;expectedOut:string;cashNet:string};

const metricIcons=[CheckCheck,HardHat,ShieldAlert,Wallet,Banknote] as const;
const card='surface-card min-w-0 rounded-md';
const heading='text-xs font-semibold uppercase tracking-wider text-muted-foreground';
const iconLink='inline-flex size-8 shrink-0 items-center justify-center rounded-sm text-foreground outline-none transition-opacity hover:bg-accent focus-visible:opacity-100 focus-visible:ring-1 focus-visible:ring-ring lg:opacity-0 lg:group-hover:opacity-100';

function InboxLink({href,label}:{href:string;label:string}){return <Link href={href} aria-label={label} title={label} className={iconLink}><ArrowUpRight aria-hidden="true" className="size-4"/></Link>;}
function TimelineItem({eyebrow,title,detail,href,tone='neutral'}:{eyebrow:string;title:string;detail:string;href:string;tone?:'neutral'|'success'|'blocked'}){return <div className="relative ml-1 border-l border-border pb-3 pl-4 last:pb-1"><span className={cn('absolute -left-[5px] top-1 size-2 rounded-full',tone==='blocked'?'bg-destructive':tone==='success'?'bg-success':'bg-muted-foreground')}/><div className="flex items-start justify-between gap-2"><div className="min-w-0"><span className="font-mono text-[10px] text-muted-foreground">{eyebrow}</span><p className="truncate text-xs font-semibold">{title}</p><p className="truncate text-xs text-muted-foreground">{detail}</p></div><Link href={href} aria-label={`Open ${title}`} className="shrink-0 text-foreground"><ArrowUpRight aria-hidden="true" className="size-4"/></Link></div></div>;}

export function TodaySurface({date,dateISO,weekEnd,attention,fieldWork,scheduleUnavailable,operations,planningJobs,metrics,openLeads,openProposals,proposalValue,nextFollowUp,customersOwe,expectedIn,expectedOut,cashNet}:TodaySurfaceProps){
  const inboxCount=attention.length+planningJobs.length;
  const now=Date.now();
  return <div className="flex min-h-full min-w-0 flex-col gap-3 p-3 text-foreground lg:h-full lg:min-h-0 lg:overflow-hidden">
    <header className="industrial-header flex shrink-0 flex-wrap items-end justify-between gap-3 px-3 py-2"><div><h1 className="text-2xl font-bold tracking-tight">Overview</h1><div className="mt-2 flex flex-wrap items-center gap-3"><time dateTime={dateISO} className="text-sm text-muted-foreground">{date}</time><PourWeatherBadge/></div></div><p className="text-xs text-muted-foreground">{inboxCount?`${inboxCount} item${inboxCount===1?'':'s'} need review or scheduling`:'All current work is accounted for'}</p></header>

    <section aria-labelledby="today-status-heading" className="shrink-0"><div className="mb-2 flex flex-wrap items-baseline justify-between gap-2"><h2 id="today-status-heading" className={heading}>Operating summary</h2><span className="text-xs text-muted-foreground">Current projects · {date} to {weekEnd}</span></div><div className="grid grid-cols-2 gap-2 md:grid-cols-3 lg:grid-cols-5">{metrics.map((metric,index)=>{const Icon=metricIcons[index];return <MetricBentoTile key={metric.label} title={metric.label} value={metric.value} prefix={metric.prefix} icon={<Icon/>} tone={metric.tone} description={metric.value===null?'Data unavailable':metric.detail}/>;})}</div></section>

    <div className="grid min-h-0 flex-1 gap-3 lg:grid-cols-12 lg:overflow-hidden">
    <section aria-labelledby="today-attention-heading" className={cn(card,'flex min-h-0 flex-col lg:col-span-8 lg:overflow-hidden')}><div className="industrial-header flex shrink-0 items-center justify-between px-4 py-3"><h2 id="today-attention-heading" className={heading}>Action inbox</h2><span className="font-mono text-xs text-muted-foreground">{inboxCount} open</span></div>
      {inboxCount?<div className="lg:min-h-0 lg:flex-1 lg:overflow-y-auto">{attention.map((item,index)=>{const aged=Boolean(item.timestamp&&Number.isFinite(Date.parse(item.timestamp))&&now-Date.parse(item.timestamp)>86_400_000),urgent=Boolean(item.urgent||aged);return <article key={`${item.subject}-${index}`} className={cn('group flex min-w-0 items-center gap-3 border-b border-border border-l-2 px-3 py-2 last:border-b-0 hover:bg-accent',urgent?'border-l-destructive':'border-l-transparent')}><ShieldAlert aria-hidden="true" className={cn('size-4 shrink-0',urgent?'text-destructive motion-safe:animate-pulse':item.tone==='warning'?'text-warning':'text-info')}/><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold">{item.subject}</h3><p className="truncate text-xs text-muted-foreground">{item.issue}</p></div><span className="hidden shrink-0 text-[11px] text-muted-foreground sm:block">{item.when}</span><InboxLink href={item.href} label={`${item.action}: ${item.subject}`}/></article>;})}
        {planningJobs.map(job=><article key={job.id} className="group flex min-w-0 items-center gap-3 border-b border-border border-l-2 border-l-transparent px-3 py-2 last:border-b-0 hover:bg-accent"><CalendarDays aria-hidden="true" className="size-4 shrink-0 text-info"/><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold">{job.project}</h3><p className="truncate text-xs text-muted-foreground">{job.nextAction}</p></div><span className="hidden shrink-0 text-[11px] text-muted-foreground sm:block">Needs scheduling</span><InboxLink href={job.href} label={`${job.held?'Clear hold':'Open project'}: ${job.project}`}/></article>)}</div>:<div className="flex min-h-36 flex-col items-center justify-center gap-2 px-4 py-8 text-center lg:min-h-0 lg:flex-1 lg:overflow-y-auto"><CheckCheck aria-hidden="true" className="size-7 text-success"/><h3 className="text-sm font-semibold text-success">Zero inbox</h3><p className="text-xs text-muted-foreground">No actions or scheduling decisions are waiting.</p></div>}
    </section>

    <div className="flex min-h-0 min-w-0 flex-col gap-3 lg:col-span-4 lg:overflow-hidden"><section aria-labelledby="today-logistics-heading" className={cn(card,'flex min-h-0 flex-1 flex-col lg:overflow-hidden')}><div className="industrial-header flex shrink-0 items-center justify-between px-4 py-3"><h2 id="today-logistics-heading" className={heading}>Logistics timeline</h2><span className="text-[11px] text-muted-foreground">{fieldWork.length} today · {operations.length} upcoming</span></div>
        {scheduleUnavailable?<p className="p-4 text-xs text-muted-foreground lg:min-h-0 lg:flex-1 lg:overflow-y-auto">Schedule unavailable. <Link href="/field?view=schedule" className="text-foreground underline">Open schedule</Link> to try again.</p>:fieldWork.length||operations.length?<div className="px-4 py-3 lg:min-h-0 lg:flex-1 lg:overflow-y-auto">{fieldWork.length?<h3 id="today-work-heading" className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Field today</h3>:null}{fieldWork.map(item=><TimelineItem key={item.id} eyebrow={item.time} title={item.project} detail={item.title} href={item.href} tone="success"/>)}{operations.length?<h3 id="today-operations-heading" className="mb-2 mt-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Upcoming operations</h3>:null}{operations.map(item=><TimelineItem key={item.id} eyebrow={`${item.time} · ${item.status}`} title={item.project} detail={item.operation} href={item.href} tone={item.tone}/>)}</div>:<div className="flex min-h-44 flex-col items-center justify-center gap-2 px-4 py-6 text-center lg:min-h-0 lg:flex-1 lg:overflow-y-auto"><svg aria-hidden="true" viewBox="0 0 104 52" className="h-12 w-24 fill-none stroke-border"><path d="M8 8h88M8 26h88M8 44h88M22 5v42M54 5v42M85 5v42" strokeWidth="1"/><circle cx="22" cy="26" r="4"/><circle cx="54" cy="8" r="4"/></svg><p className="text-xs text-muted-foreground">No field operations are scheduled.</p><Link href="/field?view=schedule" className="inline-flex items-center gap-1 rounded-sm px-2 py-1 text-xs text-foreground hover:bg-accent">Schedule now <ArrowUpRight aria-hidden="true" className="size-3.5"/></Link></div>}
      </section>
      <TodayBusinessPulse openLeads={openLeads} openProposals={openProposals} proposalValue={proposalValue} nextFollowUp={nextFollowUp} customersOwe={customersOwe} expectedIn={expectedIn} expectedOut={expectedOut} cashNet={cashNet}/>
    </div>
    </div>
  </div>;
}
