import Link from 'next/link';
import {ArrowUpRight,Banknote,CalendarDays,CheckCheck,HardHat,ShieldAlert,Wallet} from 'lucide-react';
import {MetricBentoTile} from '@/components/projects/MetricBentoTile';
import {PourWeatherBadge} from '@/components/ui/PourWeatherBadge';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {cn} from '@/lib/utils';

type Attention={tone:'danger'|'warning'|'info';subject:string;issue:string;when:string;href:string;action:string;urgent?:boolean;timestamp?:string};
type FieldWork={id:string;project:string;title:string;time:string;href:string};
type Operation={id:string;time:string;project:string;operation:string;status:string;tone:'success'|'blocked'|'neutral';href:string};
type PlanningJob={id:string;project:string;nextAction:string;held:boolean;href:string};
type Metric={label:string;value:number|null;detail:string;prefix?:string;tone?:'neutral'|'danger'|'warning'|'success'};
type TodaySurfaceProps={date:string;dateISO:string;weekEnd:string;attention:Attention[];fieldWork:FieldWork[];scheduleUnavailable:boolean;operations:Operation[];planningJobs:PlanningJob[];metrics:readonly Metric[];openLeads:string;openProposals:string;proposalValue:string;nextFollowUp:string;customersOwe:string;expectedIn:string;expectedOut:string;cashNet:string};

const metricIcons=[CheckCheck,HardHat,ShieldAlert,Wallet,Banknote] as const;
const card='surface-card min-w-0 overflow-hidden rounded-md';
const heading='text-xs font-semibold uppercase tracking-wider text-[#525C57] dark:text-[#B6BEBA]';
const iconLink='inline-flex size-8 shrink-0 items-center justify-center rounded-sm text-[#007A52] outline-none transition-opacity hover:bg-[#E9EDEA] focus-visible:opacity-100 focus-visible:ring-1 focus-visible:ring-[#007A52] dark:text-[#009966] dark:hover:bg-[#25292C] dark:focus-visible:ring-[#009966] lg:opacity-0 lg:group-hover:opacity-100';

function InboxLink({href,label}:{href:string;label:string}){return <Link href={href} aria-label={label} title={label} className={iconLink}><ArrowUpRight aria-hidden="true" className="size-4"/></Link>;}
function TimelineItem({eyebrow,title,detail,href,tone='neutral'}:{eyebrow:string;title:string;detail:string;href:string;tone?:'neutral'|'success'|'blocked'}){return <div className="relative ml-1 border-l border-[#D4DBD7] pb-3 pl-4 last:pb-1 dark:border-[#343A3F]"><span className={cn('absolute -left-[5px] top-1 size-2 rounded-full',tone==='blocked'?'bg-[#B84558] dark:bg-[#E06B74]':tone==='success'?'bg-[#347A46] dark:bg-[#6DBB77]':'bg-[#7B8580] dark:bg-[#7C8580]')}/><div className="flex items-start justify-between gap-2"><div className="min-w-0"><span className="font-mono text-[10px] text-[#7B8580] dark:text-[#7C8580]">{eyebrow}</span><p className="truncate text-xs font-semibold">{title}</p><p className="truncate text-xs text-[#525C57] dark:text-[#B6BEBA]">{detail}</p></div><Link href={href} aria-label={`Open ${title}`} className="shrink-0 text-[#007A52] dark:text-[#009966]"><ArrowUpRight aria-hidden="true" className="size-4"/></Link></div></div>;}

export function TodaySurface({date,dateISO,weekEnd,attention,fieldWork,scheduleUnavailable,operations,planningJobs,metrics,openLeads,openProposals,proposalValue,nextFollowUp,customersOwe,expectedIn,expectedOut,cashNet}:TodaySurfaceProps){
  const inboxCount=attention.length+planningJobs.length;
  const now=Date.now();
  const leadCount=Number(openLeads)||0,proposalCount=Number(openProposals)||0,maxPipeline=Math.max(leadCount,proposalCount,1);
  return <main className="mx-auto grid w-full max-w-[1460px] grid-cols-12 gap-6 pb-16 text-[#171B19] dark:text-[#F4F6F5]">
    <header className="industrial-header col-span-12 flex flex-wrap items-end justify-between gap-3 px-4 py-3"><div><h1 className="text-2xl font-bold tracking-tight">Overview</h1><div className="mt-2 flex flex-wrap items-center gap-3"><time dateTime={dateISO} className="text-sm text-[#525C57] dark:text-[#B6BEBA]">{date}</time><PourWeatherBadge/></div></div><p className="text-xs text-[#7B8580] dark:text-[#7C8580]">{inboxCount?`${inboxCount} item${inboxCount===1?'':'s'} need review or scheduling`:'All current work is accounted for'}</p></header>

    <section aria-labelledby="today-status-heading" className="col-span-12"><div className="mb-3 flex flex-wrap items-baseline justify-between gap-2"><h2 id="today-status-heading" className={heading}>Operating summary</h2><span className="text-xs text-[#7B8580] dark:text-[#7C8580]">Current projects · {date} to {weekEnd}</span></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-5">{metrics.map((metric,index)=>{const Icon=metricIcons[index];return <MetricBentoTile key={metric.label} title={metric.label} value={metric.value} prefix={metric.prefix} icon={<Icon/>} tone={metric.tone} description={metric.value===null?'Data unavailable':metric.detail}/>;})}</div></section>

    <section aria-labelledby="today-attention-heading" className={cn(card,'col-span-12 self-start lg:col-span-8')}><div className="industrial-header flex items-center justify-between px-4 py-3"><h2 id="today-attention-heading" className={heading}>Action inbox</h2><span className="font-mono text-xs text-[#7B8580] dark:text-[#7C8580]">{inboxCount} open</span></div>
      {inboxCount?<div>{attention.map((item,index)=>{const aged=Boolean(item.timestamp&&Number.isFinite(Date.parse(item.timestamp))&&now-Date.parse(item.timestamp)>86_400_000),urgent=Boolean(item.urgent||aged);return <article key={`${item.subject}-${index}`} className={cn('group flex min-w-0 items-center gap-3 border-b border-[#D4DBD7] border-l-2 px-3 py-2 last:border-b-0 hover:bg-[#E9EDEA] dark:border-b-[#343A3F] dark:hover:bg-[#1E2123]',urgent?'border-l-[#B84558] dark:border-l-[#E06B74]':'border-l-transparent')}><ShieldAlert aria-hidden="true" className={cn('size-4 shrink-0',urgent?'text-[#B84558] dark:text-[#E06B74] motion-safe:animate-pulse':item.tone==='warning'?'text-[#8A610B] dark:text-[#D5A94A]':'text-[#426F93] dark:text-[#6F9FC6]')}/><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold">{item.subject}</h3><p className="truncate text-xs text-[#525C57] dark:text-[#B6BEBA]">{item.issue}</p></div><span className="hidden shrink-0 text-[11px] text-[#7B8580] dark:text-[#7C8580] sm:block">{item.when}</span><InboxLink href={item.href} label={`${item.action}: ${item.subject}`}/></article>;})}
        {planningJobs.map(job=><article key={job.id} className="group flex min-w-0 items-center gap-3 border-b border-[#D4DBD7] border-l-2 border-l-transparent px-3 py-2 last:border-b-0 hover:bg-[#E9EDEA] dark:border-b-[#343A3F] dark:hover:bg-[#1E2123]"><CalendarDays aria-hidden="true" className="size-4 shrink-0 text-[#426F93] dark:text-[#6F9FC6]"/><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold">{job.project}</h3><p className="truncate text-xs text-[#525C57] dark:text-[#B6BEBA]">{job.nextAction}</p></div><span className="hidden shrink-0 text-[11px] text-[#7B8580] dark:text-[#7C8580] sm:block">Needs scheduling</span><InboxLink href={job.href} label={`${job.held?'Clear hold':'Open project'}: ${job.project}`}/></article>)}</div>:<div className="flex min-h-36 flex-col items-center justify-center gap-2 px-4 py-8 text-center"><CheckCheck aria-hidden="true" className="size-7 text-[#347A46] dark:text-[#6DBB77]"/><h3 className="text-sm font-semibold text-[#347A46] dark:text-[#6DBB77]">Zero inbox</h3><p className="text-xs text-[#525C57] dark:text-[#B6BEBA]">No actions or scheduling decisions are waiting.</p></div>}
    </section>

    <div className="col-span-12 min-w-0 space-y-6 lg:col-span-4"><section aria-labelledby="today-logistics-heading" className={card}><div className="industrial-header flex items-center justify-between px-4 py-3"><h2 id="today-logistics-heading" className={heading}>Logistics timeline</h2><span className="text-[11px] text-[#7B8580] dark:text-[#7C8580]">{fieldWork.length} today · {operations.length} upcoming</span></div>
        {scheduleUnavailable?<p className="p-4 text-xs text-[#525C57] dark:text-[#B6BEBA]">Schedule unavailable. <Link href="/field?view=schedule" className="text-[#007A52] underline dark:text-[#009966]">Open schedule</Link> to try again.</p>:fieldWork.length||operations.length?<div className="max-h-[420px] overflow-y-auto px-4 py-3">{fieldWork.length?<h3 id="today-work-heading" className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-[#7B8580] dark:text-[#7C8580]">Field today</h3>:null}{fieldWork.map(item=><TimelineItem key={item.id} eyebrow={item.time} title={item.project} detail={item.title} href={item.href} tone="success"/>)}{operations.length?<h3 id="today-operations-heading" className="mb-2 mt-2 text-[10px] font-semibold uppercase tracking-wider text-[#7B8580] dark:text-[#7C8580]">Upcoming operations</h3>:null}{operations.map(item=><TimelineItem key={item.id} eyebrow={`${item.time} · ${item.status}`} title={item.project} detail={item.operation} href={item.href} tone={item.tone}/>)}</div>:<div className="flex min-h-44 flex-col items-center justify-center gap-2 px-4 py-6 text-center"><svg aria-hidden="true" viewBox="0 0 104 52" className="h-12 w-24 fill-none stroke-[#B9C3BE] dark:stroke-[#465058]"><path d="M8 8h88M8 26h88M8 44h88M22 5v42M54 5v42M85 5v42" strokeWidth="1"/><circle cx="22" cy="26" r="4"/><circle cx="54" cy="8" r="4"/></svg><p className="text-xs text-[#525C57] dark:text-[#B6BEBA]">No field operations are scheduled.</p><Link href="/field?view=schedule" className="inline-flex items-center gap-1 rounded-sm px-2 py-1 text-xs text-[#007A52] hover:bg-[#E9EDEA] dark:text-[#009966] dark:hover:bg-[#25292C]">Schedule now <ArrowUpRight aria-hidden="true" className="size-3.5"/></Link></div>}
      </section>
      <section aria-labelledby="today-business-heading" className={cn(card,'p-4')}><h2 id="today-business-heading" className={heading}>Business pulse</h2><Tabs defaultValue="pipeline" className="mt-3 gap-2"><TabsList className="w-full rounded-full bg-muted/50 p-1"><TabsTrigger value="pipeline" className="rounded-full text-xs data-active:bg-[#FFFFFF] data-active:text-[#171B19] dark:data-active:bg-[#2D3236] dark:data-active:text-[#F4F6F5]">Pipeline</TabsTrigger><TabsTrigger value="cash" className="rounded-full text-xs data-active:bg-[#FFFFFF] data-active:text-[#171B19] dark:data-active:bg-[#2D3236] dark:data-active:text-[#F4F6F5]">Cash</TabsTrigger></TabsList><TabsContent value="pipeline" className="space-y-3"><div><div className="mb-1 flex justify-between text-xs"><span>Open leads</span><span className="font-mono">{openLeads}</span></div><div className="h-1.5 bg-[#E1E6E3] dark:bg-[#292D30]"><div className="h-full bg-[#426F93] transition-[width] duration-300 dark:bg-[#6F9FC6]" style={{width:`${leadCount/maxPipeline*100}%`}}/></div></div><div><div className="mb-1 flex justify-between text-xs"><span>Proposals out</span><span className="font-mono">{openProposals}</span></div><div className="h-1.5 bg-[#E1E6E3] dark:bg-[#292D30]"><div className="h-full bg-[#007A52] transition-[width] duration-300 dark:bg-[#009966]" style={{width:`${proposalCount/maxPipeline*100}%`}}/></div></div><div className="flex justify-between gap-3 border-t border-[#D4DBD7] pt-2 text-xs dark:border-[#343A3F]"><span className="text-[#525C57] dark:text-[#B6BEBA]">Proposal value</span><strong className="font-mono">{proposalValue}</strong></div><p className="text-[11px] text-[#7B8580] dark:text-[#7C8580]">Next follow-up: {nextFollowUp}</p></TabsContent><TabsContent value="cash"><dl className="divide-y divide-[#D4DBD7] text-xs dark:divide-[#343A3F]">{[['Customers owe',customersOwe],['Expected in · 7 days',expectedIn],['Expected out · 7 days',expectedOut],['7-day net',cashNet]].map(([label,value])=><div key={label} className="flex justify-between gap-3 py-2"><dt className="text-[#525C57] dark:text-[#B6BEBA]">{label}</dt><dd className="font-mono font-semibold">{value}</dd></div>)}</dl></TabsContent></Tabs></section>
    </div>
  </main>;
}
