'use server';
import {revalidatePath} from 'next/cache';
import {createClient} from '@/lib/supabase/server';

async function ctx(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Not signed in');const {data:p}=await supabase.from('profiles').select('company_id,role').eq('id',user.id).single();if(!p?.company_id||p.role==='employee')throw new Error('Owner access required');return{supabase,user,companyId:p.company_id};}
const val=(fd:FormData,k:string)=>String(fd.get(k)||'').trim();
const num=(fd:FormData,k:string,d=0)=>{const n=Number(fd.get(k));return Number.isFinite(n)?n:d;};
const refresh=()=>{for(const p of ['/readiness/resources','/readiness','/look-ahead','/schedule','/production/work-packages','/production/work-packages/financials','/equipment','/employee','/'])revalidatePath(p);};

export async function createResourceRequirement(fd:FormData){
 const operationId=val(fd,'work_package_operation_id'),type=val(fd,'resource_type'),label=val(fd,'label');const quantity=num(fd,'required_quantity',1);if(!operationId||!['material','equipment','vendor'].includes(type)||!label||quantity<=0)throw new Error('Choose the work, resource type, name and required quantity.');
 const {supabase,user,companyId}=await ctx();const {data:op}=await supabase.from('work_package_operations').select('id,work_packages!inner(project_id)').eq('id',operationId).eq('company_id',companyId).single();if(!op)throw new Error('Work package operation not found.');
 const inventoryId=type==='material'?(val(fd,'inventory_item_id')||null):null,equipmentId=type==='equipment'?(val(fd,'equipment_asset_id')||null):null,vendorId=type==='vendor'?(val(fd,'vendor_id')||null):null,poLineId=type==='material'?(val(fd,'purchase_order_line_id')||null):null;
 const {data:req,error}=await supabase.from('work_package_resource_requirements').insert({company_id:companyId,work_package_operation_id:operationId,resource_type:type,label,required_quantity:quantity,unit:val(fd,'unit')||'EA',inventory_item_id:inventoryId,equipment_asset_id:equipmentId,vendor_id:vendorId,purchase_order_line_id:poLineId,required_before_start:fd.get('required_before_start')==='on',need_offset_days:num(fd,'need_offset_days',0),need_by_override:val(fd,'need_by_override')||null,vendor_status:type==='vendor'?(val(fd,'vendor_status')||'needed'):'needed',vendor_reference:val(fd,'vendor_reference')||null,notes:val(fd,'notes')||null,created_by:user.id}).select('id').single();if(error)throw new Error(error.message);
 if(poLineId){const {error:e}=await supabase.from('purchase_order_lines').update({work_package_operation_id:operationId}).eq('id',poLineId).eq('company_id',companyId);if(e)throw new Error(e.message);}
 const reserveQty=num(fd,'reserve_quantity',0);if(req&&type==='material'&&inventoryId&&reserveQty>0){const {error:e}=await supabase.from('inventory_reservations').insert({company_id:companyId,resource_requirement_id:req.id,inventory_item_id:inventoryId,quantity:reserveQty,status:'reserved',created_by:user.id});if(e)throw new Error(e.message);}
 const start=val(fd,'reservation_start'),end=val(fd,'reservation_end')||start;if(req&&type==='equipment'&&equipmentId&&start){const {error:e}=await supabase.from('equipment_reservations').insert({company_id:companyId,resource_requirement_id:req.id,equipment_asset_id:equipmentId,start_date:start,end_date:end,status:fd.get('equipment_confirmed')==='on'?'confirmed':'planned',created_by:user.id});if(e)throw new Error(e.message);}
 refresh();
}

export async function reserveMaterial(fd:FormData){
 const id=val(fd,'requirement_id'),inventoryId=val(fd,'inventory_item_id'),quantity=num(fd,'quantity');if(!id||!inventoryId||quantity<=0)throw new Error('Choose inventory and reservation quantity.');const {supabase,user,companyId}=await ctx();const {data:req}=await supabase.from('work_package_resource_requirements').select('id,resource_type').eq('id',id).eq('company_id',companyId).single();if(!req||req.resource_type!=='material')throw new Error('Material requirement not found.');
 await supabase.from('work_package_resource_requirements').update({inventory_item_id:inventoryId,updated_at:new Date().toISOString()}).eq('id',id).eq('company_id',companyId);const {error}=await supabase.from('inventory_reservations').upsert({company_id:companyId,resource_requirement_id:id,inventory_item_id:inventoryId,quantity,status:'reserved',created_by:user.id,updated_at:new Date().toISOString()},{onConflict:'resource_requirement_id'});if(error)throw new Error(error.message);refresh();
}

export async function markMaterialConsumed(fd:FormData){const id=val(fd,'requirement_id');if(!id)return;const {supabase}=await ctx();const {error}=await supabase.rpc('consume_work_package_inventory',{p_requirement_id:id});if(error)throw new Error(error.message);refresh();}

export async function linkPurchaseOrderLine(fd:FormData){const id=val(fd,'requirement_id'),lineId=val(fd,'purchase_order_line_id');if(!id||!lineId)throw new Error('Choose a purchase order line.');const {supabase,companyId}=await ctx();const {data:req}=await supabase.from('work_package_resource_requirements').select('work_package_operation_id,resource_type').eq('id',id).eq('company_id',companyId).single();if(!req||req.resource_type!=='material')throw new Error('Material requirement not found.');const {error}=await supabase.from('work_package_resource_requirements').update({purchase_order_line_id:lineId,updated_at:new Date().toISOString()}).eq('id',id).eq('company_id',companyId);if(error)throw new Error(error.message);const {error:e}=await supabase.from('purchase_order_lines').update({work_package_operation_id:req.work_package_operation_id}).eq('id',lineId).eq('company_id',companyId);if(e)throw new Error(e.message);refresh();}

export async function reserveEquipment(fd:FormData){const id=val(fd,'requirement_id'),assetId=val(fd,'equipment_asset_id'),start=val(fd,'start_date'),end=val(fd,'end_date')||start;if(!id||!assetId||!start)throw new Error('Choose equipment and reservation date.');const {supabase,user,companyId}=await ctx();const {data:req}=await supabase.from('work_package_resource_requirements').select('resource_type').eq('id',id).eq('company_id',companyId).single();if(!req||req.resource_type!=='equipment')throw new Error('Equipment requirement not found.');await supabase.from('work_package_resource_requirements').update({equipment_asset_id:assetId,updated_at:new Date().toISOString()}).eq('id',id).eq('company_id',companyId);const {error}=await supabase.from('equipment_reservations').upsert({company_id:companyId,resource_requirement_id:id,equipment_asset_id:assetId,start_date:start,end_date:end,status:fd.get('confirmed')==='on'?'confirmed':'planned',created_by:user.id,updated_at:new Date().toISOString()},{onConflict:'resource_requirement_id'});if(error)throw new Error(error.message);refresh();}

export async function updateVendorCommitment(fd:FormData){const id=val(fd,'requirement_id'),vendorId=val(fd,'vendor_id'),status=val(fd,'vendor_status')||'needed';if(!id)throw new Error('Vendor requirement missing.');const {supabase,companyId}=await ctx();const {error}=await supabase.from('work_package_resource_requirements').update({vendor_id:vendorId||null,vendor_status:status,vendor_reference:val(fd,'vendor_reference')||null,updated_at:new Date().toISOString()}).eq('id',id).eq('company_id',companyId).eq('resource_type','vendor');if(error)throw new Error(error.message);refresh();}

export async function waiveResourceRequirement(fd:FormData){const id=val(fd,'requirement_id'),reason=val(fd,'waiver_reason');if(!id||!reason)throw new Error('Explain why this resource requirement can be waived.');const {supabase,user,companyId}=await ctx();const {error}=await supabase.from('work_package_resource_requirements').update({waived_at:new Date().toISOString(),waived_by:user.id,waiver_reason:reason,updated_at:new Date().toISOString()}).eq('id',id).eq('company_id',companyId);if(error)throw new Error(error.message);refresh();}
export async function restoreResourceRequirement(fd:FormData){const id=val(fd,'requirement_id');if(!id)return;const {supabase,companyId}=await ctx();await supabase.from('work_package_resource_requirements').update({waived_at:null,waived_by:null,waiver_reason:null,updated_at:new Date().toISOString()}).eq('id',id).eq('company_id',companyId);refresh();}
export async function deleteResourceRequirement(fd:FormData){const id=val(fd,'requirement_id');if(!id)return;const {supabase,companyId}=await ctx();await supabase.from('work_package_resource_requirements').delete().eq('id',id).eq('company_id',companyId);refresh();}
