import Link from 'next/link';
import {redirect} from 'next/navigation';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';
import {DocumentUpload} from '@/components/documents/DocumentUpload';
import {createPoReceiptFromDocument,deleteDocument,matchDocumentToBank,matchDocumentToVendorBill,reconcileReceiptToCompanyExpense,reconcileReceiptToJobCost,updateDocumentReview} from './actions';

const money=(n:any)=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n));
const num=(n:any)=>Number(n||0);
const costTypes=['receipt','delivery_ticket','concrete_ticket','vendor_invoice'];
const typeLabel=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default async function DocumentsPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
 const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(!profile?.company_id)redirect('/login');if(profile.role==='employee')redirect('/employee');const companyId=profile.company_id;
 const [{data:docs},{data:projects},{data:vendors},{data:bills},{data:pos},{data:poLines},{data:bankTx},{data:codes},{data:overhead}]=await Promise.all([
  supabase.from('company_documents').select('*,projects(job_number,name),vendors(name),vendor_bills(vendor_bill_number),purchase_orders(po_number)').eq('company_id',companyId).order('created_at',{ascending:false}).limit(250),
  supabase.from('projects').select('id,job_number,name,status').eq('company_id',companyId).in('status',['active','on_hold','completed']).order('job_number'),
  supabase.from('vendors').select('id,name').eq('company_id',companyId).eq('active',true).order('name'),
  supabase.from('vendor_bills').select('id,project_id,vendor_id,vendor_bill_number,bill_date,status,projects(job_number,name),vendors(name)').eq('company_id',companyId).in('status',['draft','posted','partial','paid']).order('bill_date',{ascending:false}).limit(120),
  supabase.from('purchase_orders').select('id,project_id,vendor_id,po_number,status,pour_plan_id,projects(job_number,name),vendors(name)').eq('company_id',companyId).in('status',['issued','closed']).order('created_at',{ascending:false}).limit(120),
  supabase.from('purchase_order_lines').select('id,purchase_order_id,description,quantity,unit,pour_plan_id,cost_codes(code,name)').eq('company_id',companyId).order('sort_order'),
  supabase.from('plaid_transactions').select('id,transaction_date,name,merchant_name,cash_amount,review_status').eq('company_id',companyId).eq('removed',false).eq('pending',false).eq('review_status','unreviewed').lt('cash_amount',0).order('transaction_date',{ascending:false}).limit(150),
  supabase.from('cost_codes').select('id,code,name,cost_type').eq('company_id',companyId).eq('active',true).order('sort_order'),
  supabase.from('overhead_items').select('id,category,name,business_use_percent').eq('company_id',companyId).eq('active',true).order('sort_order')
 ]);
 const signed=await Promise.all((docs||[]).map(async(d:any)=>{if(!d.storage_path)return {...d,url:null};const {data}=await supabase.storage.from('carez-documents').createSignedUrl(d.storage_path,3600);return {...d,url:data?.signedUrl||null};}));
 const queue=signed.filter((d:any)=>d.review_status==='needs_review');const matched=signed.filter((d:any)=>d.review_status==='matched');const missingJob=signed.filter((d:any)=>!d.project_id&&!['ignored'].includes(d.review_status));const concrete=signed.filter((d:any)=>d.document_type==='concrete_ticket');
 const poMap=new Map((pos||[]).map((p:any)=>[p.id,p]));
 const lineOptions=(poLines||[]).map((l:any)=>{const po:any=poMap.get(l.purchase_order_id)||{};return {...l,po};});
 const outgoing=(bankTx||[]).map((t:any)=>({...t,amount:Math.abs(num(t.cash_amount))}));
 const projectOpts=(projects||[]).map((p:any)=>({id:p.id,label:`${p.job_number} — ${p.name}`}));const vendorOpts=(vendors||[]).map((v:any)=>({id:v.id,label:v.name}));
 return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page">
  <div className="command-hero"><div><div className="section-kicker">Field Evidence</div><h1>Documents, Receipts & Concrete Tickets</h1><p>Capture the photo once, then tie it to the job, vendor, PO delivery, vendor bill or bank charge that it proves.</p></div></div>
  <div className="command-grid"><div className={`command-card ${queue.length?'watch':'good'}`}><div className="command-label">Needs Review</div><div className="command-value">{queue.length}</div><div className="command-help">Receipts and tickets waiting to be filed or matched.</div></div><div className={`command-card ${missingJob.length?'watch':'good'}`}><div className="command-label">Need a Job</div><div className="command-value">{missingJob.length}</div><div className="command-help">Evidence not assigned to a project.</div></div><div className="command-card"><div className="command-label">Matched</div><div className="command-value">{matched.length}</div><div className="command-help">Connected to accounting or procurement.</div></div><div className="command-card"><div className="command-label">Concrete Tickets</div><div className="command-value">{concrete.length}</div><div className="command-help">Delivery evidence retained by pour/job.</div></div></div>
  <section className="section"><div className="surface"><div className="surface-header"><div><div className="surface-title">Add From Phone</div><div className="surface-subtitle">Camera-first. Photograph the receipt or ticket before it disappears into a truck, wallet or batch plant clipboard.</div></div></div><div className="surface-body"><DocumentUpload companyId={companyId} projects={projectOpts} vendors={vendorOpts}/></div></div></section>

  <section className="section"><div className="section-heading"><div><div className="section-kicker">Inbox</div><div className="section-title">Review Queue</div><div className="section-heading-meta">Use the shortest workflow that matches what the document actually proves.</div></div></div>
  {queue.length===0?<div className="empty-state"><div><div className="title">Document inbox is clear</div><div className="meta">New receipts, invoices and tickets will land here.</div></div></div>:<div className="project-list">{queue.map((d:any)=>{
   const probableBank=outgoing.filter((t:any)=>d.amount==null||Math.abs(t.amount-num(d.amount))<0.011).slice(0,20);const ticketLines=lineOptions.filter((l:any)=>{const po=l.po;return (!d.project_id||po.project_id===d.project_id)&&(!d.vendor_id||po.vendor_id===d.vendor_id)&&['delivery_ticket','concrete_ticket'].includes(d.document_type);});const billOpts=(bills||[]).filter((b:any)=>(!d.project_id||b.project_id===d.project_id)&&(!d.vendor_id||b.vendor_id===d.vendor_id));
   return <article className="project-card" key={d.id}><header className="project-header"><div><div className="project-name">{d.title}</div><div className="project-location">{d.document_date||'No date'} · {typeLabel(d.document_type)}{d.reference_number?` · #${d.reference_number}`:''}</div></div><span className="status on-hold">Needs Review</span></header>
    <section className="project-section"><div className="row"><div><div className="title">{d.projects?`${d.projects.job_number} — ${d.projects.name}`:'No job assigned'}</div><div className="meta">{d.vendors?.name||'No vendor'} · {money(d.amount)}</div>{d.notes&&<div className="meta">{d.notes}</div>}</div><div className="action-row">{d.url&&<a className="button secondary" href={d.url} target="_blank" rel="noreferrer">Open File</a>}</div></div></section>
    <section className="project-section tinted"><details className="controls-disclosure"><summary>File / Correct Details</summary><div className="controls-body"><form action={updateDocumentReview} className="form"><input type="hidden" name="id" value={d.id}/><div className="grid grid2"><label className="field"><span>Job</span><select name="project_id" defaultValue={d.project_id||''}><option value="">Company / no job</option>{projectOpts.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label className="field"><span>Vendor</span><select name="vendor_id" defaultValue={d.vendor_id||''}><option value="">None</option>{vendorOpts.map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select></label></div><div className="grid grid2"><label className="field"><span>Date</span><input type="date" name="document_date" defaultValue={d.document_date||''}/></label><label className="field"><span>Amount</span><input type="number" step="0.01" min="0" name="amount" defaultValue={d.amount??''}/></label></div><label className="field"><span>Receipt / Ticket #</span><input name="reference_number" defaultValue={d.reference_number||''}/></label><label className="field"><span>Note</span><input name="notes" defaultValue={d.notes||''}/></label><input type="hidden" name="review_status" value="filed"/><button className="button">File Document</button></form></div></details>
    {['delivery_ticket','concrete_ticket'].includes(d.document_type)&&<details className="controls-disclosure"><summary>Match to PO Delivery</summary><div className="controls-body"><form action={createPoReceiptFromDocument} className="form"><input type="hidden" name="id" value={d.id}/><label className="field"><span>PO Line</span><select name="purchase_order_line_id" required defaultValue=""><option value="" disabled>Choose ordered item</option>{ticketLines.map((l:any)=><option key={l.id} value={l.id}>{l.po?.projects?.job_number} · {l.po?.po_number} · {l.description} ({num(l.quantity)} {l.unit})</option>)}</select></label><div className="grid grid2"><label className="field"><span>Delivered Quantity</span><input type="number" min="0" step="0.01" name="quantity_received" required/></label><label className="field"><span>Delivery Date</span><input type="date" name="received_date" defaultValue={d.document_date||new Date().toISOString().slice(0,10)}/></label></div><label className="field"><span>Ticket #</span><input name="delivery_ticket" defaultValue={d.reference_number||''}/></label><label className="field"><span>Note</span><input name="notes" defaultValue={d.notes||''}/></label><button className="button">Post Delivery</button></form>{ticketLines.length===0&&<div className="alert info">No issued PO lines match this document's job/vendor. Correct the document details or issue the PO first.</div>}</div></details>}
    {d.document_type==='vendor_invoice'&&<details className="controls-disclosure"><summary>Match to Vendor Bill</summary><div className="controls-body"><form action={matchDocumentToVendorBill} className="form"><input type="hidden" name="id" value={d.id}/><label className="field"><span>Vendor Bill</span><select name="vendor_bill_id" required defaultValue=""><option value="" disabled>Choose bill</option>{billOpts.map((b:any)=><option key={b.id} value={b.id}>{b.projects?.job_number} · {b.vendors?.name} · #{b.vendor_bill_number} · {b.bill_date}</option>)}</select></label><button className="button">Attach to Bill</button></form></div></details>}
    {d.document_type==='receipt'&&<><details className="controls-disclosure"><summary>Receipt → Job Cost</summary><div className="controls-body"><form action={reconcileReceiptToJobCost} className="form"><input type="hidden" name="id" value={d.id}/><div className="grid grid2"><label className="field"><span>Bank Charge</span><select name="bank_transaction_id" required defaultValue=""><option value="" disabled>Choose charge</option>{probableBank.map((t:any)=><option key={t.id} value={t.id}>{t.transaction_date} · {t.merchant_name||t.name} · {money(t.amount)}</option>)}</select></label><label className="field"><span>Job</span><select name="project_id" required defaultValue={d.project_id||''}><option value="" disabled>Choose job</option>{projectOpts.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label></div><div className="grid grid2"><label className="field"><span>Cost Code</span><select name="cost_code_id" required defaultValue=""><option value="" disabled>Choose cost code</option>{(codes||[]).map((c:any)=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></label><label className="field"><span>Vendor</span><select name="vendor_id" defaultValue={d.vendor_id||''}><option value="">None</option>{vendorOpts.map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select></label></div><label className="field"><span>Description</span><input name="description" defaultValue={d.title}/></label><label className="checkbox-row"><input type="checkbox" name="remember_cost_code"/><span>Remember this merchant → cost code for future review</span></label><button className="button">Match Receipt + Create Job Cost</button></form>{probableBank.length===0&&<div className="alert info">No open bank charge has this exact amount. Use the company expense workflow or correct the receipt amount/date first.</div>}</div></details>
    <details className="controls-disclosure"><summary>Receipt → Company Expense</summary><div className="controls-body"><form action={reconcileReceiptToCompanyExpense} className="form"><input type="hidden" name="id" value={d.id}/><label className="field"><span>Bank Charge</span><select name="bank_transaction_id" required defaultValue=""><option value="" disabled>Choose charge</option>{probableBank.map((t:any)=><option key={t.id} value={t.id}>{t.transaction_date} · {t.merchant_name||t.name} · {money(t.amount)}</option>)}</select></label><div className="grid grid2"><label className="field"><span>Overhead Item</span><select name="overhead_item_id" defaultValue=""><option value="">Custom category</option>{(overhead||[]).map((o:any)=><option key={o.id} value={o.id}>{o.category} — {o.name}</option>)}</select></label><label className="field"><span>Category if Custom</span><input name="category" placeholder="Fuel / Office / Insurance"/></label></div><div className="grid grid2"><label className="field"><span>Business Use %</span><input type="number" min="0" max="100" step="1" name="business_use_percent" defaultValue="100"/></label><label className="field"><span>Description</span><input name="description" defaultValue={d.title}/></label></div><button className="button">Match Receipt + Record Expense</button></form></div></details></>}
    {!costTypes.includes(d.document_type)&&<details className="controls-disclosure"><summary>Match to Bank Transaction</summary><div className="controls-body"><form action={matchDocumentToBank} className="form"><input type="hidden" name="id" value={d.id}/><label className="field"><span>Bank Transaction</span><select name="bank_transaction_id" required defaultValue=""><option value="" disabled>Choose charge</option>{outgoing.slice(0,40).map((t:any)=><option key={t.id} value={t.id}>{t.transaction_date} · {t.merchant_name||t.name} · {money(t.amount)}</option>)}</select></label><button className="button">Attach Evidence</button></form></div></details>}
    <details className="controls-disclosure"><summary>Ignore / Delete</summary><div className="controls-body"><div className="action-row"><form action={updateDocumentReview}><input type="hidden" name="id" value={d.id}/><input type="hidden" name="project_id" value={d.project_id||''}/><input type="hidden" name="vendor_id" value={d.vendor_id||''}/><input type="hidden" name="document_date" value={d.document_date||''}/><input type="hidden" name="amount" value={d.amount??''}/><input type="hidden" name="reference_number" value={d.reference_number||''}/><input type="hidden" name="notes" value={d.notes||''}/><input type="hidden" name="review_status" value="ignored"/><button className="button secondary">Ignore</button></form><form action={deleteDocument}><input type="hidden" name="id" value={d.id}/><button className="button secondary">Delete File</button></form></div></div></details>}
    </section></article>})}</div>}</section>

  <section className="section"><div className="section-heading"><div><div className="section-kicker">Archive</div><div className="section-title">Filed & Matched Documents</div><div className="section-heading-meta">Evidence remains searchable by job, vendor, date and reference number.</div></div></div><div className="project-list">{signed.filter((d:any)=>d.review_status!=='needs_review').slice(0,120).map((d:any)=><article className="project-card" key={d.id}><header className="project-header"><div><div className="project-name">{d.title}</div><div className="project-location">{d.document_date||'No date'} · {typeLabel(d.document_type)} · {d.projects?`${d.projects.job_number} — ${d.projects.name}`:'Company'}</div></div><span className={`status ${d.review_status==='matched'?'completed':d.review_status==='ignored'?'':'active'}`}>{typeLabel(d.review_status)}</span></header><section className="project-section"><div className="row"><div><div className="meta">{d.vendors?.name||'No vendor'} · {money(d.amount)}{d.reference_number?` · #${d.reference_number}`:''}</div><div className="meta">{d.purchase_orders?.po_number?`PO ${d.purchase_orders.po_number}`:''}{d.vendor_bills?.vendor_bill_number?` · Bill ${d.vendor_bills.vendor_bill_number}`:''}</div></div><div className="action-row">{d.url&&<a className="button secondary" href={d.url} target="_blank" rel="noreferrer">Open</a>}<form action={updateDocumentReview}><input type="hidden" name="id" value={d.id}/><input type="hidden" name="project_id" value={d.project_id||''}/><input type="hidden" name="vendor_id" value={d.vendor_id||''}/><input type="hidden" name="document_date" value={d.document_date||''}/><input type="hidden" name="amount" value={d.amount??''}/><input type="hidden" name="reference_number" value={d.reference_number||''}/><input type="hidden" name="notes" value={d.notes||''}/><input type="hidden" name="review_status" value="needs_review"/><button className="button secondary">Reopen</button></form></div></div></section></article>)}</div></section>
  <div className="alert info"><strong>Accounting rule:</strong> a receipt photo is evidence, not a second cost. The Job Cost workflow creates the cost from the matched bank charge; vendor invoices attach to the existing vendor bill; concrete tickets post received quantity against the issued PO.</div>
  <div className="action-row"><Link className="button secondary" href="/banking/reconcile">Bank Reconciliation</Link><Link className="button secondary" href="/procurement">Procurement</Link><Link className="button secondary" href="/pour-control">Pour Control</Link></div>
 </div></AppShell>;
}
