import {redirect} from 'next/navigation';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';
import {DocumentUpload} from '@/components/documents/DocumentUpload';
import {deleteDocument} from './actions';

const money=(n:any)=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n));

export default async function DocumentsPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(!profile?.company_id)redirect('/login');if(profile.role==='employee')redirect('/employee');
 const [{data:docs},{data:projects},{data:vendors}]=await Promise.all([supabase.from('company_documents').select('*,projects(job_number,name),vendors(name)').eq('company_id',profile.company_id).order('document_date',{ascending:false}).order('created_at',{ascending:false}).limit(200),supabase.from('projects').select('id,job_number,name').in('status',['active','on_hold','completed']).order('job_number'),supabase.from('vendors').select('id,name').eq('active',true).order('name')]);
 const signed=await Promise.all((docs||[]).map(async(d:any)=>{if(!d.storage_path)return {...d,url:null};const {data}=await supabase.storage.from('carez-documents').createSignedUrl(d.storage_path,3600);return {...d,url:data?.signedUrl||null};}));
 const receipts=signed.filter((d:any)=>['receipt','delivery_ticket','concrete_ticket','vendor_invoice'].includes(d.document_type));const unassigned=signed.filter((d:any)=>!d.project_id);
 return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page"><div className="command-hero"><div><h1>Documents & Receipts</h1><p>Take a photo from the field and keep the proof tied to the right job instead of buried in your phone.</p></div></div><div className="command-grid"><div className="command-card"><div className="command-label">Saved Documents</div><div className="command-value">{signed.length}</div><div className="command-help">Receipts, tickets, plans, inspections and photos.</div></div><div className={`command-card ${unassigned.length?'watch':'good'}`}><div className="command-label">Need a Job</div><div className="command-value">{unassigned.length}</div><div className="command-help">Documents not tied to a project yet.</div></div><div className="command-card"><div className="command-label">Cost Documents</div><div className="command-value">{receipts.length}</div><div className="command-help">Receipts, delivery tickets and vendor invoices.</div></div></div>
 <section className="section"><div className="surface"><div className="surface-header"><div><div className="surface-title">Add From Phone</div><div className="surface-subtitle">Use the camera for receipts, delivery tickets, concrete tickets or job photos.</div></div></div><div className="surface-body"><DocumentUpload companyId={profile.company_id} projects={(projects||[]).map((p:any)=>({id:p.id,label:`${p.job_number} — ${p.name}`}))} vendors={(vendors||[]).map((v:any)=>({id:v.id,label:v.name}))}/></div></div></section>
 <section className="section"><div className="section-heading"><div><div className="section-kicker">Files</div><div className="section-title">Recent Documents</div><div className="section-heading-meta">Open any file for the original photo/PDF.</div></div></div>{signed.length===0?<div className="empty-state"><div><div className="title">No documents yet</div><div className="meta">Your first receipt or field photo will show here.</div></div></div>:<div className="project-list">{signed.map((d:any)=><article className="project-card" key={d.id}><header className="project-header"><div><div className="project-name">{d.title}</div><div className="project-location">{d.document_date||'No date'} · {d.document_type.replaceAll('_',' ')}{d.projects?` · ${d.projects.job_number} — ${d.projects.name}`:' · Company / unassigned'}</div></div><span className={`status ${d.project_id?'active':'on-hold'}`}>{d.project_id?'Filed':'Needs Job'}</span></header><section className="project-section"><div className="row"><div><div className="meta">{d.vendors?.name||'No vendor'} · {money(d.amount)}</div>{d.notes&&<div className="meta">{d.notes}</div>}</div><div className="action-row">{d.url&&<a className="button secondary" href={d.url} target="_blank" rel="noreferrer">Open File</a>}<form action={deleteDocument}><input type="hidden" name="id" value={d.id}/><button className="button secondary">Delete</button></form></div></div></section></article>)}</div>}</section></div></AppShell>;
}
