'use client';

import { useState } from 'react';
import { ArrowLeft, ArrowRight, ChevronDown, CircleHelp, Copy, SlidersHorizontal } from 'lucide-react';
import { PourtraceDialog, PourtraceDrawer, PourtraceMenu, PourtracePopover } from './PourtraceOverlays';

const button = 'inline-flex min-h-9 items-center justify-center gap-2 rounded-[5px] border border-border bg-secondary px-3 text-[13px] font-semibold text-foreground transition-colors hover:border-primary hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring';
const greenButton = 'inline-flex min-h-9 items-center justify-center gap-2 rounded-[5px] border border-primary bg-primary px-3 text-[13px] font-bold text-primary-foreground transition-transform hover:brightness-110 active:translate-y-px focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring';
const input = 'h-9 w-full rounded-[4px] border border-border bg-background px-3 text-sm text-foreground focus:border-primary focus:outline-none';

function DemoCard({ number, name, use, motion, children }: { number: string; name: string; use: string; motion: string; children: React.ReactNode }) {
  return <article className="flex min-h-48 flex-col border border-border bg-card/70 shadow-[inset_0_1px_rgba(255,255,255,.04)]">
    <div className="border-l-[3px] border-primary bg-[linear-gradient(100deg,color-mix(in_srgb,var(--primary),transparent_91%),transparent_65%)] px-4 py-3">
      <div className="text-[11px] font-semibold text-primary">{number}</div><h3 className="mt-1 font-semibold text-foreground">{name}</h3>
    </div>
    <div className="flex flex-1 flex-col justify-between gap-4 p-4"><p className="text-[12px] leading-relaxed text-muted-foreground">{use}</p><div>{children}</div></div>
    <div className="border-t border-border px-4 py-2 text-[11px] text-muted-foreground">Motion · {motion}</div>
  </article>;
}

function Section({ id, title, description, children }: { id: string; title: string; description: string; children: React.ReactNode }) {
  return <section id={id} className="scroll-mt-24"><div className="mb-3 border-l-4 border-primary bg-card px-4 py-3"><h2 className="font-[family-name:var(--font-roboto-slab)] text-lg font-bold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{description}</p></div><div className="grid gap-3 md:grid-cols-3">{children}</div></section>;
}

function ReviewLines() { return <div className="divide-y divide-border border border-border text-xs"><div className="grid grid-cols-[1fr_auto] gap-3 bg-secondary px-3 py-2 font-semibold"><span>Pricing output</span><span>Status</span></div><div className="grid grid-cols-[1fr_auto] gap-3 px-3 py-2"><span>Form lumber / hardware allowance</span><span className="text-warning">Missing price</span></div><div className="grid grid-cols-[1fr_auto] gap-3 px-3 py-2"><span>#4 reinforcing steel</span><span className="text-success">Complete</span></div></div>; }

export function OverlayReview() {
  const [step, setStep] = useState(1);
  const [review, setReview] = useState<'unreviewed' | 'reviewed'>('unreviewed');
  const [menuValue, setMenuValue] = useState('All outputs');
  const [copied, setCopied] = useState(false);
  return <main className="min-h-screen bg-background px-4 py-5 text-foreground sm:px-7 lg:px-10">
    <header className="mx-auto max-w-[1440px] border-b border-border pb-5">
      <a href="/estimates/9a000002-0000-4000-8000-000000000002#pricing-coverage" className="inline-flex items-center gap-2 text-xs text-muted-foreground hover:text-primary"><ArrowLeft size={14}/> Pricing Coverage</a>
      <div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-primary">Pourtrace · interaction study</p><h1 className="mt-1 font-[family-name:var(--font-roboto-slab)] text-3xl font-bold tracking-tight">Overlays with a purpose</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Twelve working patterns in the approved visual language. Choose by task: decisions and edits belong in dialogs; contextual evidence can live in a drawer, menu, or popover.</p></div><span className="rounded border border-primary/50 bg-primary/10 px-3 py-2 text-xs font-semibold text-primary">Design review · no estimate data changes</span></div>
      <nav className="mt-5 flex flex-wrap gap-2 text-xs"><a className={button} href="#dialogs">Dialogs</a><a className={button} href="#drawers">Drawers</a><a className={button} href="#menus">Menus</a><a className={button} href="#popovers">Popovers</a><a className={button} href="#metrics">Metrics strip</a></nav>
    </header>

    <div className="mx-auto mt-6 grid max-w-[1440px] gap-8">
      <Section id="dialogs" title="Dialog · focused decisions" description="Centered, modal, and task complete. Recommended for the Pricing Coverage View / Edit action.">
        <DemoCard number="D1" name="Quick decision" use="Resolve one missing price with a small, confident action surface." motion="focus compression, soft blur, spring settle"><PourtraceDialog variant="decision" trigger="Open quick decision" title="Resolve missing price" description="Form lumber / hardware allowance · 166.67 SFCA"><div className="grid gap-3"><label className="text-xs font-semibold">Unit price <input className={`${input} mt-1`} type="number" placeholder="Enter project price" /></label><p className="text-xs text-muted-foreground">A company recommendation can appear here; the estimator makes the final selection.</p><button className={greenButton} onClick={() => setReview('reviewed')}>{review === 'reviewed' ? 'Marked for review' : 'Preview resolution'}</button></div></PourtraceDialog></DemoCard>
        <DemoCard number="D2 · recommended" name="Pricing evidence review" use="Compare source, quantity, and quote candidates without losing the table." motion="staged lift, deliberate settle"><PourtraceDialog variant="review" trigger="Open evidence review" title="Pricing evidence" description="A single place to understand and select a source for an output."><div className="grid gap-4 md:grid-cols-[1fr_1fr]"><ReviewLines/><div className="space-y-3"><div className="border border-border p-3"><div className="text-xs text-muted-foreground">Production quantity</div><div className="mt-1 font-mono text-lg font-bold">166.67 SFCA</div></div><div className="border border-border p-3"><div className="text-xs text-muted-foreground">Source</div><div className="mt-1 text-sm">No selected supplier quote</div></div></div></div><div className="mt-4 flex justify-end"><button className={greenButton} onClick={() => setReview('reviewed')}>Review source</button></div></PourtraceDialog></DemoCard>
        <DemoCard number="D3" name="Guided workflow" use="Major multi-step actions, such as preparing a quote set, keep progress visible." motion="aperture reveal, content continuity"><PourtraceDialog variant="workflow" trigger="Open guided workflow" title="Build supplier quote set" description={`Step ${step} of 3 · This is a preview, not a saved quote.`}><div className="mb-4 flex gap-1">{[1,2,3].map(n=><span key={n} className={`h-1.5 flex-1 ${n<=step?'bg-primary':'bg-border'}`} />)}</div><p className="mb-4 text-sm">{step===1?'Name the material or service package.':step===2?'Attach supplier responses to the package.':'Review rates, units, and expiry before selection.'}</p><div className="flex justify-between"><button className={button} disabled={step===1} onClick={()=>setStep(Math.max(1,step-1))}>Back</button><button className={greenButton} onClick={()=>setStep(step===3?1:step+1)}>{step===3?'Start again':'Next step'}<ArrowRight size={14}/></button></div></PourtraceDialog></DemoCard>
      </Section>

      <Section id="drawers" title="Drawer · contextual continuity" description="Useful when the table must remain visibly connected to the detail; not the default for every View / Edit.">
        <DemoCard number="R1" name="Compact inspector" use="Trace a selected output to its drawing and source evidence." motion="edge travel, surface shadow"><PourtraceDrawer variant="inspector" trigger="Open inspector" title="Output lineage" description="Ready-mix concrete · QA-1"><div className="space-y-4"><ReviewLines/><div className="border-l-2 border-primary pl-3 text-xs"><b>Drawing</b><p className="mt-1 text-muted-foreground">QA-1 · Strip footing · measured 100 LF</p></div></div></PourtraceDrawer></DemoCard>
        <DemoCard number="R2" name="Mobile-ready tray" use="Short review or selection on a phone; thumb-reachable actions stay at the bottom." motion="weighted rise, rounded landing"><PourtraceDrawer variant="tray" trigger="Open bottom tray" title="Select output" description="A compact choice surface for field and mobile work."><ReviewLines/><div className="mt-5 flex justify-end"><button className={greenButton}>Preview selection</button></div></PourtraceDrawer></DemoCard>
        <DemoCard number="R3" name="Evidence ledger" use="A wider side panel for multiple sources and audit context." motion="masked reveal from the edge"><PourtraceDrawer variant="ledger" trigger="Open evidence ledger" title="Source ledger" description="Compare available evidence without changing takeoff quantity."><div className="grid gap-3"><ReviewLines/><div className="border border-border p-3 text-xs"><b>Selected pricing authority</b><p className="mt-1 text-muted-foreground">The estimator confirms quote, manual override, or company source.</p></div></div></PourtraceDrawer></DemoCard>
      </Section>

      <Section id="menus" title="Menu · compact commands" description="Short choices and actions anchored to the control that opened them.">
        <DemoCard number="M1" name="Command menu" use="Frequent row actions, with clear labels and no extra inspector panel." motion="origin-scale with a subtle blur"><PourtraceMenu variant="command" trigger={<>Actions <ChevronDown size={14}/></>} title="Output actions" items={[{label:'View pricing evidence',detail:'Open a focused review'},{label:'Locate on drawing',detail:'Jump to Takeoff page'},{label:'Copy output reference',detail:'Copy a stable ID'}]}/></DemoCard>
        <DemoCard number="M2" name="Row action menu" use="A compact overflow control for secondary commands within dense tables." motion="horizontal reveal from row edge"><PourtraceMenu variant="row" trigger="More ···" title="Form lumber / hardware" items={[{label:'View source'},{label:'Compare quotes'},{label:'Open estimate line'}]}/></DemoCard>
        <DemoCard number="M3" name="Filter menu" use="Switch review scope without adding a large persistent filter panel." motion="low rise, anchored settle"><PourtraceMenu variant="filter" trigger={<><SlidersHorizontal size={14}/> {menuValue}</>} title="Pricing view" items={['All outputs','Needs attention','Supplier quotes','Manual overrides'].map(label=>({label,selected:menuValue===label,onSelect:()=>setMenuValue(label)}))}/></DemoCard>
      </Section>

      <Section id="popovers" title="Popover · nearby explanation" description="Lightweight help and recommendations anchored to the field or metric they explain.">
        <DemoCard number="P1" name="Quantity formula" use="Explain a derived quantity while keeping the estimator in context." motion="anchored unfold with focus sharpening"><PourtracePopover variant="formula" trigger={<><CircleHelp size={14}/> How calculated?</>} title="Form contact area" description="Derived from the selected footing geometry."><div className="font-mono text-sm">2 sides × 100 LF × 0.833 ft = <b>166.67 SFCA</b></div><p className="mt-2 text-muted-foreground">Measurement geometry remains the quantity authority.</p></PourtracePopover></DemoCard>
        <DemoCard number="P2" name="Rate recommendation" use="Show a National Estimator suggestion only when the rate field is focused." motion="lift from input, fast settle"><PourtracePopover variant="recommendation" trigger="Show recommended rate" title="Recommended production" description="A reviewable reference, never an automatic project rate."><div className="flex items-center justify-between"><span>Footing placement</span><strong className="font-mono text-primary">4.2 CY/MH</strong></div><p className="mt-2 text-muted-foreground">Illustrative preview only; no book rate is applied here.</p></PourtracePopover></DemoCard>
        <DemoCard number="P3" name="Source snapshot" use="Reveal who supplied a value and when, without expanding a row." motion="precise scale from trigger"><PourtracePopover variant="snapshot" trigger={<>Source details <ChevronDown size={14}/></>} title="Pricing source" description="A compact audit preview."><div className="grid grid-cols-2 gap-2 text-xs"><span className="text-muted-foreground">Type</span><b>Company default</b><span className="text-muted-foreground">Checked</span><b>Sep 27, 2026</b></div><button className={`${button} mt-3 w-full`} onClick={()=>{setCopied(true);setTimeout(()=>setCopied(false),1800)}}><Copy size={13}/>{copied?'Copied':'Copy source reference'}</button></PourtracePopover></DemoCard>
      </Section>

      <section id="metrics" className="scroll-mt-24"><div className="mb-3 border-l-4 border-primary bg-card px-4 py-3"><h2 className="font-[family-name:var(--font-roboto-slab)] text-lg font-bold">Summary metrics strip</h2><p className="mt-1 text-xs text-muted-foreground">Also called a KPI strip, stat bar, or dashboard summary band. These three versions use title case and center the values.</p></div><div className="grid gap-4">
        <div className="border border-border bg-card p-4"><h3 className="mb-3 text-sm font-semibold">A · Instrument rail <span className="ml-2 text-xs text-primary">Recommended</span></h3><div className="grid grid-cols-2 gap-px bg-border sm:grid-cols-4"><Metric label="Generated outputs" value="9" detail="Takeoff linked" tone="default"/><Metric label="Priced" value="66.7%" detail="6 of 9 outputs" tone="good"/><Metric label="Missing price" value="1" detail="Needs review" tone="warn"/><Metric label="Expired quotes" value="0" detail="Current" tone="default"/></div></div>
        <div className="border border-border bg-card p-4"><h3 className="mb-3 text-sm font-semibold">B · Priority split</h3><div className="grid gap-2 sm:grid-cols-2"><div className="flex items-center justify-between border-l-[3px] border-primary bg-secondary px-4 py-3"><span className="text-sm">Priced outputs</span><strong className="font-mono text-xl text-primary">6 / 9</strong></div><div className="flex items-center justify-between border-l-[3px] border-warning bg-secondary px-4 py-3"><span className="text-sm">Requires attention</span><strong className="font-mono text-xl text-warning">3</strong></div></div></div>
        <div className="border border-border bg-card p-4"><h3 className="mb-3 text-sm font-semibold">C · Progress ledger</h3><div className="grid gap-3 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex justify-between text-sm"><span>Pricing coverage</span><strong className="font-mono">66.7%</strong></div><div className="mt-2 h-2 bg-secondary"><div className="h-full w-2/3 bg-primary" /></div></div><span className="font-mono text-sm text-warning">3 unresolved outputs</span></div></div>
      </div></section>
      <footer className="border-t border-border py-5 text-xs text-muted-foreground">These are review examples. No design variant has been applied to production routes.</footer>
    </div>
  </main>;
}

function Metric({label,value,detail,tone}:{label:string;value:string;detail:string;tone:'default'|'good'|'warn'}) {return <div className="bg-card px-3 py-3 text-center"><div className="text-xs text-muted-foreground">{label}</div><div className={`mt-1 font-mono text-xl font-bold ${tone==='good'?'text-primary':tone==='warn'?'text-warning':''}`}>{value}</div><div className="text-[11px] text-muted-foreground">{detail}</div></div>}
