import {redirect} from 'next/navigation';
import Link from 'next/link';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';
const n=(v:any)=>Number(v||0);const q=(v:any,u?:string)=>`${n(v).toLocaleString(undefined,{maximumFractionDigits:2})}${u?` ${u}`:''}`;const dateLabel=(v:string)=>new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric'}).format(new Date(`${v}T12:00:00`));
export default async function LookAheadPage(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const {data:p}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(!p?.company_id)redirect('/login');if(p.role==='employee')redirect('/employee');const today=new Date().toISOString().slice(0,10),end=new Date(Date.now()+21*86400000).toISOString().slice(0,10);
 const [{data:rows},{data:readyQueue}]=await Promise.all([
  supabase.from('work_package_lookahead').select('*').eq('company_id',p.company_id).gte('schedule_date',today).lte('schedule_date',end).order('schedule_date').order('start_time'),
  supabase.from('work_package_start_readiness').select('*').eq('company_id',p.company_id).eq('ready_to_start_all',true).in('operation_status',['planned','in_progress','on_hold']).order('job_number').order('package_name').order('sequence').limit(50)
 ]);
 const list=rows||[],blocked=list.filter((x:any)=>!x.ready_to_start),warnings=list.filter((x:any)=>x.ready_to_start&&(x.warning_reasons||[]).length),understaffed=list.filter((x:any)=>n(x.crew_needed)>n(x.assigned_crew)),atRisk=blocked.reduce((s:number,x:any)=>s+n(x.planned_man_hours_at_risk),0),scheduledOps=new Set(list.map((x:any)=>x.work_package_operation_id)),unscheduledReady=(readyQueue||[]).filter((x:any)=>!scheduledOps.has(x.operation_id));
 return <AppShell userName={p.full_name||user.email||'Owner'}><div className="contractor-page"><div className="command-hero"><div><div className="section-kicker">21-DAY PLAN</div><h1>Constraint-Driven Look-Ahead</h1><p>Carez scans scheduled work against predecessors, inspections, materials, equipment, vendors and pour controls before crew hours are committed.</p></div><div className="command-actions"><Link className="button secondary" href="/schedule">Schedule</Link><Link className="button secondary" href="/readiness">Work Readiness</Link><Link className="button secondary" href="/readiness/resources">Resources</Link></div></div>
 <div className="command-grid"><div className={`command-card ${blocked.length?'bad':'good'}`}><div className="command-label">Blocked Scheduled Work</div><div className="command-value">{blocked.length}</div><div className="command-help">Crew work scheduled before constraints are clear.</div></div><div className={`command-card ${atRisk>0?'bad':'good'}`}><div className="command-label">Planned MH At Risk</div><div className="command-value">{atRisk.toFixed(1)}</div><div className="command-help">Remaining labor plans attached to blocked scheduled work.</div></div><div className={`command-card ${understaffed.length?'watch':'good'}`}><div className="command-label">Crew Short</div><div className="command-value">{understaffed.length}</div><div className="command-help">Scheduled scopes without the planned crew count.</div></div><div className={`command-card ${warnings.length?'watch':'good'}`}><div className="command-label">Ready With Warning</div><div className="command-value">{warnings.length}</div><div className="command-help">Startable work with a condition worth watching.</div></div></div>
 {blocked.length>0&&<section className="section"><div className="section-heading"><div><div className="section-kicker">FIX BEFORE CREW ARRIVES</div><div className="section-title">Blocked Work Already on the Schedule</div><div className="section-heading-meta">The calendar can hold future work, but Carez will not let employees start these operations until the underlying facts clear.</div></div></div><div className="project-list">{blocked.map((x:any)=><article className="project-card" key={x.schedule_item_id}><header className="project-header"><div><div className="project-name">{dateLabel(x.schedule_date)} · {x.job_number} — {x.package_name}</div><div className="project-location">{x.field_label||x.task_name}{x.location?` · ${x.location}`:''}</div></div><span className="status on-hold">HOLD</span></header><section className="project-section"><div className="metric-grid"><div className="metric-card"><div className="label">Known Scope</div><div className="metric-value">{q(x.planned_quantity,x.unit)}</div></div><div className="metric-card"><div className="label">Crew</div><div className="metric-value">{x.assigned_crew}/{x.crew_needed||0}</div></div><div className={`metric-card ${n(x.planned_man_hours_at_risk)>0?'danger-metric':''}`}><div className="label">MH At Risk</div><div className="metric-value">{n(x.planned_man_hours_at_risk).toFixed(1)}</div></div></div><div className="alert warning section"><strong>DO NOT START:</strong> {x.next_action}</div>{(x.blocking_reasons||[]).length>1&&<div className="meta">Also blocked by: {(x.blocking_reasons||[]).slice(1).join(' · ')}</div>}{x.replacement_operation_id&&<div className="surface section"><div className="surface-body"><div className="section-kicker">READY ALTERNATIVE — SAME JOB</div><div className="title">{x.replacement_package_name} — {x.replacement_work_label}</div><div className="meta">Carez found open work on the same project whose current constraints are clear. This is a recommendation, not an automatic schedule change.</div></div></div>}<div className="action-row section"><Link className="button secondary" href="/readiness">Clear Work Hold</Link>{n(x.blocking_resource_count)>0&&<Link className="button secondary" href="/readiness/resources">Clear Resources</Link>}<Link className="button" href="/schedule">Adjust Schedule</Link></div></section></article>)}</div></section>}
 <section className="section"><div className="section-heading"><div><div className="section-kicker">READY QUEUE</div><div className="section-title">Productive Work Available</div><div className="section-heading-meta">Use this list when a scheduled scope slips. These operations are currently open and have no known start blocker.</div></div></div>{unscheduledReady.length===0?<div className="empty-state"><div><div className="title">No unscheduled ready work showing</div><div className="meta">That can be normal when all ready work is already on the 21-day plan.</div></div></div>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Job</th><th>Package</th><th>Work</th><th>Known Scope</th><th>Status</th></tr></thead><tbody>{unscheduledReady.slice(0,25).map((x:any)=><tr key={x.operation_id}><td><strong>{x.job_number}</strong><div className="meta">{x.project_name}</div></td><td>{x.package_name}<div className="meta">{x.location||''}</div></td><td>{x.field_label||x.task_name}</td><td>{q(x.planned_quantity,x.unit)}</td><td><span className="status completed">Ready</span></td></tr>)}</tbody></table></div>}</section>
 <section className="section"><div className="section-heading"><div><div className="section-kicker">FULL LOOK-AHEAD</div><div className="section-title">Next 21 Days</div></div></div>{list.length===0?<div className="empty-state"><div><div className="title">Nothing scheduled in the next 21 days</div><div className="meta">Build the field plan in Schedule and Carez will automatically scan it.</div></div></div>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Job / Work</th><th>Crew</th><th>Readiness</th><th>Constraint / Warning</th></tr></thead><tbody>{list.map((x:any)=><tr key={x.schedule_item_id}><td>{dateLabel(x.schedule_date)}</td><td><strong>{x.job_number} — {x.package_name}</strong><div className="meta">{x.field_label||x.task_name}</div></td><td>{x.assigned_crew}/{x.crew_needed||0}</td><td><span className={`status ${x.ready_to_start?'completed':'on-hold'}`}>{x.ready_to_start?'READY':'HOLD'}</span></td><td>{x.ready_to_start?((x.warning_reasons||[])[0]||'Clear'):(x.next_action||'Clear readiness')}</td></tr>)}</tbody></table></div>}</section>
 </div></AppShell>;
}
