import { redirect } from 'next/navigation';
import { AppShell } from '@/components/AppShell';
import { createClient } from '@/lib/supabase/server';
import { updateProjectBillingSetup,createInvoice,addInvoiceLine,deleteInvoiceLine,updateInvoice,sendInvoice,voidInvoice,recordInvoicePayment } from './actions';

const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const num=(v:any)=>Number(v||0);
const today=()=>new Date().toISOString().slice(0,10);
const units=['LS','EA','CY','LF','SF','HR','DAY','TON','GAL'];

export default async function BillingPage(){
  const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
  const {data:profile}=await supabase.from('profiles').select('full_name,company_id').eq('id',user.id).single();
  const [{data:projects},{data:projectBilling},{data:invoices},{data:lines},{data:changeOrders},{data:payments}]=await Promise.all([
    supabase.from('projects').select('id,job_number,name,status,customer_id,sales_tax_rate_percent,sales_tax_exempt,sales_tax_jurisdiction,customers(name,contact_name,email,billing_terms)').in('status',['active','on_hold','completed']).order('job_number'),
    supabase.from('project_billing_summary').select('*').order('job_number'),
    supabase.from('invoice_financial_summary').select('*').order('issue_date',{ascending:false}).order('invoice_number',{ascending:false}),
    supabase.from('invoice_lines').select('*').order('sort_order'),
    supabase.from('change_order_financial_summary').select('change_order_id,project_id,co_number,title,status,selected_sell_price').eq('status','approved').order('requested_date'),
    supabase.from('payment_financial_summary').select('*').order('received_date',{ascending:false}).limit(50)
  ]);

  const projectMap=new Map((projects||[]).map((p:any)=>[p.id,p]));
  const billingMap=new Map((projectBilling||[]).map((b:any)=>[b.project_id,b]));
  const lineMap=new Map<string,any[]>();for(const l of lines||[]){if(!lineMap.has(l.invoice_id))lineMap.set(l.invoice_id,[]);lineMap.get(l.invoice_id)!.push(l);}
  const coByProject=new Map<string,any[]>();for(const co of changeOrders||[]){if(!coByProject.has(co.project_id))coByProject.set(co.project_id,[]);coByProject.get(co.project_id)!.push(co);}

  const totalAuthorized=(projectBilling||[]).reduce((s:any,b:any)=>s+num(b.authorized_contract),0);
  const totalBilled=(projectBilling||[]).reduce((s:any,b:any)=>s+num(b.billed_contract),0);
  const totalAR=(projectBilling||[]).reduce((s:any,b:any)=>s+num(b.outstanding_ar),0);
  const totalOverdue=(projectBilling||[]).reduce((s:any,b:any)=>s+num(b.overdue_ar),0);
  const totalCollected=(projectBilling||[]).reduce((s:any,b:any)=>s+num(b.cash_collected),0);
  const totalRetainage=(projectBilling||[]).reduce((s:any,b:any)=>s+num(b.retainage_held),0);
  const aging=['current','1-30','31-60','61-90','90+'].map(bucket=>({bucket,total:(invoices||[]).filter((i:any)=>i.status==='sent'&&i.aging_bucket===bucket).reduce((s:number,i:any)=>s+Math.max(0,num(i.balance_due)),0)}));

  return <AppShell userName={profile?.full_name||user.email||'Owner'}>
    <div className="page-heading"><div><h1 className="page-title">Billing</h1><p className="subtitle">Invoices, customer payments, retainage and accounts receivable tied to the authorized project contract.</p></div></div>

    <div className="grid grid4">
      <div className="card"><div className="label">Authorized Contract</div><div className="value">{money(totalAuthorized)}</div><div className="meta">Original contracts + approved changes − backcharges</div></div>
      <div className="card"><div className="label">Contract Billed</div><div className="value">{money(totalBilled)}</div><div className="meta">Pre-sales-tax billed revenue</div></div>
      <div className={`card ${totalOverdue>0?'elevated':''}`}><div className="label">Outstanding A/R</div><div className="value">{money(totalAR)}</div><div className="meta">Overdue {money(totalOverdue)}</div></div>
      <div className="card"><div className="label">Cash Collected</div><div className="value">{money(totalCollected)}</div><div className="meta">Retainage currently held {money(totalRetainage)}</div></div>
    </div>

    <div className="card section"><div className="section-heading"><div><div className="section-kicker">Collections</div><div className="section-title">A/R Aging</div></div></div><div className="metric-grid">{aging.map(a=><div className={`metric-card ${a.bucket==='90+'&&a.total>0?'danger-metric':a.bucket!=='current'&&a.total>0?'warning':''}`} key={a.bucket}><div className="label">{a.bucket==='current'?'Current':`${a.bucket} Days`}</div><div className="metric-value">{money(a.total)}</div></div>)}</div></div>

    <div className="split section">
      <details className="controls-disclosure create-disclosure"><summary>Create Invoice</summary><div className="controls-body"><form action={createInvoice} className="form">
        <label className="field"><span>Project</span><select name="project_id" required defaultValue=""><option value="" disabled>Select project</option>{(projects||[]).map((p:any)=><option key={p.id} value={p.id}>{p.job_number} — {p.name}</option>)}</select></label>
        <div className="grid grid2"><label className="field"><span>Invoice Type</span><select name="invoice_type" defaultValue="progress"><option value="deposit">Deposit</option><option value="progress">Progress</option><option value="final">Final</option><option value="change_order">Change Order</option><option value="credit_memo">Credit Memo</option></select></label><label className="field"><span>Retainage %</span><input type="number" min="0" max="100" step="0.1" name="retainage_percent" defaultValue="0"/></label></div>
        <div className="grid grid2"><label className="field"><span>Issue Date</span><input type="date" name="issue_date" defaultValue={today()} required/></label><label className="field"><span>Due Date</span><input type="date" name="due_date" defaultValue={today()} required/></label></div>
        <div className="grid grid2"><label className="field"><span>Billing Period Start</span><input type="date" name="billing_period_start"/></label><label className="field"><span>Billing Period End</span><input type="date" name="billing_period_end"/></label></div>
        <label className="field"><span>PO / Customer Reference</span><input name="po_number"/></label><label className="field"><span>Notes</span><input name="notes" placeholder="Optional"/></label>
        <button className="button">Create Draft Invoice</button>
      </form></div></details>

      <details className="controls-disclosure create-disclosure"><summary>Project Billing / Sales Tax Setup</summary><div className="controls-body"><div className="list">{(projects||[]).map((p:any)=><details className="controls-disclosure" key={p.id} style={{marginBottom:10}}><summary>{p.job_number} — {p.name}</summary><div className="controls-body"><form action={updateProjectBillingSetup} className="form"><input type="hidden" name="project_id" value={p.id}/><div className="grid grid2"><label className="field"><span>Sales Tax Rate %</span><input type="number" min="0" step="0.001" name="sales_tax_rate_percent" defaultValue={num(p.sales_tax_rate_percent)}/></label><label className="field"><span>Jurisdiction</span><input name="sales_tax_jurisdiction" defaultValue={p.sales_tax_jurisdiction||''} placeholder="Project location / tax code"/></label></div><label className="field" style={{display:'flex',gridTemplateColumns:'auto 1fr',alignItems:'center'}}><input type="checkbox" name="sales_tax_exempt" defaultChecked={Boolean(p.sales_tax_exempt)}/><span>Sales-tax exempt project/customer</span></label><div className="meta">Customer: {p.customers?.name||'Not linked'}{p.customers?.email?` · ${p.customers.email}`:''}</div><button className="button secondary">Save Billing Setup</button></form></div></details>)}</div></div></details>
    </div>

    <div className="section"><div className="section-heading"><div><div className="section-kicker">Projects</div><div className="section-title">Billing Position</div><div className="section-heading-meta">How much is authorized, billed, collected and still exposed.</div></div></div><div className="project-list">{(projectBilling||[]).map((b:any)=>{
      const p:any=projectMap.get(b.project_id)||{};const unbilled=num(b.unbilled_contract),ar=num(b.outstanding_ar),overdue=num(b.overdue_ar);
      return <article className="project-card" key={b.project_id}><header className="project-header"><div><div className="project-name">{b.job_number} — {b.name}</div><div className="project-location">{p.customers?.name||'Customer not linked'}</div></div><span className={`status ${overdue>0?'on-hold':'active'}`}>{overdue>0?'A/R attention':'billing active'}</span></header><section className="project-section"><div className="metric-grid"><div className="metric-card brand"><div className="label">Authorized</div><div className="metric-value">{money(num(b.authorized_contract))}</div></div><div className="metric-card"><div className="label">Billed</div><div className="metric-value">{money(num(b.billed_contract))}</div><div className="metric-detail">{num(b.billing_percent).toFixed(1)}%</div></div><div className={`metric-card ${unbilled<0?'danger-metric':''}`}><div className="label">Unbilled Contract</div><div className="metric-value">{money(unbilled)}</div></div><div className={`metric-card ${ar>0?'warning':''}`}><div className="label">Outstanding A/R</div><div className="metric-value">{money(ar)}</div><div className="metric-detail">Overdue {money(overdue)}</div></div></div></section></article>;
    })}</div></div>

    <div className="section"><div className="section-heading"><div><div className="section-kicker">Invoices</div><div className="section-title">Invoice Register</div></div></div><div className="project-list">{(invoices||[]).length===0?<div className="card"><div className="title">No invoices yet</div><div className="meta">Create the first draft invoice above.</div></div>:(invoices||[]).map((inv:any)=>{
      const p:any=projectMap.get(inv.project_id)||{};const invLines=lineMap.get(inv.invoice_id)||[];const approvedCOs=coByProject.get(inv.project_id)||[];
      const balance=num(inv.balance_due);const paid=num(inv.amount_paid);const locked=inv.status!=='draft';
      const statusClass=inv.collection_status==='paid'?'completed':inv.collection_status?.startsWith('overdue')?'on-hold':inv.status==='sent'?'active':'';
      return <article className="project-card" key={inv.invoice_id}>
        <header className="project-header"><div><div className="project-name">{inv.invoice_number} — {p.job_number||'Project'} · {inv.invoice_type.replace('_',' ')}</div><div className="project-location">{inv.bill_to_name||p.customers?.name||'Customer not linked'} · Issued {inv.issue_date} · Due {inv.due_date}</div></div><span className={`status ${statusClass}`}>{inv.collection_status.replace('_',' ')}</span></header>
        <section className="project-section tinted"><div className="metric-grid"><div className="metric-card"><div className="label">Subtotal</div><div className="metric-value">{money(num(inv.subtotal))}</div></div><div className="metric-card"><div className="label">Sales Tax</div><div className="metric-value">{money(num(inv.sales_tax))}</div><div className="metric-detail">{inv.sales_tax_exempt?'Exempt':`${num(inv.sales_tax_rate_percent).toFixed(3)}% ${inv.sales_tax_jurisdiction||''}`}</div></div><div className="metric-card"><div className="label">Retainage Held</div><div className="metric-value">{money(num(inv.retainage_held))}</div></div><div className={`metric-card ${balance>0&&inv.collection_status?.startsWith('overdue')?'danger-metric':'brand'}`}><div className="label">Balance Due</div><div className="metric-value">{money(balance)}</div><div className="metric-detail">Invoice {money(num(inv.invoice_total))} · Paid {money(paid)}</div></div></div>
          {inv.status==='draft'&&!inv.sales_tax_exempt&&num(inv.sales_tax_rate_percent)===0&&<div className="alert warn"><strong>Sales tax rate is 0%.</strong> Confirm this invoice is actually exempt or set the correct project/invoice tax rate before sending.</div>}
          {inv.collection_status?.startsWith('overdue')&&<div className="alert danger"><strong>{inv.days_overdue} days overdue.</strong> Outstanding balance {money(balance)}.</div>}
        </section>
        <section className="project-section"><div className="section-heading"><div><div className="section-kicker">Invoice Detail</div><div className="section-title">Lines</div></div></div><div className="list">{invLines.length===0?<div className="meta">No invoice lines yet.</div>:invLines.map((l:any)=><div className="row" key={l.id}><div><div className="title">{l.description}</div><div className="meta">{l.source_type.replace('_',' ')} · {num(l.quantity).toFixed(2)} {l.unit} × {money(num(l.unit_price))} · {l.taxable?'taxable':'non-taxable'}</div></div><div style={{textAlign:'right'}}><strong>{money(num(l.line_amount))}</strong>{!locked&&<form action={deleteInvoiceLine}><input type="hidden" name="invoice_id" value={inv.invoice_id}/><input type="hidden" name="line_id" value={l.id}/><button className="button secondary" style={{marginTop:6}}>Delete</button></form>}</div></div>)}</div>
          {!locked&&<details className="controls-disclosure section"><summary>Add Invoice Line</summary><div className="controls-body"><form action={addInvoiceLine} className="form"><input type="hidden" name="invoice_id" value={inv.invoice_id}/><div className="grid grid2"><label className="field"><span>Source</span><select name="source_type" defaultValue={inv.invoice_type==='change_order'?'change_order':'manual'}><option value="original_contract">Original Contract</option><option value="change_order">Approved Change Order</option><option value="manual">Manual Billing Line</option><option value="credit">Credit</option></select></label><label className="field"><span>Approved Change Order</span><select name="change_order_id" defaultValue=""><option value="">Not tied to a CO</option>{approvedCOs.map((co:any)=><option key={co.change_order_id} value={co.change_order_id}>{co.co_number} — {co.title} ({money(num(co.selected_sell_price))})</option>)}</select></label></div><label className="field"><span>Description</span><input name="description" required placeholder="Progress billing — stem walls"/></label><div className="grid grid2"><label className="field"><span>Quantity</span><input type="number" min="0" step="0.01" name="quantity" defaultValue="1" required/></label><label className="field"><span>Unit</span><select name="unit" defaultValue="LS">{units.map(u=><option key={u}>{u}</option>)}</select></label></div><label className="field"><span>Unit Price</span><input type="number" step="0.01" name="unit_price" required placeholder={inv.invoice_type==='credit_memo'?'-500.00':'5000.00'}/></label><label className="field" style={{display:'flex',gridTemplateColumns:'auto 1fr',alignItems:'center'}}><input type="checkbox" name="taxable" defaultChecked={true}/><span>Taxable line</span></label><label className="field"><span>Notes</span><input name="notes"/></label><button className="button">Add Line</button></form></div></details>}
        </section>
        <section className="project-section tinted">
          {!locked&&<div className="split"><div><div className="subcard-title">Invoice Settings</div><form action={updateInvoice} className="form"><input type="hidden" name="invoice_id" value={inv.invoice_id}/><div className="grid grid2"><label className="field"><span>Issue Date</span><input type="date" name="issue_date" defaultValue={inv.issue_date}/></label><label className="field"><span>Due Date</span><input type="date" name="due_date" defaultValue={inv.due_date}/></label></div><div className="grid grid2"><label className="field"><span>Billing Period Start</span><input type="date" name="billing_period_start" defaultValue={inv.billing_period_start||''}/></label><label className="field"><span>Billing Period End</span><input type="date" name="billing_period_end" defaultValue={inv.billing_period_end||''}/></label></div><div className="grid grid2"><label className="field"><span>Sales Tax Rate %</span><input type="number" min="0" step="0.001" name="sales_tax_rate_percent" defaultValue={num(inv.sales_tax_rate_percent)}/></label><label className="field"><span>Retainage %</span><input type="number" min="0" max="100" step="0.1" name="retainage_percent" defaultValue={num(inv.retainage_percent)}/></label></div><label className="field"><span>Tax Jurisdiction</span><input name="sales_tax_jurisdiction" defaultValue={inv.sales_tax_jurisdiction||''}/></label><label className="field" style={{display:'flex',gridTemplateColumns:'auto 1fr',alignItems:'center'}}><input type="checkbox" name="sales_tax_exempt" defaultChecked={Boolean(inv.sales_tax_exempt)}/><span>Sales-tax exempt</span></label><label className="field"><span>PO / Reference</span><input name="po_number" defaultValue={inv.po_number||''}/></label><label className="field"><span>Terms</span><input name="terms_text" defaultValue={inv.terms_text||''}/></label><label className="field"><span>Notes</span><input name="notes" defaultValue={inv.notes||''}/></label><button className="button secondary">Save Draft Settings</button></form></div><div><div className="subcard-title">Issue Invoice</div><div className="meta" style={{marginBottom:12}}>Once sent, the invoice lines and tax snapshot are locked. Corrections should be handled by voiding an unpaid invoice or issuing a credit memo.</div><form action={sendInvoice}><input type="hidden" name="invoice_id" value={inv.invoice_id}/><button className="button">Mark Sent & Lock Invoice</button></form></div></div>}
          {inv.status==='sent'&&balance>0.009&&inv.invoice_total>0&&<div className="split"><div><div className="subcard-title">Record Customer Payment</div><form action={recordInvoicePayment} className="form"><input type="hidden" name="invoice_id" value={inv.invoice_id}/><div className="grid grid2"><label className="field"><span>Payment Date</span><input type="date" name="received_date" defaultValue={today()} required/></label><label className="field"><span>Amount</span><input type="number" min="0.01" max={balance.toFixed(2)} step="0.01" name="amount" defaultValue={balance.toFixed(2)} required/></label></div><div className="grid grid2"><label className="field"><span>Method</span><select name="payment_method" defaultValue="check"><option value="check">Check</option><option value="ach">ACH</option><option value="card">Card</option><option value="cash">Cash</option><option value="wire">Wire</option><option value="other">Other</option></select></label><label className="field"><span>Processing Fee</span><input type="number" min="0" step="0.01" name="processing_fee" defaultValue="0"/></label></div><label className="field"><span>Check / Transaction #</span><input name="reference_number"/></label><label className="field"><span>Notes</span><input name="notes"/></label><button className="button">Record Payment</button></form></div><div><div className="subcard-title">Invoice Control</div><div className="meta" style={{marginBottom:12}}>Void is allowed only when no payment is allocated.</div>{paid<=0.009&&<form action={voidInvoice}><input type="hidden" name="invoice_id" value={inv.invoice_id}/><button className="button secondary">Void Invoice</button></form>}</div></div>}
        </section>
      </article>;
    })}</div></div>

    <div className="card section"><div className="section-heading"><div><div className="section-kicker">Payments</div><div className="section-title">Recent Collections</div></div></div><div className="list">{(payments||[]).length===0?<div className="meta">No payments recorded yet.</div>:(payments||[]).map((p:any)=><div className="row" key={p.payment_id}><div><div className="title">{p.received_date} · {p.payment_method.toUpperCase()}</div><div className="meta">{p.reference_number||'No reference'} · Allocated {money(num(p.allocated_amount))}{num(p.unapplied_amount)>0?` · Unapplied ${money(num(p.unapplied_amount))}`:''}</div></div><strong>{money(num(p.amount))}</strong></div>)}</div></div>
  </AppShell>;
}
