import {redirect} from 'next/navigation';
import Link from 'next/link';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';
import {approveEmployeeShift,rejectEmployeeShift,saveDailyProduction} from '../employee-actions';

const hoursBetween=(a:string,b:string)=>Math.max(0,(new Date(b).getTime()-new Date(a).getTime())/3600000);
const h=(n:number)=>`${n.toFixed(2)} hr`;
const fmt=(v:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v));

export default async function FieldReviewPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(!profile?.company_id||profile.role==='employee')redirect('/employee');
 const [{data:shifts},{data:breaks},{data:segments},{data:tasks},{data:projects},{data:riskClasses},{data:rates}]=await Promise.all([
  supabase.from('employee_shift_sessions').select('*,crew_members(name,default_risk_class_code),projects(job_number,name,address,city,geofence_radius_ft)').eq('status','submitted').order('work_date',{ascending:false}).order('clock_in_at'),
  supabase.from('employee_break_periods').select('*'),
  supabase.from('employee_task_segments').select('*,production_tasks(name,production_unit,category)').order('started_at'),
  supabase.from('production_tasks').select('*').eq('active',true).order('sort_order'),
  supabase.from('projects').select('id,job_number,name').eq('status','active').order('job_number'),
  supabase.from('li_risk_classes').select('code,name').eq('company_id',profile.company_id).eq('tax_year',2026).eq('active',true).order('code'),
  supabase.from('production_rate_history').select('*').eq('company_id',profile.company_id).order('work_date',{ascending:false}).limit(30)
 ]);
 const breakMap=new Map<string,any[]>();for(const b of breaks||[]){const a=breakMap.get(b.shift_id)||[];a.push(b);breakMap.set(b.shift_id,a);}const segMap=new Map<string,any[]>();for(const s of segments||[]){const a=segMap.get(s.shift_id)||[];a.push(s);segMap.set(s.shift_id,a);}
 return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page">
  <div className="command-hero"><div><h1>Time Review</h1><p>Employees clock their own time. You verify the hours, GPS and work performed before it hits payroll and job cost.</p></div><div className="command-actions"><Link className="button secondary" href="/field">Back to Field</Link></div></div>
  <div className="command-grid"><div className={`command-card ${(shifts||[]).length?'watch':'good'}`}><div className="command-label">Waiting for You</div><div className="command-value">{(shifts||[]).length}</div><div className="command-help">Submitted shifts that are not payroll time until you approve them.</div></div><div className="command-card"><div className="command-label">Production Rates Captured</div><div className="command-value">{(rates||[]).length}</div><div className="command-help">Verified task/day production records with crew man-hours.</div></div></div>
  <section className="section"><div className="section-heading"><div><div className="section-kicker">Daily Approval</div><div className="section-title">Time Waiting for Approval</div><div className="section-heading-meta">GPS is a verification flag, not an automatic payroll denial.</div></div></div>
   {(shifts||[]).length===0?<div className="empty-state"><div><div className="title">Nothing waiting</div><div className="meta">Employee clock-outs will appear here.</div></div></div>:<div className="project-list">{(shifts||[]).map((s:any)=>{const bs=breakMap.get(s.id)||[];const breakHours=bs.reduce((sum:number,b:any)=>sum+(b.ended_at?hoursBetween(b.started_at,b.ended_at):0),0);const raw=hoursBetween(s.clock_in_at,s.clock_out_at);const payable=Math.max(0,raw-breakHours);const segs=segMap.get(s.id)||[];const gpsBad=s.clock_in_inside_geofence===false||s.clock_out_inside_geofence===false;return <article className="project-card" key={s.id}><header className="project-header"><div><div className="project-name">{s.crew_members?.name} · {s.projects?.job_number} — {s.projects?.name}</div><div className="project-location">{s.work_date} · {fmt(s.clock_in_at)} to {fmt(s.clock_out_at)}</div></div><span className={`status ${gpsBad?'on-hold':'active'}`}>{gpsBad?'Check GPS':'GPS OK'}</span></header><section className="project-section"><div className="metric-grid"><div className="metric-card brand"><div className="label">Calculated Work Time</div><div className="metric-value">{h(payable)}</div><div className="metric-detail">{h(raw)} elapsed − {h(breakHours)} breaks</div></div><div className={`metric-card ${s.clock_in_inside_geofence===false?'danger-metric':'positive'}`}><div className="label">Clock In</div><div className="metric-value">{s.clock_in_distance_ft==null?'GPS Only':`${Math.round(Number(s.clock_in_distance_ft))} ft`}</div><div className="metric-detail">{s.clock_in_inside_geofence==null?'Jobsite pin not set':s.clock_in_inside_geofence?'Inside jobsite radius':'Outside jobsite radius'}</div></div><div className={`metric-card ${s.clock_out_inside_geofence===false?'danger-metric':'positive'}`}><div className="label">Clock Out</div><div className="metric-value">{s.clock_out_distance_ft==null?'GPS Only':`${Math.round(Number(s.clock_out_distance_ft))} ft`}</div><div className="metric-detail">GPS accuracy: {Number(s.clock_out_accuracy_m||0).toFixed(0)} m</div></div></div>
    <div className="surface section"><div className="surface-header"><div><div className="surface-title">Tasks Worked</div><div className="surface-subtitle">These man-hours feed production tracking once the shift is approved.</div></div></div><div className="surface-body"><div className="list">{segs.length===0?<div className="meta">No task was selected during this shift.</div>:segs.map((x:any)=><div className="row" key={x.id}><div><div className="title">{x.production_tasks?.name}</div><div className="meta">{fmt(x.started_at)} – {x.ended_at?fmt(x.ended_at):'open'}</div></div><strong>{x.ended_at?h(hoursBetween(x.started_at,x.ended_at)):'—'}</strong></div>)}</div></div></div>
    {s.employee_note&&<div className="alert info"><strong>Employee note:</strong> {s.employee_note}</div>}
    <form action={approveEmployeeShift} className="form section"><input type="hidden" name="shift_id" value={s.id}/><div className="grid grid2"><label className="field"><span>Regular Hours You Approve</span><input type="number" name="regular_hours" step="0.01" min="0" defaultValue={payable.toFixed(2)} required/></label><label className="field"><span>Overtime Hours You Approve</span><input type="number" name="overtime_hours" step="0.01" min="0" defaultValue="0"/></label></div><label className="field"><span>L&I Work Class</span><select name="risk_class_code" defaultValue={s.crew_members?.default_risk_class_code||''}><option value="">Choose class</option>{(riskClasses||[]).map((r:any)=><option key={r.code} value={r.code}>{r.code} — {r.name}</option>)}</select></label><label className="field"><span>Your Note (optional)</span><input name="owner_note" placeholder="Adjusted lunch, confirmed late clock-out, etc."/></label><div className="action-row"><button className="button">Approve Time</button></div></form>
    <form action={rejectEmployeeShift} className="section"><input type="hidden" name="shift_id" value={s.id}/><input type="hidden" name="owner_note" value="Rejected for correction"/><button className="button secondary">Reject / Needs Correction</button></form>
   </section></article>})}</div>}
  </section>
  <section className="section"><div className="section-heading"><div><div className="section-kicker">Production</div><div className="section-title">Verify What the Crew Built</div><div className="section-heading-meta">Enter the crew quantity once per job/task/day. Carez combines it with every worker's approved task time.</div></div></div><div className="surface"><div className="surface-body"><form action={saveDailyProduction} className="form"><div className="grid grid2"><label className="field"><span>Job</span><select name="project_id" defaultValue="" required><option value="" disabled>Choose job</option>{(projects||[]).map((p:any)=><option key={p.id} value={p.id}>{p.job_number} — {p.name}</option>)}</select></label><label className="field"><span>Date</span><input type="date" name="work_date" defaultValue={new Date().toISOString().slice(0,10)} required/></label></div><div className="grid grid2"><label className="field"><span>Task</span><select name="production_task_id" defaultValue="" required><option value="" disabled>Choose task</option>{(tasks||[]).map((t:any)=><option key={t.id} value={t.id}>{t.name} · {t.production_unit}</option>)}</select></label><label className="field"><span>Quantity Completed</span><input type="number" name="quantity_completed" step="0.01" min="0" required/></label></div><label className="field"><span>Unit</span><select name="unit" defaultValue="LF"><option>LF</option><option>SF</option><option>CY</option><option>EA</option><option>LB</option><option>TON</option><option>HR</option></select></label><label className="field"><span>Note (optional)</span><input name="notes" placeholder="North stem walls, garage slab, etc."/></label><button className="button">Save Production</button></form></div></div></section>
  <section className="section"><div className="section-heading"><div><div className="section-kicker">History</div><div className="section-title">Actual Carez Production Rates</div><div className="section-heading-meta">These are measured field results—not estimating assumptions.</div></div></div>{(rates||[]).length===0?<div className="empty-state"><div><div className="title">No production rates yet</div><div className="meta">Approve task time and verify a quantity to create the first rate.</div></div></div>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Task</th><th>Quantity</th><th>Man-Hours</th><th>Production</th><th>MH / Unit</th></tr></thead><tbody>{(rates||[]).map((r:any)=><tr key={`${r.project_id}-${r.work_date}-${r.production_task_id}`}><td>{r.work_date}</td><td>{r.task_name}</td><td>{Number(r.quantity_completed).toFixed(2)} {r.unit}</td><td>{Number(r.man_hours).toFixed(2)} MH</td><td>{Number(r.units_per_man_hour).toFixed(2)} {r.unit}/MH</td><td>{Number(r.man_hours_per_unit).toFixed(3)} MH/{r.unit}</td></tr>)}</tbody></table></div>}</section>
 </div></AppShell>;
}
