import {redirect} from 'next/navigation';
import Link from 'next/link';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';
import {approveEmployeeShift,rejectEmployeeShift,saveDailyProduction} from '../employee-actions';

const hoursBetween=(a:string,b:string)=>Math.max(0,(new Date(b).getTime()-new Date(a).getTime())/3600000);
const h=(n:number)=>`${n.toFixed(2)} hr`;
const fmt=(v:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v));

export default async function FieldReviewPage(){
 const supabase=await createClient();
 const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');
 const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();
 if(!profile?.company_id||profile.role==='employee')redirect('/employee');
 const [{data:shifts},{data:breaks},{data:segments},{data:tasks},{data:projects},{data:riskClasses},{data:rates}]=await Promise.all([
  supabase.from('employee_shift_sessions').select('*,crew_members(name,default_risk_class_code),projects(job_number,name,address,city,geofence_radius_ft)').eq('status','submitted').order('work_date',{ascending:false}).order('clock_in_at'),
  supabase.from('employee_break_periods').select('*'),
  supabase.from('employee_task_segments').select('*,production_tasks(name,production_unit,category),work_package_operations(field_label,planned_quantity,unit,work_packages(name,location))').order('started_at'),
  supabase.from('production_tasks').select('*').eq('active',true).order('sort_order'),
  supabase.from('projects').select('id,job_number,name').eq('status','active').order('job_number'),
  supabase.from('li_risk_classes').select('code,name').eq('company_id',profile.company_id).eq('tax_year',2026).eq('active',true).order('code'),
  supabase.from('earned_production_rate_history').select('*').eq('company_id',profile.company_id).order('completed_at',{ascending:false}).limit(30)
 ]);
 const breakMap=new Map<string,any[]>();for(const b of breaks||[]){const a=breakMap.get(b.shift_id)||[];a.push(b);breakMap.set(b.shift_id,a);}
 const segMap=new Map<string,any[]>();for(const s of segments||[]){const a=segMap.get(s.shift_id)||[];a.push(s);segMap.set(s.shift_id,a);}
 const all=shifts||[];
 const needsAttention=all.filter((s:any)=>Boolean(s.requires_review)||s.clock_in_inside_geofence===false||s.clock_out_inside_geofence===false||(s.task_coverage_percent!=null&&Number(s.task_coverage_percent)<90)||(segMap.get(s.id)||[]).length===0);
 const attentionIds=new Set(needsAttention.map((s:any)=>s.id));
 const clean=all.filter((s:any)=>!attentionIds.has(s.id));

 const shiftCard=(s:any)=>{
  const bs=breakMap.get(s.id)||[];const breakHours=bs.reduce((sum:number,b:any)=>sum+(b.ended_at?hoursBetween(b.started_at,b.ended_at):0),0);const raw=hoursBetween(s.clock_in_at,s.clock_out_at);const payable=Math.max(0,raw-breakHours);const segs=segMap.get(s.id)||[];const gpsBad=s.clock_in_inside_geofence===false||s.clock_out_inside_geofence===false;const reasons:string[]=Array.isArray(s.review_reasons)?s.review_reasons:[];const coverage=s.task_coverage_percent==null?null:Number(s.task_coverage_percent);const flagged=attentionIds.has(s.id);
  return <article className="project-card" key={s.id}><header className="project-header"><div><div className="project-name">{s.crew_members?.name} · {s.projects?.job_number} — {s.projects?.name}</div><div className="project-location">{s.work_date} · {fmt(s.clock_in_at)} to {fmt(s.clock_out_at)}</div></div><span className={`status ${flagged?'on-hold':'completed'}`}>{flagged?'Review':'Clean'}</span></header><section className="project-section">
   {flagged&&<div className="alert warning"><strong>Carez flagged this shift.</strong><div>{reasons.length?reasons.join(' · '):segs.length===0?'No work was identified during the shift.':gpsBad?'GPS needs review.':'Work tracking needs review.'}</div></div>}
   <div className="metric-grid"><div className="metric-card brand"><div className="label">Calculated Work Time</div><div className="metric-value">{h(payable)}</div><div className="metric-detail">{h(raw)} elapsed − {h(breakHours)} breaks</div></div><div className={`metric-card ${coverage!=null&&coverage<90?'danger-metric':'positive'}`}><div className="label">Work Identified</div><div className="metric-value">{coverage==null?'Legacy':`${Math.round(coverage)}%`}</div><div className="metric-detail">{coverage==null?'Shift predates task coverage tracking':coverage>=90?'Work coverage looks complete':'Some paid time has no work assignment'}</div></div><div className={`metric-card ${gpsBad?'danger-metric':'positive'}`}><div className="label">GPS</div><div className="metric-value">{gpsBad?'Check':'OK'}</div><div className="metric-detail">In {s.clock_in_distance_ft==null?'—':`${Math.round(Number(s.clock_in_distance_ft))} ft`} · Out {s.clock_out_distance_ft==null?'—':`${Math.round(Number(s.clock_out_distance_ft))} ft`}</div></div></div>
   <div className="surface section"><div className="surface-header"><div><div className="surface-title">Physical Work Identified</div><div className="surface-subtitle">Package-linked hours become estimating intelligence when the package is finished and this time is approved.</div></div></div><div className="surface-body"><div className="list">{segs.length===0?<div className="meta">No work selected.</div>:segs.map((x:any)=>{const op:any=x.work_package_operations;const pkg:any=op?.work_packages;return <div className="row" key={x.id}><div><div className="title">{pkg?.name||op?.field_label||x.production_tasks?.name}</div><div className="meta">{pkg?`${op?.field_label||x.production_tasks?.name}${pkg.location?` · ${pkg.location}`:''} · ${Number(op.planned_quantity||0).toLocaleString(undefined,{maximumFractionDigits:2})} ${op.unit} known scope · `:''}{fmt(x.started_at)} – {x.ended_at?fmt(x.ended_at):'open'}{x.notes?` · ${x.notes}`:''}</div></div><strong>{x.ended_at?h(hoursBetween(x.started_at,x.ended_at)):'—'}</strong></div>})}</div></div></div>
   {s.employee_note&&<div className="alert info"><strong>Employee note:</strong> {s.employee_note}</div>}
   <form action={approveEmployeeShift} className="form section"><input type="hidden" name="shift_id" value={s.id}/><div className="grid grid2"><label className="field"><span>Regular Hours</span><input type="number" name="regular_hours" step="0.01" min="0" defaultValue={payable.toFixed(2)} required/></label><label className="field"><span>Overtime Hours</span><input type="number" name="overtime_hours" step="0.01" min="0" defaultValue="0"/></label></div><label className="field"><span>L&I Work Class</span><select name="risk_class_code" defaultValue={s.crew_members?.default_risk_class_code||''}><option value="">Choose class</option>{(riskClasses||[]).map((r:any)=><option key={r.code} value={r.code}>{r.code} — {r.name}</option>)}</select></label><label className="field"><span>Owner Note (optional)</span><input name="owner_note" placeholder="Only add a note if you changed or confirmed something."/></label><div className="action-row"><button className="button">{flagged?'Approve After Review':'Approve Clean Shift'}</button></div></form>
   {flagged&&<form action={rejectEmployeeShift} className="section"><input type="hidden" name="shift_id" value={s.id}/><input type="hidden" name="owner_note" value="Rejected for correction"/><button className="button secondary">Reject / Needs Correction</button></form>}
  </section></article>;
 };

 return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page">
  <div className="command-hero"><div><div className="section-kicker">EXCEPTION-BASED TIME</div><h1>Time Review</h1><p>Clean time should take one click. Work-package hours are already tied to the physical scope that will produce Carez's real production rate.</p></div><div className="command-actions"><Link className="button secondary" href="/production/work-packages">Work Packages</Link><Link className="button secondary" href="/production">Production Control</Link><Link className="button secondary" href="/field">Back to Field</Link></div></div>
  <div className="command-grid"><div className={`command-card ${needsAttention.length?'watch':'good'}`}><div className="command-label">Need Attention</div><div className="command-value">{needsAttention.length}</div><div className="command-help">GPS, missing work time or other exceptions.</div></div><div className={`command-card ${clean.length?'good':''}`}><div className="command-label">Clean Shifts</div><div className="command-value">{clean.length}</div><div className="command-help">Calculated hours and package tracking look normal.</div></div><div className="command-card"><div className="command-label">Total Waiting</div><div className="command-value">{all.length}</div><div className="command-help">Nothing reaches payroll until you approve it.</div></div><div className="command-card"><div className="command-label">Earned Rate Samples</div><div className="command-value">{(rates||[]).length}</div><div className="command-help">Completed packages with fully approved crew man-hours.</div></div></div>

  {needsAttention.length>0&&<section className="section"><div className="section-heading"><div><div className="section-kicker">LOOK HERE FIRST</div><div className="section-title">Exceptions</div><div className="section-heading-meta">These are the only submitted shifts Carez thinks deserve a closer look.</div></div></div><div className="project-list">{needsAttention.map(shiftCard)}</div></section>}

  <section className="section"><div className="section-heading"><div><div className="section-kicker">ONE-CLICK REVIEW</div><div className="section-title">Clean Shifts</div><div className="section-heading-meta">No GPS or work-coverage exception detected. Confirm regular/overtime split and approve.</div></div></div>{clean.length===0?<div className="empty-state"><div><div className="title">No clean shifts waiting</div><div className="meta">When employees submit clean time it will appear here.</div></div></div>:<div className="project-list">{clean.map(shiftCard)}</div>}</section>

  <section className="section"><div className="section-heading"><div><div className="section-kicker">EXCEPTION ONLY</div><div className="section-title">Manual Production Quantity</div><div className="section-heading-meta">Normal production now comes from Work Packages. Use this only for unexpected work that genuinely has no predefined package.</div></div></div><div className="surface"><div className="surface-body"><form action={saveDailyProduction} className="form"><div className="grid grid2"><label className="field"><span>Job</span><select name="project_id" defaultValue="" required><option value="" disabled>Choose job</option>{(projects||[]).map((p:any)=><option key={p.id} value={p.id}>{p.job_number} — {p.name}</option>)}</select></label><label className="field"><span>Date</span><input type="date" name="work_date" defaultValue={new Date().toISOString().slice(0,10)} required/></label></div><div className="grid grid2"><label className="field"><span>Unplanned Work</span><select name="production_task_id" defaultValue="" required><option value="" disabled>Choose work</option>{(tasks||[]).map((t:any)=><option key={t.id} value={t.id}>{t.name} · {t.production_unit}</option>)}</select></label><label className="field"><span>Quantity Completed</span><input type="number" name="quantity_completed" step="0.01" min="0" required/></label></div><label className="field"><span>Unit</span><select name="unit" defaultValue="LF"><option>LF</option><option>SF</option><option>CY</option><option>EA</option><option>LB</option><option>TON</option><option>HR</option></select></label><label className="field"><span>Why was this outside a work package?</span><input name="notes" required placeholder="Change order, unexpected repair, field-directed extra work..."/></label><button className="button secondary">Save Exception Production</button></form></div></div></section>

  <section className="section"><div className="section-heading"><div><div className="section-kicker">CAREZ HISTORY</div><div className="section-title">Earned Production Rates</div><div className="section-heading-meta">Completed physical scopes with approved employee man-hours—not daily estimates from a foreman.</div></div></div>{(rates||[]).length===0?<div className="empty-state"><div><div className="title">No earned rates yet</div><div className="meta">Finish a work package operation and approve its employee time to create the first trusted sample.</div></div></div>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Completed</th><th>Job / Package</th><th>Work</th><th>Quantity</th><th>Man-Hours</th><th>Production</th><th>MH / Unit</th></tr></thead><tbody>{(rates||[]).map((r:any)=><tr key={r.operation_id}><td>{r.completed_date}</td><td>{r.job_number} — {r.package_name}</td><td>{r.task_name}</td><td>{Number(r.quantity_completed).toFixed(2)} {r.unit}</td><td>{Number(r.man_hours).toFixed(2)} MH</td><td>{Number(r.units_per_man_hour).toFixed(2)} {r.unit}/MH</td><td>{Number(r.man_hours_per_unit).toFixed(4)} MH/{r.unit}</td></tr>)}</tbody></table></div>}</section>
 </div></AppShell>;
}
