'use server';
import {revalidatePath} from 'next/cache';
import {createClient} from '@/lib/supabase/server';

async function company(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Not signed in');const {data:profile}=await supabase.from('profiles').select('company_id,role').eq('id',user.id).single();if(!profile?.company_id||profile.role==='employee')throw new Error('Owner access required');return {supabase,user,companyId:profile.company_id};}

export async function createLead(formData:FormData){const customer_name=String(formData.get('customer_name')||'').trim();const project_name=String(formData.get('project_name')||'').trim();if(!customer_name||!project_name)return;const value=String(formData.get('estimated_value')||'').replace(/[$,]/g,'');const {supabase,user,companyId}=await company();const {data:lead,error}=await supabase.from('leads').insert({company_id:companyId,customer_name,project_name,city:String(formData.get('city')||'').trim()||null,scope:String(formData.get('scope')||'').trim(),estimated_value:value&&Number.isFinite(Number(value))?Number(value):null,bid_due:String(formData.get('bid_due')||'')||null,follow_up:String(formData.get('follow_up')||'')||null,status:'new'}).select('id').single();if(error)throw new Error(error.message);if(lead)await supabase.from('lead_activities').insert({company_id:companyId,lead_id:lead.id,activity_type:'created',note:'Lead added to Carez',created_by:user.id});revalidatePath('/');revalidatePath('/leads');}

export async function updateLeadStatus(formData:FormData){const id=String(formData.get('id')||''),status=String(formData.get('status')||'new');if(!id)return;const {supabase,user,companyId}=await company();await supabase.from('leads').update({status}).eq('id',id).eq('company_id',companyId);await supabase.from('lead_activities').insert({company_id:companyId,lead_id:id,activity_type:'status',note:`Status changed to ${status.replaceAll('_',' ')}`,created_by:user.id});revalidatePath('/');revalidatePath('/leads');}

export async function addLeadActivity(formData:FormData){const lead_id=String(formData.get('lead_id')||''),activity_type=String(formData.get('activity_type')||'note'),note=String(formData.get('note')||'').trim(),next=String(formData.get('next_follow_up')||'')||null;if(!lead_id||(!note&&!next))return;const {supabase,user,companyId}=await company();const {error}=await supabase.from('lead_activities').insert({company_id:companyId,lead_id,activity_type,note:note||null,next_follow_up:next,created_by:user.id});if(error)throw new Error(error.message);if(next)await supabase.from('leads').update({follow_up:next,status:activity_type==='proposal'?'proposal_sent':'follow_up'}).eq('id',lead_id).eq('company_id',companyId);revalidatePath('/');revalidatePath('/leads');}

export async function setLeadFollowUp(formData:FormData){const id=String(formData.get('id')||''),follow_up=String(formData.get('follow_up')||'')||null;if(!id)return;const {supabase,user,companyId}=await company();await supabase.from('leads').update({follow_up}).eq('id',id).eq('company_id',companyId);await supabase.from('lead_activities').insert({company_id:companyId,lead_id:id,activity_type:'follow_up',note:follow_up?`Follow-up set for ${follow_up}`:'Follow-up cleared',next_follow_up:follow_up,created_by:user.id});revalidatePath('/');revalidatePath('/leads');}
