import {redirect} from 'next/navigation';
import Link from 'next/link';
import {AppShell} from '@/components/AppShell';
import {createClient} from '@/lib/supabase/server';
import {createLead,convertLeadToEstimate,updateLeadStatus,addLeadActivity,setLeadFollowUp} from './actions';

const money=(n:any)=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n));
const today=()=>new Date().toISOString().slice(0,10);
const stageLabel=(s:string)=>({new:'New Lead',reviewing:'Looking At It',estimating:'Pricing It',proposal_sent:'Price Sent',follow_up:'Follow Up',won:'Won',lost:'Lost'} as Record<string,string>)[s]||s.replaceAll('_',' ');
const sourceLabel=(s:string)=>({outlook:'Outlook Email',phone:'Phone',website:'Website',referral:'Referral',gc_invitation:'GC Invitation',repeat_customer:'Repeat Customer',manual:'Entered Manually',other:'Other'} as Record<string,string>)[s]||s||'Not Set';

export default async function LeadsPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const {data:profile}=await supabase.from('profiles').select('full_name,company_id,role').eq('id',user.id).single();if(!profile?.company_id)redirect('/login');if(profile.role==='employee')redirect('/employee');
 const [{data:leads},{data:activities},{data:estimates},{data:inbox}]=await Promise.all([
  supabase.from('leads').select('*').eq('company_id',profile.company_id).order('created_at',{ascending:false}),
  supabase.from('lead_activities').select('*').eq('company_id',profile.company_id).order('activity_date',{ascending:false}).limit(300),
  supabase.from('estimates').select('id,lead_id,estimate_number,version,status').eq('company_id',profile.company_id).not('lead_id','is',null).order('created_at',{ascending:false}),
  supabase.from('lead_inbox_candidates').select('id',{count:'exact',head:true}).eq('company_id',profile.company_id).eq('status','pending')
 ]);
 const open=(leads||[]).filter((l:any)=>!['won','lost'].includes(l.status)),pipeline=open.reduce((s:number,l:any)=>s+Number(l.estimated_value||0),0),due=open.filter((l:any)=>l.follow_up&&l.follow_up<=today()),bidsDue=open.filter((l:any)=>l.bid_due&&l.bid_due<=today()),activityMap=new Map<string,any[]>(),estimateMap=new Map<string,any>();for(const a of activities||[]){const arr=activityMap.get(a.lead_id)||[];arr.push(a);activityMap.set(a.lead_id,arr);}for(const e of estimates||[])if(e.lead_id&&!estimateMap.has(e.lead_id))estimateMap.set(e.lead_id,e);
 return <AppShell userName={profile.full_name||user.email||'Owner'}><div className="contractor-page">
  <div className="command-hero"><div><h1>Leads</h1><p>Every opportunity gets one permanent number. Carez carries that number from first contact through estimate, proposal and awarded job.</p></div><div className="command-actions"><Link className="button secondary" href="/leads/inbox">Lead Inbox{Number((inbox as any)?.count||0)>0?` (${(inbox as any).count})`:''}</Link><details className="controls-disclosure create-disclosure"><summary>Add Lead</summary><div className="controls-body"><form action={createLead} className="form">
   <div className="alert info"><strong>Carez assigns the number automatically.</strong> You do not need to invent a lead name or job number.</div>
   <div className="grid grid2"><label className="field"><span>Customer / GC</span><input name="customer_name" required placeholder="Smith Homes / John Smith"/></label><label className="field"><span>Contact Name</span><input name="contact_name" placeholder="John Smith"/></label></div>
   <div className="grid grid2"><label className="field"><span>Email</span><input type="email" name="email"/></label><label className="field"><span>Phone</span><input type="tel" name="phone"/></label></div>
   <label className="field"><span>Project Address</span><input name="address" placeholder="123 Main St"/></label>
   <div className="grid grid3"><label className="field"><span>City</span><input name="city"/></label><label className="field"><span>State</span><input name="state" defaultValue="WA"/></label><label className="field"><span>ZIP</span><input name="postal_code"/></label></div>
   <label className="field"><span>Concrete Work</span><textarea name="scope" rows={3} placeholder="Driveway replacement, foundation, slab, walls..."/></label>
   <div className="grid grid2"><label className="field"><span>Rough Value</span><input name="estimated_value" inputMode="decimal"/></label><label className="field"><span>Lead Source</span><select name="source" defaultValue="manual"><option value="manual">Entered Manually</option><option value="phone">Phone</option><option value="website">Website</option><option value="referral">Referral</option><option value="gc_invitation">GC Invitation</option><option value="repeat_customer">Repeat Customer</option><option value="other">Other</option></select></label></div>
   <div className="grid grid2"><label className="field"><span>Bid Due</span><input type="date" name="bid_due"/></label><label className="field"><span>Follow Up</span><input type="date" name="follow_up"/></label></div>
   <label className="field"><span>Notes</span><textarea name="notes" rows={2}/></label><button className="button">Create Numbered Lead</button>
  </form></div></details></div></div>
  <div className="command-grid"><div className={`command-card ${open.length===0?'bad':''}`}><div className="command-label">Jobs in the Pipeline</div><div className="command-value">{open.length}</div><div className="command-help">Open leads and bids that could become work.</div></div><div className="command-card"><div className="command-label">Pipeline Value</div><div className="command-value">{money(pipeline)}</div></div><div className={`command-card ${due.length?'bad':'good'}`}><div className="command-label">Follow Ups Due</div><div className="command-value">{due.length}</div></div><div className={`command-card ${bidsDue.length?'watch':'good'}`}><div className="command-label">Bid Deadlines Due</div><div className="command-value">{bidsDue.length}</div></div></div>
  <section className="section"><div className="section-heading"><div><div className="section-kicker">Sales</div><div className="section-title">Job Pipeline</div><div className="section-heading-meta">L-26-### becomes E-26-###-R0, then P-26-###-R0, then Job 26-### when accepted.</div></div></div>
   {(leads||[]).length===0?<div className="empty-state"><div><div className="title">No possible jobs entered</div><div className="meta">Use Add Lead or connect Outlook in Lead Inbox.</div></div></div>:<div className="project-list">{(leads||[]).map((l:any)=>{const history=activityMap.get(l.id)||[],followDue=l.follow_up&&l.follow_up<=today()&&!['won','lost'].includes(l.status),est=estimateMap.get(l.id);return <article className="project-card" key={l.id}><header className="project-header"><div><div className="project-name">L-{l.opportunity_number||'UNNUMBERED'} — {l.project_name}</div><div className="project-location">{l.customer_name}{l.city?` · ${l.city}, ${l.state||'WA'}`:''} · {money(l.estimated_value)} · {sourceLabel(l.source)}</div></div><span className={`status ${followDue?'on-hold':l.status==='won'?'completed':'active'}`}>{followDue?'Follow Up Due':stageLabel(l.status)}</span></header><section className="project-section">
    <div className="metric-grid"><div className="metric-card"><div className="label">Contact</div><div className="metric-value" style={{fontSize:18}}>{l.contact_name||l.customer_name}</div><div className="metric-detail">{l.email||l.phone||'Contact details not entered'}</div></div><div className="metric-card"><div className="label">Jobsite</div><div className="metric-value" style={{fontSize:18}}>{l.address||l.city||'Not entered'}</div></div><div className="metric-card"><div className="label">Bid Due</div><div className="metric-value" style={{fontSize:18}}>{l.bid_due||'Not Set'}</div></div><div className={`metric-card ${followDue?'danger-metric':''}`}><div className="label">Next Follow Up</div><div className="metric-value" style={{fontSize:18}}>{l.follow_up||'Not Set'}</div></div></div>
    <div className="next-action section"><div><div className="next-action-label">Concrete Work</div><div className="next-action-text">{l.scope||'Scope not entered yet.'}</div></div></div>
    <div className="action-row section">{est?<Link className="button" href="/estimates">Open {est.estimate_number}-R{est.version}</Link>:!['won','lost'].includes(l.status)&&<form action={convertLeadToEstimate}><input type="hidden" name="lead_id" value={l.id}/><button className="button">Start Estimate</button></form>}<Link className="button secondary" href="/leads/inbox">Email / Lead Inbox</Link></div>
    <div className="grid grid2 section"><form action={updateLeadStatus} className="form"><input type="hidden" name="id" value={l.id}/><label className="field"><span>Where Is This Job?</span><select name="status" defaultValue={l.status}><option value="new">New Lead</option><option value="reviewing">Looking At It</option><option value="estimating">Pricing It</option><option value="proposal_sent">Price Sent</option><option value="follow_up">Follow Up</option><option value="won">Won</option><option value="lost">Lost</option></select></label><button className="button secondary">Save Status</button></form><form action={setLeadFollowUp} className="form"><input type="hidden" name="id" value={l.id}/><label className="field"><span>Next Follow Up</span><input type="date" name="follow_up" defaultValue={l.follow_up||''}/></label><button className="button secondary">Save Follow Up</button></form></div>
    <details className="controls-disclosure section"><summary>Calls / Emails / Notes ({history.length})</summary><div className="controls-body"><form action={addLeadActivity} className="form"><input type="hidden" name="lead_id" value={l.id}/><label className="field"><span>What Happened?</span><select name="activity_type"><option value="call">Phone Call</option><option value="email">Email</option><option value="meeting">Meeting / Site Visit</option><option value="proposal">Proposal Sent</option><option value="note">Note</option></select></label><label className="field"><span>Note</span><textarea name="note" rows={2}/></label><label className="field"><span>Follow Up Again</span><input type="date" name="next_follow_up"/></label><button className="button">Save Activity</button></form><div className="list section">{history.slice(0,8).map((a:any)=><div className="row" key={a.id}><div><div className="title">{a.activity_type.replaceAll('_',' ')}</div><div className="meta">{new Date(a.activity_date).toLocaleString()} · {a.note||'No note'}</div></div></div>)}</div></div></details>
   </section></article>})}</div>}
  </section>
 </div></AppShell>;
}
