-- Carez OS: remove anonymous access from authenticated business RPCs and keep trigger-only helpers internal.

revoke all on function public.apply_bank_reconciliation_rule(uuid,uuid) from public, anon;
revoke all on function public.approve_change_order(uuid) from public, anon;
revoke all on function public.approve_payroll_run(uuid) from public, anon;
revoke all on function public.capture_overhead_rate_snapshot(date) from public, anon;
revoke all on function public.convert_vendor_quote_to_purchase_order(uuid) from public, anon;
revoke all on function public.create_payroll_run(date,date,date,text) from public, anon;
revoke all on function public.ignore_bank_transaction(uuid,text,boolean,boolean) from public, anon;
revoke all on function public.issue_purchase_order(uuid,date) from public, anon;
revoke all on function public.next_company_document_number(text) from public, anon;
revoke all on function public.next_invoice_number() from public, anon;
revoke all on function public.post_vendor_bill(uuid) from public, anon;
revoke all on function public.process_payroll_run(uuid,numeric,text) from public, anon;
revoke all on function public.reconcile_bank_as_transfer(uuid,uuid) from public, anon;
revoke all on function public.reconcile_bank_existing(uuid,text,uuid,text,integer) from public, anon;
revoke all on function public.reconcile_bank_to_company_expense(uuid,uuid,text,numeric,text,boolean,boolean) from public, anon;
revoke all on function public.reconcile_bank_to_invoice(uuid,uuid) from public, anon;
revoke all on function public.reconcile_bank_to_job_cost(uuid,uuid,uuid,uuid,text,boolean) from public, anon;
revoke all on function public.reconcile_bank_to_payroll_run(uuid,uuid) from public, anon;
revoke all on function public.reconcile_bank_to_tax(uuid,text) from public, anon;
revoke all on function public.reconcile_bank_to_vendor_bill(uuid,uuid) from public, anon;
revoke all on function public.record_vendor_bill_payment(uuid,date,numeric,text,text,numeric,text) from public, anon;
revoke all on function public.void_payroll_run(uuid) from public, anon;
revoke all on function public.void_vendor_payment(uuid) from public, anon;

grant execute on function public.apply_bank_reconciliation_rule(uuid,uuid) to authenticated, service_role;
grant execute on function public.approve_change_order(uuid) to authenticated, service_role;
grant execute on function public.approve_payroll_run(uuid) to authenticated, service_role;
grant execute on function public.capture_overhead_rate_snapshot(date) to authenticated, service_role;
grant execute on function public.convert_vendor_quote_to_purchase_order(uuid) to authenticated, service_role;
grant execute on function public.create_payroll_run(date,date,date,text) to authenticated, service_role;
grant execute on function public.ignore_bank_transaction(uuid,text,boolean,boolean) to authenticated, service_role;
grant execute on function public.issue_purchase_order(uuid,date) to authenticated, service_role;
grant execute on function public.next_company_document_number(text) to authenticated, service_role;
grant execute on function public.next_invoice_number() to authenticated, service_role;
grant execute on function public.post_vendor_bill(uuid) to authenticated, service_role;
grant execute on function public.process_payroll_run(uuid,numeric,text) to authenticated, service_role;
grant execute on function public.reconcile_bank_as_transfer(uuid,uuid) to authenticated, service_role;
grant execute on function public.reconcile_bank_existing(uuid,text,uuid,text,uuid,text,integer) from public, anon;
revoke all on function public.reconcile_bank_existing(uuid,text,uuid,text,integer) from public, anon;
grant execute on function public.reconcile_bank_existing(uuid,text,uuid,text,integer) to authenticated, service_role;
grant execute on function public.reconcile_bank_to_company_expense(uuid,uuid,text,numeric,text,boolean,boolean) to authenticated, service_role;
grant execute on function public.reconcile_bank_to_invoice(uuid,uuid) to authenticated, service_role;
grant execute on function public.reconcile_bank_to_job_cost(uuid,uuid,uuid,uuid,text,boolean) to authenticated, service_role;
grant execute on function public.reconcile_bank_to_payroll_run(uuid,uuid) to authenticated, service_role;
grant execute on function public.reconcile_bank_to_tax(uuid,text) to authenticated, service_role;
grant execute on function public.reconcile_bank_to_vendor_bill(uuid,uuid) to authenticated, service_role;
grant execute on function public.record_vendor_bill_payment(uuid,date,numeric,text,text,numeric,text) to authenticated, service_role;
grant execute on function public.void_payroll_run(uuid) to authenticated, service_role;
grant execute on function public.void_vendor_payment(uuid) to authenticated, service_role;

revoke all on function public.carez_assign_work_package_sequence() from public, anon, authenticated;
revoke all on function public.carez_sync_inspection_schedule() from public, anon, authenticated;
revoke all on function public.protect_project_award_snapshot() from public, anon, authenticated;
revoke all on function public.protect_proposal_presentation_snapshot() from public, anon, authenticated;
revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.sync_proposal_token_revocation() from public, anon, authenticated;
revoke all on function public.validate_procurement_header_links() from public, anon, authenticated;
revoke all on function public.validate_procurement_line_links() from public, anon, authenticated;
revoke all on function public.validate_proposal_engagement_event() from public, anon, authenticated;
